= Create and Configure Endpoints

You can create new endpoints from the *Host* or *Partner* page, or by using the Message Flow wizard.

== Create Endpoints from the Partners Page

Use the *Partners* page to create new send and receive endpoints owned by partners or 3rd party connections:

. In the navigation menu, select *Partners*.
. Select the partner or 3rd party connection for which to create the endpoint.
. In the *Endpoints* section, click *New*.
. In the *New Endpoint* window *Usage* field, select *Receive from partners* or *Send to partners*.
. In the *Protocol* field, select the protocol to use for the endpoint.
. <<configure-endpoint,Configure the endpoint>> according to the type of endpoint you are creating and the protocol you selected.
. Click *Save*.

Ownership of the endpoints (receive or send) is automatically assigned based on the partner or 3rd party connection from which you are creating the endpoint.

== Create Endpoints from the Host Page

You can use the *Host* page to create new send and receive endpoints owned by the host:

. In the navigation menu, select the host.
. In the *Endpoints* section, click *New*.
. In the *New Endpoint* window *Usage* field, select the endpoint type.
. In the *Protocol* field, select the protocol to use for the endpoint.
. <<configure-endpoint,Configure the endpoint>> according to the type of endpoint you are creating and the protocol you selected.
. Click *Save*.

== Create Endpoints Using the Message Flow Wizard

You can use the Message Flow Wizard to create send and receive endpoints owned by hosts, partners, or 3rd party connections.

For information about using the Message Flow wizard to create new endpoints, see xref:configure-message-flows.adoc[Create and Configure an Inbound Message Flow] and xref:create-outbound-message-flow.adoc[Create and Configure an Outbound Message Flow].

== Supported Endpoint Protocols

The configuration of Partner Manager endpoints depends on the protocol used to send and receive messages.

Partner Manager supports the following endpoint protocols:

The following table describes the endpoint types, along with their supported protocols and owners:

[%header%autowidth.spread]
|===
|Endpoint Type | Protocol | Can be owned by
.1+| Source at host .2+.^| FTP, HTTP, HTTPS, SFTP .2+| Host
.1+| Target at host
.2+.^| Receive from partners .1+| AS2 .1+| Host
.1+| FTP, SFTP .1+| Host, partner, 3rd party connection
.2+.^| Send to partners .1+| AS2 | Partner, 3rd party connection
.1+| FTP, HTTP, HTTPS, SFTP .1+| Host, partner, 3rd party connection
|===

== Endpoint Runtime Services

Using dynamic configurations, Partner Manager deploys generic endpoint services that can receive data from or send data to different endpoint configurations. Endpoint configurations of all supported protocols can be reused across various message flows and trading partners.

Partner Manager’s deployment orchestration service inspects the message flow and associated configuration objects and determines which endpoint services to deploy or update based on whether or not any new endpoint configurations are added, updated, or removed.

The number and type of endpoint services deployed to your runtime depends on the transport protocols used to exchange data with your trading partners and backend systems.

Each unique AS2 and HTTP and HTTPS receive endpoint configurations result in the deployment of their own runtime applications. You can view the Runtime application name corresponding to a given configuration in Partner Manager, from the endpoint detail page.

The endpoints for the transport protocols are always managed within a single generic endpoint service for the protocol and direction:

=== Endpoint Services
[%header%autowidth.spread]
|===
|Protocol |Direction |Application Name Prefix
|AS2 |Receive |b2b-inbound-as2-
|AS2 |Send |b2b-outbound-as2-
|FTP | Receive | b2b-inbound-ftp-
|FTP | Send | b2b-outbound-ftp-
|HTTP or HTTPS |Receive |b2b-inbound-http-
|HTTP or HTTPS |Send |b2b-outbound-http-
|SFTP |Receive |b2b-inbound-sftp-
|SFTP |Send |b2b-outbound-sftp-
|===

If your deployment target is CloudHub, you can assign static IP addresses to your endpoint applications connecting to external systems from Runtime Manager, if your organization or your trading partners require allowlisting IP addresses. You can share the xref:runtime-manager::managing-applications-on-cloudhub#static-ips[static IP] address assigned to your endpoint application with your trading partners for them to allowlist the IP address, allowing the application to connect with their server.

[[configure-endpoint]]
== Configure Endpoint Protocol and Type-Specific Settings

The values for the endpoint's settings vary according to the protocol-type of the endpoint for which you are configuring the settings:

* xref:endpoint-as2-receive.adoc[AS2 Receive Endpoint Settings]
* xref:endpoint-as2-send.adoc[AS2 Send Endpoint Settings]
* xref:endpoint-ftp-receive.adoc[FTP Receive Endpoint Settings]
* xref:endpoint-ftp-send.adoc[FTP Send Endpoint Settings]
* xref:endpoint-https-receive.adoc[HTTP and HTTPS Receive Endpoint Settings]
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Endpoint Settings]
* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
* xref:endpoint-sftp-send.adoc[SFTP Send Endpoint Settings]

== See Also

* xref:endpoints.adoc[Endpoints]
