= Create and Configure an Inbound Message Flow
:page-aliases: configure-message-flows.adoc

Create and configure an inbound message flow to:
* Receive EDI messages from your trading partners, including messages that go through 3rd party connections
* Validate and transform the inbound messages
* Send the translated message (JSON or XML) to your backend applications

To receive messages sent from a trading partner through a 3rd party connection, select an endpoint owned by that connection.

=== Prerequisites
Before you create your first inbound message flow, you must configure your xref:setup-payload-storage-API.adoc[payload storage API].

=== Steps

. From the Anypoint Partner Manager navigation menu, select *Message Flows*.
. Click *New message flow > Receive from partner*.
. Either select an existing partner from the list or select *New* to create a new partner, as described in xref:create-partner.adoc#[Create a partner].
+
A new message flow is created.
+
. <<receiving-endpoint,Configure the receiving endpoint>>.
. <<source-message-type,Configure the source message type>>.
. <<import-map,Import the translation map>>.
. <<verify-message-flow,Verify that the message flow is complete>>.

[receiving-endpoint]
== Specify the Receiving Endpoint

Use one of the following methods to specify the endpoint to receive the message you are sending:

* Select an existing endpoint owned by the host, target partner, or 3rd party connection.
+
If you select an endpoint owned by a 3rd party connection, the inbound message goes through that connection.
+
* Create a new receiving endpoint for this message flow.

To specify the receiving endpoint:

. In the message flow, expand the *Receiving from <partner>* section and click *Select endpoint*.
. In the *Receiving endpoint* section, click *Select*.
. In the *Select an endpoint: Receive from <partner>* window, do either of the following:
* Select an existing receiving endpoint and click *Select*.
* Click *New* to create a new endpoint, as described in xref:<<create-endpoint.adoc, Create and Configure Endpoints>>.
+
The endpoint is added to the message flow, and a message appears indicating that the endpoint is missing an identifier.

=== AS2 Sender

If the protocol of the receive endpoint is AS2, select the AS2 sender from the dropdown menu:

* If your organization will receive the AS2 messages directly from the partner for whom the message flow is created, select the partner’s name (default).
* If your organization will receive the AS2 messages for the partner via a 3rd party connection, such as a VAN or 3PL, select the name of the 3rd party connection. The AS2 identifier and certificate of the selected 3rd party connection will be used in AS2 message validation.
* If you selected AS2 as the receive to partner endpoint protocol, you must import the AS2 certificate of the partner or the 3rd party connection sending the AS2 message, if a certificate already does not exist in the partner or 3rd party connection’s profile.

[source-message-type]
== Configure the Source Message Type

. In the message flow, expand the *Source message* section and click *Select*.
. In the *Select message type* window:
.. To use an existing message type, select the message type from the list and then click *Select*.
.. To create a new message type, click *New* next to the search box, configure the X12 or EDIFACT xref:partner-manager-create-message-type.adoc[message type], and click *Save*.
The message type and its validation settings are added to the message flow.
. If your partner expects your organization to return functional acknowledgements:
.. In the *Acknowledgement* section, select the check box next to *Send 997 functional acknowledgment (X12)* or *Send CONTRL functional acknowledgement (EDIFACT)* .
.. Click *Select*.
.. In the *Select an endpoint: Send acknowledgment to <partner>* window, click *Select* to specify the endpoint from which to receive the acknowledgment transactions from your partner.
+
.. Alternatively, you can create a new send to partner endpoint:
... Click *New*.
... In the *Owner* field, select the endpoint owner.
... In the *Protocol* field, select and configure the protocol.
... Click *Save*.
+
The acknowledgment is added to the message flow.

[[import-map]]
== Import the Translation Map

To create your inbound EDI-to-application message (JSON or XML) map in Anypoint Studio, follow xref:partner-manager-maps.adoc[these instructions]:

. In the message flow, expand the *Map* section.
. Click *Import* and then click *Choose file*.
. In the *New mapping file* window, navigate to the DataWeave map you want to use and then click *Open*.
. Click *Upload mapping*. +
The translation map is added to the message flow.

[[configure-target]]
== Configure the Target

. In the message flow, expand the *Target at <host>* section.
. In the *Message Type* section, click *Select*.
. In the *Select message type* window:
* To use an existing message type, select the message type from the list and then click *Select*.
* To create a new message type, click *New* next to the search box, define the xref:partner-manager-create-message-type.adoc#target-at-host[target at host message type], and click *Save*.
+
The message type is selected for your backend system to use to map the EDI transaction. Partner Manager routes inbound EDI transactions based on matching identifiers configured at the Partner level.
. In the *Target at <host>* section, expand the *Endpoint* section and click *Select*.
. In the *Select an endpoint: Target to <host>* window:
.. To use an existing endpoint, select the endpoint from the list and  then click *Select*.
.. To create a new endpoint:
... Click *New* next to the search box.
... From the *Owner* drop-down, select the endpoint's owner.
... From the *Protocol* drop-down, select the protocol and configure it according to the protocol you select:
* xref:endpoint-https-send.adoc[HTTP or HTTPS]
* xref:endpoint-ftp-send.adoc[FTP]
* xref:endpoint-sftp-send.adoc[SFTP]
+
... Click *Save*. +
The endpoint to which to send the translated message (JSON or XML) for further processing in your backend system is added to the message flow. Partner Manager routes inbound EDI transactions based on matching identifiers configured at the partner level.

[[verify-message-flow]]
== Verify That the Message Flow Is Complete

Partner Manager dynamically validates the message flow configuration elements and confirms by displaying a green checkmark, indicating that you are ready to deploy the message flow.

== See Also

* xref:deploy-message-flows.adoc[Deploy Message Flows]
* xref:manage-message-flows.adoc[Manage Message Flows]
* xref:activity-tracking.adoc[Activity Tracking]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
