<<<<<<< Updated upstream
= Access Inbound Message Attributes

When you create a translation map for an inbound message flow, you can add additional message attributes to that map. These attributes will then be visible in the message payload of the transmissions that use the map. Use the *Activity* page to view this payload, as described in xref:activity-tracking.adoc#view-details[View Details for an Inbound Transmission].

Additon 

The attributes that you can add depend on the protocol of the receiving endpoint:

|===
|Endpoint Protocol |Attributes |Example
=======
= Accessing Inbound Message Attributes

When you create a translation map for an inbound Anypoint Partner Manager message flow, you can add additional attributes to that map. These added attributes show up in the message payload and you can view them on the activity screen for transmissions that use the map.

The attributes you can add depend on the protocol of the endpoint in the message flow:

[%header%cols="30,30,40"]
|===
|Protocol |Attributes |Example
>>>>>>> Stashed changes
|AS2
a|
* sourceProtocol
* endpointName
* transmissionId
* messageId
* as2MessageId
* as2From
* as2To
* fileName
* as2-subject (if available)
<<<<<<< Updated upstream
* Headers that start with `x-apm`
=======
* Headers that start with `x-apm-`
>>>>>>> Stashed changes
a| 
[source,json,linenums]
----
{
<<<<<<< Updated upstream
  "sourceProtocol": "HTTPS",
  "transmissionId": "32268139-8c05-4cb3-b1ba-dce07eb57fe2",
  "sourceEndpointAttributes": {
    "path": "/",
    "fileSize": 2228
  },
    "customProtocolHeaders": {
    "x-apm-order-number": "ORD12345-A",
    "x-apm-order-type": "drop-ship"
  },
    "messageId": "b5a645e7-aa2d-4d37-bb62-0b68e2991356"
}
 ----

|FTP and SFTP
 a|
 * sourceProtocol
 * transnmissionId
 * messageId
 * path
 a|
 [source,json,linenums]
 ----
 {
  "sourceProtocol": "SFTP",
  "sourceEndpointAttributes": {
=======
  "sourceProtocol": "AS2",
  "transmissionId": "043bbc1a-e043-4bf0-8c65-06082caf4d9b",
  "sourceEndpointAttributes": {
      "as2MessageId": "<2023-03-14T06:04:15.750-9282af1d-a03a-469a-a591-41ef52457e4b@partnera_mythical-as2>",
      "as2From": "partnera",
      "as2To": "mythical-as2",
      "fileName": "\"smime.p7m\"",
      "subject": "EDI Message via Mule Generic Service",
      "fileSize": 3831
      },
    "customProtocolHeaders": {
      "x-apm-order-type": "drop-ship",
      "x-apm-tracking-id": "9f0808ad-6503-438a-9f9b-2e65cdacb344"
    },
    "messageId": "a79b1939-3cd6-415b-8a3c-83cc2a4f0da4"
    }
}
----
|FTP and SFTP
 a|
* sourceProtocol
* transnmissionId
* messageId
* path
a|
[source,json,linenums]
----
{
  "sourceProtocol": "SFTP",
    "transmissionId": "231839bf-09fa-41f6-a9f4-6f49187f0802",
    "sourceEndpointAttributes": {
>>>>>>> Stashed changes
    "fileName": "custom-po-xml-sftp_PacificCorp_PO_123.xml",
    "filePath": "/partners/pacific-corp/in-orders",
    "fileSize": 4889,
    "fileTimeStamp": "2023-03-16T20:40:59"
  },
<<<<<<< Updated upstream
    "messageId": "c93ca021-4adc-48e4-a147-a8d74ba1dac0"
}
----

=======
  "messageId": "c93ca021-4adc-48e4-a147-a8d74ba1dac0"
}
----
>>>>>>> Stashed changes
 |HTTP and HTTPS
 a|
 * sourceProtocol
 * endpointName
 * transnmissionId
 * messageId
 * Headers that start with `x-apm-`
 a|
<<<<<<< Updated upstream
 [source,json,linenums]
 ----
 {
=======
----
{
>>>>>>> Stashed changes
  "sourceProtocol": "HTTPS",
  "transmissionId": "abcd-1234-121121-2323",
  "messageId": "abcd-1234-1232212-1212",
  "customProtocolAttributes": {
    "x-apm-order-type": "drop-ship",
    "x-apm-order-number": "ORD2o99244",
    "x-apm-idoc-number": "IDOC-239839131"
<<<<<<< Updated upstream
  }
}
----
|====
=======
}
----
|===
>>>>>>> Stashed changes
