= Accessing Source Message Attributes

When you create a translation map for an inbound or outbound Anypoint Partner Manager message flow, you can add additional source message attributes to that map. The added attributes appear in the message payload, and you can view them on the activity screen for transmissions that use the map. 

Adding additional message attributes to translation maps enables you to achieve end-to-end tracing by passing transmission IDs to the translated JSON or XML output file. You can also add additional message attributes to help Partner Manager make routing decisions and to have Partner Manager perform specific fuctions within the data transformation in the message flow execution.

Some common use cases include:

* Mapping attributes such as the source filename or a specific header to a field in the translated data payload within a message flow's translation map.
+
For example, you can map... 
+
* Applying mapping logic based either on the filename prefix or on a pattern within the transformation.
+
For example, you can ... 
+
* Accessing a specific header filename part through substring operations to map the partner or host Reference ID in the message type level reference mapping (*Vijay, map these to what?*) - making dynamic routing decisions.
* Mapping the source filename or a specific header as a custom message attribute in the reference mapping.
+

The attributes that you can add are available within a predefined variable named `b2bMessageContext`. The content of this variable varies based on the source endpoint's protocol.

== AS2 Message Attributes

Messages received via AS2 contain the following fields in the `b2bMessageContext` variable:

* sourceProtocol
* transmissionId
* sourceEndpointAttributes:
** as2MessageId
** as2From
** as2To
** fileName
** subject
** fileSize 
* customProtocolHeaders: (The headers always begin with `x-apm-`.)
** x-apm-<header1>
** x-apm-<header2> +
   +.+ +
   +.+ +
   +.+

For example:

[source,json]
----
{
  "sourceProtocol": "AS2",
  "transmissionId": "06bc20c8-475e-4a6f-b010-9b7933b2bfac",
  "sourceEndpointAttributes": {
    "as2MessageId": "<2023-04-12T19:37:42.273-46b95696-83f4-4e65-9222-61c40a854200@partnera_mythical-as2>",
    "as2From": "partnera",
    "as2To": "mythical-as2",
    "fileName": "EDI_850_20230401_1245678.edi",
    "subject": "EDI Message via Mule Generic Service",
    "fileSize": 3887
  },
  "customProtocolHeaders": {
    "x-apm-order-type": "drop-ship",
    "x-apm-tracking-id": "9d26d4ce-59ea-4448-8b51-ccc975d4efec"
  },
  "messageId": "9bf446f8-4a02-475f-afa3-c8772a340154"
}
----

== FTP and SFTP Message Attributes
 
Messages received via FTP and SFTP contain the following fields in the `b2bMessageContext` variable:

* sourceProtocol
* transmissionId
* sourceEndpointAttributes:
** fileName
** filePath
** fileSize
** fileTimeStamp
** partnerReferenceId
+
Available only on Receive from Partner endpoints that have the partner reference ID configured
+
* messageId

For example:

[source,json]
----
{
"sourceProtocol": "SFTP",
  "transmissionId": "3ef5654a-5cda-41b1-8909-59a28c8b1537",
  "sourceEndpointAttributes": {
    "fileName": "RandomMessageType_PO_20230331_1559_003.xml",
    "filePath": "/partners/pacific-corp/in-orders",
    "fileSize": 4889,
    "fileTimeStamp": "2023-04-05T15:16:29",
    "partnerReferenceId": "PACIFICCORP"
  },
  "messageId": "cdaf6c12-bb3b-4978-9ac6-e8ace053f7c5"
}
----

== HTTP and HTTPS Message Attributes

* sourceProtocol
* transnmissionId
* sourceEndpointAttributes:
** path
** fileSize
* customProtocolHeaders: (The headers always begin with `x-apm-`.)
** x-apm-<header1>
** x-apm-<header2> +
   +.+ +
   +.+ +
   +.+
* messageId   

For example:

[source,json]
----
{
  "sourceProtocol": "HTTPS",
  "transmissionId": "a7a800ad-4117-40c1-98a0-79892c982fd4",
  "sourceEndpointAttributes": {
    "path": "/",
    "fileSize": 866
  },
  "customProtocolHeaders": {
    "x-apm-order-number": "ORD12345-A",
    "x-apm-order-type": "drop-ship",
  },
  "messageId": "cdaf6c12-bb3b-4978-9ac6-e8ace053f7c5"
}
----

== See Also

* xref:partner-manager-maps.adoc[Translation Maps]
* xref:create-inbound-message-flow.adoc[Creating Inbound Message Flows]
* xref:activity-tracking.adoc[Tracking Transmissions]
