= Accessing Inbound Message Attributes

When you create a translation map for an inbound message flow, you can add additional message attributes to that map. These attributes will then be visible in the message payload of the transmissions that use the map. Use the *Activity* page to view this payload, as described in xref:activity-tracking.adoc#view-details[View Details for an Inbound Transmission].

The attributes you can add depend on the protocol of the receiving endpoint:

|===
|Endpoint Protocol |Attributes |Example
|AS2
a|
* sourceProtocol
* endpointName
* transmissionId
* messageId
* as2MessageId
* as2From
* as2To
* fileName
* as2-subject (if available)
* Headers that start with `x-apm`
a| 
[source,json,linenums]
----
{
  "sourceProtocol": "HTTPS",
  "transmissionId": "32268139-8c05-4cb3-b1ba-dce07eb57fe2",
  "sourceEndpointAttributes": {
    "path": "/",
    "fileSize": 2228
  },
    "customProtocolHeaders": {
    "x-apm-order-number": "ORD12345-A",
    "x-apm-order-type": "drop-ship"
  },
    "messageId": "b5a645e7-aa2d-4d37-bb62-0b68e2991356"
}
 ----

|FTP and SFTP
 a|
 * sourceProtocol
 * transnmissionId
 * messageId
 * path
 a|
 [source,json,linenums]
 ----
 {
  "sourceProtocol": "SFTP",
  "sourceEndpointAttributes": {
    "fileName": "custom-po-xml-sftp_PacificCorp_PO_123.xml",
    "filePath": "/partners/pacific-corp/in-orders",
    "fileSize": 4889,
    "fileTimeStamp": "2023-03-16T20:40:59"
  },
    "messageId": "c93ca021-4adc-48e4-a147-a8d74ba1dac0"
}
----

 |HTTP and HTTPS
 a|
 * sourceProtocol
 * endpointName
 * transnmissionId
 * messageId
 * Headers that start with `x-apm-`
 a|
 [source,json,linenums]
 ----
 {
  "sourceProtocol": "HTTPS",
  "transmissionId": "abcd-1234-121121-2323",
  "messageId": "abcd-1234-1232212-1212",
  "customProtocolAttributes": {
    "x-apm-order-type": "drop-ship",
    "x-apm-order-number": "ORD2o99244",
    "x-apm-idoc-number": "IDOC-239839131"
  }
}
----