= Track Transmission Activity

B2B transactions often communicate sensitive contractual obligations between companies. You can use Anypoint Partner Manager to track transmissions and to store both transmission content and metadata.

Anypoint Partner Manager enables you to monitor trading partner transmission activity. _Activity_ is the complete set of end-to-end events related to transmission metadata in processing a transmission. Use transmission metadata to troubleshoot issues.

With activity tracking, you can:

* Search for message metadata (such as partner name, message type, filename, control number, endpoint, or date received).
* View and download the original payload related to the transmission to help you troubleshoot or keep records.
* Review errors and acknowledgment payloads.

== Track Message Flow Activity

Select a message flow to view its transmission details and view and download the payload:

. Open Anypoint Partner Manager.
. In the menu on the left, select *Activity*.
. Locate the message flow whose activity you want to track.
+
Use the search box to find the transmission based on criteria such as:
+
* Trading partner name
* Message type
* Filename
* Control number
* Endpoint
* Received date the file +

. You can then use the filters to find transmissions based on:

* *Type* +
Type of message transmission:
** *Both directions*
** *Sent to partners*
** *Received from partners*
* *From Date* +
Filter for transmissions sent or received after this date.
* *To Date* +
Filter for transmissions sent or received up to this date.
* *Ack Status* +
Filter for transmissions based on their acknowledgment status:
** *All*
** *Overdue*
** *Rejected* +
* *Message Processing Status* +
Filter for transmissions based on their message processing status:
** *All*
** *Delivered*
** *Errored*
** *Processing*
** *Received*
* *Partner name* +
Filter for transmissions based on your partner's name.
* *Partner message type* +
Filter for transmissions based on the message type, such as `X12` or `850`. +
* *Host message type* +
Filter for transmissions based on the host message type, such as `JSON host-purchase-order`.
. Select the transmission that matches your search criteria and review the summary information:
+
* The success or failure status of the transmission (indicated by either a green checkmark for success or a red circle with an exclamation point for failure)
* The name of the received file
* The control number associated with the file (if available)
* The receiving endpoint
* The received date and time of the file
* The types of messages received (depending on the configured message flows)
* The number of messages received in the file
* Transmission flow +
The *Transmission Flow* section of the summary information shows:
* Success or failure of the transmission
* Acknowledgment status +
If the configured outbound message flow expects an acknowledgment from the trading partner or if the configured inbound message flow returns an acknowledgment to the trading partner, then you can view the acknowledgment (997 and TA1) payloads in the transmission detail.
+
If you have not received an acknowledgment from your trading partner or if your trading partner sent a rejection acknowledgment, then you can review the acknowledgment status of outbound transactions.
* Transformation and routing information
+
An exclamation point (!) appearing next to any of the rectangle boxes in the *Transmission Flow* section indicates an issue with the transmission.
. Click *View Payload* to view and download the originally-received payload.
+
You can examine the received payload to troubleshoot issues and find the issue location within the message flow.
+
* For outbound transmissions, you can view the source message payload received from your backend systems and the EDI message sent to your trading partner.
* For inbound transmissions, you can view the received EDI message payload from your trading partner.


== See Also

* xref:edi-ack-reconciliation.adoc[EDI Acknowledgment Reconciliation]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
