= Track Transmission Activity

B2B transactions often communicate contractual obligations between companies. Due to the sensitivity of this information, it is desirable (and often necessary) to track transmissions and store both transmission content and metadata.

Anypoint Partner Manager enables you to monitor trading partner transmission activity. _Activity_ is the complete set of end-to-end events related to transmission metadata in processing a transmission. Use transmission metadata to troubleshoot issues.

With activity tracking, you can:

* Search for message metadata (such as partner name, message type, filename, control number, endpoint, or date received).
* View and download the original payload related to the transmission to help you troubleshoot, or to keep records of transmissions.
* Review errors and acknowledgment payloads.

== Track Message Flow Activity

Select a message flow to view its transmission details and view and download the payload:

. Open Anypoint Partner Manager.
. Select *Activity* from the left navigation menu.
. Locate the message flow for which you want to track the activity. 
+
Use the search box to find the transmission based on criteria such as:
+
* Trading partner name
* Message type
* Filename
* Control number
* Endpoint
* Date the file was received
+
Use the filters to find transmissions based on:
+
* *Type* +
Type of message transmission:
** *Both directions*
** *Sent to partners*
** *Received from partners*
* *From Date*
Filter for transmissions that sent or received after this date. 
* *To Date* +
Filter for transmissions that are sent or received up to this date. 
* *Ack Status* +
Filter for transmissions based on their acknowledgment status:
** *All*
** *Overdue*
** *Rejected*
. Select the transmission that matches your search criteria and review the summary information: 
+
* The status of the transmission, indicated by a green checkmark for a successful transmission, or a red circle with an exclamation point for a failed transmission
* The name of the file that was received
* The control number associated with the file (if available)
* The receiving endpoint 
* The date and time when the file was received
* The types of messages received (depending on the message flows you configured)
* The number of messages received in the file
* Transmission flow +
The *Transmission Flow* section of the summary information shows:
* Success or failure of the transmission
* Acknowledgment status
* Transformation and routing information 
+
If there is an exclamation point (!) next to any of the rectangle boxes in the *Transmission Flow* section, this indicates there is an issue with the transmission.
. Click *View Payload* to view and download the original payload that was received. 
+
Examining the received payload can help you to determine where there might be a problem in the message flow.
+
* For outbound transmissions, you can view the payload of the source message received from your backend systems and the EDI message you sent to your trading partner
* For inbound transmissions, you can view the payload of the EDI message you received from your trading partner.
. You can view the acknowledgement (997 and TA1) payloads from the transmission detail page if the outbound message flow is configured to expect an acknowledgement from the trading partner, or the inbound message flow is configured to return an acknowledgement to the trading partner.
+
You can review the acknowledgement status of outbound transactions when you have not received an acknowledgement back from your trading partner or when your trading partner has sent an acknowledgement indicating a rejection of your message.

== See Also

* xref:edi-ack-reconciliation.adoc[EDI Acknowledgment Reconciliation]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
