= Activity Tracking

B2B transactions often communicate contractual obligations between companies. Due to the sensitivity of this information, it is desirable (and often necessary) to track transmissions and store both transmission content and metadata.

Anypoint Partner Manager enables you to monitor trading partner transmission activity. Activity is the complete set of end-to-end events related to transmission metadata, messages, and errors that are involved in processing a transmission.

Metadata includes things like the date and time the transmission was sent or received, the identity of the partner, and the success or failure of processing.

Common uses for this metadata include:

* Nonrepudiation
* Auditing
* Correlation of acknowledgments
* Error reporting

With activity tracking, you can:

* Search for message metadata (such as partner name, message type, filename, control number, endpoint, or date received).
* View and download the original payload related to the transmission.
* Review errors and acknowledgment payloads.

== Track Message Flow Activity

To track message flow activity:

. Open Anypoint Partner Manager.
. Select *Activity* from the left navigation menu.
. Locate a transmission you are interested in viewing. 
. Use the search box and filters to find the transmission based on criteria such as:
+
* Trading partner name
* Message type
* Filename
* Control number
* Endpoint
* Date the file was received
. Select the transmission that matches your search criteria and review the summary information. +
The summary information contains:
* The status of the transmission, which indicates either a success (green checkmark) or failure (red circle with an exclamation point)
* The name of the file that was received
* The control number associated with the file (if available)
* The endpoint at which the file was received
* The date and time that the file was received
* The types of messages received (depending on the message flows you configured)
* The number of messages received in the file
+
If there is an exclamation point (!) next to any of the rectangle boxes in the *Transmission Flow* section, this indicates there is an issue with the transmission.

The *Transmission Flow* section shows the steps the file was processed in, for example, if:
* The file was successfully received and routed
* An acknowledgement was sent back to the trading partner
* The message was appropriately transformed and routed to the target endpoint 
. Click *View Payload* to view and download the original payload that was received. +
Examining the received payload can help you to determine where there might be a problem in the message flow.

== See Also

* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
