= Tracking Transmission Activity

B2B transactions often communicate sensitive contractual obligations between companies. You can use Anypoint Partner Manager to monitor transmissions, view message contents, and store both transmission content and metadata.

== Locate a Message Flow

Select a message flow to view its transmission details and view and download the message contents:

. In the navigation menu, select *Activity*.
. Search for the message flow.
+
When you search for a message flow, you can filter the results based on the following criteria:

* Message type: `Sent to partners` or `Received from partners`
* Date sent or received
+
You can filter for up to one week's worth of messages at a time.
+
* Acknowledgement status: `Overdue` or `Rejected`
* Messaging processing status: `Delivered`, `Failed`, `Processing`, or `Received`
* Partner name
* Partner message type, such as `X12 - 850`
* Host message type, such as `JSON host-purchase-order`
. Select the transmission to review the summary information and message flow.

== View Details for an Inbound Message

The summary information for an inbound transmission includes the following:

* Transmission status (a green checkmark for success and a red exclamation point for failure)
* Transmission ID
* Name of the transmitted file
* Control number associated with the transmitted file, if available
* Name of the receiving endpoint
* Date and time when the file was received
* Message type
* Number of received messages in the file

Do any of the following to xxx the message contents:

To view the message contents, click *View Payload* and optionally specify a wrap character in the *Wrap at* field.

To download the message contents as an EDI file, click *View Payload* and then click *Download*.



== View Details for an Outbound Transmission

The summary information for an outbound transmission includes the following:

* Transmission status (a green checkmark for success and a red exclamation point for failure)
* Transmission ID
* Date and time when the file was sent
* Control number associated with the transmitted file
* Message type
* Date and time when the file was received
* Name of the transmitted file




== See Also

* xref:edi-ack-reconciliation.adoc[EDI Acknowledgment Reconciliation]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
