= Activity Tracking
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

B2B transactions often communicate contractual obligations between companies.
Due to the sensitivity of this information, it is desirable (and often necessary) to track transmissions and store both transmission content and metadata.
Metadata includes things like the date and time the transmission was sent or received, the identity of the partner, and the success or failure of processing.
Uses for this data include:

* Non-repudiation.
* Correlation of acknowledgments.
* Error correction.
* Auditing.

Anypoint Partner Manager allows you to monitor B2B transmission activity.
Activity is the full set of end-to-end events involved in processing a transmission. This includes transmission metadata, messages, and errors.

You can:

* Search for document metadata (such as partner name, message type, filename, control number, endpoint, or date received).
* View and download the payload information from the transmission.
* Review errors and acknowledgement payloads.
// * Filter to find the specific transmission flow data.

== Track Activity for Message Flows:

. Open Partner Manager.
. From within your Partner Manager environment, select Activity from the left-hand navigation. You see the activity on the message flows you created.
. Scroll the list for the transmission you are interested in. 
If you do not see that transmission, use the search box to find a partner name, message type, filename, control number, endpoint, or date received.
. Select the transmission and review the summary information.
The Transmission Flow section shows the stages of the flow including any acknowledgement you set. If you see an exclamation point in the rectangle box next to one of the stages it means that this is the place where there is an issue with the transmission. Typically, any errors can be viewed in the transmission payload. To inspect the payload:

. Click the *View Payload* button to see the payload transmission.
. Click the *Download* button to download the payload for analysis.
. Continue for any other transmission.

// Refer to the Troubleshooting section for common message flow errors.

== See also

