= Activity Tracking
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

B2B transactions often communicate contractual obligations between companies.
It is desirable (and often necessary) to track transmissions that are sent or received and store the transmission content as well as any metadata.
Metadata can be the date and time the transmission was sent or received, the identity of the partner, and the success or failure of processing.
Some uses for this data include:

* Non-repudiation.
* Correlation of acknowledgments.
* Error correction.
* Auditing.

Anypoint Partner Manager enables you to monitor B2B transmission activity.
Activity is the full set of end-to-end events (including transmission meta data, messages, and errors) involved in processing a transmission.

You can:

* Search for document metadata (such as filename, control number, endpoint, or date received).
* Filter to find the specific transmission flow data.
* View and download the payload information from the transmission.
* Review and monitor errors and acknowledgements.

== Track Activity for Message Flows:

. Open Partner Manager.
. From within your Partner Manager environment, select Activity from the left-hand navigation. You see the activity on the message flows you created.
. Scroll the list. If you don't see the desired message flow, type a filename, control number, endpoint, or date received in the search box.
. Select the message flow. You see a summary with the File name, Control Number, Endpoint, and date and time the transmission was received.
The Transmission Flow section shows the stages of the flow. If you see an exclamation point next to one of the stages it means that this is the place where there is an issue with the activity.
. Click the *View Payload* button to see the payload transmission.
. Click the *Download* button to download the payload for analysis.
. Continue for any other message flow.

Refer to the Troubleshooting section for common message flow errors.

== See also
