= Use Anypoint Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Partner Manager enables you to manage the transmission of business messages with a large number of trading partners through the creation and deployment of message flows.
A message flow is the path along which a message travels from its source, through a DataWeave transformation map, to its target.

You'll need to perform some tasks before you can begin transmitting messages with your trading partners.
A transmission is a single communication event during which a payload is transferred between two business entities. These payloads can contain one or more business messages.

In anypoint Partner Manager, you set yourself up as a host partner, configure your trading partners, and then create message flows between you and your trading partners.

== Prepare to Configure Anypoint Partner Manager

Before you configure your message flows to send and receive messages with your trading partners, you'll need to collect some information from them.
You’ll also need to have an understanding of how your backend systems work.

Information you'll need about your organization:

* Your organization's identifiers (such as the AS2 ID, X12-ISA, X12 GS, and so on).

* Endpoints: There are three types of endpoints within AnyPoint Partner Manager -

** Receive endpoints - On the Host side, to receive a transmission from your trading partner you need endpoints that your organization reveals to your trading partners.

** Target endpoints - As the Host, your organization has internal endpoints where you route messages from the trading partner, after they are transformed within the message flow.

** Acknowledgement endpoints - Your partners provide you with endpoint configurations that can be used by you to send acknowledgement messages (like a X12 997 or a X12 999) back to them.
Acknowledgements are typically sent back to trading partners based on one or more B2B messages that you receive from them.

* Your digital certificates (such as an X.509 certificate).

* Electronic Data Interchange (EDI) message type preferences for your organization.

* DataWeave transformation maps your organization uses for B2B transformations.

Information you need about each trading partner:

* The trading Partners name (usually the name of the company).

* Partner identifiers (such as the AS2 ID, X12-ISA, X12 GS, and so on).

* Partner endpoints (where you send transmissions to your partners, including acknowledgement endpoints).

* EDI message format preferences for your partner (such as X12), and any associated validations such as the need for acknowledgments (like TA1, 997, 999, and so on).

* Message types to use. For example, a purchase order in X12 is an 850 message. You also need to know the X12 version to use in your transactions (such as 004010, 005010, and so on).

* Your Trading Partner's digital certificates (such as an X.509 certificate).

After gathering this information, you are ready to configure yourself as host, configure your trading partners, and create a message flow.


// == See Also

// * xref:configure-host.adoc[Configure Host]
