= Use Anypoint Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Partner Manager enables you to manage a large number of trading partners and their message flows. A message flow is the path along which a message travels, from its source, through a transformation (via a DataWeave map), and to its target. 

You'll need to perform some tasks before you can begin transmitting messages with your trading partners. A transmission is a single communication event during which payload transfer sometimes requires more than one message. Even though a transmission is a single communication event, it sometimes requires more than one message (or X12 transaction set) to transfer payload.

You set yourself up as a host partner, configure your partners, and then create message flows between you and your partners.

== Prepare to Configure Anypoint Partner Manager

Before you configure your message flows to send and receive messages with your partners, you'll need to collect some information from them. You’ll also need an understanding of how your backend systems work.

Information you'll need about your organization:

* Your organization's identifiers (such as the AS2 ID, X12 ISA, X12 GS, and so on)

* Endpoints: There are three types of endpoints within AnyPoint Partner Manager -

** Receive endpoints - On the Host side, for an inbound transmission you need endpoints your organization uses to receive transmissions from your partners. These endpoints are resources your organization exposes to your trading partners.

** Target endpoints - As the Host, your organization has internal endpoints where you route messages from the trading partner, after they are transformed within the message flow.

** Acknowledgement endpoints - Your partners provide you with endpoint configurations that can be used to send acknowledgement messages like 997s or 999s back to them. Acknowledgements are typically sent back to trading partners corresponding to one or more B2B messages you receive from them.

* Your digital certificates (such as X.509)

* Electronic Data Interchange (EDI) message type preferences for your organization

* A storage solution to store your B2B message payloads

* Dataweave transformation maps your organization uses for B2B

Information you need about each trading partner:

* Partner name (usually the name of the company)

* Partner identifiers (such as the AS2 ID, X12 ISA, X12 GS, and so on)

* Partner endpoints (where you send transmissions to your partners, including acknowledgement endpoints)

* EDI message format preferences for your partner (such as X12), and any associated validations that require an acknowledgment (such as TA1, 997, 999, and so on)

* Message types to use. For example, a purchase order in X12 is an 850 message. You also need to know the X12 version to use in your transactions (such as 004010, 005010, and so on).

* Partner digital certificates (such as X.509)

After gathering this information, you are ready to configure yourself as host, configure your partners, and create a message flow.


// == See Also

// * xref:configure-host.adoc[Configure Host]
