= Partner Manager Configuration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Overview
Partner Manager allows you to enable your system to receive a wide range of messages from your partners by dynamically applying rules and configuration data. You can support new transaction types without having to develop, test, or deploy new Mule Runtime flows.

First, you set yourself up as a host partner, then you create a message flow between your partner and yourself. The message flow is the path along which the message travels from a source through the map to its target. 
The single communication between two trading partners containing one or more messages is called a transmission. 

The setup steps are: Receiving partner info > receiving endpoint > source message type > document map > target host.

For example, a distributor could group a set of purchase orders sending them in one transmission to a supplier trading partner.

== Partner Manager Setup Checklist

Before you set up your message flows to send and receive messages with your partners, you'll need to collect some information from them. You’ll also need to understand how your backend systems work. Use this checklist to help organize the information you need to gather for entering into AnyPoint Partner Manager later.

* Information you'll need as the host organization:

** Endpoints, depending on the direction of interactions with your partner.

** Identifiers (such as the AS2 Identifier, X12 ISA, and so on).

** The digital certificate (such as X.509).

** EDI message type preferences for your organization. [Example?]

** Storage for your B2B message payloads.

* Information needed for each trading partner:

** Partner name (usually the name of the company).

** Identifiers (such as the AS2 Identifier, X12 ISA, and so on).

** Message formats to send to one another (such as X12, and so on), and any associated validations with the need for acknowledgment (such as TA1, 997, 999, and so on).

** Message types to use. For example, a purchase order in X12 is an 850 mesage. You also need to know which X12 version to use in your transactions (such as 004010, 005010, and so on).

** The digital certificate (such as X.509).

** Endpoints, depending on the direction of interactions (send/receive) you want to have with your partner.

== See Also

* xref:create-receive-message-flow.adoc[Create Receive Message Flows]
* xref:activity-tracking.adoc[Activity Tracking]


