= B2B Solutions and Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Overview

B2B (Business-to-Business) is the use of API's or Electronic Data Interchange (EDI) by enterprises to carry out business transactions such as purchasing goods from one another. B2B messages are typically sent over transports such as HTTP(s), FTP, FTPS, SFTP, JMS, and exchanges such as AS2. MuleSoft's B2B solutions integrate seamlessly into the Mule runtime.

== Anypoint Partner Manager

Through its web interface, Anypoint Partner Manager enables effective setup and management of a large number of trading partners. Additionally, via the ability to track and report on transaction progress, Partner Manager drives greater operational efficiency while managing B2B transactions. With Anypoint Partner Manager you can:

* Perform technical on-boarding of partners.
* Set up message flows to receive and send messages between your backend systems and your partners.
* View and monitor how partner messages are being processed in the system in case of failure in order to take corrective action.

== Available Message Formats

ANSI X12, X12 HIPAA

== Transport Protocols Used

SFTP

== Types of Exchanges

AS2

|===
