= Central Pane Elements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::partial$include-v1-eol.adoc[]

== Dashboard

* Top of Central Pane
* Provides data for the timeframe you select in the <<Overview for _timeframe_ Dropdown List>> at the upper left.

=== Overview for _timeframe_ Dropdown List

Enables you to present data specific to the following timeframes:

* *Today*
* *Past 48 Hours*
* *This Week*
* *This Month*

The default is *Today*.



==== Dashboard Data

Between the <<Overview for _timeframe_ Dropdown List>> and the <<View Dropdown List>>, Dashboard Data is presented in two forms:

Numerical form:: The actual number

Pie chart::
* A representation of the data as a percentage of all data of that type over that time frame. It is split by the different sections of said data.
* When you hover over or click on a section of the error pie chart, the section illuminates and provides the number corresponding to that section.
* When you click a section of the piechart, the content area will apply necessary filters to display the corresponding data

=== View Dropdown List

This menu, just above the <<Filter Bar>> grid, presents the following view choices:

* *Transactions*
* *Transmissions*
* *Errors*
* *Documents*

The type of data that appears in the <<Content Area>> depends on the menu option you choose here.

=== Filter Bar

* Enables users to filter the results of a view.
* Consists of Dropdown Filter lists that enable you to specify the criteria by which you want to filter.
* Which specific Dropdown Filter Lists appear depends on the value in the <<View Dropdown List>>.
* Any of the type-able fields will auto-filter as you type into them. In some cases, copying and pasting the value may be helpful.

==== To Clear a Filter

. Click the Dropdown Filter List you want to clear.
+
The Filter List appears.
. At the top right of the Filter List, click the *clear* button.

==== To Clear All Filters

. In the Filter Bar, click the *Clear Filters* button.


=== Content Area

A table appears in the lower part of the Central Pane. Table column headings depend on  on the choices you make in the <<Overview for _timeframe_ Dropdown List>> and the <<View Dropdown List>>.

The following views are possible:

* xref:transactions-view.adoc[Transactions View]
* xref:transmissions-view.adoc[Transmissions View]
* xref:errors-view.adoc[Errors View]
* xref:documents-view.adoc[Documents View]
