= Certificate Settings

All certificates in Anypoint Partner Manager are securely stored in Anypoint Platform's secrets manager, which uses a secure vault technology to store and control access to private keys, passwords, certificates, and other secrets.

Configure your SSL certificate settings based on your certificate needs.

The information provided for each certificate includes:

* *Authority* +
Certificate provider
* *Serial Number* +
Serial number from the certificate
* *Status* +
Active is shown with a green icon or Inactive is shown with a red icon. +
* *Start Date* +
Date from when the certificate is valid
* *Expires* +
Date after which the certificate is no longer valid 
* *Endpoints* +
Number of endpoints where the certificate is used
* *Message Flows* +
Number of message flows that use the certificate

In Partner Manager, you can:

* Use a CA-signed certificate. +
You do not need to upload an additional certificate because this endpoint already uses a CA-signed certificate. +
* Upload your own, self-signed certificate. +
You can upload a new certificate (in `<certifcate name>.PEM` format), or view all the certificates available for use with this endpoint setup. 
* Enable an insecure connection for local testing that doesn’t perform certificate validation by selecting *Allow insecure connection*. 

== Adding PEM Certificates

You can add certificates from the Host or Partner page.

. In Partner Manager's left navigation, select *<host name>* or *Partners*.
. In the *Certificates* section, click *New*. 
. Click *Choose file* to upload a PEM certificate. 
. Click *Upload Certificate*.

== Deleting Certificates

You can delete certificates that are not deployed or associated with endpoints. 

You cannot delete a certificate if it is the only certificate that is uploaded.

To delete a certificate:

. In Partner Manager's left navigation, select *<host name>* or *Partners*.
. In the *Certificates* section, click the certificate to delete.
. In the dialog window, click *Delete*.

