== Certificate Settings
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


You can configure your SSL certificate settings based on your certificate needs.
All certificates in Anypoint Partner Manager are securely stored in Anypoint platform's secrets manager.
It uses a secure vault technology to store and control access to private keys, passwords, certificates, and other secrets.

You can:

* Use a CA-signed certificate where no upload is necessary. +
You do not require an additional certificate because this endpoint already uses a CA-signed certificate. +

* Upload your own, self-signed certificate. +
You can upload a new certificate (in `.PEM` format), or view all the certificates available for use with this endpoint setup. +

* Enable an insecure connection for local testing that doesn’t perform certificate validation. +
You can use Allow insecure connection. +

Information provided for each certificate: +

`Authority` is the certificate provider. +

`Serial Number` is from the certificate. +

`Status` Active is shown with a green icon or Inactive is shown with a red icon. +

`Endpoints` are the number of endpoints where it is used. +

`Start Date` is the date from when the certificate can be used. +

`Expires` is the date from when the certificate can no longer be used. +

`Days to expiration` is the countdown to the expiration date. +
