== Certificate Settings
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


You can configure your SSL certificate settings based on your certificate needs. All certificates in Anypoint Partner Manager are securely stored in Anypoint platform's secrets manager that uses a secure vault technology to store and control access to private keys, passwords, certificates, and other secrets.

You can:

* Enable an insecure connection for local testing that doesn’t perform certificate validation. +
Use Allow insecure connection. +

* Use a CA-signed certificate where no upload is necessary. +
Use the option: Do not require an additional certificate because this endpoint already uses a CA-signed certificate. +

* Upload your own, self-signed certificate. +
Upload a new certificate (`.PEM` format), or view all the certificates available for use with this endpoint setup. +

Information provided for each certificate: +

`Authority` is the certificate provider. +

`Serial Number` is from the certificate. +

`Status` Active is shown with a green icon or Inactive is shown with a red icon. +

`Endpoints` are the number of endpoints where it is used. +

`Start Date` is the date from when the certificate can be used. +

`Expires` is the date from when the certificate can no longer be used. +

`Days to expiration` is the countdown to expiration date. +

// One example might be that you may need your partner’s digital certificate - such as an X.509 certificate in the PKCS12 file // format for the AS2 transport protocol.
=======
You can configure your SSL certificate settings based on your certificate needs. You can:

* Enable an insecure connection for a local testing that doesn’t perform certificate validation. +
Use Allow insecure connection. +

* Use a CA-signed certificate where no upload is necessary. +
Use the option: Do not require an additional certificate because this endpoint already uses a CA-signed certificate. +

* Upload your own, self-signed certificate. +
Upload a new certificate (`.PEM` format), or view all the certificates available for use with this endpoint setup. +

Information provided for each certificate: +

`Authority` is the certificate provider. +

`Serial Number` is from the certificate. +

`Status` Active is shown with a green icon or Inactive is shown with a red icon. +

`Endpoints` are the number of endpoints where it is used. +

`Start Date` is the date from when the certificate can be used. +

`Expires` is the date from when the certificate can no longer be used. +

`Days to expiration` is the countdown to expiration date. +

// One example might be that you may need your partner’s digital certificate - such as an X.509 certificate in the PKCS12 file // format for the AS2 transport protocol.

