= Certificate Settings

*Vijay, can you help with this introductory material*? We may want to introduct keystores here as well - I am not sure.*

All certificates in Anypoint Partner Manager are securely stored in the Anypoint Platform secrets manager, which uses secure vault technology to store and to control access to private keys, passwords, certificates, and other secrets.

In Partner Manager, you can:

* Use a CA-signed certificate. +
If an endpoint is currently using a CA-signed certificate, you do not need to upload an additional certificate. +
* Upload your own, self-signed certificate. +
You can upload a new certificate (in `<certifcate name>.PEM` format) or view all the certificates available for use with this endpoint setup.
* Enable an insecure connection for local testing that doesn’t perform certificate validation by selecting *Allow insecure connection*.


== See Also

* xref:manage-as2-host-keystores.adoc[Managing AS2 Host Keystores]
* xref:manage-as2-partner-certificates.adoc[Managing AS2 Partner Certificates]
