= Certificate Settings

You can configure your SSL certificate settings based on your certificate needs.

All certificates in Anypoint Partner Manager are securely stored in Anypoint Platform's secrets manager, which uses a secure vault technology to store and control access to private keys, passwords, certificates, and other secrets.

The information provided for each certificate includes:

** *Authority* +
Certificate provider
** *Serial Number* +
Serial number from the certificate
** *Status* +
Active is shown with a green icon or Inactive is shown with a red icon. +
** *Start Date* +
Date from when the certificate is valid
** *Expires* +
Date after which the certificate is no longer valid 
** *Endpoints* +
Number of endpoints where the certificate is used
** *Message Flows* +
Number of message flows that use the certificate

You can:

* Use a CA-signed certificate. +
You do not need to upload an additional certificate because this endpoint already uses a CA-signed certificate. +
* Upload your own, self-signed certificate. +
You can upload a new certificate (in `<certifcate name>.PEM` format), or view all the certificates available for use with this endpoint setup. 
* Enable an insecure connection for local testing that doesn’t perform certificate validation by selecting *Allow insecure connection*. 

== Adding PEM Certificates

You can add certificates from the Host or Partner page.

. Select *<host name>* or *Partners* from the navigation menu on the left. 
. In the *Certificates* section, click *New*. 
. Click *Choose file* to upload a PEM certificate. 
. Click *Upload Certificate*.

== Deleting Certificates

You can delete certificates that are not deployed or associated with endpoints. 

If a single certificate is uploaded, Partner Manager prevents you from deleting your only certificate.

