= Certificates
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Certificate Settings

You can adjust your certificate settings as needed for the level of security.
When using Certificates you are:

* uploading your own, self-signed certificate
* using a CA certificate
* not using any at all

For example, you may need your partner’s digital certificate such as an X.509 certificate in PKCS12 file format for the AS2 transport protocol.

[%header,cols="3s,7a"]
|===
|Name |Description
|Allow insecure connection
|Can be used for local testing which doesn’t perform certificate validation. +

|Do not require an additional certificate because this endpoint already uses a CA-signed certificate:
|This endpoint already uses a CA-signed certificate and does not require an additional certificate. +

|Certificates
|Upload a new certificate (.PEM format), or view all certificates available for use with this endpoint setup. +
Information provided for each certificate: +

`Authority` - certificate provider +

`Serial Number` - from the certificate +

`Status` - Active is shown with a green icon or Inactive is shown with a red icon +

`Endpoints` - the number of endpoints used +

`Start Date` - from when the certificate can be used +

`Expires` - the date from which the certificate can no longer be used +

`Days to expiration` - countdown to expiration date +

|===
