= Partner Manager CloudHub 2.0 Migration Guide

To migrate your B2B operations from CloudHub 1.0 (CH1) to the more advanced CloudHub 2.0 (CH2), follow the relevant path in this guide based on your deployment scenario.

== Migration With VPC and DLB with URL Preservation

. Follow the steps on the xref:runtime-manager::vpc-upgrade.adoc[] page to upgrade your CH1 Anypoint Virtual Private Cloud (Anypoint VPC) to a CH2 private space.
. In Runtime Manager:
.. Stop all inbound Partner Manager applications deployed to CH1.
.. Make sure you don't have any inflight messages.
.. Delete these Partner Manager deployed applications but not the `inbound-as2` and `inbound-http` applications:
... b2b-outbound-*
... b2b-document-processing-service-*
... b2b-api-replication-service-*
. On the Partner Manager tab in Access Management > Business Groups:
.. Click *Edit Configuration* for the environment you want to update.
.. Select CloudHub 2.0 from the *Deployment Target Type* dropdown.
.. In the *Deployment Target* dropdown, select the private space that was configured previously.
.. Before saving, open your browser's developer tools and navigate to the *Network* tab to make sure the Method column is enabled.
.. Click *Save* in Access Management.
.. Check the *I understand the effects of this action* box and click *Save*. Ignore the error message about the target runtime type.
. In your browser's developer tools:
.. Right-click on the most recent PUT request, and then hover over *Copy* and select *Copy as CURL*.
.. Paste the CURL command into your preferred API Client, such as  Postman. Set *forceUpdate* to True by updating the URL.
.. Send the PUT request.
. In Access Management, refresh the Partner Manager tab. The deployment target is now CH2.
. In Runtime Manager, start the `inbound-as2` and `inbound-http` applications.
[NOTE]
Incoming messages are delivered to Anypoint MQ but aren't processed until the CH1 app is running. For the app switching to work, ensure the CH1 app is in a Running state.

. Use the CH1 to CH2 migration tool xref:runtime-manager::app-migration.adoc[] to upgrade the deployment for the `inbound-as2` and `inbound-https` applications, which creates their counterparts in CH2.
.. Make sure the name remains the same.
.. Use a dummy jar file with the same name, "dummy jar."
.. Preserve the ingress urls. Initially, the name resolution is 0% for CH2 and 100% for CH1.
. On the Message Flows tab in Partner Manager:
.. Click Manage Deployments and choose either Upgrade deployments or Apply environment settings.
.. Check *I understand the effects of these actions* and click *Confirm*.
+
Partner Manager deploys and updates the corresponding apps in CH2 that were deployed with dummy jar files.
+
Before shifting traffic, keep the CH1 inbound AS2 and HTTP applications running and handling 100% of the traffic to confirm they're functioning as expected post-migration.
. In Runtime Manager, increase the traffic on the CH2 app incrementally over a period of a few days until it reaches 100%. Keep the CH1 apps in a Shutdown status after traffic reaches 100%.
. After you've stopped all CH1 applications that use the DLB, failover the DLB domain (anypointdns.net) to CH2 and delete the DLB.

New message flow deployments in Partner Manager beyond this point only update the CH2 apps.


== Migration With VPC and DLB but Without URL Preservation

. Follow the steps on the xref:runtime-manager::vpc-upgrade.adoc[] page to upgrade your CH1 Anypoint VPC to a CH2 private space.
. In Runtime Manager:
.. Stop all inbound Partner Manager applications deployed to CH1.
.. Make sure you don't have any inflight messages.
.. Delete these Partner Manager deployed applications:
... b2b-inbound-*
... b2b-outbound-*
... b2b-document-processing-service-*
... b2b-api-replication-service-*
. On the Partner Manager tab in Access Management > Business Groups:
.. Click *Edit Configuration* for the environment you want to update.
.. Select CloudHub 2.0 from the *Deployment Target Type* dropdown.
.. In the *Deployment Target* dropdown, select the private space that was configured previously.
.. Before saving, open your browser's developer tools and navigate to the *Network* tab to make sure the Method column is enabled.
.. Click *Save* in Access Management.
.. Check *I understand the effects of this action* and click *Save*. Ignore the error message about the target runtime type.
. In Developer Tools:
.. Right-click on the most recent PUT request, and then hover over *Copy* and select *Copy as CURL*.
.. Paste the CURL command into your preferred API Client, such as  Postman. Update the URL so that *forceUpdate* is set to True.
.. Send the PUT request.
. In Access Management, refresh the Partner Manager tab. The deployment target is now CH2.
. On the Message Flows tab in Partner Manager:
.. Click *Manage Deployments* and choose either Upgrade deployments or Apply environment settings.
.. Check *I understand the effects of these actions* and click *Confirm*.
+
Partner Manager deploys and updates the corresponding apps in CH2 that were deployed with dummy jar files.

New message flow deployments in Partner Manager beyond this point only update the CH2 apps.

== SLB Migration to a Private Space

. In Runtime Manager:
.. Stop all inbound Partner Manager applications deployed to CH1.
.. Make sure you don't have any inflight messages.
.. Delete these Partner Manager deployed applications:
... b2b-inbound-*
... b2b-outbound-*
... b2b-document-processing-service-*
... b2b-api-replication-service-*
. On the Partner Manager tab in Access Management > Business Groups:
.. Click *Edit Configuration* for the environment you want to update.
.. Select CloudHub 2.0 from the *Deployment Target Type* dropdown.
.. In the *Deployment Target* dropdown, select the private space or shared space.
.. Before saving, open your browser's developer tools and navigate to the *Network* tab to make sure the Method column is enabled.
.. Click *Save* in Access Management.
.. Check the *I understand the effects of this action* box and click *Save*. Ignore the error message about the target runtime type.
. In Developer Tools:
.. Right-click on the most recent PUT request, and then hover over *Copy* and select *Copy as CURL*.
.. Paste the CURL command into your preferred API Client, such as Postman. Update the URL so that *forceUpdate* is set to True.
.. Send the PUT request.
. In Access Management, refresh the Partner Manager tab. The deployment target is now CH2.
. On the Message Flows tab in Partner Manager:
.. Click *Manage Deployments* and choose either Upgrade deployments or Apply environment settings.
.. Check *I understand the effects of these actions* and click *Confirm*.
+
Partner Manager deploys and updates the corresponding apps in CH2 that were deployed with dummy jar files.

New message flow deployments in Partner Manager beyond this point only update the CH2 apps.
