= CloudHub Deployment Settings

If you are deploying Partner Manager applications to CloudHub, use the *Partner Manager Settings* page in access management to specify CloudHub deployment options for the sandbox and production environments, including the Mule runtime engine (Mule) version, CloudHub region, Anypoint MQ region, and so on.

== Access Partner Manager Settings

To access the deployment settings for your organization:

. In Anypoint Platform, navigate to *Access Management*.
. From Access Management navigation menu, select *Settings > Partner Manager*. +
On the *Partner Manager Settings* page, you can configure the following settings:

=== Mule Version Setting

Specify the Mule version to use to deploy your application in the *Runtime version* drop-down menu.

The default is *Use latest version*, which deploys new Partner Manager message flows using the latest Mule version.

Otherwise, deploy Partner Manager applications to a specific Mule version by selecting that version from the drop-down list.

=== CloudHub Region Setting

The default CloudHub region is automatically retrieved from the business group’s *Runtime Manager General Settings* region setting in access management.

If you want to change the default CloudHub region, you must select the new region before you deploy your first message flow. The CloudHub region you specify for the first deployment becomes the default setting for subsequent deployments.

To change the default CloudHub region:

. Undeploy message flows that are deployed to the currently specified CloudHub region.
. Redeploy the message flows after you specify a new default region.

=== Anypoint MQ Region

This is automatically assigned, based on the specified CloudHub region; you cannot change it.

=== Automatically Restart the App

To have CloudHub automatically restart your application when the monitoring system discovers an issue, select the *Automatically restart app when not responding* checkbox.

=== vCore Settings

Configure the following vCore settings for the sandbox and production environments:

* *Each B2B endpoint (inbound, outbound, and ack)*
+
Partner Manager deploys a generic Mule app to the runtime for each endpoint protocol and direction (receive or send) combination. Each runtime app requires a minimum of 0.1 vCore.
+
* *B2B DocumentProcessingService*
+
This core component of the Partner Manager workflow requires a minimum of 0.2 vCore.
+
* *B2B APIReplicationService*
+
This core component of the Partner Manager workflow requires a minimum of 0.2 vCore.

To have CloudHub automatically deploy newly created HTTP, HTTPS, and AS2 endpoints to a private port, select the *Deploy HTTP/AS2 apps to private port* checkbox.

For assistance with sizing, contact your MuleSoft account representative.

== See Also

* xref:message-flows.adoc[Partner Manager Message Flows]
* xref:configure-message-flows.adoc[Create Inbound Message Flows]
* xref:create-outbound-message-flow.adoc[Create Outbound Message Flows]
