= CloudHub Deployment Options
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Partner Manager message flows are initially deployed by default to the CloudHub region specified in the default
settings of Access Manager's business group. Subsequent deployments are deployed to the same region as the first deployment.

To access the deployment settings for your organization, navigate to *Access Management > Partner Manager*.

* Runtime version

The default and recommended option is `Use latest version`, which deploys new Partner Manager message flows by using the latest Mule runtime version.
If you want the applications deployed to another version, choose it from the menu.

* CloudHub region

The default option is retrieved from the business group’s default region setting for Runtime Manager in Access Manager.
If you want the B2B integration flows from Partner Manager to be deployed to a different region,
select it from the drop-down menu prior to deploying your first message flow.

Subsequent deployments get deployed to the same region as the first deployment.
To change the default region and have it persist as the default, you must undeploy and redeploy any previously deployed message flows.
For more information about undeploying message flows, refer to xref:configure-message-flows.adoc[Configure Message Flows].

* Anypoint MQ region

This is automatically assigned, based on the CloudHub region; you cannot change it.

* Automatically restart app when not responding

CloudHub automatically restarts your application when the monitoring system discovers an issue.

* vCore settings

Configure these at the sandbox or production environment type.
The `Document Processing` and `API Replication` services are core components of the Partner Manager workflow,
requiring a minimum of 1 vCore each. Each unique trading partner and internal endpoints get deployed to isolated workers - requiring a minimum of 0.1 vCore each.
If you require assistance with sizing, contact your account representative.
