= Create a Receive Message Flow from Your Partner
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Message flow diagram here to show all the stages? - Inbound transmission > validate transmission payload > route to message flows > route through message flows

When receiving a B2B message from your trading partner, in cases where there may be more than one URL, you only need to configure the receiving URL.
If a separate URL is required for returning MDNs, it is sent in the AS2 transmission and Partner Manager reads it from there.

== Set up Receive from a Partner

. Open Partner Manager. To find a partner, search the Partners list by name, and select the name of the partner.
. From within your Partner Manager environment (either Sandbox or Production), select *Message Flows* from the left-hand navigation.
. Click the *New Message Flow* button and select a partner from the list and click the *Select* button.

You see the named Message Flow with a dialog that allows you to enter the following information:

* Partner Receiving Endpoints (required) - where you send transmissions to your partners, including acknowledgements.

* Message types to use. For example, a purchase order in X12 is an 850 message.

* Any Dataweave transformation maps your organization uses for EDI.

* The Target Message type for the type of document. For example, a purchase order in X12 is an 850 message.
You also need to know the X12 version to use in your transactions (such as 004010, 005010, and so on).

* The Target Endpoint

There are three types of endpoints within AnyPoint Partner Manager.

From the Host side:

* To receive transmissions from your partners

* Where you route messages from your partners to a target at your backend systems.

* Sources of messages from your backend system that you send to your partners.

From the Partner side:

* Where you send transmissions to your partners, including acknowledgments.

Refer to the Endpoints for AS2, SFTP, or HTTP(s) for more information.

* Click the *Deploy* button when you are ready to make the created flow live.

You can begin to monitor the activity from the Activity page.

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:activity-tracking.adoc[Activity Tracking]

// == Create a Send Message Flow from Your Partner
