= Create a Receive Message Flow from Your Partner
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To receive messages from a trading partner, create a message flow and configure the sections for the source, target, and mapping.
Your organization is typically referred to as the host. The enterprise you interact with is referred to as your trading partner.

The source of the message flow is defined by the partner, a host endpoint, often an API, and the message type you are receiving from them.

The target is the final destination of a message flow and is defined by a host message type and endpoint, often a Host API.

You'll need the following for the Source:

* The trading partner's name and associated identifiers (such as X12 ISA, X12 GS, and so on).

* The endpoint where you receive the transmission.

* The message type to process for this message flow (such as X12, 4010, 850, and so on).

* The endpoint where your trading partner may want to receive an acknowledgment related to the messages they send.

* The DataWeave map that transforms the received message contents into a format you can use.

You'll need the following for the Target:

* The message type your system understands. This is also the format that DataWeave map transforms received messages into.

* The endpoint in your organization where you route the transformed message.

If a separate URL is required for returning MDNs, it is sent in the AS2 transmission and Anypoint Partner Manager reads it from there.

== Set up Receive from a Partner

. From within your Anypoint Partner Manager environment (either Sandbox or Production), click *New message flows* from the left-hand navigation.

. To Select an Existing Partner from the *Select a partner* dialog, search for the trading partner by name.

. Once you find a match, choose the partner name and click *Select*.

Clicking each section of the message flow expands it. A green checkmark next to any a section indicates that it is complete.

* Alternatively, to create a new Trading Partner

. In the *Select a partner* dialog,, click *New* button.

. Provide the trading partner's name and create at least one identifier (such as X12 ISA, X12 GS, and so on).

. Once you have provided the information you need, click *Create Partner and Message Flow*.

Once your trading partner is created, you can configure your message flow to receive messages from the selected trading partner or add more information.

[start=4]
. Configure the source endpoint where you receive the transmission by clicking *Receiving endpoint* section to expand it and click *select*.

. Search and select an existing endpoint and click *Select*, or create a new endpoint.

. To create a new endpoint, depending on the protocol, refer to the following:

* <<AS2 Send Settings>>

* <<SFTP Send Settings>>

[start=8]
. Select the source message type by clicking the *Source message* section to expand it.

. Click *Select* and either search and select an existing message type, or create a new message type.

. To create a new message type, depending on the message standard, refer to the following:

* xref:document-type.adoc[Message (Document) Types]

[start=11]
. Configure acknowledgments (optional, only if the partner requires them for X12 messages), the type of acknowledgment, and the endpoint to which you send it.
Refer to the following information:

* <<HTTP(s) Protocol Send Settings>>

* <<HTTP Protocol Send Settings>>

. Upload a DataWeave map. Click the *Map* section to expand it and click *Import* to choose a DataWeave map and click *Upload mapping*.

. Click the *Target at <Partner name>* section and click *Select* button to set up a target message type.
This is the target message type and the Endpoint where you want to route the transformed message.

. Either search and select an existing message type, or create a new message type.

. To create a new message type, depending on the message standard, follow instructions in one of these sections.

* xref:document-type.adoc[Message (Document) Types]
[start=17]
. Set up a target endpoint by clicking *Select*.

. Either search and select and existing endpoint, or create a new endpoint.

. To create a new endpoint, depending on the protocol, refer to the following:

* <<SFTP Send Settings>>

* <<HTTP(s) Protocol Send Settings>>

* <<HTTP Protocol Send Settings>>

When you complete all of the sections - they will have a green check mark next to all of them in the flow, you can deploy your message flow and start receiving messages from your partner.
[start=20]
. Click *Deploy* when you are ready to deploy the configurations to your Mule Runtime.
If your message flow does not deploy right away, wait a bit and try again.

You can begin to monitor the activity from the Activity page.

== See Also

* xref:endpoints.adoc[Endpoints]
// * xref:activity-tracking.adoc[Activity Tracking]

// == Create a Send Message Flow from Your Partner
