= Create a Receive Message Flow from Your Partner
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To receive messages from a trading partner, create a message flow and configure the sections for both the source and target. Your organization is typically referred to as the `host`, while the partner you interact with is refered to as a `trading partner`.

For the receiving endpoint - this is the origin of the message flow when defined by a host endpoint and message type, often an API. For the target endpoint - this is the final destination of a message flow when defined by a host endpoint and message type, often a Host API.

You'll need the following for the Source:

* The trading partner and associated identifiers (such as X12 ISA, X12 GS, and so on)

* The endpoint where you receive the transmission

* The message type to process for this message flow (such as X12 4010 850 and so on)

* The endpoint where your trading partner may want to receive an acknowlegement related to the transactions they send

* The DataWeave map that transforms the received message contents into a format you prefer

You'll need the following for the Target:

* The message type your system understands. This is also the format that dataweave transforms received messages into

* The endpoint in your organization where you route the transformed message

If a separate URL is required for returning MDNs, it is sent in the AS2 transmission and Partner Manager reads it from there.

== Set up Receive from a Partner
[start=1]
. From within your Anypoint Partner Manager environment (either Sandbox or Production), select *Message Flows* from the left-hand navigation.

. Click the `New Message Flow` button and select a trading partner from the list and click the `Select` button. You can also choose to create a new trading partner by clicking the `New` button.

TIP: You can expand each section of the message flow by clicking it. A green checkmark next to any a section indicates that it is complete.

* Selecting an existing trading partner
** In the `Select a partner` modal window, search for the trading partner by their name. Once you find a match, click on the corresponding row, and proceed to click on the `Select` button
** Now proceed to configure your message flow to receive messages from the selected trading partner

* Creating a new trading partner
** In the `Select a partner` modal window, click on the `New` button
** in the ensuing modal window, provide the trading partners name and create at least one identifier (such as X12 ISA, X12 GS, and so on)
** Once you have provided the information needed, click on the `Create Partner and Message Flow` button
** Now proceed to configure your message flow to receive messages from the selected trading partner

[start=3]
. Configure the source endpoint where you receive the transmission. Click on the `Receiving endpoint` section to expand it. Within this section click on the `select` button. In the ensuing modal window, proceed to either search and select and existing endpoint, or create a new endpoint. To create a new endpoint, depending on the protocol, follow instructions below
** Setting up SFTP receiving endpoint
** Setting up AS2 receiving endpoint

. Select the source message type. Click on the `Source message` section to expand it. Within this section, click on the `select` button. In the ensuing modal window, proceed to either search and select and existing message type, or create a new message type. To create a new message type, depending on the message standard, follow instructions below
** Setting up X12 message type
** Setting up JSON message type

. Configure acknowledgments (optional, only if the partner requires them for X12 messages), the type of acknowledgment, and the endpoint to which you send it

. Upload a DataWeave map. Click on the `Map` section to expand it. Within this section, click on the `import` button and upload a dataweave map. Click the `Upload mapping` button to successfully upload your dataweave map.

. Setup the target within your organization where you want to forward the transformed message. Click on the `Map` section to expand it. Within this section, proceed to setup the target message type and the endpoint where you want to route the transformed message.

** Setup a target message type. Click on the `select` button. In the ensuing modal window, proceed to either search and select and existing message type, or create a new message type. To create a new message type, depending on the message standard, follow instructions below
*** Setting up JSON message type

** Setup a target endpoint. Click on the `select` button. In the ensuing modal window, proceed to either search and select and existing endpoint, or create a new endpoint. To create a new endpoint, depending on the protocol, follow instructions below
*** Setting up SFTP receiving endpoint
*** Setting up HTTP / HTTPS receiving endpoint

. Click the `Deploy` button when you are ready to deploy the configurations to your mule runtime.

TIP: When you complete all of the sections i.e. have a green check mark againt all sections in the flow, you can `Deploy` your message flow and start receiving messages from your partner.

You can begin to monitor the activity from the Activity page.

== See Also

* xref:endpoints.adoc[Endpoints]
// * xref:activity-tracking.adoc[Activity Tracking]

// == Create a Send Message Flow from Your Partner
