= Create a Receive Message Flow from Your Partner
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To receive messages from a trading partner, create a message flow and configure the sections for both the source, mapping, and the target. Your organization is typically referred to as the host, while the enterprise you interact with is refered to as a trading partner.

For the receiving endpoint - this is the origin of the message flow when defined by a host endpoint and message type, often an API.

For the target endpoint - this is the final destination of a message flow when defined by a host endpoint and message type, often a Host API.

You'll need the following for the Source:

* The trading partner's name and associated identifiers (such as X12 ISA, X12 GS, and so on)

* The endpoint where you receive the transmission

* The message type to process for this message flow (such as X12, 4010, 850, and so on)

* The endpoint where your trading partner may want to receive an acknowlegement related to the transactions they send

* The DataWeave map that transforms the received message contents into a format you prefer

You'll need the following for the Target:

* The message type your system understands. This is also the format that DataWeave transforms received messages into

* The endpoint in your organization where you route the transformed message

If a separate URL is required to returning MDNs, it is sent in the AS2 transmission and Anypoint Partner Manager reads it from there.

== Set up Receive from a Partner
[start=1]
. From within your Anypoint Partner Manager environment (either Sandbox or Production), select `Message Flows` from the left-hand navigation.

* To Select an Existing Partner

** In the `Select a partner` window, search for the trading partner by name, and once you find a match, click on the corresponding row, and click the *Select* button.

Clicking each section of the message flow expands it. A green checkmark next to any a section indicates that it is complete.

* Alternatively, to create a new Trading Partner

. In the `Select a partner` window, click  the `New` button.

. Provide the trading partner's name and create at least one identifier (such as X12 ISA, X12 GS, and so on).

. Once you have provided the information needed, click the *Create Partner and Message Flow* button.

Once your trading partner is created, you can configure your message flow to receive messages from the selected trading partner or add more information.

[start=3]
. Configure the source endpoint where you receive the transmission.

. Click on the `Receiving endpoint` section to expand it and click the *select* button.

. Search and select and existing endpoint, or create a new endpoint.

. To create a new endpoint, depending on the protocol, follow instructions in these sections:

[xref] Setting up SFTP endpoint

[xref] Setting up AS2 endpoint
[start=7]
. Select the source message type by clickin on the `Source message` section to expand it.

. Click the `Select` button and either search and select and existing message type, or create a new message type.
To create a new message type, depending on the message standard, follow instructions in these sections:

[xref] Setting up X12 message type

[xref] Setting up JSON message type
[start=9]
. Configure acknowledgments (optional, only if the partner requires them for X12 messages), the type of acknowledgment, and the endpoint to which you send it.

. Upload a DataWeave map. Click the `Map` section to expand it and click the *Import* button to upload a DataWeave map.

. Click the `Upload map` button to successfully upload your dataweave map.

. To set up the target within your organization where you want to forward the transformed message, click on the `Map` section to expand it.

. Go to the setup the target message type and the Endpoint where you want to route the transformed message.???

. Click the `Select` button to set up a target message type.

. Either search and select an existing message type, or create a new message type.

. To create a new message type, depending on the message standard, follow instructions in one of these sections.

[xref] Setting up JSON message type
[start=17]
. Set up a target endpoint by clicking the `Select` button.

Either search and select and existing endpoint, or create a new endpoint.
[start=18]
. To create a new endpoint, depending on the protocol, follow instructions in these sections:

[xref] Setting up SFTP endpoint

[xref] Setting up HTTP / HTTPS endpoint

When you complete all of the sections - they will have a green check mark next to all of them in the flow, you can deploy your message flow and start receiving messages from your partner.
[start=19]
. Click the *Deploy* button when you are ready to deploy the configurations to your Mule Runtime. How you set up Mule Runtime can impact your deployment. If your message flow does not deploy right away. Try again later.

You can begin to monitor the activity from the Activity page.

== See Also

* xref:endpoints.adoc[Endpoints]
// * xref:activity-tracking.adoc[Activity Tracking]

// == Create a Send Message Flow from Your Partner
