= Create and Configure an Inbound Message Flow

You can create and configure an inbound message flow to receive EDI messages from your trading partners, validate and transform those messages, and then send the translated application (JSON or XML) message to your back-end applications.

== Create an Inbound Message Flow

=== Prerequisites
Before you create your first inbound message flow, you must configure your xref:setup-payload-storage-API.adoc[payload storage API].

=== Steps

. From your Anypoint Partner Manager sandbox or production environment, select *Message Flows* in the left navigation menu.
. Click *New message flow > Receive from partner* in the upper right of the page.
. Either select an existing partner from the list and click *Select* or select *New* to xref:configure-partner.adoc#create-partner[create a trading partner]. +
A new message flow is created. +

== Configure the Receive Endpoint

. In the message flow, expand the *Receiving endpoint* section and click *Select*.
. To use an existing receiving endpoint:
.. Select the endpoint from the list and click *Select* in the lower right side of the page. +
The endpoint is added to the message flow, and you see a message that tells you the endpoint is missing an identifier.
.. Click *Add* to add a unique identifier for the endpoint.
. To create a new receiving endpoint:
.. Click *New* on the right of the search box.
.. From the *Owner* drop-down, select the endpoint's owner.
.. From the *Protocol* drop-down, select the protocol and configure it according to the protocol you select:
* xref:endpoint-as2-receive.adoc[*AS2*]
* xref:endpoint-sftp-receive-target.adoc[*SFTP*]
+
[NOTE]
Translated files are delivered to file-based endpoints with a unique file name with the pattern `<doctype>-<senderid>-<ISACtrlNum>-<GSCtrlNum>-<STCtrlNum>-<timeInMillis>.<format>`, for example: `850-ABCCORP-40952-5850-179960-1587685726355.JSON`
. Click *Save*.

== Configure the Source Message Type

. In the message flow, expand the *Source message type* section and click *Select*.
.. To use an existing message type, select the message type from the list and click *Select* in the lower right side of the page. +
.. To create a new message type:
... Click *New* on the right side of the search box.
... From *Format*, select *X12*.
... From *Version*, select the X12 version.
... From *Message type*, select the message type.
... From schema select *Use standard X12-<version>-<message-type>* or select *Customize* to define a custom schema.
. Click *Save*. +
The message type and its validation settings are added to the message flow.

== Import the Translation Map

=== Prerequisites
To create your inbound EDI-to-application message (JSON or XML) map in Anypoint Studio, follow xref:partner-manager-maps.adoc[these instructions].

=== Steps

. In the message flow, expand the *Map* section.
. Click *Import* to upload the DataWeave map to translate the EDI message to your application message format.

== Configure the Target

. In the message flow, expand the *Target at <your organization>* section.
. Select a message type for your backend system to use to map the EDI transaction. +
Partner Manager routes inbound EDI transactions based on matching identifiers configured at the Partner level.
. In the message flow, expand the *Endpoint* section.
. Select the endpoint or select *New* to create a new endpoint to which to send the translated message (JSON or XML) for further processing in your backend system. +
Partner Manager routes inbound EDI transactions based on matching identifiers configured at the Partner level.

== Verify the Message Flow is Complete

Partner Manager dynamically validates the message flow configuration elements for completeness and displays a green checkmark if all the building blocks of the message flow are complete. After you verify the configurations, you are ready to deploy the message flow.

== See Also

* xref:deploy-message-flows.adoc[Deploy Message Flows]
* xref:manage-message-flows.adoc[Manage Message Flows]
* xref:activity-tracking.adoc[Activity Tracking]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
