= Create a Receive Message Flow from Your Partner
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To receive messages from a trading partner, create a message flow and configure the sections for both the source and target. Your organization is typically referred to as the `host`, while the partner you interact with is refered to as a `trading partner`.

For the receiving endpoint - this is the origin of the message flow when defined by a host endpoint and message type, often an API. For the target endpoint - this is the final destination of a message flow when defined by a host endpoint and message type, often a Host API.

You'll need the following for the Source:

* The trading partner and associated identifiers (such as X12 ISA, X12 GS, and so on)

* The endpoint where you receive the transmission

* The message type to process for this message flow (such as X12 4010 850 and so on)

* The endpoint where your trading partner may want to receive an acknowlegement related to the transactions they send

* The DataWeave map that transforms the received message contents into a format you prefer

You'll need the following for the Target:

* The message type your system understands. This is also the format that dataweave transforms received messages into

* The endpoint in your organization where you route the transformed message

If a separate URL is required for returning MDNs, it is sent in the AS2 transmission and Partner Manager reads it from there.

== Set up Receive from a Partner

. From within your Anypoint Partner Manager environment (either Sandbox or Production), select *Message Flows* from the left-hand navigation.

. Click the `New Message Flow` button and select a partner from the list and click the `Select` button. You can also choose to create a new partner by clicking the `New` button.

You can open each section of the message flow by clicking it. This is where you enter the information you collected from your checklist about your partner and your own backend system.
A green checkmark next to any of the sections indicates that the particular section is complete. When you complete all of the sections i.e. have a green check mark againt all sections in the flow, you can `Deploy` your message flow and start receiving messages from your partner.

Enter the following information:

* Configure the source endpoint, where you receive the transmission

* Select the source message type

* Configure acknowledgments (if the partner requires them), the type of acknowledgment, and the endpoint to which you send it

* Upload a DataWeave map

* Select the target message type for the type of document. For example, a purchase order in X12 is an 850 message.
You also need to know the X12 version to use in your transactions (such as 004010, 005010, and so on).

* Click the *Deploy* button when you are ready to make the created flow live

You can begin to monitor the activity from the Activity page.

== See Also

* xref:endpoints.adoc[Endpoints]
// * xref:activity-tracking.adoc[Activity Tracking]

// == Create a Send Message Flow from Your Partner
