= Configure Trading Partners
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The only information you need to create a new trading partner is the name and a single identifier.
You can add other information later.
Once created, each partner has its own page and shows up in the 'Partners' tab in the left-hand navigation menu.

From the Partners page you can:

* Add information about your trading partners along with contact details.

* Add identifiers to uniquely identify them from one another.

* Add certificates owned by your partner.

* Configure global validation, acknowledgement, control number, and character set settings.

== Create a Trading Partner

. Open Anypoint Partner Manager.

. From within your Anypoint Partner Manager environment, select the Partners from the left-hand navigation.

. Click the *New Partner* button and proceed to:
- Add your trating partners name, and
- Select an Identifier from the *Type* drop-down menu. This uniquely identifies you as a trading partner. For example, depending on your setup, select one of the following: AS2, X12 ISA, X12 GS, or the DUNS number.

. Click *Create Partner* to create your trading partner. at this point, your trading partner has been created within the Anypoint platform and you may proceed to setup message flows related to this partner. 

== Update Trading Partner Profile

You may now also proceed to the partners profile page to add more details related to this trading partner. You can add the following information for each trading partner from the *Partners* selection in the left-hand navigation:

* About - the following information can be provided in this section by clicking on the *Edit* button under the 'About' section
- Description - Provide a brief description about your partners business, what kind of trading relation your organization has with the trading partner, etc.
- Website - associate your trading partners website.
- Logo - upload a logo associated to your trading partner. jpeg and png files are acceptable formats for the logo. Please ensure the logo file is smaller than 25kb.
- Corporate address - provide an address comprsing of the street, City, State, Postal code, and Country.
- Add contacts - Options are available to add 'business contacts', 'technical contacts' or 'other contacts'. You may add up to 3 contacts associated to a trading partners profile.

Click on the *Save* button when you have provided all the necessary information. When the trading partner's profile is successfully updated you will receive a confirmation message indicating 'Partner "<your trading partners name>" updated'

* Add more identifiers for your Trading partner. To add more identifiers, click on the *New* button within the 'Identifiers' section. Select an appropriate identifier type and provide a the identifier value as provided by your trading partner. after you have provided all the information needed, click on the *Create identifier* button. When an identifier is successfully created you will receive a confirmation message indicating 'Identifier created'.

* Your partner's digital certificate (such as an X.509 certificate in PKCS12 file format for the AS2 transport protocol). To add a certificate, click on the *New* button within the 'Certificates' section. Upload the digital certificate (typically a .pem file) provided by your trading partner, and proceed to click on *Upload certificate* button. When a certificate is successfully uploaded you will receive a confirmation message indicating 'Partner certificate created'.

* Configure any global validation settings if you need to override a default value for a particular partner. Global X12 setting include:
- Validations: Please apply validations as needed from the options mentioned below.
[%header,cols="3s,7a"]
|===
|Setting |Description

|Fail document when value length outside allowed range
|If selected, a transaction with values too long or too short is rejected. If not selected, the values are used anyway and the transaction is not rejected. In either case the error is logged and reported in 997/999 acknowledgments

Required?::
`No`

Default::
`Selected`

|Fail document when invalid character in value
|If selected, a transaction with invalid characters is rejected. If not selected, the characters are either passed through or substituted and the transaction is not rejected. In either case the error is reported in 997/999 acknowledgments

Required?::
`No`

Default::
`Not Selected`

|Fail document if value is repeated too many times
|If selected, a transaction with values repeated too many or too few times is rejected. If not selected, the value are accepted and the transaction is not rejected. In either case the error is reported in 997/999 acknowledgments.

Required?::
`No`

Default::
`Selected`

|Fail document if unknown segments are used
|If selected, a transaction containing any unknown segments is rejected. If not selected, unknown segments are ignored and the transaction is not rejected. In either case the error is reported in 997/999 acknowledgments

Required?::
`No`

Default::
`Selected`

|Fail document when segments are out of order
|If selected, a transaction with segments out of order is rejected. If not selected, the segment can be reordered the transaction is not rejected. In either case the error is reported in 997/999 acknowledgments

Required?::
`No`

Default::
`Selected`

|Fail document when unused segments are included
|If selected, a transaction containing segments marked as unused in the schema is rejected. If not selected, the transaction is not rejected and the unused segments are ignored. In either case the error is reported in 997/999 acknowledgments

Required?::
`No`

Default::
`Selected`

|Fail document when too many repeats of a segment
|A transaction with a segment repeated too many times is rejected. The error is reported in 997/999 acknowledgments

Required?::
`No`

Default::
`Selected`
|===

- Control Numbers: Please apply validations related to your partners / your use of control numbers within the X12 message.
[%header,cols="3s,7a"]
|===
|Setting |Description

|Requires unique interchange control number (ISA13)
|If selected, Anypoint Partner Manager records the interchange numbers previously processed and reject any duplicate interchange numbers from the same partner (as determined by the interchange sender and receiver identification). If not selected, allows processing of the received interchange to continue

Required?::
`No`

Default::
`Not Selected`

|Requires unique group control number (GS06)
|If selected, Anypoint Partner Manager enforces globally unique Group Control Numbers (GS06) for received functional groups. This configuration requires group numbers to be unique across all interchanges received from the same partner and application (as determined by the interchange sender and receiver identification, combined with the functional group sender and receiver application codes)

Required?::
`No`

Default::
`Not Selected`

|Requires unique transaction set control number (ST02)
|If selected, Anypoint Partner Manager enforces globally unique Transaction Set Control Numbers (ST02) for received transaction sets. This configuration requires transaction set numbers to be unique across all functional groups received from the same partner and application (as determined by the interchange sender and receiver identification, combined with the functional group sender and receiver application codes)

Required?::
`No`

Default::
`Not Selected`

* To find a partner, search the Partners list by name, and select the name of the partner.

Refer to the X12 Settings to change any of the default settings for all X12 received messages.

When you are ready, you can Configure Message Flows.

== See Also

* xref:x12-identity-settings.adoc[X12 Settings]
* xref:configure-message-flows.adoc[Create a Receive Message Flow from Your Partner]
