= Create, Configure, and Update Trading Partners

The Partner Manager *Partners* page lists all the configured trading partner profiles. 

On the *Partners* page, you can:

* <<create-partner,Create and configure new trading partners>>
* <<view-partner-details,View the details>> of a partner
* xref:partner-manager-identifiers.adoc[Add the EDI and AS2 identifiers] used by your trading partner.
* Add xref:Certificates.adoc[digital certificates] associated with your trading partner.
* xref:create-endpoint.adoc[Create] and manage source and target endpoints owned by the trading partner.
* Manage EDI validation settings for inbound and outbound transactions.

== Required Information

To create a new partner, you need the following information:

* The partner's name (usually the name of the company).
* Partner identifiers (such as the AS2 ID, X12-ISA, X12 GS, and so on).

[[create-partner]]
== Create a Partner

. From within your Anypoint Partner Manager environment, select *Partners* from the left navigation.
. Click *New partner*.
. In *Name*, enter a name that easily identifies your partner.
. Select an identifier from the *Type* list: 
* *AS2 Identity*
* *Reference ID*
* *X12-GS*
* *X12-ISA*
. In *Identifier Value*, enter a value to uniquely identify your partner. 
. If you selected *X12-ISA* as the *Type*, you must also select a *Qualifier* from the list. 
. Click *Create partner* to create your trading partner.

You can now xref:configure-message-flows.adoc[set up message flows] for this trading partner or continue to <<update-partner,update this partner>>.

[[update-partner]]
== Update a Partner's Profile

You can add and update the following information for each trading partner from the *Partners* tab in the left navigation:

. In Partner Manager, select *Partners* in the left navigation menu. 
. Click the partner for whom to update the profile.
. Under the *About* section, click *Edit* to add or update the following information:
* *Description* +
Provide a brief description of your partner's business, what kind of trading relationship your organization has with them, and so on.
* *Website* +
Enter a valid URL to your trading partner's website.
* *Logo* +
Upload a logo for your trading partner. Supported logo file formats are: `.jpg`, `.jpeg`, `.png`, `.gif`, and `.svg`. +
The maximum file size is 30KB.
* *Corporate address* +
Provide a complete address that includes the Street, City, State, Postal code, and Country.
* *Add contacts* +
You can add up to three contacts associated with a trading partner's profile. You can also delete contacts from here. 
+
Available contact types are: 
+
** Business
** Technical 
** Other 
. Click *Save*. +
A message confirms that the partner's profile is successfully updated.

[[view-partner-details]]
== View a Partner's Details

After you create a new partner, you can view and update details for the partner:

. In Partner Manager, select *Partners* in the left navigation menu. 
. Click the partner to view its details and make updates. +
From the partner's detail page you can:
* Add information about your partner along with contact details.
* Add partner endpoints (where you send and receive messages to and from your partners, including acknowledgment endpoints).
* Specify EDI message format preferences for your partner (such as X12), and any associated validations such as the need for acknowledgments (like TA1, 997, 999, and so on).
* Specify the message types to use. +
For example, a purchase order in X12 is an 850 message. You also need to know the X12 version to use in your transactions (such as 004010, 005010, and so on).
* Add your partner's digital certificates (such as an X.509 certificate).

You can also configure validation, acknowledgment, control number, and character set settings applicable to all message flows for the trading partner.

== See Also

* xref:partner-manager-identifiers.adoc[Sender and Receiver Identifiers]
* xref:create-endpoint.adoc[Create and Configure Endpoints]
* xref:endpoint-as2-receive.adoc[AS2 Receive Endpoint Settings]
* xref:endpoint-as2-send.adoc[AS2 Send Endpoint Settings]
* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
* xref:endpoint-sftp-send-adoc[SFTP Send Endpoint Settings]
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Settings]
* xref:endpoint-https-receive.adoc[HTTP and HTTPS Receive Settings]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
