= Create a Message Flow
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To receive messages from a trading partner, create a message flow and configure the sections for the source, map, and target.
Your organization is typically referred to as the host. The enterprise or customer you interact with is referred to as your partner.

The source of the message flow is defined by the partner, a receiving endpoint at the host, often an API, and the message type you are receiving from the partner.

The target is the final destination of a message flow and is defined by a host message type and endpoint, often a Host API.

You'll need the following for the Source:

* The partner's name and associated identifiers (such as X12-ISA, X12 GS, and so on).

* The endpoint where you receive transmissions.

* The message type to process for this message flow (such as X12, 4010, 850, and so on).

* The endpoint where your partner may want to receive an acknowledgment related to the messages they send.

* The DataWeave map that transforms the received message contents into a format you can use.

You'll need the following for the Target:

* The message type your system understands. This is also the format into which DataWeave map transforms received messages.

* The endpoint in your organization where you route the transformed message.

If a separate URL is required for returning MDNs, it is sent in the AS2 transmission and Anypoint Partner Manager reads it from there.

== Configure a message flow

. From within your Anypoint Partner Manager environment (either Sandbox or Production), click *New message flows* in the upper right.

. Select an Existing Partner. You can do this from the *Select a partner* dialog, by searching for a partner by name.

. Once you find a match, choose the partner name and click *Select*. Clicking each section of the message flow expands it. A green checkmark next to any a section indicates that it is complete.

* Alternatively from the *Select a partner* dialog, you can create a new partner by clicking *New*.
This is the same as xref:configure-partner.adoc#create-a-trading-partner[Create a Trading Partner] except that when you are finished, you'll click *Create Partner and Message Flow*.
You can add more information to the partner later.
+
. Click *Select* from the *Receiving endpoint* section to configure the source endpoint where you receive the transmission.

. Click *Select* to search and select an existing endpoint or click *New* to create a new endpoint.

. To create a new endpoint, depending on the protocol, refer to the following:
+
* xref:endpoint-as2-receive.adoc[AS2 Endpoint Settings]

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]

+
. In the *Source message* section, click *Select* to expand the Message Type section.

. Either search and click *Select* to choose a previously used message type, or click *New* to create a new message type.

. For a new message type, depending on the message standard, refer to the following:
+
* xref:document-types.adoc[X12 and JSON Message Types]
+
. To optionally edit the validation settings, click *View* and the hostname.
For more information, see xref:x12-receive-read-settings.adoc[X12 Settings - Receive from Partner].
+
NOTE: It may take five minutes or so for your configuration changes to sync with Mule runtime.
+
. For X12 partner requirements, optionally configure the type of functional acknowledgment and the endpoint to which you send it.
+
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Configuration]

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
+
. Click the *Map* section and then click *Import* to choose a DataWeave map.

. Select a map and click *Upload mapping*.

. Click the *Target at <Partner name>* section and click *Select* to set up a target message type.
This is the target message type and the Endpoint where you want to route the transformed message.

. Either search and select an existing message type, or create a new message type. To create a new message type, depending on the message standard, follow instructions in one of these sections.

+
* xref:document-types.adoc[X12 and JSON Message Types]
+
.  Click *Select* to set up a target endpoint.
. Either search for and select an existing endpoint, or create a new endpoint by clicking *New*.
+
* To create a new endpoint, depending on the protocol, refer to the following:

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]

* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Configuration]

. After you create the source, map, and target sections in the interface, confirm that each shows a green check mark next to it in the flow), and click *Deploy* to deploy the configurations to your Mule Runtime.

NOTE: The deployment process might take several minutes. Please do not log out of the Anypoint platform while the deployment is in-progress as it will cause the deployment to terminate leading to a `failed` deployment. You may continue to work within the Anypoint platform during this time.

+
Your message flow configuration is deployed to your Mule runtime engine and you can start receiving messages from your partner. Use the Activity page to track processed messages.
+
Once a message flow is successfully deployed, you can track its processed messages from the Activity page.

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:activity-tracking.adoc[Activity Tracking]
