= Create and Deploy an Inbound Message Flow

You can create and configure an inbound message flow either when you create a trading partner, or after you create a trading partner. After you deploy the message flow, it's best to test it.

. From your Anypoint Partner Manager *Sandbox* or *Production* environment, select *Message Flows* in the left navigation menu. 
. Click *New message flow > Receive from partner* in the upper right of the page.
. Select an existing Partner from the list and click *Select*. +
A new message flow is created. +
Alternatively, from the *Select a partner* dialog, you can click *New* to create a new partner.
Follow the process to xref:configure-partner.adoc#create-a-trading-partner[create a Trading Partner], except that when you are finished, click *Create Partner and Message Flow*.
. Click each section of the message flow to expand it. +
A green checkmark next to any section indicates that it is complete.
. Expand the *Receiving endpoint* section and click *Select*.
. To use an existing receiving endpoint, select the endpoint from the list and click *Select* in the lower right side of the page. +
To create a new receiving endpoint, click *New* on the right of the search box and follow the instructions for creating a new endpoint. 
+
[NOTE]
Translated files are delivered to file-based endpoints with a unique file name with the pattern `<doctype>-<senderid>-<ISACtrlNum>-<GSCtrlNum>-<STCtrlNum>-<timeInMillis>.<format>`, for example: `850-ABCCORP-40952-5850-179960-1587685726355.JSON`
. Expand the *Source message type* section, and click *Select*.
. To use an existing message type, select the message type from the list and click *Select* in the lower right side of the page. +
To create a new message type, click *New* on the right side of the search box and follow the instructions for creating a message type. 
. Expand the *Map* section and click *Import* to upload the DataWeave map to translate the EDI message to your application message format. +
Follow these instructions to create your inbound EDI-to-application message (JSON or XML) map in Anypoint Studio.
. Expand the *Target at <your organization>* section.
. Select the message type of your backend system to which to map the EDI transaction. +
Partner Manager routes inbound EDI transactions based on matching identifiers configured at the Partner level. +
NOTE:
Translated files are delivered to file-based endpoints with a unique file name with the pattern `<doctype>-<senderid>-<ISACtrlNum>-<GSCtrlNum>-<STCtrlNum>-<timeInMillis>.<format>`.
Example: 850-ABCCORP-40952-5850-179960-1587685726355.JSON
In the *Select message type* window, click *New* to create a new target at host message type.
. Select the endpoint to which to send the translated message (XML or JSON) for further processing in your backend system. +
In the *Select endpoint* window, click *New* to create a new endpoint. 

== Deploy the Message Flow

Partner Manager dynamically validates the message flow configuration elements for completeness and displays a green checkmark next to each of the message flow building blocks as they are completed and validated. 

It is best to test the message flow by deploying it in a sandbox environment. When you verify that the message flow is successful, you can then undeploy it from the sandbox and deploy it to your production environment.

After you verify that each part of the message flow is complete, click the *Deploy* button to deploy the message flow to the runtime.

[NOTE]
---
For B2B workloads on-premises, deploying a message flow for a new trading partner while using an existing AS2 endpoint to receive messages can result in a brief interruption to the service for existing AS2 trading partner users.

To minimize the impact of the service interruption, it is best to perform message flow deployments outside of your regular business hours.

This issue does not exist on CloudHub, as CloudHub provides a zero-downtime update of the AS2 endpoint application.
---

Your message flow configuration is deployed to Mule runtime engine and you can start receiving messages from your partner. After a message flow is successfully deployed, you can track its processed messages using the *Activity* page.

== Test Message Flows

After you deploy the message flow, send test messages to verify the following:

* You are receiving messages and acknowledgments from your partners.
* The DataWeave map is working and your backend systems receive the transformed message.

Test your message flow in your Anypoint Partner Manager Sandbox environment:

. Initiate a transmission on the receiving endpoint.
. From the Partner Manager left navigation, select *Activity*.
. Select the transmission to test from the list.
. Scan for an exclamation point (!) in any of the boxes next to the displayed flow stages. Exclamation points indicate that there is an issue with the transmission. Address any issues you find.
. If the system was set up to view payloads, you can review the received payload by clicking *View payload* next to the *Received transmission* section. +
If you are unsure about whether you should be able to view a payload, contact your B2B System Administrator.
. If you have TA1 and functional acknowledgments (999 or 997) set, review and confirm that they are there.
. Verify that the transmission routed the messages to the correct message flows.
. Verify that the messages are routed to the target system and that they:
* Were successfully delivered to the target endpoint
* Transformed correctly

== See Also

* xref:manage-message-flows.adoc[Manage Message Flows]
* xref:activity-tracking.adoc[Activity Tracking]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
