= Configure Trading Partners
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The only information you need to create a new partner is its name and a single identifier related to that partner.
You can add other information after creating the partner.
Once created, each partner has its own page located in the *Partners* section in the left navigation menu.

From the Partner detail page you can:

* Add information about your partner along with contact details.

* Add identifiers to uniquely identify it from other partners.

* Add certificates owned by the partner.

* Configure validation, acknowledgement, control number, and character set settings applicable to all message flows for this trading partner.

== Create a Partner

. From within your Anypoint Partner Manager environment, select *Partners* from the left navigation.

. Click *New partner*.

. Add a name that easily identifies your partner.

. Select an identifier from the *Type* drop-down menu. This uniquely identifies your partner.
For example, depending on your setup, select one of the following: AS2 ID, X12-ISA, X12 GS, or the DUNS number.

. Provide a value for your identifier (and qualifier for X12-ISA) and click *Create partner* to create your trading partner.
See xref:x12-identity-settings.adoc[X12 Identifiers] for more info on X12 Identity settings.
You can now setup message flows xref:configure-message-flows.adoc[Create a Message Flow] related to this trading partner or continue to update this partner.

== Update a Partner's Profile

You can add the following information for each trading partner from the *Partners* selection in the left navigation:

. Under the *About* section, click *Edit*. Add or update the following information:

* Description - Provide a brief description about your partner's business, what kind of trading relationship your organization has with them, and so on.

* Website - enter a valid URL to your trading partner's website.

* Logo - upload a logo associated to your trading partner. Supported logo file formats are: `.jpg`, `.jpeg`, `.png`, `.gif`, or `.svg` files. Maximum file size is 30KB.

* Corporate address - provide a complete address that includes the Street, City, State, Postal code, and Country.

* Add contacts - contact types available are: Business, Technical or Other. You can add up to three contacts associated with a trading partner's profile. You can also delete contacts from here.
+
. Click *Save*. A message confirms that the partner's profile is successfully updated.

. (Optional) You can add more identifiers for your trading partner by clicking *New* within the *Identifiers* section.

* Select an identifier type from the *Type* drop-down menu. This uniquely identifies your partner.
For example, depending on your setup, select one of the following: AS2 ID, X12-ISA, X12 GS, or the DUNS number.

* Provide a value for your identifier (and qualifier for X12-ISA) and click *Create identifier* to save your changes.
See xref:x12-identity-settings.adoc[Identifiers] for more info on X12 settings.

. Click *New* within the *Certificates* section to upload any needed digital certificates. This is your partner's digital certificate (such as an X.509 certificate in PKCS12 file format for the AS2 transport protocol).

* Click *Choose file* to select and upload the certificate.

* Click *Upload certificate* (typically a .PEM file provided by your trading partner) to upload the chosen digital certificate file.
+
View information about an uploaded certificate by clicking it's link. See xref:Certificates.adoc[Certificates] for more info on configuring certificates in Partner Manager.
+
. Configure X12 validation settings that can be used for all message flows that you are configuring with your trading partners. These include:

* Validations
* Acknowledgment
* Control numbers
* Character sets

Refer to the options for each at xref:x12-receive-read-settings.adoc[X12 Settings - Receive from Partner]
