= Create and Configure an Inbound Message Flow
:page-aliases: configure-message-flows.adoc

Create and configure an inbound message flow to receive EDI messages from your partners, including messages that go through 3rd party connections. When you create an inbound message flow, you can validate and transform the inbound messages and then send the translated message (JSON or XML) to your backend applications.

To receive messages sent from a partner through a 3rd party connection, select an endpoint owned by that connection.

=== Prerequisites

Before you create your first inbound message flow, you must configure your xref:setup-payload-storage-API.adoc[payload storage API].

=== Steps

. From the Anypoint Partner Manager navigation menu, select *Message Flows*.
. Click *New message flow > Receive from partner*.
. Either select an existing partner from the list or select *New* to create a new partner, as described in xref:create-partner.adoc#[Create a partner].
+
A new message flow is created.
+
. <<receiving-endpoint,Configure the receiving endpoint>>.
. <<source-message-type,Configure the source message type>>.
. <<import-map,Import the translation map>>.
. <<configure-target,Configure the target message type>>.
. <<configure-target-endpoint,Configure the target endpoint>>.
. <<verify-message-flow,Verify that the message flow is complete>>.

[receiving-endpoint]
== Configure the Receiving Endpoint

Configure the endpoint that will receive the Messages that your partners send. You can either select an existing endpoint owned by the host, target partner, or 3rd party connection, or you can create a new endpoint for the message flow. If you select an endpoint owned by a 3rd party connection, the inbound message goes through that connection.

To configure the receiving endpoint:

. In the message flow, expand the *Receiving endpoint <endpoint> from <partner>* section and click *Select*.
. In the *Receiving endpoint* section, click *Select*.
. In the *Select an endpoint: Receive from <partner>* window, do either of the following:
* Select an existing receiving endpoint and click *Select*.
* Click *New* to create a new endpoint, as described in <<xref:create-endpoint.adoc,Create and Configure Endpoints>>.

+
The endpoint is added to the message flow.

If the protocol of the receive endpoint is AS2, perform these additional steps:

. Select the AS2 Sender from the dropdown menu:
* To enable your organization to receive the AS2 messages directly from the partner for whom the message flow is created, select the partner’s name (default).
* To enable your organization to receive the AS2 messages for the partner via a 3rd party connection, such as a VAN or 3PL, select the name of the 3rd party connection.
+
The AS2 identifier and certificate of the selected 3rd party connection will be used in AS2 message validation.
+
. Import the AS2 certificate of the partner or 3rd party connection sending the AS2 message, if there is no existing certificate in their profiles.

[source-message-type]
== Configure the Source Message Type

The source message type defines the schematic structure of the messages that Partner Manager receives from a partner or 3rd party connection. Partner Manager supports the EDIFACT and X12 formats for source message types in an inbound message flow.

To configure the source message type:

. In the message flow, expand the *Source message* section and click *Select*.
. In the *Select message type* window, do either of the following:
* Select an existing receiving message type and click *Select*.
* Click *New* to create a new message type, as described in <<xref:partner-manager-create-message-type,Create and Configure Message Types>>.

+
The message type and its validation settings are added to the message flow.

If your partner expects your organization to return functional acknowledgements, perform these additional steps:

. In the *Acknowledgement* section, select the check box next to *Send 997 functional acknowledgment (X12)* or *Send CONTRL functional acknowledgement (EDIFACT)*.
. Click *Select*.
. In the *Select an endpoint: Send acknowledgement to <partner>* window, do either of the following:
* Select the endpoint where to receive the acknowledgment messages from your partner and click *Select*.
* Click *New* to create a new endpoint, as described in <<xref:create-endpoint.adoc,Create and Configure Endpoints>>.

+
The acknowledgment is added to the message flow.

[[import-map]]
== Import the Translation Map

To create your inbound EDI-to-application message (JSON or XML) map in Anypoint Studio, follow xref:partner-manager-maps.adoc[these instructions].

. In the message flow, expand the *Map* section.
. Click *Import* and then click *Choose file*.
. In the *New mapping file* window, navigate to the DataWeave map you want to use and then click *Open*.
. Click *Upload mapping*. +
The translation map is added to the message flow.

[[configure-target]]
== Configure the Target Message Type

The target message type defines the schematic structure of the messages that Partner Manager sends to the backend system.

To configure the target message type:

. In the message flow, expand the *Target at <host>* section.
. In the *Message Type* section, click *Select*.
. In the *Select message type* window, do either of the following:
* Select an existing receiving message type and click *Select*.
* Click *New* to create a new message type, as described in <<xref:partner-manager-create-message-type,Create and Configure Message Types>>.
. Click *Save*.

[[target-endpoint]]
== Configure the Target Endpoint

Configure the endpoint that will receive the messages that your partners send. You can either select an existing endpoint owned by the host, or you can create a new endpoint for the message flow. Partner Manager supports the FTP, HTTP, HTTPS, and SFTP formats for the target endpoint in an inbound message flow.

To configure the target endpoint:

. In the message flow, expand the *Target at <host>* section.
. In the *Target at <host>* section, expand the *Endpoint* section and click *Select*.
. In the *Select an endpoint: Target to <host>* window, do either of the following:
* Select an existing receiving endpoint and click *Select*.
* Click *New* to create a new endpoint, as described in <<xref:create-endpoint.adoc,Create and Configure Endpoints>>.


////
Partner Manager routes inbound EDI messages based on matching identifiers configured at the partner level.
The target endpoint to which to send the translated message (JSON or XML) for further processing in your backend system is added to the message flow.

Partner uses the message type is used by the backend system to map EDI messages. Partner Manager routes inbound EDI messages based on matching identifiers configured at the partner level.
////

[[verify-message-flow]]
== Verify That the Message Flow Is Complete

Partner Manager dynamically validates the message flow configuration elements for completeness and displays a green checkmark if all of the message flow building blocks are complete. After you verify the configurations, you are ready to deploy the message flow.

== See Also

* xref:deploy-message-flows.adoc[Deploy Message Flows]
* xref:manage-message-flows.adoc[Manage Message Flows]
* xref:activity-tracking.adoc[Activity Tracking]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
