= Create a Map For XML or JSON to Outbound EDI X12

You can create the dataweave map to transform your application message formats such as XML or JSON to outbound EDI X12 transactions following the below steps:
Launch Anypoint Studio
From the File menu, Click New and Project from Template
Login to Anypoint Exchange with your Anypoint platform credentials
Search for X12
Click the template named Template to map application messages to outbound EDI X12 transactions.
Click Open, to create a new project in your Studio workspace pre-loaded with the template.
The template can also be downloaded from Anypoint Exchange and exported to Anypoint Studio.
Setting the source JSON/XML message type for the map
Copy the schema file of your target application message type into src/main/resources folder in the project
Click the Transform message component in the Mule application
Click Define metadata under Input
Click Add
Enter a new message type id; Example: enterprise-outbound-purchase-order
From the drop-down menu Type, Select JSON or XML
Select you JSON/XML schema file imported in the earlier step
Click Select
Setting the target X12 message type for the map
The template has the X12 configuration for the below X12 transaction set
Version: 4010
Transaction Set: 850 (Purchase order)
Navigate to the Global Elements configuration in global-configs.xml
Edit the configuration named X12_EDI_Write
Under the Schema definitions section, click the value /x12/004010/850.esl
Click the Edit button
Change the Schema value to the version and transaction set you want to map from.
Example: Set the value to /x12/004010/204.esl, if you want to map to 4010-204 Load tender transaction
You will now see your application message structure (JSON or XML) on the input pane in the left, and the X12 transaction set structure on the output pane in the right.
You can begin mapping from input to the output.
You can download a sample project from Exchange that has pre-built mapping to transform outbound purchase order messages from XML to 4010 850 transactions.
You can test the map locally in Anypoint Studio following the below steps
Right click on the project, and click Run → Run as Mule application
Using a REST client, POST a JSON or an XML payload to the URL http://localhost:8081/x12/out
The application will return the translated EDI X12 transaction.
Copy the dataweave map from src/main/resources/x12/OUT-application-message-to-X12-version-transaction-partner.dwl, and rename it.
Example: OUT-SAP-purchaseorder-XML-to-X12-4010-850-MythicalSupplier.dwl
Import the dwl file in the Map section of outbound message flows.
