= Creating Reference Maps for Message Types

When you create a new message type, you can associate it with a DataWeave reference map. This is mandatory for Receive from Partners message types formatted with JSON or XML and for all Source at Host message types.

* The input of the map is the payload that follows the schema uploaded in the definition for the message type.
* The output of the map contains the following fields:

|===
| *Field* | *Description* | *Required*
| partnerReferenceId
| Identifier that uniquely identifies the partner
a| Yes. This field is required for:

* Receive from Partners message types formatted with JSON or XML
* All Source at Host message types
| hostReferenceId
| Identifier that uniquely identifies the host
a| No. This field is optional for:

* Receive from partners message types formatted with JSON or XML
* All Source at Host message types
| BusinessDocumentKey
|Key reference value, such as `Order Number` or `Invoice number`
| No
| customAttributes
| Array of attributes to extract from the payload.
{sp}+
{sp}+
Use an array, even if there is only one custom attribute to extract. This enables support for transactions with one-to-many relationships, such as transactions in which one shipment notice includes multiple purchase order numbers.
a| No. This field is optional for:

* All Receive from Partners message types
* All Source at Host message types
|===

== Example Map for a Receive from Partners Message Type

The following map transforms a partner's inbound X12 payload. It contains a business document key and two custom message attributes:

* The value of the business document key is `payload.TransactionSets.v004010."855".Heading."020_BAK".BAK03[0]`.
* The value of the `purchaseOrderNumber` custom message attribute is `payload.TransactionSets.v004010."855".Heading."020_BAK".BAK03[0]`.
* The value of the `vendorSalesOrderNumber` custom message attribute is `payload.TransactionSets.v004010."855".Heading."020_BAK".BAK08[0]`.

The input to the map looks like this:

----
%dw 2.0
output application/json
{
	businessDocumentKey: payload.TransactionSets.v004010."855".Heading."020_BAK".BAK03[0] default "",
	customAttributes: [
		{
			alias: "purchaseOrderNumber",
			values: [payload.TransactionSets.v004010."855".Heading."020_BAK".BAK03[0]]
		},
		{
			alias: "vendorSalesOrderNumber",
			values: [payload.TransactionSets.v004010."855".Heading."020_BAK".BAK08[0]]
		}
	]
}
----

The generated output of the map looks like this:

----
{
  "businessDocumentKey": "ORDER-70010",
  "customAttributes": [
    {
      "alias": "purchaseOrderNumber",
      "values": [
        "ORDER-70010"
      ]
    },
    {
      "alias": "vendorSalesOrderNumber",
      "values": [
        "SO-5100803142"
      ]
    }
  ]
}
----


== Example Map for a Source at Host Message Type

The following map transforms the outbound JSON or XML payload from the backend. It contains the partner reference ID, host reference Id, business document key, and three custom attributes:

* The value of the partner reference ID is `payload.Header.CustomerName`.
* The value of the host reference ID is `payload.Invoice.Header.LineOfBusiness`.
* The value of the business document key is `payload.Invoice.Header.InvoiceNumber`.
* The value of the `invoiceNumber` custom attribute is `payload.Invoice.Header.InvoiceNumber`.
* The value of the `purchaseOrderNumber` custom message attribute is `payload.Invoice.Header.PurchaseOrderNumber`.
* The value of the `invoiceAmount` custom message attribute is  `payload.Invoice.Header.TotalInvoiceAmt`.

The input to the map looks like this:

----
%dw 2.0
output application/json
---
{
	partnerReferenceId: payload.Invoice.Header.CustomerName,
	hostReferenceId: payload.Invoice.Header.LineOfBusiness default "MYTHICAL",
	businessDocumentKey: payload.Invoice.Header.InvoiceNumber,
	customAttributes: [
		{
			alias: "invoiceNumber",
			values: [payload.Invoice.Header.InvoiceNumber default "UNKNOWN"]
	},
	{
			alias: "purchaseOrderNumber",
			values: [payload.Invoice.Header.PurchaseOrderNumber default "UNKNOWN"]
	},
	{
			alias: "invoiceAmount",
			values: [ "\$ " ++ payload.Invoice.Header.TotalInvoiceAmt default "UNKNOWN"]
	}
]
}
----

The generated output of the map looks like this:

----
{
  "partnerReferenceId": "ALPHA-CAN",
  "hostReferenceId": "Mythical-MG",
  "businessDocumentKey": "INV97750061",
  "customAttributes": [
    {
      "alias": "invoiceNumber",
      "values": [
        "INV97750061"
      ]
    },
    {
      "alias": "purchaseOrderNumber",
      "values": [
        "ORD3893988"
      ]
    },
    {
      "alias": "invoiceAmount",
      "values": [
        "$ 3756.24"
      ]
    }
  ]
}
----

== Exchange Example of Using Custom Attributes

To see a comprehensive example that uses custom attributes when implementing an end to end B2B order to cash, see https://anypoint.mulesoft.com/exchange/com.mulesoft.muleesb.modules/b2b-order-to-cash-mapping/.

== See Also

* xref:partner-manager-create-message-type.adoc[Creating a Message Type]
* xref:modify-message-type-settings.adoc[Modifying Message Type Settings]
* xref:use-custom-attributes.adoc[Using Custom Message Attributes with Message Types]
