= Create and Configure Endpoints

You can create endpoints in either the host or partner page or from the Message Flow configuration wizard.

== Create Endpoints from the Partner Page

Create and configure new send or receive endpoints in the partner page:

. In the left navigation menu, select *Partners*.
. Select the partner for which to you want to create and configure an endpoint.
. Click *New* in the *Endpoints: Receive from <partner-name>* or *Endpoints: Send to <partner-name>* section.
. <<configure-endpoint,Configure the endpoint>> according to the type of endpoint you are creating and the protocol you selected.
. Click *Save*.

The partner page in which you create send and receive endpoints automatically owns those endpoints.

== Creating Endpoints From the Host Page

. In the left navigation, select the host.
. Click *New* in the section for the type of endpoint you are creating:
* *Endpoints: Receive from partners*
* *Endpoints: Send to partners*
* *Endpoints: Target at <host-name>*
* *Endpoints: Source at <host-name>*
. <<configure-endpoint,Configure the endpoint>> according the type of endpoint you are creating and the protocol you selected.
. Click *Save*.

== Creating Endpoints From the Message Flow

When you create endpoint types from the message flow, Partner Manager automatically designates the usage.

When you create partner facing (receive or send) endpoints from the message flow wizard, you can assign the owner by making appropriate selection.

For more information about creating endpoints from the message flow wizard, see xref:configure-message-flows.adoc[Create and Configure an Inbound Message] and xref:create-outbound-message-flow.adoc[Create and Configure an Outbound Message Flow].

== Supported Endpoint Protocols

The way you configure Partner Manager endpoints depends on the protocol you use to send and receive messages.

Partner Manager supports the following endpoint protocols:

[%header%autowidth.spread]
|===
|Protocol | Trading Partners | Backend
|SFTP | Receive, Send | Receive, Send
| HTTP/HTTPS | Send | Receive, Send
| AS2 | Receive, Send | N/A
|===

[[configure-endpoint]]
== Configure Endpoint Protocol and Type-Specific Settings

The values for the endpoint's settings vary according to the protocol-type of the endpoint for which you are configuring the settings:

* xref:endpoint-as2-receive.adoc[AS2 Receive Endpoint Settings]
* xref:endpoint-as2-send.adoc[AS2 Send Endpoint Settings]
* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
* xref:endpoint-sftp-send.adoc[SFTP Send Endpoint Settings]
* xref:endpoint-https-receive.adoc[HTTP and HTTPS Receive Endpoint Settings]
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Endpoint Settings]
