= Create and Configure Endpoints

You can create endpoints in the host or partner page or by using the Message Flow wizard.

== Create and Configure Endpoints from the Partner Page

Create and configure new send or receive endpoints using the partner page:

. In the left navigation menu, select *Partners*.
. Select the partner for which to create and configure the endpoint.
. Click *New* in the *Endpoints: Receive from <partner-name>* or *Endpoints: Send to <partner-name>* section.
. <<configure-endpoint,Configure the endpoint>> according to the type of endpoint you are creating and the protocol you selected in the *Endpoints: Send to <partner-name>* window.
. Click *Save*.

Ownership of the endpoints (receive or send) is automatically assigned based on the partner from which you are creating the endpoint.

== Create and Configure Endpoints from the Host Page

. In the left navigation, select the host.
. Click *New* in the section for the type of endpoint you are creating:
* *Endpoints: Receive from partners*
* *Endpoints: Send to partners*
* *Endpoints: Target at <host-name>*
* *Endpoints: Source at <host-name>*
. <<configure-endpoint,Configure the endpoint>> type and compatibility with the protocol you selected in the *New endpoint: <endpoint-type>* window.
. Click *Save*.

== Create and Configure Endpoints Using the Message Flow Wizard

When you create endpoint types and configure them using the Message Flow wizard, Partner Manager automatically determines whether they are used for inbound or outbound message flows. Using the Message Flow wizard, you can xref:configure-message-flows.adoc[Create and Configure an Inbound Message Flow] or xref:create-outbound-message-flow.adoc[Create and Configure an Outbound Message Flow].

== Supported Endpoint Protocols

The configuration of Partner Manager endpoints depends on the protocol used to send and receive messages.

Partner Manager supports the following endpoint protocols:

[%header%autowidth.spread]
|===
|Protocol | Trading Partners | Backend
|SFTP | Receive, Send | Receive, Send
| HTTP/HTTPS | Send | Receive, Send
| AS2 | Receive, Send | N/A
|===

[[configure-endpoint]]
== Configure Endpoint Protocol and Type-Specific Settings

The values for the endpoint's settings vary according to the protocol-type of the endpoint for which you are configuring the settings:

* xref:endpoint-as2-receive.adoc[AS2 Receive Endpoint Settings]
* xref:endpoint-as2-send.adoc[AS2 Send Endpoint Settings]
* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
* xref:endpoint-sftp-send.adoc[SFTP Send Endpoint Settings]
* xref:endpoint-https-receive.adoc[HTTP and HTTPS Receive Endpoint Settings]
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Endpoint Settings]

== See Also

* xref:endpoints.adoc[Endpoints]
