= Creating Endpoints

You can create new endpoints from the *Partners*, *<host>*, or third-party page, or by using the Message Flow wizard.

== Create Endpoints from the Partners Page

Use the *Partners* page to create new send and receive endpoints owned by partners or third-party connections:

. In the sidebar, select *Partners*.
. Select the partner or third-party connection for which to create the endpoint.
. In the *Endpoints* section, click *New*.
. In the *New Endpoint* window *Usage* field, select *Receive from partners* or *Send to partners*.
. In the *Protocol* field, select the protocol to use for the endpoint.
. <<configure-endpoint,Configure the endpoint>> according to the endpoint type and protocol.
. Click *Save*.

Ownership of endpoints is automatically assigned based on the partner or third-party connection from which you are creating the endpoint.

== Create Endpoints from the Host Page

Use the *<host>* page to create new send and receive endpoints owned by the host:

. In the sidebar, select the host.
. In the *Endpoints* section, click *New*.
. In the *New Endpoint* window *Usage* field, select the endpoint type.
. In the *Protocol* field, select the protocol to use for the endpoint.
. <<configure-endpoint,Configure the endpoint>> according to the endpoint type and protocol.
. Click *Save*.

== Create Endpoints Using the Message Flow Wizard

You can use the Message Flow Wizard to create send and receive endpoints owned by hosts, partners, or third-party connections.

For information about using the Message Flow wizard to create new endpoints, see xref:configure-message-flows.adoc[Create Inbound Message Flows] and xref:create-outbound-message-flow.adoc[Create Outbound Message Flows].

[[configure-endpoint]]
== Protocol-Specific Endpoint Settings

The values for the endpoint's settings vary according to the endpoint type and protocol:

* xref:endpoint-as2-receive.adoc[AS2 Receive Endpoint Settings]
* xref:endpoint-as2-send.adoc[AS2 Send Endpoint Settings]
* xref:endpoint-ftp-receive.adoc[FTP Receive Endpoint Settings]
* xref:endpoint-ftp-send.adoc[FTP Send Endpoint Settings]
* xref:endpoint-https-receive.adoc[HTTP and HTTPS Receive Endpoint Settings]
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Endpoint Settings]
* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
* xref:endpoint-sftp-send.adoc[SFTP Send Endpoint Settings]

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:deploying-receive-endpoints.adoc[Deploying Receive Endpoints]
* xref:modify-endpoints.adoc[Modifying Endpoints]
* xref:delete-endpoints.adoc[Deleting Endpoints]
