= Create and Configure an Outbound Message Flow

You can create and configure an outbound message flow to receive application messages from your backend systems, validate and transform these messages, and then send the translated EDI message to your trading partners either directly, or through 3rd party connections.

== Create an Outbound Message Flow

. From your Anypoint Partner Manager sandbox or production environment, select *Message Flows* in the navigation menu.
. Click *New message flow > Send to partner*.
. Select an existing partner from the list and click *Select* or select *New* to xref:configure-partner.adoc#create-partner[create a trading partner]. +
A new message flow is created. +

== Configure the Source at Host Endpoint

. Expand the *Source at <host-name>* section.
. In *Endpoint: Source at <host-name>*, click *Select*.
. In the *Select an endpoint: Source at <host-name>* window:
.. To use an existing receiving endpoint:
... Select the endpoint from the list and click *Select*.  +
The endpoint is added to the message flow, and a message appears indicating that the endpoint is missing an identifier.
... Click *Add* to add a unique identifier for the endpoint.
.. To create a new receiving endpoint:
... Click *New* next to the search box.
... From the *Owner* drop-down list, select the endpoint's owner.
... From the *Protocol* drop-down, select the protocol and configure it according to the protocol you select:

. Click *Save*. +
The endpoint is added to the message flow.

== Configure the Source Message Type

. Expand the *Source at <host>* section.
. In the *Source message type section*, click *Select*.
. In the *Select message type* section:
.. To use an existing message type, select the message type from the list and click *Select*.
.. To create a new message type:
... Click *New* next to the search box.
... From *Format*, select either:
* *JSON*
* *XML*
... From *Schema*, click *Choose file* and browse to the location of your custom schema.
... Accept the default value for *Message type identifier* or enter a new value.
... Click *Choose file* to browse to the location of the DataWeave map and select it.
... Click *Save*.
The message type is added to the message flow.

== Configure Reference IDs

. Expand the *Source at <host>* section.
. From the *<host> reference ID* drop-down list, select your organization’s internal reference ID (such as business unit name) as it would appear in the data element of the source JSON or XML payload from your backend systems. +
The reference ID is added to the message flow

== Import the Translation Map

=== Prerequisites
To create your outbound EDI-to-application message (JSON or XML) map in Anypoint Studio, see xref:partner-manager-maps.adoc[EDI Translation Maps].

=== Steps

. In the message flow, expand the *Map* section.
. Click *Import* and then click *Choose file*.
. In the *New mapping file* window, navigate to the DataWeave map you want to use and then click *Open*.
. Click *Upload mapping*. +
The translation map is added to the message flow.

== Configure the Target Message Type

. Expand the *Message type* section and click *Select*.
. In the *Select message type* window:
* To use an existing message type, select the message type from the list and click *Select*.
* To create a new message type, click *New* next to the search box, define the xref:partner-manager-create-message-type.adoc#create-message-type[EDIFACT and X12 message type], and click *Save*.
+
The message type and its validation settings are added to the message flow.
. In the *Acknowledgement* section, select *Expect functional acknowledgement* (X12) or *Expect CONTRL functional acknowledgment* (EDIFACT).
.. Click *Select*.
.. In the *Select an endpoint: Receive acknowledgment from <partner>* window, click *Select* to specify the endpoint from which to receive your partner's acknowledgment transactions.
+
.. Alternatively, you can create a new receive from partner endpoint:
... Click *New*.
... In the *Owner* field, select the endpoint owner.
... In the *Protocol* field, select the protocol and configure it accordingly:
* xref:endpoint-as2-receive.adoc[AS2]
* xref:endpoint-ftp-receive.adoc[FTP]
* xref:endpoint-sftp-receive-target.adoc[SFTP]
... Click *Save*.
.. In the *Mark overdue after* field, accept the default value of *24 Hours* or configure values based on when you want the outbound transaction to be designated as overdue for an acknowledgment, according to the SLAs you have with your trading partner.
+
When a functional acknowledgment is not received within the specified timer value, Partner Manager marks the outbound transactions as `Overdue`.
. In the *<message format> Settings* section, select the settings.
+
By default, Partner Manager uses the X12 send or EDIFACT send settings that are configured in the trading partner profile page for message validation, delimiters, and character encoding.
+
To apply custom validation settings and delimiters for the message flow you are setting up, select *Custom X12 settings* or *Custom EDIFACT settings* and provide custom configuration values.
. In the *<protocol> Identifiers* section, select the sender and receiver identifiers that are configured under the host and trading partner profiles to use them on the X12 ISA and GS segments or the EDIFACT UNB segments.

== Configure the Target endpoint

. Expand the *Target at <host>* section.
. In the *Send to <partner> section*, click *Select*.
. In the *Select an endpoint: Send to <partner>* window:
.. To use an existing endpoint, select the endpoint from the list and click *Select*.
+
You can select any previously configured Send to partner endpoints owned by the host, the trading partner for whom the message flow is configured, or a 3rd party connection.
+
.. To create a new endpoint:
... Click *New* next to the search box.
... From the *Owner* drop-down,
... From the *Protocol* drop-down, select the protocol and configure it according to the protocol you select:
* xref:endpoint-as2-send.adoc[AS2]
* xref:endpoint-https-send.adoc[HTTP or HTTPS]
* xref:endpoint-ftp-send.adoc[FTP]
* xref:endpoint-sftp-send.adoc[SFTP]
... Click *Save*.

If you selected AS2 as the send to partner endpoint protocol, you must import the AS2 certificate of the partner or 3rd party connection that owns the endpoint, if a certificate already does not exist in the partner or 3rd party connection’s profile.

== Verify the Message Flow is Complete

Partner Manager dynamically validates the message flow configuration elements for completeness and displays a green checkmark if all the building blocks of the message flow are complete. After you verify the configurations, you are ready to deploy the message flow.

== See Also

* xref:create-map-json-xml-to-outbound-x12.adoc[Create a Map For XML or JSON to Outbound EDI X12]
* xref:deploy-message-flows.adoc[Deploy, Test, and Undeploy Message Flows]
* xref:partner-manager-create-message-type.adoc[Create and Configure a Message Type]
