= Creating Inbound Message Flows
:page-aliases: configure-message-flows.adoc

Create inbound message flows to receive messages from partners, including messages that go through third party connections. When you create an inbound message flow, you can validate and transform the inbound messages and then send them to your backend applications.

Anypoint Partner Manager routes inbound messages based on matching identifiers configured for the partner.

Before you create your first message flow, configure your xref:setup-payload-storage-API.adoc[payload storage API].

To create an inbound message flow:

. From the Partner Manager navigation menu, select *Message Flows*.
. Click *New message flow > Receive from partner*.
. Either select an existing partner from the list or select *New* to create a new partner, as described in xref:create-partner.adoc[Create a Partner].
. Configure the receiving endpoint.
. Configure the source message type.
. Import the translation map.
. Configure the target message type.
. Configure the target endpoint.
. Verify that the message flow is complete.

[[receiving-endpoint]]
== Configure the Receiving Endpoint

The receiving endpoint in an inbound message flow receives the messages that your partners send, either directly or via third party connections. To configure a receiving endpoint, you can either select an existing endpoint owned by the host, partner, or third party connection, or you can create a new endpoint.

Partner Manager supports the AS2, FTP, HTTP, HTTPS, and SFTP formats for the receiving endpoint in an inbound message flow.

To configure the receiving endpoint:

. In the message flow, expand the *Receiving endpoint* section and click *Select*.
. In the *Select an endpoint: Receive from <partner>* window, do either of the following:
* Select an existing receiving endpoint and click *Select*.
* Click *New* to create a new receiving endpoint, as described in xref:create-endpoint.adoc[Create and Configure Endpoints].
+
If you select an endpoint owned by a third party connection, the messages go through that connection.
+
After you select an endpoint, it is added to the message flow.

If the protocol of the receiving endpoint is AS2, perform these additional steps:

. Select the AS2 sender from the dropdown menu and then select either of the following:
* The partner's name, to enable your organization to receive the AS2 messages directly from the partner for whom the message flow is created
* The name of a third-party connection, to enable your organization to receive the partner's AS2 messages via a third-party connection, such as a VAN or 3PL
+
The AS2 identifier and certificate of the selected third party-connection are used for validating the AS2 messages.
+
. If there is no valid certificate in the associated profile, import one from the partner or from the third-party connection sending the AS2 message.

[[source-message-type]]
== Configure the Source Message Type

The source message type in an inbound message flow defines the structure of the messages that Partner Manager receives from a partner or third party connection. Partner Manager supports the JSON, EDIFACT, X12, and XML formats for source message types in an inbound message flow.

To configure the source message type:

. In the message flow, expand the *Source message* section and click *Select*.
. In the *Select message type* window, do either of the following:
* Select an existing message type and click *Select*.
* Click *New* to create a new receive from partners type, as described in xref:partner-manager-create-message-type.adoc[Create and Configure Message Types].

+
The message type and its validation settings are added to the message flow.

If the source message type is X12 or EDIFACT and your partner expects your organization to return functional acknowledgements, perform these additional steps:

. In the *Acknowledgement* section, select the check box next to *Send 997 functional acknowledgment (X12)* or *Send CONTRL functional acknowledgement (EDIFACT)*.
. Click *Select*.
. In the *Select an endpoint: Send acknowledgement to <partner>* window, do either of the following:
* Select the endpoint to receive the acknowledgment messages from your partner and click *Select*.
* Click *New* to create a new send to endpoint, as described in xref:create-endpoint.adoc[Create and Configure Endpoints].

+
The acknowledgment is added to the message flow.

[[import-map]]
== Import the Translation Map

A translation map in an inbound message flow transforms your inbound messages to your organization's enterprise application format. Create a translation map by using DataWeave. For more information, see xref:partner-manager-maps.adoc[ Translation Maps].

To import the translation map:

. In the message flow, expand the *Map* section.
. Click *Import > Choose file*.
. Navigate to the DataWeave map you want to use and click *Open*.
. Click *Upload mapping*.
+
The translation map is added to the message flow.

[[configure-target]]
== Configure the Target Message Type

The target message type in an inbound message flow defines the structure of the messages that Partner Manager sends to the backend applications. Partner Manager supports the JSON and XML formats for target message type in an inbound message flow.

To configure the target message type:

. In the message flow, expand the *Target at <host>* section.
. In the *Message Type* section, click *Select*.
. In the *Select message type* window, do either of the following:
* Click *New* to create a new target at host message type.
. Click *Save*.

[[target-endpoint]]
== Configure the Target Endpoint

The target endpoint in an inbound message flow receives the transformed messages on the backend applications. Partner Manager supports the FTP, HTTP, HTTPS, and SFTP formats for the target endpoint in an inbound message flow.

To configure the target endpoint:

. In the message flow, expand the *Target at <host>* section.
. In the *Target at <host>* section, expand the *Endpoint* section and click *Select*.
. In the *Select an endpoint: Target to <host>* window, do either of the following:
* Select an existing target at host endpoint and click *Select*.
* Click *New* to create a new endpoint, as described in xref:create-endpoint.adoc[Create and Configure Endpoints].

+
After you select an endpoint, it is added to the message flow.

[[verify-message-flow]]
== Verify That the Message Flow Is Complete

Partner Manager dynamically validates the message flow configuration elements for completeness and displays a green checkmark if all of the message flow building blocks are complete. After you verify the message flow configuration, you can deploy and test it.

== See Also

* xref:inbound-message-flows.adoc[Inbound Message Flows]
* xref:deploy-message-flows.adoc[Deploying and Testing Message Flows]
* xref:manage-message-flows.adoc[Modifying Message Flow Settings]
* xref:inbound-message-routing.adoc[Inbound Message Routing]
