= Custom Message Attributes

Configure integrations to enable users to search for messages by using key fields like Purchase Order Number and Shipment ID. These fields are essential because B2B workflows often involve multiple transactions of different message types, each with unique data fields that identify the transaction.

Partner Manager’s custom message attributes feature helps you define and map these key fields from the data payload structure. Once defined in the source message type for inbound and outbound flows, Partner Manager automatically extracts these custom attributes from the payload.

The image highlights common custom message attributes by showing two B2B workflows and the sequence of message types exchanged between organizations. Some custom attributes are included in all message types and serve as a key for the entire transaction lifecycle. For example, the Purchase Order Number appears in all transactions in a B2B Purchase Order workflow. In a B2B Load Tender workflow, the Shipment ID remains consistent throughout.

image placeholder

Key attributes often appear in different parts of a transaction payload, making them difficult to locate, such as in consolidated shipment notices where one shipment contains multiple order numbers.  To define the fields you want to extract as custom attributes, upload a reference attributes mapping for each transaction for Receive from Partners and Source at Target message types. Custom attribute values are stored in a flat array, allowing you to link multiple values to the same field.

Custom message attributes  provide an open framework to extract data fields for any B2B transaction workflow, such as order to cash and procurement. This explains how to use the feature for a B2B Purchase Order to Invoice workflow. 

== Purchase Order to Invoice Workflow

These examples show how a simple attribute mapping in your message type definition enhances transaction visibility, making it easier to search for and troubleshoot messages.

Before you associate an attribute label with a message type, define the attribute name and alias and a flag to indicate that you want to make the attribute searchable.

image placeholder

=== Inbound EDI X12 4010 850 Purchase Order

Reference mapping for the Receive from Partners X12-4010-850 message type shows how to retrieve fields like Purchase Order Number and Buyer’s Name from different elements in the incoming EDI data payload. 

Notice that the Buyer data is extracted by applying filter criteria to the PER segment based on the PER-01 Qualifier field. Dataweave maps any complexity level to extract information that simplifies the job functions of your operational user personas.

image placeholder

=== Outbound EDI X12 4010 855 Purchase Order Acknowledgement

The reference mapping attached for the Source at Host message type for outbound PO Acknowledgement shows how to retrieve fields like Purchase Order Number andSales Order Number from different fields in the source payload that’s received from the backend. 

image placeholder

=== Outbound EDI X12 4010 856 Advance Shipment Notice

The reference mapping for the Source at Host message type for outbound Advance Ship Notice shows how to retrieve fields like Shipment ID and Carrier SCAC Code from different fields in the source payload received from the backend system. 

In transactions like Advance Shipment Notice, one shipment notice often references multiple order numbers, especially in consolidated shipments where items from several purchase orders are sent together. Custom message attribute values are defined as an array to handle these scenarios.

image placeholder

=== Outbound EDI X12 4010 810 Invoice

The reference mapping for the Source at Host message type for an outbound invoice shows how to retrieve fields like Invoice Number and Invoice Amount from different fields in the source payload that’s received from the backend system. 

image placeholder

=== Search by Custom Attributes

Key fields, like Purchase Order Number and Sales Order Number, that appear in multiple message types are extracted into the same attribute alias. By using the filter options, users can retrieve all transactions that match the attribute value.
 
This image shows a search for all transactions that match a partner’s purchase order number.

image placeholder

This image shows a search for all transactions that match a partner’s invoice number. 

image placeholder
