= Delete Identifiers

You might want to delete an identifier when it is no longer needed. 

You can delete identifiers such as X12 ISA, X12 GS, AS2, and DUNS. You cannot delete the last identifier, as there must be at least one identifier in the list of identifiers.

Before you delete an identifier, consider the following: 

* Deleting an existing host or partner identifier impacts the identification and routing of B2B messages to the associated partner.
* Do you need to replace the identifier with another identifier? +
If you need to replace the identifier, record the values and qualifier type needed.
* Remember that there must always be at least one identifier per message flow before you can delete it.
* You cannot delete an identifier that is used in a message flow.

== Deleting Identifiers

. In the left navigation menu, select *Partners*.
. From the list of partners, select the partner that has the identifier to delete. 
. In the *Identifiers* section, hover over the identifier you want to delete and click the trash can icon that appears on right-hand side of the *Identifiers* row.
. If you want to replace the identifier, click *New* and xref:partner-manager-identifeiers.adoc[follow the steps to create an identifier]. 

After successfully deleting an identifier, you can create a new identifier with the same name as the one you deleted.