= Delete Identifiers

You might want to delete an identifier when it is no longer needed.
Consider that deleting an existing host or partner identifier impacts the identification and routing of B2B messages to the associated partner.
Ask yourself the following when deleting an identifier: Why do you want to delete it? Do you need to replace it with another identifier?
Remember that there must always be at least one identifier per message flow before you can delete it.

After successfully deleting an identifier, you can create a new identifier with the same value as the one you deleted.

You can delete identifiers such as X12 ISA, X12 GS, AS2, and DUNS. You cannot delete the last identifier, as there must be at least one in the list.

. If you need to replace the identifier, record the values and qualifier type needed.

. Choose the partner name and click *<Partner name>* to expand it.

. Hover over the identifier you want to delete and click the trashcan icon that appears towards the right-hand side of the identifiers row.

. If you need a replacement, add it now by clicking *New*.