= Deleting Endpoints

You can delete endpoints from the
host or partner page if the endpoints are not used in message flows:

. From Anypoint Partner Manager, do either of the following:
* If the host owns the endpoint, select the *<host name>* from the navigation menu.
* If a partner or third-party connection owns the endpoint, select *Partners* from the navigation menu and then select the owning partner or third-party connection.
. In the *Endpoints* section, locate the endpoint that you want to delete.
+
To locate endpoints that don’t have associated message flows, look for `-` in the *Message Flows* column.
+
. In the row containing the endpoint that you want to delete, hover over the endpoint name, select the trash can icon that appears, and click *Delete*.

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoints[Creating Endpoints]
* xref:modify-endpoints[Modifying Endpoints]
* xref:create-outbound-message-flow.adoc[Creating Outbound Message Flows]
* xref:configure-message-flows.adoc[Creating Inbound Message Flows]
