= Delete Identifiers

When an identifier is no longer needed, consider deleting the identifier.

You can delete identifiers such as X12 ISA, X12 GS, AS2, and DUNS.

Before you delete an identifier, consider the following:

* Remember that there must always be at least one identifier per message flow.
* You cannot delete an identifier that is used in a message flow.
* Deleting an existing host or partner identifier impacts the identification and routing of B2B messages to the associated partner.
* If you need to replace the identifier with another identifier, record the required values and qualifier type.



. In the left navigation menu, select *Partners*.
. Select the partner containing the identifier you want to delete.
. In the *Identifiers* section, in the right-hand side of the *Identifiers* row, hover over the identifier you want to delete and click the trash can.
. If you want to replace the identifier, click *New* and xref:partner-manager-identifiers.adoc[follow the steps to create an identifier].

After successfully deleting an identifier, you can create a new identifier with the same name as the one you deleted.

== See Also

* xref:configure-host.adoc[Configure and Manage a Host Profile]
* xref:message-flows.adoc[Message Flows]
* xref:outbound-message-routing.adoc[Outbound Message Routing]
