= Deploying and Testing Message Flows

Anypoint Partner Manager dynamically validates the message flow configuration elements as you complete them and displays a green checkmark next to each of the validated elements.

After Partner Manager validates the message flow configuration elements, deploy and test the message flow in a sandbox environment. It can take up to five minutes from the time the message flow deployment completes in the UI for the changes to take effect in the runtime.

== Deploy Message Flows

To deploy a message flow, click the *Deploy* button.

The message flow is deployed to Mule runtime engine, enabling you to:

* Start receiving messages from your partner.
* Use the *Activity* page to track the processed messages.

== Test a Deployed Message Flow

After you deploy the message flow, send test messages to verify that:

* You can receive messages and acknowledgments from your partners.
* The DataWeave map transformed the payload correctly.
* Your backend applications received the transformed messages.

Test your message flow in the Partner Manager sandbox environment by sending a test file to the receiving endpoint:

. In the sidebar, select *Activity*.
. Search for the transmission by specifying the desired filters.
. In the transmission search results, you can do the following:
* Verify that the transmission was sent or received. 
* Verify that Partner Manager sent the transmission to the correct endpoint.
* If TA1 and functional acknowledgments (999 or 997) were set, review and confirm that they are present in the transmission.
. Click the transmission to view more summary information. 
+
Here, you can verify whether Partner Manager routed the transmission to the correct message flow and whether it sent a message disposition notification (MDN).
+
. Click the messages link to view summary information for the messages in the transmission and then click an individual message.
. Click *Target payload* in the *Target* section to view the message's payload and determine whether Partner Manager transformed the message correctly.
. Repeat steps 5-6 for each message to verify.

== See Also

* xref:undeploy-message-flows.adoc[Undeploying Message Flows]
* xref:create-inbound-message-flow.adoc[Creating Inbound Message Flows]
* xref:create-outbound-message-flow.adoc[Creating Outbound Message Flows]
