= Deploying Partner Manager On-Premises

To deploy Partner Manager on-premises, install and set up Mule runtime engine (Mule) on-premises and register it in Anypoint Runtime Manager in the appropriate environment, then create a server group to which to add the servers you create.

. In the appropriate environment within your Anypoint Platform account, create a server group in the Runtime agent and name it `B2BServerGroup`. All Mule B2B-processing apps are deployed to this server group.
+
When you create the server group:

* Name `B2BServerGroup` exactly as shown, because the server group name is case-sensitive.
* Configure `B2BServerGroup` with a single Mule runtime server because Partner Manager does not support multiple runtime instances within the group.

+
See the Runtime Manager documentation xref:runtime-manager::server-group-create.adoc[Create a Server Group (Hybrid)] for the steps to create a server group.
+
. xref:mule-runtime::runtime-installation-task.adoc[Download and Install Mule]. +
Partner Manager supports Mule 4.3.
. After you install Mule, navigate to the `wrapper.conf` file, which is located in `$MULE_HOME/conf/`.
. In the `wrapper.conf` file, add the required parameters and adjust the memory and heap size configuration values for your environment.
+
If you are unsure about the Mule capacity you need to manage your B2B transactions, contact your MuleSoft account representative for assistance.
+
These are example values:
+
[source,xml,linenums]
----
# Increase the MetaSpace.
wrapper.java.additional.7=-XX:MetaspaceSize=1256m
wrapper.java.additional.8=-XX:MaxMetaspaceSize=2256m

# Increase JVM Memory
# Initial Java Heap Size (in MB)
wrapper.java.initmemory=4606
# Maximum Java Heap Size (in MB)
wrapper.java.maxmemory=4606
----
+
. xref:mule-runtime::installing-an-enterprise-license.adoc[Install an Enterprise License].
. Add the server in Runtime Manager based on the instructions in xref:runtime-manager::servers-create.adoc[Add Servers to Runtime Manager].
. Start Mule and verify it is active within Anypoint Runtime Manager.
. Add the servers you created to the `B2BServerGroup` server group you created earlier. +
See xref:runtime-manager::server-group-add.adoc[Add Servers to a Group].
