= Deploy and Test a Message Flow

Anypoint Partner Manager dynamically validates the message flow configuration elements as you complete them and displays a green checkmark next to each of the validated elements.

After Partner Manager validates the message flow configuration elements, you can deploy and test the message flow. It is best to deploy the message flow in a sandbox environment. After you verify that the message flow is successful, you can undeploy it from the sandbox and redeploy it to your production environment.

== Deploy Inbound Message Flows

To minimize the impact of the service interruption caused by deploying a message flow, perform message flow deployments outside of your regular business hours. This issue does not exist on CloudHub because CloudHub provides a zero-downtime update of the AS2 endpoint application. [*Vijay, is this applicable only for AS2 endpoints - send or receive?*]

To Deploy Inbound Message Flows, click the *Deploy* button.

The message flow is deployed to Mule runtime engine, and you can do the following:

* Start receiving messages from your partner
* Use the *Activity* page to track the processed messages.

== Test a Deployed Message Flow

After you deploy the message flow, send test messages to verify that:

* You can receive messages and acknowledgments from your partners.
* The DataWeave map works.
* Your backend applications receive the transformed messages.

Test your message flow in your Partner Manager sandbox environment by sending a test file to the receiving endpoint:

. In the navigation menu, select *Activity* and select the transmission to test.
. Scan for an exclamation point (!) in any of the boxes next to the displayed flow stages.
+
Exclamation points indicate that there is an issue with the transmission. Address any issues you find.
. If the system was set up to view payloads, review the received payload by clicking *View payload* next to the *Received transmission* section.
+
If you not sure about whether you should be able to view a payload, contact your B2B System Administrator.
. If TA1 and functional acknowledgments (999 or 997) are set, review and confirm that they are present.
. Verify that the transmission routed the messages to the correct message flow.
. Verify that Partner Manager routed the messages to the target system, delivered the messages to the target endpoint,
 and transformed the messages correctly.

== See Also

* xref:undeploy-message-flows.adoc[UnDeploy Inbound Message Flows]
* xref:create-inbound-message-flow.adoc[Create an Inbound Message Flow]
* xref:create-outbound-message-flow.adoc[Create an Outbound Message Flow]
