= Message Types

Message types define the structure of the transactions that Anypoint Partner Manager receives or sends. You can define the following kinds of message types:

* Receive from Partners
+
Defines the structure of the transactions that partners or third-party connections send to the host
+
* Target at Host
+
Defines the structure of the transactions that the backend sends to the host
+
* Source at Host
+
Defines the structure of the transactions that the host sends to partners or third-party connections
+
* Send to Partners
+
Defines the structure of the transactions that the host sends to partners or third-party connections

Message types are always managed in the host profile page, regardless of whether they are used for a single partner or for multiple partners. Additionally, message types are reusable across message flows for different trading partners.

== See Also

* xref:partner-manager-create-message-type.adoc[Creating Message Types]
* xref:modify-message-types.yml[Modifying Message Types]
* xref:delete-message-types.adoc[Deleting Message Type Settings]
