= Message Types

Message types define the structure of the messages that Anypoint Partner Manager receives or sends. Partner Manager supports the following message types:

* Receive from Partners
+
Defines the structure of the EDIFACT, JSON, X12, or XML messages that Partner Manager receives from partners either directly or via third-party connections
+
Send to Partners
+
Defines the structure of the EDIFACT, JSON, X12, or XML messages that Partner Manager sends to partners either directly or via third-party connections
+
* Source at Host
+
Defines the structure of the JSON or XML messages that Partner Manager receives from the backend applications
+
* Target at host
+
Defines the structure of the JSON or XML messages that Partner Manager sends to the backend applications

Message types are always managed in the *<host>* page, regardless of whether they are used for a single partner or for multiple partners. Additionally, message types are reusable across message flows for different partners.

== See Also

* xref:partner-manager-create-message-type.adoc[Creating Message Types]
