= Configuring Send Settings for Outbound EDIFACT Messages

Partner Manager enables you to configure the EDIFACT envelope parameters, validation rules, control numbers, character encoding, and separators to apply when sending an outbound EDIFACT transmission from the host to a partner.

To configure a partner's EDIFACT send settings:

. In the navigation menu, select *Partners*.
. Select the partner for whom to configure the send settings.
. In the *Validation and acknowledgment settings* section's *Send to <partner-name>* column, click *EDIFACT*.
. In the menu on the left, select the setting to configure:
* <<general-settings,General settings>>
* <<global-control-numbers,Global control numbers>>
* <<character-set,Character set and separators>>
. Click *Save*.

The values you configure in the partner's settings page are used by default for all EDIFACT messages sent to that trading partner. You can override the settings you configure at the message flow level by selecting the custom option while creating an outbound message flow.

[NOTE]
It can take up to five minutes for your configuration changes to sync with Mule.

[[general-settings]]
== General Settings

Use the following settings to configure the general validation rules for outbound EDIFACT messages:

[%header%autowidth.spread]
|===
|Setting |Description |Default Value
|Send Syntax Version
|Syntax version for outbound messages
|VERSION4
|Send UNA
|If enabled, adds a UNA segment at the beginning of the generated EDIFACT payload
|Enabled
|Enforce valid characters
|Enforces valid characters
|Enabled
|Enforce length limits
|Validates data elements against length limits defined in the EDI schema used
|Enabled
|Expect CONTRL for each transmission sent to <partner>
|When enabled, sets UNB-09 to `1`, indicating that a technical acknowledgment is expected in the partner's response
|Disabled
|===

[[global-control-numbers]]
== Global Control Numbers

Partner Manager applies a global control number at the partner level on the EDIFACT interchanges generated from outbound message flows. These control numbers are sequenced across all message types sent to a trading partner, including functional acknowledgments. The control number starts with a default value of `1` and increases sequentially each time your organization sends outbound transmissions.

To change the initial value to maintain sequencing and avoid duplication:

. Click *Change* and enter the desired initial control number.
. Click *Save*.

[NOTE]
It can take up to five minutes to apply the change at runtime.

[[character-set]]
== Character Set and Separators

Use the following settings to set the character encoding and separators for the generated EDIFACT payload:

[%header%autowidth.spread]
|===
|Setting |Description |Default
|Character encoding
a|Character encoding for messages
|ASCII_B
|Data element separator
|Data element separator character
|+
|Component separator
|Component element separator characters
|:
|Repetition separator
|Repetition separator character
|*
|Segment terminator
|Segment terminator character
|'
|Release character
|Release character
|?
|Line ending between segments
a|
Character that adds line endings between segments to improve the readability of the output message text. Possible values include:

* NONE
+
Generates the EDIFACT payload as a single line with segments separated by this character
+
* CR
+
Carriage return
+
* CRLF
+
Carriage return and line feed
+
* LF
+
Line Feed
|CRLF
|Test Indicator
a| When you select *Test* from the drop-down, sets UNB-11 to `1`, which indicates that this is a test message.
|Production
|===

== See Also

* xref:create-outbound-message-flow.adoc[Creating and Configuring Outbound Message Flows]
* xref:create-partner.adoc[Creating Partners]
* xref:modify-partner-settings.adoc[Modify Partner Settings]
