= EDIFACT Receive (Inbound) Settings

Partner Manager enables you to configure the EDIFACT acknowledgments and validation rules to apply when processing an inbound EDIFACT message.

== Configure the Receive Settings

. In the navigation menu, select *Partners*.
. Select the partner for whom you want to configure the settings.
. In the *Validation and acknowledgment settings* section, under *Send to <partner-name>*, click *EDIFACT*.
. In the menu on the left, select the setting to configure:
* <<ack-settings,Acknowledgments>>
* <<validation-settings,Validation>>
* <<control-numbers,Control Numbers>>
. Click *Save*.

[NOTE]
It can take up to five minutes or so for your configuration changes to sync with Mule.

[[ack-settings]]
== Acknowledgment Settings

To configure acknowledgements:

. Enable the *Send CONTRL functional acknowledgement when messages fail to route to a message flow* setting.
. Select an endpoint where the functional acknowledgement message will be sent to the trading partner.

The *Send CONTRL functional acknowledgement when messages fail to route to a message flow* setting provides a functional acknowledgment (the receipt and syntactical acceptability of a message) with the exchange. Functional acknowledgment settings are configured for each message flow and apply only when there is a failure to route the message to one of the message flows.

== Validation settings

Select one or more of the following options to ensure that all EDIFACT messages received from the trading partner meet validation rules. If a message does not meet an enabled rule, Partner Manager rejects it. Parter Manager logs all validation errors and reports them in the CONTRL acknowledgments.

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Enforce length limits
a|
If selected, Partner Manager rejects a message with values that are too short or long. If unselected, Partner Manager accepts the message.
|Enabled
|Enforce value repeats
a|
If selected, Partner Manager rejects a message with values that are repeated too many or too few times. If unselected, Partner Manager accepts the message.
|Enabled
|Enforce valid characters
| If selected, Partner Manager rejects a message with invalid characters. If unselected, the characters are either passed through or substituted and Partner Manager accepts the message.
|Enabled
| Allow unknown segments
a|
If selected, Partner Manager ignores unknown segments. If unselected, Partner Manager rejects a message that contains unknown segments.
|Disabled
|Enforce segment order
|
If selected, Partner Manager enables the segment to be reordered. If unselected, Partner Manager rejects a message that contains segments that are out of order.
|Enabled
|Allow Unused segments
|If selected, Partner Manager ignores unused segments. If unselected, Partner Manager rejects a message that contains unused segments.
|Enabled
|Enforce segment repeats
|If selected, Partner Manager rejects a message that contains segments that repeat too many times. If unselected, Partner Manager accepts the message.
|Enabled
|===

[[control-numbers]]
== Control Numbers

Use these settings to apply validations related to your partners or your use of control numbers within the EDIFACT message:

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Requires unique interchange control number
|If selected, Partner Manager records the interchange numbers previously processed and rejects duplicate interchange numbers from the same partner, as determined by the interchange sender and receiver identification. If unselected, Partner Manager enables processing of the received interchange to continue.
|Disabled

|Requires unique message control number
| If selected, Partner Manager enforces globally unique message control numbers (UNH01) for received transaction sets. This configuration requires message control numbers to be unique across all EDIFACT messages received from the same partner and application, as determined by the interchange sender and receiver identification, and application codes.
| Disabled
|===
