= SFTP Send Endpoint Settings

SFTP send endpoint settings configure where to send B2B messages transmitted over SFTP. There are two types of SFTP send endpoints:

* Send to Partners
+
Target endpoint in an outbound message flow to which transformed B2B EDI messages are sent to partners, either directly or through third-party connections
+
A host, partner, or third-party connection can own SFTP Send to Partners endpoints.

* Target at Host
+
Target endpoint in an inbound message flow to which transformed JSON and XML messages are sent to the backend applications.
+
A host, partner, or 3rd party connection can own FTP send endpoints.

Create SFTP send endpoints by configuring these settings on the *<host>* or *Partner* pages. You can also create these endpoints when you configure an outbound message flow:

[%header%autowidth.spread]
|===
|Name |Description | Required

| Owner
| Partner or host that owns the endpoint.
| Yes

| Protocol
| Protocol selected in the *Protocol* field of the *New endpoint: Receive from partners* window.
| Yes

|Endpoint Name
| Name used to identify the endpoint. The value in the *Endpoint Name* field is generated automatically, but can be modified manually.
| Yes

|Description
|User-supplied value that describes the purpose of the endpoint.
| No

|Host
| SFTP server host, such as `sftp.mulesoft.com`, `localhost`, or `192.168.0.1`. The host must be accessible from your Mule environment.
|Yes

|Port
|Port number of the SFTP server to connect.
|Yes

|Username
|Username for the SFTP server.
|Yes

|Password
|Password for the SFTP server.
|Yes

|Target Path
|Path on your SFTP server to EDI files that were generated from outbound message flows. This is also the path on your SFTP server for storing
transformed JSON and XML files generated from inbound message flows.
|Yes

|Filename pattern
|xref:file-name-pattern.adoc[File name pattern] required by your trading partner or backend application.
|
|===

For EDI messages that are not time-sensitive, such as invoice and payment remittances, use the Write batch operation to merge multiple individual messages into a single interchange and send to your trading partners.

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoint.adoc[Creating Endpoints]
