= Endpoints

Endpoints define the transport protocol configurations necessary to receive or send messages with external trading partners or internal backend applications.

Partner Manager uses endpoints to receive transmissions from partners and messages from backend application, define transport protocols, and specify message or message acknowledgment destinations.

== Endpoint Ownership

You can assign the host, partner, or third party connection as the owner of endpoints to control the use of endpoints within inbound and outbound message flows.

When creating partner-facing endpoints directly from the partner, or third party connection, the ownership of the endpoint is automatically assigned to the entity from which the endpoint was created.

In a message flow, availability depends on the endpoint assignment:

* Any partner can select an endpoint assigned to the host.
* If an endpoint is assigned to a specific partner or third party connection, than that endpoint is available only to the partner for which the endpoint is assigned.

== Supported Endpoint Protocols

The configuration of Partner Manager endpoints depends on endpoint type and protocol. The following table describes the endpoint types, along with their supported protocols and owners:

[%header%autowidth.spread]
|===
|Endpoint Type | Protocol | Can be owned by
| Source at host | FTP, HTTP, HTTPS, SFTP | Host
| Target at host | FTP, HTTP, HTTPS, SFTP | Host
| Receive from partners | AS2 |Host
|  | FTP, HTTP, HTTPS, SFTP | Host, partner, third party connection
| Send to partners| AS2
| Partner, third party connection
|  | FTP, HTTP, HTTPS, SFTP | Host, partner, third party connection
|===

== See Also

* xref:create-endpoint.adoc[Creating Endpoints]
* xref:endpoint-runtime-services.adoc[Endpoint Runtime Services]
* xref:delete-endpoints.adoc[Delete Endpoints]
