= FTP Send Endpoint Settings

FTP send endpoint settings configure where to send data. There are two types of FTP send endpoints:

* Send to Partners
+
Target endpoint in an outbound message flow to which transformed B2B EDI messages are sent to partners, either directly or through third-party connections
+
A host, partner, or third-party connection can own FTP Send to Partners endpoints.

* Target at Host
+
Target endpoint in an inbound message flow to which transformed JSON and XML messages are sent to the backend applications
+
Only a host can own FTP Target at Host endpoints.

Create FTP send endpoints by configuring these settings on the *<host>* or *Partner* pages. You can also create these endpoints when you configure an outbound message flow:

[%header%autowidth.spread]
|===
|Name |Description | Required

| Owner
| Trading partner or host that owns the endpoint.
| Yes

| Protocol
| Protocol selected in the *Protocol* field of the *New endpoint: Receive from partners* window.
| Yes

|Endpoint Name
| Name used to identify the endpoint. The value in the *Endpoint Name* field is generated automatically, but can be modified manually.
| Yes

|Description
|User-supplied value that describes the purpose of the endpoint.
| No

|Host
| FTP server host, such as `ftp.mulesoft.com`, `localhost`, or `192.168.0.1`. The host must be accessible from your Mule environment.
|Yes

|Port
|Port number of the FTP server to connect.
|Yes

|Username
|Username for the FTP server.
|Yes

|Password
|Password for the FTP server.
|Yes

|Target Path
|Path on your FTP server to EDI files that were generated from outbound message flows. This is also the path on your FTP server for storing transformed JSON and XML files generated from inbound message flows.
|Yes

|File name pattern
|xref:file-name-pattern.adoc[File name pattern] required by your partner or backend application.
|
|===

For EDI messages that are not time-sensitive, such as invoice and payment remittances, use the Write batch operation to merge multiple individual messages into a single interchange and send to your trading partners.

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoint.adoc[Create and Configure Endpoints]
