= AS2 Receive Endpoint Settings

Anypoint Partner Manager supports the AS2 Receive from Partners endpoint type, which configures the source endpoint in an inbound message flow that receives B2B messages from partners either directly or via third-party connections. One AS2 endpoint can receive data from multiple partners, multiple third-party connections, or both.

Only a host can own AS2 Receive from Partners endpoints.

Create an AS2 Receive from Partners endpoint by configuring these settings on the *<host>* page:

NOTE: Each AS2 receive endpoint configuration gets deployed as an individual Mule application in the runtime. Consider reusing an existing AS2 receive endpoint configuration across message flows.

[%header%autowidth.spread]
|===
| Setting | Description | Required

|Protocol
|Protocol that the endpoint supports.
|Yes

|Owner
|Host that owns the endpoint.
|Yes

|Endpoint name
|Automatically-generated name used to identify the endpoint, which you can modify manually.
|Yes

|Description
|User-supplied value that describes the purpose of the endpoint.
|No

|Private port (when deploying to VPC)
a|
* When enabled, the AS2 receive endpoint application deploys to the private port `8092` in your xref:runtime-manager::virtual-private-cloud.adoc[Anypoint VPC]. You can manage the access control to the endpoint via the Anypoint VPC and dedicated load balancer settings.
* When disabled, the AS2 receive endpoint application deploys to the public port `8082` by default. You can access the endpoint URL directly over the internet.
|No

|Enforce security level
a|Indicates whether Partner Manager rejects incoming AS2 messages that aren't signed or encrypted. When Partner Manager rejects a message, it returns a negative Message Disposition Notification (MDN) to the sender.

Allowed values:

* Signed & Encrypted
+
(Default) Rejects incoming messages that aren't both signed and encrypted.
* Signed
+
Rejects incoming messages that aren't signed.
* Encrypted
+
Rejects incoming messages that aren't encrypted.
* None
+
Accepts messages that aren't signed or encrypted.
|

|<Host> keystore
|Host keystore files in your environment that store your organization's public certificate and private key.
|Yes
|===

== Next Step

After you create an AS2 receive endpoint, you can deploy it, as described in xref:deploying-receive-endpoints.adoc[Deploying AS2, HTTP, and HTTPS Receive Endpoints].

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoint.adoc[Creating Endpoints]
* xref:as2-endpoints-algorithms.adoc[AS2 Signature and Encryption Algorithms]
* xref:create-keystore.adoc[Creating AS2 Host Keystores]
