= HTTP and HTTPS Send Endpoint Settings

Configure HTTP and HTTPS send endpoints to use when sending transmissions directly to your partners, sending transmissions to your partners through 3rd party connections, and sending transmissions to endpoints that are targets within your organization.

You can use the following types of send endponts:

* Send to partners
+
Sends outbound EDI files to your partners or 3rd party connections, or both, in outbound message flows
* Target at host
+
Sends application messages (JSON or XML) to your backend applications in inbound message flows (*Vijay should this be outbound messageflows?*)

Only hosts and partners can own HTTP and HTTPS send endpoints.

[%header%autowidth.spread]
|===
|Name |Description |Required
| Owner
| Partner or host who owns the endpoint
| Yes

|Protocol
| `HTTP` or `HTTPS`. The default is *HTTPS*.
|Yes

|Endpoint Name
|Automatically-generated name that identifiers the endpoint, which you can modify manually later on
|Yes

|Description
|User-supplied description of the endpoint's purpose and use
|No

|URL
|Target HTTP or HTTPs service to which to send translated EDI, JSON, or XML messages. The URL must be accessible from the runtime environment that processes your B2B integrations.
Enter a well-formed URL (including the path) that specifies where to send the request, for example:
`+https://www.mulesoft.com/sendRequest?name=something+`
|Yes

|Connection Idle Timeout (milliseconds)
|Connection idle timeout period in milliseconds. The default is `30000`.
|Yes

|Response Timeout (milliseconds)
|Maximum time, in milliseconds, for which the request element blocks the execution of the flow that is waiting for the HTTP response
|No
|===

== Authentication Settings

Depending on how you set up your authentication policy, refer to the appropriate authentication type and descriptions here.

[%header%autowidth.spread]
|===
|Authentication Type |Description
|None
|No authentication

|API Key
a| * HTTP Header Name +
The HTTP header parameter associated with the *API Key* value. +
* API Key +
The value for the access key you set

|Basic
a|Specifies a simple authentication policy that protects the API by requiring a username and password when calling apps to make a request.

* Username +
The username you set up with this authentication policy.
* Password +
The password you set up with this authentication policy.

|Client Credentials
a|* Client ID +
The client ID provided when registering your application.
* Client Secret +
The client secret provided when registering your application.
* Client Header +
The client header.
* Client Secret Header +
The client secret header.

|OAuth Token
a|* Token URL +
The valid authorization URL.
* Client ID +
The client ID provided when registering your application.
* Client Secret +
The client secret provided when registering your application.
|===

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoint.adoc[Create and Configure Endpoints]
* xref:Certificates.adoc[Certificates]
