= Endpoint Types and Protocols

Endpoints define the transport protocol configurations necessary to receive or send messages with external trading partners or internal backend applications.

Partner Manager uses endpoints to:

* Receive transmissions from partners 
* Receive application messages from the backend system
* Specify the final destination of the message 
* Define transport protocols
* Specify where to send acknowledgments

== Endpoint Ownership

Partner Manager enables you to assign the host or a particular partner as the owner of endpoints that are partner-facing (receive or send) to control the usage of endpoints within inbound and outbound message flows. 

Endpoints owned by the host are available for selection in message flows for any trading partners. Endpoints owned by a specific trading partner are available for selection in message flows created for that partner only.  

== Types of Endpoints

AnyPoint Partner Manager provides three types of endpoints:

* Receive endpoints. +
Your organization needs to provide endpoints to receive transmissions from your trading partners. +
These endpoints are resources your organization exposes to your trading partners.
* Target endpoints. +
Your organization also has internal endpoints to which it routes messages from the trading partners. The messages routed to the target endpoint are typically validated and transformed before they are routed to the configured target endpoint.
* Acknowledgement endpoints +
Your partners provide you with their own endpoint configurations to which your organization can send acknowledgments, such as an X12 997 or X12 999. Acknowledgments are typically sent back to trading partners and correspond to one or more B2B messages you receive from your trading partners.

== Supported Endpoint Protocols

The way you configure Partner Manager endpoints depends on the protocol you use to send and receive messages. 

Partner Manager supports the following endpoint protocols:

[%header%autowidth.spread]
|===
|Protocol | Trading Partners | Backend
|SFTP | Receive, Send | Receive, Send
| HTTP/HTTPS | Send | Receive, Send
| AS2 | Receive, Send | N/A
|===

== Endpoint Name, Protocol and Type

[%header,cols="3s,7a"]
|===
|Setting |Description

|Name

|Name for this endpoint

Required: Yes +

Default: Automatically populates based on the following values: `Protocol` or `Type`

|Protocol

|Protocol for this endpoint

Required: No +

Valid values: +

`AS2` +

`SFTP` +

`HTTPS` +

Default: None +

|Type

|Type of endpoint

Required: No +

Default: None +

|===

== Configure Endpoint Protocol and Type-Specific Settings

The values for the endpoint's settings vary according to the protocol-type of the endpoint for which you are configuring the settings:

* xref:endpoint-as2-receive.adoc[AS2 Endpoint Settings]
* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Configuration]




