= Endpoints

Endpoints define the transport protocol configurations necessary to receive or send messages with external trading partners or internal backend applications.

Partner Manager uses endpoints to:

* Receive transmissions from partners
* Receive application messages from the backend system
* Specify the final destination of the message
* Define transport protocols
* Specify where to send acknowledgments

== Endpoint Ownership

You can assign the host or a partner as the owner of partner-facing endpoints to control the use of endpoints within inbound and outbound message flows. When creating a message flow, endpoints owned by:

* The host are available for selection for any trading partners.
* A specific trading partner are available for selection by that partner only.

== Types of Endpoints

AnyPoint Partner Manager provides the following types of endpoints:

* Receive endpoints +
Receive transmissions from your trading partners. +
These endpoints are resources your organization exposes to your trading partners.
* Send endpoints +
Send transmissions to your trading partners
* Target endpoints +
Your organization also has internal endpoints to which it routes messages from the trading partners. The messages routed to the target endpoint are typically validated and transformed before they are routed to the configured target endpoint.

== See Also

* xref:create-endpoint.adoc[Create and Configure Endpoints]
* xref:delete-endpoints.adoc[Delete Endpoints]
