= Endpoint Types and Protocols
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

There are three types of endpoints within AnyPoint Partner Manager

** Receive endpoints - On the Host side, for an inbound transmission you need endpoints your organization uses to receive transmissions from your partners.
These endpoints are resources your organization exposes to your trading partners.

** Target endpoints - As the Host, your organization has internal endpoints where you route messages from the trading partner, after they are transformed within the message flow.

** Acknowledgement endpoints - Your partners provide you with endpoint configurations that can be used to send acknowledgement messages like 997s or 999s back to them.
Acknowledgements are typically sent back to trading partners and correspond to one or more B2B messages you receive from them.

Refer to the following section for the type of endpoint you are configuring.

== Endpoint Name, Protocol and Type

[%header,cols="3s,7a"]
|===
|Setting |Description

|Name

|Name for this endpoint

Required:: Yes

Default:: Auto-populates based on the following values:

* Protocol
* Type

|Protocol

|Protocol for this endpoint

Required:
No

Valid values:

* `AS2`
* `SFTP`
* `HTTPS`

Default:

None

|Type

|Type of endpoint

Required:

No

Valid values:

* `SEND`
* `RECEIVE`

Default:

None

// |Default for partner_ checkbox

// |Select this box if you want the choices you make for this endpoint to apply to all endpoints for this partner.

|===

== Protocol/Type-Specific Endpoint Settings

Choose the section that corresponds to the Protocol-Type of the Endpoint for which you are entering settings.

//* <<AS2 Send Settings>>
* <<AS2 Receive Settings>>
//* <<SFTP Send Settings>>
* <<SFTP Receive and Target Settings>>
* <<HTTP(S) Send Settings>>
