= Endpoints
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

A source and target endpoint are the entry points to a service, a process, or a queue or topic destination in service-oriented architecture. In APM, an endpoint defines the protocol, address, and other details specific to an exchange of messages between partners.

== Endpoint Name, Protocol and Type

[%header,cols="3s,7a"]
|===
|Setting |Description

|Name

|Name for this endpoint

Required:: Yes

Default:: Auto-populates based on the following values:

* *Protocol*
* *Type*


|Protocol

|Protocol for this endpoint

Required?::
No

Valid values::

* `AS2`
* `SFTP`

Default::

None

|Type

|Type of endpoint

Required?::

No

Valid values::

* `SEND`
* `RECEIVE`

Default::

None

|Default for partner_ checkbox

|Select this box if you want the choices you make for this endpoint to apply to all endpoints for this partner.

|===

== Protocol/Type-Specific Endpoint Settings

Choose the section that corresponds to the Protocol-Type of the Endpoint for which you are entering settings. Links not working for Beta.

* <<AS2 Send Settings>>
* <<AS2 Receive Settings>>
* <<SFTP Send Settings>>
* <<SFTP Receive Settings>>

