= AS2 Receive Endpoint Settings

The AS2 Receive from Partners endpoint settings configure the source endpoint in an inbound message flow that receives B2B EDI messages from partners directly or via third-party connections. One AS2 endpoint can receive data from multiple partners, third-party connections, or both.

Only a host can own AS2 receive endpoints. Use a host-owned AS2 receive endpoint for an inbound message flow that uses a third-party connection.

Create an AS2 Receive from Partners endpoint by configuring these settings on the *<host>* page:

[%header%autowidth.spread]
|===
| Setting | Description | Required

|Protocol
|`AS2`
|Yes

|Owner
|Host that owns the endpoint
|Yes

|Endpoint name
|Automatically-generated name used to identify the endpoint, which you can subsequently modify manually.
|Yes

|Description
|User-supplied value that describes the purpose of the endpoint.
|No

|Private port (when deploying to VPC)
a|
* When enabled, the AS2 receive endpoint application deploys to the private port `8092` in your xref:runtime-manager::virtual-private-cloud.adoc[Anypoint VPC]. You can manage the access control to the endpoint via the Anypoint VPC and dedicated load balancer settings.
* When disabled, the AS2 receive endpoint application deploys to the public port `8082` by default. You can access the endpoint URL directly over the internet.
+
This configuration applies only to Anypoint VPC deployments from Partner Manager.
|No

|Enforce security level
a|Indicates whether Partner Manager rejects incoming AS2 messages that aren't signed, encrypted, or both. When Partner Manager rejects a message, it returns a negative Message Disposition Notification (MDN) to the sender.

Allowed values:

* Signed & Encrypted
+
(Default) Rejects incoming messages that aren't both signed and encrypted.
* Signed
+
Rejects incoming messages that aren't signed.
* Encrypted
+
Rejects incoming messages that aren't encrypted.
* None
+
Accepts messages that aren't signed or encrypted.
|

|<Host> keystore
|Host xref:create-keystore.adoc[keystore] files in your environment that store your organization's public certificate and private key.
|Yes
|===

== Next Step

After you create an AS2 receive endpoint, you can deploy it as described in xref:deploy-endpoints.adoc[Deploy Receive Endpoints].

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoint.adoc[Create and Configure Endpoints]
* xref:as2-endpoints-algorithms.adoc[AS2 Signature and Encryption Algorithms]
