= Endpoints

Endpoints define the required transport protocol configurations to receive or send messages with external trading partners or internal backend applications.

Partner Manager uses endpoints to:

* Define transport protocols
* Receive transmissions from partners
* Receive messages from backend applications
* Specify the final destination of messages
* Specify where to send acknowledgments

== Endpoint Ownership

You can assign the host or a trading partner as the owner of partner-facing endpoints to control the use of endpoints within inbound and outbound message flows.

When creating partner-facing endpoints directly from the host or a trading partner, the ownership of the endpoint is automatically assigned to the host or trading partner from which the endpoint was created.

In a message flow, availability depends on the endpoint assignment:
* Any trading partner can select an endpoint assigned to the host.
* Only the same trading partner can select an endpoint assigned to that trading partner.

== See Also

* xref:create-endpoint.adoc[Create and Configure Endpoints]
* xref:delete-endpoints.adoc[Delete Endpoints]
