= Endpoint Runtime Services

Partner Manager deploys generic endpoint services that can receive data from or send data to different endpoint configuration, through dynamic configurations. Endpoint configurations of all supported protocols can be reused across message flows and trading partners.

Partner Manager’s deployment orchestration service inspects the message flow and associated configuration objects and determines if and which endpoint services need to be deployed or updated based on if any new endpoint configurations are being added, updated or removed.

The number and type of endpoint services deployed to your runtime will depend on the transport protocols used to exchange data with your trading partners and backend systems.

Each unique AS2 and HTTP(s) receive endpoint configurations result in deployment of their own runtime applications. You can view the Runtime application name corresponding to a given configuration in Partner Manager, from the endpoint detail page.  while you can reuse a single endpoint configuration across multiple message flows and partners.

SFTP Receive, SFTP Send, AS2 Send and HTTP(s) send endpoints are always managed within a single generic endpoint service for the protocol & direction.

== CloudHub Deployments
[%header%autowidth.spread]
|===
|Protocol |Direction |Application Name Prefix
|SFTP |Receive |b2b-inbound-sftp-
|SFTP |Send |b2b-outbound-sftp-
|AS2 |Receive |b2b-inbound-as2-
|AS2 |Send |b2b-outbound-as2-
|HTTP or HTTPS |Receive |b2b-inbound-http-
|HTTP or HTTPS |Send |b2b-outbound-http-
|===

== On Premise Deployments
[%header%autowidth.spread]
|===
|Protocol |Direction |Application Name Prefix
|SFTP |Receive |inbound-sftp-
|SFTP |Send |outbound-sftp-
|AS2 |Receive |inbound-as2-
|AS2 |Send |outbound-as2-
|HTTP or HTTPS |Receive |inbound-http-
|HTTP or HTTPS |Send |outbound-http-
|===


If your deployment target is CloudHub, You can assign static IP addresses to your endpoint applications connecting to external systems from xref:runtime-manager::managing-applications-on-cloudhub#static-ips[Runtime Manager], if your organization or your trading partners require whitelisting IP addresses. You can share the static IP address assigned to your endpoint application with your trading partners for them to whitelist the IP address, allowing the application to connect with their server.
