= Endpoint Types and Protocols
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

There are three types of endpoints within AnyPoint Partner Manager:

* Receive endpoints, inbound transmission. +
As host, you need the endpoints that your organization uses to receive transmissions from your partners. +
These endpoints are resources your organization exposes to your trading partners.

* Target endpoints. +
As host, your organization has internal endpoints to which it routes messages from the trading partner, after those messages are transformed within the message flow.

* Acknowledgement endpoints +
Your partners provide you with their own external endpoint configurations, to which your organization can send + acknowledgments, such as like 997 or 999 acknowledgements. Acknowledgements are typically sent back to trading partners and correspond to one or more B2B messages you receive from them.

Refer to the following to configure your endpoint. Your configuration varies based on the protocol and type you use.

== Endpoint Name, Protocol and Type

[%header,cols="3s,7a"]
|===
|Setting |Description

|Name

|Name for this endpoint

Required: Yes +

Default: Automatically populates based on the following values: `Protocol` or `Type`

|Protocol

|Protocol for this endpoint

Required: No +

Valid values: +

`AS2` +
`SFTP` +
`HTTPS` +

Default: None +

|Type

|Type of endpoint

Required: No +

Valid values: +

`SEND` +

`RECEIVE` +

Default: None +

// |Default for partner_ checkbox

// |Select this box if you want the choices you make for this endpoint to apply to all endpoints for this partner.

|===

== Protocol/Type-Specific Endpoint Settings

Select the section that corresponds to the Protocol-Type of the Endpoint for which you are entering settings.

//* <<AS2 Send Settings>>
* [AS2 Receive Settings]
//* <<SFTP Send Settings>>
* [SFTP Receive and Target Settings]
* [HTTP(S) Send Settings]
