= HTTP and HTTPS Receive Endpoint Settings

HTTP and HTTPS receive endpoints configure where to receive B2B messages transmitted over HTTP or HTTPS, respectively. There are two type of HTTP and HTTPS endpoints:

* Receive from Partners
+
Source endpoint in an inbound message flow that receives inbound B2B messages from partners either directly or via third-party connections.
+
A host, partner, or third-party connection can own HTTP and HTTPS Receive from Partners endpoints.
+
* Source at Host
+
Source endpoint in an outbound message flow that receives application messages from the backend applications
+
Only a host can own FTP Source at Host endpoints.

IMPORTANT: Each HTTP and HTTPS receive endpoint configuration is deployed as an individual Mule application in the runtime. Consider reusing existing HTTP and HTTPS receive endpoint configurations across message flows.

Create HTTP and HTTPS receive endpoints by configuring these settings on the *<host>* page:

[%header%autowidth.spread]
|===
|Name |Description |Required
|Endpoint Name
|Automatically-generated name used to identify the endpoint, which you can modify manually.
|x

| Owner
a| Host, partner, or third-party connection that owns the endpoint.
| x

| Protocol
| Protocol that the endpoint supports.
| x

| Description
| User-supplied value that describes the purpose of the endpoint.
|

| Private port (when deploying to VPC)
a|
* When enabled, the HTTP receive endpoint runtime application deploys to the private port `8092` in your Anypoint VPC.
+
You can manage the access control to the endpoint via the Anypoint VPC and dedicated load balancer settings.
* When disabled, the HTTP receive endpoint application deploys to the public port `8082` by default.
+
You can access the endpoint URL directly from the internet.
|

| Manage with API manager
a| Enable this setting to manage the endpoint with API Manager. To use this functionality, you must create an HTTP API in API Manager in the same environment and organization as the endpoint.

When you create this API in API Manager:

* Select `HTTP API` as the asset type.
* Leave the defaults on the *Endpoint configuration* screen.
* Copy the API instance ID and paste it into the  *API Auto discovery id* field on the Partner Manager *New endpoint: Receive from Partners* window.

NOTE: Using this feature requires an API Manager license.
|

|URL
a|HTTP or HTTPS address where you receive outbound source messages from backend applications or inbound B2B messages from your partners. Partner Manager automatically generates this ID after the first message flow that uses the endpoint is deployed.
|x

|Response timeout (in milliseconds)
|Response timeout period in milliseconds. The default is `15000`.
|x

|Authentication type
a|Type of authentication method used to protect the HTTP receive service. This field is disabled when you manage the endpoint with API Manager.

|x

|Basic authentication
a|User name and password that protects the HTTP listener.

After saving your new or reconfigured endpoint, you cannot subsequently retrieve or modify the password.

The backend applications that send payloads to the HTTP or HTTPS receive endpoint must pass the credentials in the HTTP request header.
|x

|API Key
a|API key for the HTTP listener.

After selecting *API Key* in the *Authentication type* list, specify the HTTP header name and API key to protect the HTTP listener. After saving your new or reconfigured endpoint, you cannot subsequently retrieve or modify the API key.

The backend applications that send payloads to the HTTP receive endpoint must pass the API key in the HTTP request with the configured HTTP header name.
|x
|===

== Next Step

After you create an HTTP or HTTPS receive endpoint, you can deploy it, as described in xref:deploying-receive-endpoints.adoc[Deploying AS2, HTTP, and HTTPS Receive Endpoints].

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoint.adoc[Creating Endpoints]
