= HTTP and HTTPS Send Configuration

The HTTP and the secure HTTPS protocol send settings are used with endpoints for sending transmissions to your partner and endpoints that are targets at your organization.

You can use the HTTP and HTTPS endpoint to:

* Send to partners +
Send outbound EDI files to your trading partners in outbound message flows.
* Target at host +
Send application messages (JSON or XML) to your backend applications in inbound message flows.

[%header%autowidth.spread]
|===
|Name |Description |Required
| Owner
| The trading partner or host that owns the endpoint. The value in this field is populated automatically and cannot be modified.
| Yes

|Protocol
| The protocol selected in the `Protocol` field of the *New endpoint: Receive from partners* window. You can select *HTTP* or *HTTPS*. The value in this field is set to *HTTPS* by default.
|Yes

|Endpoint Name
|The name used to identify the endpoint. The `Endpoint Name` field is generated automatically, but can be modified manually.
|Yes

|Description
|The user-defined field for describing the purpose and use of the endpoint.
|No

|URL
|The target HTTP or HTTPs service to which to send translated EDI, JSON, or XML messages. The URL must be accessible from the runtime environment that processes your B2B integrations.
Enter a well-formed URL (including the path) that specifies where to send the request, for example:
`+https://www.mulesoft.com/sendRequest?name=something+`
|Yes

|Connection Idle Timeout (milliseconds)
|The connection idle timeout period in milliseconds. The value in this field is set to `30000` by default.
|Yes

|Response Timeout (milliseconds)
|The maximum time in milliseconds that the request element blocks the execution of the flow that is waiting for the HTTP response.
|No
|===


== Authentication Settings

Depending on how you set up your authentication policy, refer to the appropriate authentication type and descriptions here.

[%header%autowidth.spread]
|===
|Authentication Type |Description
|None
|No authentication.

|API Key
a| * HTTP Header Name +
The HTTP header parameter associated with the API Key. +
* API Key +
The value for the access key you set.

|Basic
a|Specifies a simple authentication policy that protects the API by requiring a username and password when calling apps to make a request.

* Username +
The username you set up with this authentication policy.
* Password +
The password you set up with this authentication policy.

|Client Credentials
a|* Client ID +
The Client ID provided when registering your application.
* Client Secret +
The client secret provided when registering your application.
* Client Header +
Add the client header.
* Client Secret Header +
Add the client secret header.

|OAuth Token
a|* Token URL +
Enter a valid authorization URL.
* Client ID +
The client ID provided when registering your application.
* Client Secret +
The client secret provided when registering your application.
|===

== See Also

* xref:endpoints.adoc[Endpoints]
* xref:create-endpoint.adoc[Create and Configure Endpoints]
* xref:Certificates.adoc[Certificates]
