= Endpoints

Endpoints define the transport protocol configurations necessary to receive or send messages with external trading partners or internal backend applications.

Partner Manager uses endpoints to:

* Receive transmissions from partners 
* Receive application messages from the backend system
* Specify the final destination of the message 
* Define transport protocols
* Specify where to send acknowledgments

== Endpoint Ownership

Partner Manager enables you to assign the host or a particular partner as the owner of endpoints that are partner-facing (receive or send) to control the usage of endpoints within inbound and outbound message flows. 

Endpoints owned by the host are available for selection in message flows for any trading partners. Endpoints owned by a specific trading partner are available for selection in message flows created for that partner only.  

== Types of Endpoints

AnyPoint Partner Manager provides three types of endpoints:

* Receive endpoints. +
Your organization needs to provide endpoints to receive transmissions from your trading partners. +
These endpoints are resources your organization exposes to your trading partners.
* Target endpoints. +
Your organization also has internal endpoints to which it routes messages from the trading partners. The messages routed to the target endpoint are typically validated and transformed before they are routed to the configured target endpoint.


== See Also

xref:create-endpoint.adoc[Create and Configure Endpoints]






