= Getting Started with Partner Manager




. <<assign-permissions,Assign permissions to Partner Manager users>>.
. <<set-up-env,Set up the Partner Manager environment>>.
. <<payload-storage-API,Set up the Payload Storage API>>.
. <<configure-host-profile,Configure a host profile>>.
. <<configure-partners,Configure a profile for each of your trading partners>>.
. <<configure-third-party,Optionally configure third party connections>>.
. <<configure-message-flows,Configure message flows>>.
. <<deploy-test-message-flows,Deploy and test the configured message flows>>.
. <<monitor-transmissions,Monitor transmissions and indivual messages>>.

[[assign-permissions]]
=== Assign Permissions to Partner Manager Users

For each sandbox and production environment, use Anypoint Access Management to assign permissions to each Partner Manager user. You can assign the following permissions

For information, see xref:access-management::permissions-by-product.adoc[] .

[[set-up-env]]
=== Set Up the Partner Manager Environment

You can deploy Partner Manager to CloudHub or you can use Partner Manager on-premises:

* To deploy Partner Manager to CloudHub, use the *Partner Manager Settings* page in Anypoint Access Management to specify CloudHub deployment options for the Partner Manager sandbox and production environments.
+
For more information, see xref:cloudhub-deploy-options.adoc[].
+
* To use Partner Manager on-premises:
. Install and configure Mule runtime engine (Mule) on-premises.
. Use Anypoint Runtime Manager to register Partner Manager in the appropriate environment.
. Create a server group to which to add the servers you create.

+
For more information, see xref:deploy-onpremise.adoc[].

[[payload-storage-api]]
=== 3: Set Up the Payload Storage API

Is this optional or mandatory??? If optional, when wouldn't you do this???
Should this be part of the host setup section or should this be done before you start to configure the host profile???

Partner Manager requires that you deploy a payload storage API that it will use for storing transmission information. You can connect this API to your choice of a storage location, such as a database, Amazon S3, or a file system.

For more information, see xref:setup-payload-storage-API.adoc[].

[[configure-host-profile]]
=== Configure a Host Profile

Use the <host> page in Partner Manager to configure a host profile for your Anypoint Platform organization or business group. A <host>  profile consists of the EDI and AS2 identfiers used by your organization, associated digital certificates, Source at Host and Target at Host endpoints, message types, Payload Storage API details, and global settings for EDIFACT receive messages.

For more information, see xref:configure-host.adoc[].

[[configure-partners]]
=== Configure Profiles for Each of your Trading Partners

Create a partner profile for each of your trading partners. A partner profile consists of partner-specific settings such as the partner's name, identifiers (such as the AS2 ID, X12-ISA, X12 GS, and so on), digital certificates (such as X.509 certificates), and endpoints to use for sending and receiving messages to and from your partner. It also consists of the acknowledgements, validations, and control numbers for each message format that the partner uses.

If you plan to use host endpoints only, you don’t need to create partner-specific endpoints.

For more information, see xref:configure-partner.xml[].

[[configure-third-party]]
=== Configure Third-Party Connections

If your trading partners use third-party service providers such as VANs or 3PLs (third-party logistics providers) who manage the B2B connectivity with your organization on behalf of your partners, then create configurations for these connections.

Creating third-party connections is similar to configuring partner profiles, except that acknowledgements, validations, and control numbers associated with message formats are configured at the partner level only.

For more information, see xref:configure-third-party.adoc[].

[[configure-message-flows]]
=== Configure Message Flows

Message flows contain the following configuration objects, which execute end-to-end B2B message processing: partner identifiers, receive and send endponts, source and target message types, and DataWeave transformation maps.

Create inbound message flows to receive messages from your partners, transform the messages into your internal application format, and send the transformed message to your backend system.

Create outbound message flows to receive messages from your backend applications, transform the messages to your partner’s message format, and send the messages to your partner.

For more information, see xref:message-flows.adoc[] and xref:message-flow-components.adoc[]. 

[[deploy-test-message-flows]]
=== Deploy and Test the Configured Message Flows

Deploy and teset the message flows in a sandbox environment. After you verify that the message flow is successful, you can undeploy it from the sandbox and redeploy it to your production environment.

For more information, see xref:deploy-message-flows.adoc[]

[[monitor-transmissions]]
=== Monitor Transactions and Individual Messages

Is there info that we should incorporate (or references) on using Anypoint Monitoring for PM???

Track the activity of transmissions and individual messages by searching for transactions based on crieria such as partner name, message direction, send and receive dates, message processing status, partner message type, and host message type. You can also search for transactions based on custom message attributes that you define using DataWeave 

