= Anypoint Partner Manager Glossary
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


:keywords: Anypoint B2B Anypoint Partner Manager

<<secta,A>> <<sectb,B>> <<sectc,C>> <<sectd,D>> <<secte,E>> <<sectf,F>> <<sectg,G>> <<secth,H>> <<secti,I>> <<sectj,J>> <<sectk,K>> <<sectl,L>> <<sectm,M>> <<sectn,N>> <<secto,O>> <<sectp,P>> <<sectq,Q>> <<sectr,R>> <<sects,S>> <<sectt,T>>

////
<<sectu,U>> <<sectv,V>> <<sectw,W>> <<sectx,X>> <<secty,Y>> <<sectz,Z>>
////

[[secta]]
*A*

Acknowledgment:: Sent as a response to a B2B transmission. A TA1 acknowledgment serves as a receipt that a transmission was received. A functional acknowledgment includes details of the validation process.

Activity:: A list of transmissions sent to and received from partners.

Activity API:: Provides users with the ability to obtain transaction status.

Anypoint Partner Manager:: Configures and manages integrations between EDI transmissions with your trading partners and your backend APIs; also tracks and reports on the transmission activity.



[[secte]]
*E*

Endpoint: Source at host:: The origin of the message flow when defined by a host endpoint and message type, often an API.

Endpoint: Target at host:: The final destination of a message flow when defined by a host endpoint and message type, often a Host API.

[[sectg]]
*G*

Global Validation and Acknowledgement settings:: Settings that apply to all partners for message validation and acknowledgment responses.

[[secth]]
*H*

Host:: The Anypoint customer that sends and receives transmissions with partners.

[[secti]]
*I*

Identifier:: Uniquely identifies a particular trading partner. For example, the DUNS number.

[[sectm]]
*M*

Map:: A DataWeave script that transforms a B2B message.

Message Flow:: The path along which the B2B message travels from a source through the map to its target. 

Message Type:: The name, description, and associated schema for a message.  Includes formats such as JSON, XML, CSV, and EDI documents (such as X12 and EDIFACT).

[[sectp]]
*P*

Partner Integration Onboarding:: The setup of a trading partner for the purpose of creating integrations that includes configuring identifiers, endpoints, certificates, and message flows.

Partner Manager API:: Manages partner-related configurations such as document definitions and partner profiles.

[[sectr]]
*R*

Retry:: Resending a message through a message flow that may have previously failed. For example, a host server could have been down somewhere and is now back up.

[[sects]]
*S*

Schema:: Structure used for data organization.

[[sectt]]
*T*

Trading Partner:: Any external company with which your company does business and is configured in Anypoint Partner Manager. Your company is designated the host trading partner.

Transmission:: A single communication between two trading partners containing one or more messages. For example, a distributor could group a set of purchase orders sending them in one transmission to a supplier trading partner.

[[sectv]]
*V*

Validation:: Part of the processing of a transmission that confirms the messages are in the expected format.
