= Anypoint Partner Manager
page-aliases: docs.mulesoft.com/partner-manager/latest

Anypoint Partner Manager enables you to perform bidirectional Business-to-Business (B2B) message exchanges using APIs and Electronic Data Interchange (EDI) formats, and to conduct business transactions such as buying and selling products with your partners. Transactions are typically transmitted over transports such as HTTPS and SFTP, and exchanges such as AS2. Partner Manager supports X12, JSON, and XML message formats.

Use Anypoint Partner Manager to:

* Perform technical onboarding of your partners.
* Set up, manage, and monitor business message flows between your systems and your trading partners' systems. +
Track and report on business transactions to achieve greater operational efficiency in B2B transactions.
* View meta information, validation errors, and all messages included with each transmission payload. +
Transmission payloads can contain one or more business messages.

Members of your organization can use Partner Manager to perform a variety of functions, including:

* Designing and testing message flows
* Managing the activity of the business transactions with your trading partners
* Optimizing backend services and performance

== Before You Begin Using Partner Manager

Before you begin using Partner Manager, you must have:

* An Anypoint Platform user account with the Anypoint Partner Manager entitlement
* The Partner Manager Administrator role, which assigns permission levels for to all users who need access to B2B message flows in their environments (production or  sandbox)
* The required Mule vCore capacity to manage your B2B transaction workload needs
* Storage for the B2B transmission payloads you send or receive, such as a database, Amazon S3, Azure Blob Storage, and so on   ``
* Licenses for the AS2, EDIFACT, or X12 connectors used in your B2B message flows
* Anypoint Studio 7.4 or later

Also, you must be familiar with EDI message formats and creating DataWeave maps to use for performing data transformations.

Should we still say this???
If you require assistance, contact your account representative
To get started, ask your Anypoint Platorm administrator to follow the setup instructions.

== Next Steps


== See Also

* xref:setup.adoc[Anypoint Partner Manager Setup]
