= Anypoint Partner Manager

Anypoint Partner Manager enables Business-to-Business (B2B) message exchanges using APIs and Electronic Data Interchange (EDI) formats.

Enterprises use Anypoint Partner Manager to conduct business transactions such as purchasing products from one another.
Transactions are typically transmitted over transports such as HTTPS and SFTP, and exchanges such as AS2. Partner Manager enables business transactions to be transmitted through the use of message formats such as X12, JSON, and XML.

Use Anypoint Partner Manager to set up, manage, and monitor the flow of business messages between you and your business trading partners. The ability to track and report on business transactions drives greater operational efficiency while managing B2B transactions.

Use Anypoint Partner Manager to:

* Perform technical onboarding of your partners.
* Set up message flows to receive messages between your systems and your trading partners. +
A message flow is the path along which a message travels from its source, through a DataWeave transformation map, to its target.
* View meta information, validation errors, and all messages included with each transmission payload. +
A transmission is a single communication event during which a payload is transferred between two business entities.
These payloads can contain one or more business messages.

// * Set up message flows to receive and send messages between your systems and your partners.
// * View and monitor how partner messages are being processed in the system in case of failure in order to take corrective action.

Partner Manager can be used by different people with different roles in your organization. For example, those who:

* Primarily design and test message flows
* Manage activity of the business transactions with your trading partners
* Optimize backend services and performance

== Prerequisites

To use Partner Manager you must be familiar with EDI message formats, and how to create DataWeave transformations.

To get started, ask your Anypoint Platform administrator follow the Setup instructions.

== Architecture

== See Also

* xref:setup.adoc[Anypoint Partner Manager Setup]
