= Anypoint Partner Manager Overview
page-aliases: docs.mulesoft.com/partner-manager/latest

Anypoint Partner Manager enables you to perform bidirectional Business-to-Business (B2B) message exchanges with your external business partner ecosystem. Partner Manager supports AS2, HTTP, HTTPS, SFTP, and FTP transport protocols. The supported message formats include CSV, EDIFACT, EDI X12, JSON, XML, X12 UCS, and X12 VICS.

Partner Manager unlocks a variety of use cases, such as order to cash, procure to pay, logistics planning, warehouse management and fulfillment workflows, and transportation execution.

Use Partner Manager to:

* Perform technical onboarding of your partners.
* Set up, manage, and monitor business message flows between your systems and your partners' systems.
* Track and report on business transactions to achieve greater operational efficiency in B2B transactions.
* View meta information, validation errors, and all messages included with each transmission payload.
+
Transmission payloads can contain one or more business messages.

Watch the Partner Manager Product Spotlight video to see a quick overview of Partner Manager:

++++
include::_partials/partner-manager-spotlight-video.html[]
++++

== Before You Begin Using Partner Manager

Before you begin using Partner Manager, you must have:

* An Anypoint Platform account with the Partner Manager entitlement.
* AS2, EDIFACT, and X12 Connector entitlements, if your organization uses these standards and protocols.
* One or more of the user permissions for Partner Manager.
* The Partner Manager Administrator role, which can assign permission levels to all users who need access to B2B message flows in their sandbox or production environment.
* The required Mule runtime capacity, either vCore or messages and flows, to manage your B2B transaction workload needs.
* Storage for the B2B transmission payloads you send or receive, such as a database, Amazon S3, and Azure Blob Storage.
* Familiarity with EDI message formats.
* Anypoint Studio 7.4 or later.
* The ability to create DataWeave maps to use for performing data transformations.

== Partner Manager Concepts

To use Partner Manager, you must understand the following concepts:

=== Host

Your Anypoint Platform organization or business group. A Partner Manager implementation has a single host for which you define a host profile.

=== Partners
The partners with whom you send and receive B2B transmissions. You define a partner profile for each partner in your B2B ecosystem.

=== Payload Storage API

An API that provides Partner Manager with a standardized way to connect to your solution for storing transmission content.

=== Message Flows
The paths along which a B2B message travels from its source, through a DataWeave translation map, to its target. There are two types of message flows:

* Inbound Message Flows
+
Inbound message flows receive messages from partners, including messages that go through third-party connections. When you create an inbound message flow, you can validate and transform the inbound messages and then send them to your backend applications.
* Outbound message flows
+
Outbound message flows receive messages from your backend applications, validate and transform these messages into your partner's expected format, and send them to your partners directly or through third-party connections.
+

Message flows consist of <<endpoints,endpoints>>, <<message-types,message types>>, <<identifiers,sender and receiver identifiers>>, and <<translation-maps,translation maps>>.

[[endpoints]]
=== Endpoints

Define the transport protocol configurations necessary for:

* Receiving messages from external partners or internal backend applications
* Sending messages to external partners or backend applications

You can configure the following types of endpoints:

* Receive from Partners
+
Source endpoint in an inbound message flow that receives inbound B2B messages from partners either directly or via third-party connections
+
* Target at Host
+
Target endpoint in an inbound message flow through which transformed messages are sent to the backend applications
+
* Source at Host
+
Source endpoint in an outbound message flow that receives application messages from the backend applications
+
* Send to Partners
+
Target endpoint in an outbound message flow through which transformed B2B messages are sent to the partners either directly or via third-party connections

[[message-types]]
=== Message Types

Define the structure of the transactions that Partner Manager receives or sends. Partner Manager supports the following message types:
	
* Receive from Partners
+
Defines the structure of the transactions that partners or third-party connections send to the host through inbound message flows. You can define <<custom-attributes,custom message attributes>> for this message type.
+
* Target at Host
+
Defines the structure of the transactions that the host sends to the backend through inbound message flows.
+
* Source at Host 
+
Defines the structure of the transactions that the backend sends to the host through outbound message flows. You can define custom message attributes for this message type. You can define <<custom-attributes,custom message attributes>> for this message type.
+
* Send to Partners
+
Defines the structure of the transactions that the host sends to partners or third-party connections through outbound message flows.

[[identifiers]]
=== Sender and Receiver Identifiers

Identifiers in AS2, EDIFACT, and X12 transactions that identify the message senders and receivers.

For X12 messages, the identifiers in the ISA and GS headers provide information that identifies the appropriate flow to process the transaction.

For EDIFACT messages, the identifiers in the UNB segment provide information that identifies the appropriate flow to process the transaction.

For other formats, such as CSV and JSON, Partner Manager extracts the identifiers from data payloads or a message contact by dynamically executing the reference mapping supplied with the message type definition.

[[custom-attributes]]
=== Custom Message Attributes

User-defined attributes associated with Receive from Partners or Source at Host message types through reference mapping. Messages extract key data fields, like Order Number, Invoice Number, and Shipment ID, as business transactions are processed. After a transaction processes, users can find the message attribute label and value by searching transactions on the Activity page in Partner Manager or via API calls.

[[translation-maps]]
=== Translation Maps

DataWeave maps transform business transactions between your partner's message formats and your organization's enterprise application message formats. You create the maps in Studio and import them into Partner Manager when you configure message flows.

=== Templates

Prebuilt templates that convert your B2B message flow configurations into runtime applications. When MuleSoft upgrades a template, you can upgrade your message flows to use them to take advantage of new capabilities that enable better integration with your partner's ecosystem.

== Next Step

Continue to xref:get-started.adoc[].

== See Also

* xref:partner-manager-architecture.adoc[Partner Manager Architecture]
* xref:setup.adoc[Anypoint Partner Manager Setup]
