= Anypoint Partner Manager Overview
page-aliases: docs.mulesoft.com/partner-manager/latest

Anypoint Partner Manager enables you to perform bidirectional Business-to-Business (B2B) message exchanges using APIs and Electronic Data Interchange (EDI) formats, and to conduct business transactions such as buying and selling products with your partners. Transactions are typically transmitted over transports such as HTTPS and SFTP, and exchanges such as AS2. Partner Manager supports X12, JSON, and XML message formats.

Use Anypoint Partner Manager to:

* Perform technical onboarding of your partners.
* Set up, manage, and monitor business message flows between your systems and your trading partners' systems. +
Track and report on business transactions to achieve greater operational efficiency in B2B transactions.
* View meta information, validation errors, and all messages included with each transmission payload. +
Transmission payloads can contain one or more business messages.

Members of your organization can use Partner Manager to perform a variety of functions, including:

* Designing and testing message flows
* Managing the activity of the business transactions with your trading partners
* Optimizing backend services and performance

== Before You Begin Using Partner Manager

Before you begin using Partner Manager, you must have:

* An Anypoint Platform user account with the Anypoint Partner Manager entitlement
* The Partner Manager Administrator role, which assigns permission levels for to all users who need access to B2B message flows in their environments (production or  sandbox)
* The required Mule vCore capacity to manage your B2B transaction workload needs
* Storage for the B2B transmission payloads you send or receive, such as a database, Amazon S3, Azure Blob Storage, and so on
* Licenses for the AS2, EDIFACT, or X12 connectors used in your B2B message flows
* Anypoint Studio 7.4 or later

* Familiarity with EDI message formats
* Ability to create DataWeave maps to use for performing data transformations

== Partner Manager Concepts

To use Partner Manager, you must understand the following concepts:

===== host

Your Anypoint platform or business group. A Partner Manager implementation has a single host for which you define a host profile.

===== partners
The trading partners with whom you send and receive B2B transmissions. You define a partner profile for each partner in your B2B ecosystem.

===== payload storage API

An API that provides Partner Manager with a standardized way to connect to your solution for storing transmission content.

===== message flows
The paths along which a B2B message travels from its source, through a DataWeave translation map, to its target. There are two types of message flows:

* Inbound message flows
+
Inbound message flows receive messages from partners, including messages that go through third-party connections. When you create an inbound message flow, you can validate and transform the inbound messages and then send them to your backend applications.
* Outbound message flows
+
Outbound message flows receive messages from your backend applications, validate and transform these messages to the format your partners expect, and then send them to your partners either directly, or through third-party connections.
+

Message flows consist of <<endpoints,endpoints>>, <<message-types,message types>>, <<identifiers,sender and receiver identifiers>>, and <<translation-maps,translation maps>> (optional).

[[endpoints]]
===== endpoints

Define the transport protocol configurations necessary for:

* Receiving messages from external trading partners or internal backend applications
* Sending messages to external trading partners or backend applications

You can configure the following types of endpoints:

* Receive from Partners
+
Source endpoint in an inbound message flow that receives inbound B2B messages from partners either directly or via third-party connections
+
* Target at Host
+
Target endpoint in an inbound message flow through which transformed messages are sent to the backend applications
+
* Source at Host
+
Source endpoint in an outbound message flow that receives application messages from the backend applications
+
Send to Partners
+
Target endpoint in an outbound message flow through which transformed B2B messages are sent to the partners either directly or via third-party connections

[[message-types]]
===== message types

Define the structure of the transactions that Partner Manager receives or sends. Partner Manager supports the following message types:
	
* Receive from Partners
+
Defines the structure of the transactions that partners or third-party connections send to the host through inbound message flows. You can define <<custom-attributes,custom message attributes>> for this message type.
+
* Target at Host
+
Defines the structure of the transactions that the host sends to the backend through inbound message flows.
+
Source at Host 
+
Defines the structure of the transactions that the backend sends to the host through outbound message flows. You can define custom message attributes for this message type.
+
* Send to Partners
+
Defines the structure of the transactions that the host sends to partners or third-party connections through outbound message flows.

[[identifiers]]
===== sender and receiver identifiers

Identifiers in AS2, EDIFACT, and X12 transactions that identify the message senders and receivers. For X12 messages, the identifiers in the ISA and GS headers provide information that identifies the appropriate flow to use to process the transaction.

[[custom-attributes]]
===== custom message attributes

User-defined attributes that you can associate with a Receive from Partners or Source at Host message type. Using these attributes enables you to have visibility into the full lifecycle of your B2B workflow.

[[translation-maps]]
===== translation maps

DataWeave maps that transform business transactions between your partner’s message formats and your organization’s enterprise application message formats. You create the maps in Anypoint Studio and import them into Partner Manager when you configure message flows.

===== templates

Prebuilt templates that convert your B2B message flow configurations into runtime applications. When MuleSoft upgrades a template, you can upgrade your message flows to use them to take advantage of new capabilities that enable better integration with your trading partner’s ecosystem.

== Next Step

Continue to xref:get-started.adoc[].

== See Also

* xref:partner-manager-architecture.adoc[]
* xref:setup.adoc[]
