= Anypoint Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: b2b, edi, portal

Anypoint Partner Manager allows Business-to-Business (B2B) message exchange using APIs and Electronic Data Interchange (EDI) formats.

== Overview

Enterprises use Anypoint Partner Manager to carry out business transactions such as purchasing goods from one another.
They are typically transmitted over transports such as HTTPS and SFTP, and exchanges such as AS2. The business transactions can be transmitted via the use of message formats such as X12 and JSON.

Use Anypoint Partner Manager to set up, manage, and monitor the flow of business messages between you and your business trading partners. The ability to track and report on this drives greater operational efficiency while managing B2B transactions.

With Anypoint Partner Manager you can:

* Perform technical on-boarding of your partners.

* Set up message flows to receive messages between your systems and your trading partners.
A message flow is the path along which a message travels from its source, through a transformation map, and then to its target.

* View meta information, validation errors, and all messages included with each transmission payload.
A transmission is the transfer of a payload and the validation of the messages it contains. 

// * Set up message flows to receive and send messages between your systems and your partners.
// * View and monitor how partner messages are being processed in the system in case of failure in order to take corrective action.

Partner Manager can be used by different people in your organization.
For example, those that design and test message flows, those who manage activity of the business transactions with your trading partners, and those who optimize backend services and performance.

To use Partner Manager you will need to be familiar with EDI message formats, and how to create Dataweave transformations.

To get started, have your Anypoint Platform administrator follow the Setup instructions.

== See Also

* xref:setup.adoc[Anypoint Partner Manager Setup]

// == About this Page
//  This page introduces MuleSoft's B2B Solutions and links to pages that provide details about Anypoint Partner Manager and // // MuleSoft's EDI message packs. In addition, we provide configuration details for implementing B2B Solutions in Anypoint //  Studio's Graphical Editor.

// == Beta Documentation

// * xref:setup.adoc[Anypoint Partner Manager Setup]
// * xref:configure-message-flows.adoc[Configure Message Flows]
// * xref:activity-tracking.adoc[Activity Tracking]
// * xref:x12-identity-settings.adoc[X12 Identity Settings]
// * xref:document-types.adoc[Message Types]
// * xref:endpoints.adoc[Endpoints]
// * xref:x12-receive-read-settings.adoc[X12 Receive Read Settings]
