= Configuring Receive Settings for Inbound JSON Messages

Partner Manager receive settings include the schema validation and batching rules to apply when processing an inbound JSON message from the specified partner.

To configure JSON receive settings:

. In the navigation menu, select *Partners*.
. Select the partner to which these settings apply.
. In the *Validation and acknowledgment settings* section's *Receive from <partner-name>* column, click *EDIFACT*.
. Select a link to configure:
* <<ack-settings,Acknowledgment settings>>
* <<validation-settings,Validation settings>>
* <<control-numbers,Control Numbers>>
. Click *Save*.

[NOTE]
It can take up to five minutes or so for your configuration changes to sync with Mule.

== Validation Settings

Select one or more of the following options to ensure that all JSON messages received from the trading partner meet validation rules:

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Enforce length limits
a|
* If selected, Partner Manager rejects a message with values that are too short or long.
* If not selected, Partner Manager accepts the message.
|Enabled
|Enforce value repeats
a|
* If selected, Partner Manager rejects a message with values that are repeated too many or too few times.
* If not selected, Partner Manager accepts the message.
|Enabled
|Enforce valid characters
a| * If selected, Partner Manager rejects a message that contains invalid characters.
* If not selected, the invalid characters are either ignored or replaced, and Partner Manager accepts the message.
|Enabled
| Allow unknown segments
a|
* If selected, Partner Manager ignores unknown segments.
* If not selected, Partner Manager rejects a message that contains unknown segments.
|Disabled
|Enforce segment order
a| * If selected, Partner Manager enables the segment to be reordered.
* If not selected, Partner Manager rejects a message that contains segments that are out of order.
|Enabled
|Allow Unused segments
a|* If selected, Partner Manager ignores unused segments.
* If not selected, Partner Manager rejects a message that contains unused segments.
|Enabled
|Enforce segment repeats
a|* If selected, Partner Manager rejects a message that contains segments that repeat too many times.
* If not selected, Partner Manager accepts the message.
|Enabled
|===

If a message does not meet an enabled rule, Partner Manager rejects it.

Parter Manager logs all  errors and reports them in the CONTRL acknowledgments.

== See Also

* xref:create-inbound-message-flow.adoc[Creating and Configuring Inbound Message Flows]
* xref:create-partner.adoc[Creating Partners]
* xref:modify-partner-settings.adoc[Modifying Partner Settings]
