= Manage Message Flows
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After your message flow is running and you are using it with your partners, you should not have to change it much.
There are certain cases where you might need to make changes, for example:

* You are no longer trading with a particular partner and need to delete the message flow you created for them.

* You completed the testing for a deployed message flow in a pre-production environment, and now want to reclaim those previously allocated Mule runtime resources.
* You want to update the map.
After a message flow is deployed, you can test it, undeploy it, and delete it.

== Test Message Flows
You can send test messages through the message flow to make sure the map is working and your backend systems receive the transformed message.
You can test your message flow after you deploy it to ensure that you are receiving messages and any acknowledgments from your partners.
You can ask your partner to confirm receipt of the acknowledgement.
You can also test the flow by deploying it in a sandbox environment, then undeploying it, and then deploying it to a production environment.

Test your flow in your production environment:

. Initiate a transmission on the receiving endpoint.

. From within Anypoint Partner Manager select *Activity* and check for the transmission.

. Check the transmission details for the flow, specifically:

** Check for any errors.

** Review the received payload by clicking View payload button next to _Received transmission_.

** Review and confirm that any TA1 and functional acknowledgments (999 or 997) are there.

+

. Ensure that the messages are routed to the correct message flow from the target system. For example:

** It was successfully delivered to the target endpoint.

** The message was transformed correctly.

== Edit Message Flows

(Reviewers, I don't have this section fully fleshed out yet.)

You can make changes to a message flow such as adding receiving endpoints and certificates;
modifying your DataWeave maps; plus changing the associated message types and target endpoints.

Overview of steps include:

* Change receiving endpoints, (non AS2 Identifiers???), and certificates.

* Change associated message types (X12 or JSON) and acknowledgments.

* Upload different DataWeave maps.

* Change associated target message types (X12 or JSON) and endpoints.

You handle this by opening an existing message flow and make your changes directly in the sections you intend to modify.

Consider that modifying identifiers impact deployed message flows. 

When you are done with your changes, redeploy the message flow to ensure that the changes are propagated to the Mule applications on your Mule runtime.

. From within your Anypoint Partner Manager environment (either Sandbox or Production), click *Message Flows* in the upper left and select a message flow.

. Choose the message flow click *<Message flow name>* to expand it.

. If you want to add an identifier to the message flow, click *See All* and then *New*.

. If you want to change a receiving endpoint, click *Select* from the *Receiving endpoint* section, click *New* and select your protocol type: AS2 or SFTP.

. If you want to create a new endpoint, depending on the protocol, refer to the following:
+
* xref:endpoint-as2-receive.adoc[AS2 Endpoint Settings]

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]

. If you want to change a DataWeave map, click *Import* from the Map section to choose a different DataWeave map and click *Upload mapping*.

. If you want to add a message type, click *Select* under the Source message, select *New* and select a standard type such as X12 or JSON.

. For a new message type, depending on the message standard, refer to the following:
+
* xref:document-types.adoc[X12 and JSON Message Types]

.   If you want to set up a target endpoint click *Select* from the Target at <partner name>.
+
* To create a new endpoint, depending on the protocol, refer to the following:

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]

* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Configuration]

. After you update any of the source, map, and target sections in the interface, confirm that each shows a green check mark next to it in the flow, and click *Deploy* to deploy the configurations to your Mule Runtime.

+
NOTE: It may take five minutes or so for your configuration changes to sync with Mule runtime.
+

. To test your edited message flow, refer to Test Message Flows.

Once you confirm successful deployment of your message flow, you can track its processed messages from the Activity page.

== Undeploy Message Flows

You might want to undeploy a message flow so that you can delete it. Other reasons for undeploying a message flow are:

* To stop processing messages related to the deployed message flow configuration.

* To recover resources being consumed by a message flow that you no longer need.

When you undeploy a message flow, it stops any future messages from being processed by that flow.
During the undeployment of a message flow usually about (five minutes?),
Anypoint Partner Manager checks to see if any of the applications on your Mule runtime are orphaned as a result of the undeployment.
These applications are cleaned up to release any resources they may be consuming. You must undeploy a message flow before you delete it.

NOTE: It may take five minutes or so for your undeployment action to complete. During this time, do not log out of Anypoint Partner Manager or close your browser window. When an undeployment is in-progress, other actions on the message flow such as `deploy` and `delete` are unavailable.

. Make sure the server group in Anypoint Runtime Manager called: B2BServerGroup is running.

TIP: Your on-premise Mule runtimes, the servers hosting the runtimes, and the `B2BserverGroup` need to be active and running when an undeployment is attempted. If you are unsure, you should contact your B2B System Administrator or check the status of the server in Runtime manager: https://docs.mulesoft.com/runtime-manager/servers-settings[Server Settings].

. From within your Anypoint Partner Manager environment (either Sandbox or Production), click *Message Flows* in the upper left and select a message flow.

. Click *Undeploy* in the upper right.

== Delete Message Flows

You might want to delete a message flow when it no longer serves its purpose.

If you delete a message flow before it has been deployed, it does not affect the Mule runtime apps.
If you have a message flow that was deployed and you are attempting to delete it, you must undeploy it first.

Any previous transmissions that were created as a result of a message being processed via the now-deleted message flow has the following behavior:

* They continue to stay in the transmission records within the Activity page, but the records indicate that the corresponding message flow used to process this transmission is now deleted.
Furthermore, these activities are converted into read-only mode.
This means that no links to the message flow work. Only the links that were set up to the stored payloads (such as the original B2B message, any TA1 acknowledgments, the transformed payload, on so on) continue to work.

. Make sure the server group in Anypoint Runtime Manager called: B2BServerGroup is running.

NOTE: If you are unsure, you should contact your B2B System Administrator or check the status of the server in Runtime manager: https://docs.mulesoft.com/runtime-manager/servers-settings[Server Settings].

. From within your Anypoint Partner Manager environment (either Sandbox or Production), click *Message Flows* in the upper left and select a message flow.

. Click *Undeploy* in the upper right. After the undeployment is successful, proceed to delete the message flow.

. Click  *Delete* in the upper right.

== Delete Identifiers


You might want to delete an identifier when it is no longer needed. Consider that deleting an existing host or partner identifier impacts the identification and routing of B2B messages to the associated partner.
Ask yourself the following when deleting an identifier: Why do you want to delete it? Do you need to replace it with another identifier? Remember that there must always be at least one identifier per message flow before you can delete it.

After successfully deleting an identifier, you can create a new identifier with the same value as the one you deleted.

Currently you cannot delete AS2 indentifiers.

. If you need to replace the identifier, record the values and qualifier type needed.

. Choose the partner name and click *Receive from <Partner name>* to expand it.

. Select an identifier to the message flow, click *See All*.

. Hover over the identifier you want to delete and click the trash can icon that appears towards the right hand side of the identifiers row. 

. If you need a replacement, add it now by clicking the New button.

== Delete Partners

If you are no longer trading with a partner, you can remove the partner by deleting it. Consider that deleting a partner deletes all assets associated with that partner as well as configuration records for it. For example:

** Undeployment of all deployed messages

** Deletion of all message flows, identifiers, endpoints, and certificates associated with that partner

** Removes all listed assets

** Removes the partner from the partner list

When a partner is deleted, all activities related to the partner are converted into a read-only mode so no links to the message flows work.
Only the links to the stored payloads (such as the original B2B message, any TA1 acknowledgments, transformed payloads, and so on) continue to work.
The partner’s name stays in the transmission records but is marked as deleted.

After successfully deleting a partner, you can create a new partner with the same name as the deleted partner. (Again, why would the user want to do this?)

. Make sure the server group in Anypoint Runtime Manager called: B2BServerGroup is running.
You cannot delete a partner if the server is not running.
+
NOTE: If you are unsure, you should contact your B2B System Administrator or check the status of the server in Runtime manager: https://docs.mulesoft.com/runtime-manager/servers-settings[Server Settings].
+

. From within your Anypoint Partner Manager environment (either Sandbox or Production), select Partner from the upper left.

. Select a partner and click *Delete* in the upper right and confirm your deletion in the dialog that follows.

. If you need to create a new partner, add it now. Refer to: Configure Partner


// == See Also

// * xref:endpoints.adoc[Endpoints]
// * xref:activity-tracking.adoc[Activity Tracking]
