== Managing AS2 Partner Certificates

If you create an AS2 Receive from Partners or Send to Partners endpoint, you must assign an AS2 partner certificate to the associated partner.

== Add an AS2 Partner Certificate

To add an AS2 partner certificate:

. In the navigation menu, select *Partners*.
. Click on the partner whose certificate you want to add.
. In the *Certificates* section, click *New*.
. Select a certificate and click *Upload certificate*.
. Optionally, assign the new certificate to the partner. To do this, hover over the *AS2* cell in the row containing the certificate and click *Assign*.
+
Assigning a certificate to a partner unassigns the previously-assigned certificate.

== Update an AS2 Partner Certificate

When your partners update their AS2 certificates, they typically provide you with the new certificates and the times when they must be activated.

To update a new partner AS2 certificate:

. In the navigation menu, select *Partners*.
. Click on the partner whose certificate you want to update.
. In the *Certificates* section, click *New*.
. Select the new certificate and click *Upload certificate*.
. In the *AS2* column for the certificate entry, click *Assign*.
+
Assigning a certificate to a partner unassigns the previously-signed certificate. Anypoint Partner Manager updates the inbound and outbound AS2 applications in the runtime. The update can take up to 10 minutes to complete.

== Delete an AS2 Partner Certificate

You can delete AS2 partner certificates that are not assigned to partners.

To delete an AS2 partner certificate:

. In the navigation menu, select *Partners*.
. Click on the partner whose certificate you want to delete.
. In the *Certificates* section, hover over the row associated with the certificate to delete.
. Click the trash can icon that appears.

== See Also

* xref:Certificates.adoc[Certificate Settings]
