= Manage Message Flows
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

After your message flow is running and you are using it with your partners, you should not have to change it much.  There are certain cases where you might need to make changes. For example:
You are no longer trading with a particular partner and need to delete the message flow you created for them.
You completed the testing for a deployed message flow in a pre-production environment, and now want to reclaim those previously allocated Mule runtime resources.

After a message flow is deployed, you can test it, undeploy it, and delete it.

== Test Message Flows

You can test your message flow after you deploy it to ensure that you are receiving messages and any acknowledgments from your partners.
You should ask your partner to confirm receipt of the transmission once you deploy it to your production environment.
You can also test the flow by deploying it in a sandbox environment, then undeploying it, and then deploying it to a production environment.

Test your flow in your production environment:

. Drop an EDI file on the receiving endpoint.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select *Activity* and check for the transmission.

. Check the transmission details for the flow, specifically:

** Check for any errors, and review any that you see for the partner.

** Review the received payload by clicking the transmission and opening the payload info.

** Review and confirm that any TA1 and functional acknowledgments are there.

+

4. Ensure that the messages are routed to the correct message flow from the target system. For example:

** It was successfully delivered to the target endpoint.

** The message was transformed correctly.

== Edit Message Flows

You can make changes to a message flow such as adding receiving endpoints and certificates; modifying your DataWeave maps; plus changing the associated message types and target endpoints.
Overview of steps include:
Change receiving endpoints & certificates.
Modify DataWeave maps.
Change associated message types.
Change associated target endpoints.
You handle this by opening an existing message flow and make your changes directly in the sections you intend to modify. When you are done with your changes, deploy the message flow to ensure that the changes are propagated to the Mule applications on your Mule runtime.

. From within your Anypoint Partner Manager environment (either Sandbox or Production), click *New message flows* in the upper right.

. Select an Existing Partner. You can do this from the *Select a partner* dialog, by searching for a partner by name.

. Once you find a match, choose the partner name and click *Select*. Clicking each section of the message flow expands it. A green checkmark next to any a section indicates that it is complete.

* Alternatively from the *Select a partner* dialog, you can create a new partner by clicking *New*.
This is the same as xref:configure-partner.adoc#create-a-trading-partner[Create a Trading Partner] except that when you are finished, you'll click *Create Partner and Message Flow*.
You can add more information to the partner later.
+
. Click *Select* from the *Receiving endpoint* section to configure the source endpoint where you receive the transmission.

. Click *Select* to search and select an existing endpoint or click *New* to create a new endpoint.

. To create a new endpoint, depending on the protocol, refer to the following:
+
* xref:endpoint-as2-receive.adoc[AS2 Endpoint Settings]

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]

+
. In the *Source message* section, click *Select* to expand the Message Type section.

. Either search and click *Select* to choose a previously used message type, or click *New* to create a new message type.

. For a new message type, depending on the message standard, refer to the following:
+
* xref:document-types.adoc[X12 and JSON Message Types]
+
. To optionally edit the validation settings, click *View* and the hostname.
For more information, see xref:x12-receive-read-settings.adoc[X12 Settings - Receive from Partner].
+
NOTE: It may take five minutes or so for your configuration changes to sync with Mule runtime.
+
. For X12 partner requirements, optionally configure the type of functional acknowledgment and the endpoint to which you send it.
+
* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Configuration]

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]
+
. Click the *Map* section and then click *Import* to choose a DataWeave map.

. Select a map and click *Upload mapping*.

. Click the *Target at <Partner name>* section and click *Select* to set up a target message type.
This is the target message type and the Endpoint where you want to route the transformed message.

. Either search and select an existing message type, or create a new message type. To create a new message type, depending on the message standard, follow instructions in one of these sections.

+
* xref:document-types.adoc[X12 and JSON Message Types]
+
.  Click *Select* to set up a target endpoint.
. Either search for and select an existing endpoint, or create a new endpoint by clicking *New*.
+
* To create a new endpoint, depending on the protocol, refer to the following:

* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]

* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Configuration]

. After you create the source, map, and target sections in the interface, confirm that each shows a green check mark next to it in the flow), and click *Deploy* to deploy the configurations to your Mule Runtime.
+
Your message flow configuration is deployed to your Mule runtime engine and you can start receiving messages from your partner. Use the Activity page to track processed messages.
+
Once a message flow is successfully deployed, you can track its processed messages from the Activity page.

== Undeploy Message Flows
You might want to undeploy a message flow so that you can delete it. Other reasons for undeploying a message flow are:
To stop processing messages related to the deployed message flow configuration.
To recover resources being consumed by a message flow that you no longer need.

When you undeploy a message flow, it stops any future messages from being processed by that flow. During the undeployment of a message flow (how long do we want to say this period of time could be - five minutes?), Anypoint Partner Manager checks to see if any of the applications on your Mule runtime are orphaned as a result of the undeployment. These applications are cleaned up to release any resources they may be consuming.

Overview of steps include:
Make sure the server group in Anypoint Runtime Manager called: B2BServerGroup is running. If you are unsure, you should contact your B2B System Administrator or check the status of the server in Runtime manager: https://docs.mulesoft.com/runtime-manager/servers-settings.

Selecting the Message flow
Selecting Undeploy - Explain which buttons are grey-out with an undeploy. For example, you cannot delete until you undeploy.
(How long do users need to wait after clicking the undeploy button for the undeploy to take effect - five minutes?)

== Delete Message Flows

You might want to delete a message flow when it no longer serves its purpose. If you delete a message flow before it has been deployed, it does not affect the Mule runtime apps. If you have a message flow that was deployed and you are attempting to delete it, you must undeploy it first.

Any previous transmissions that were created as a result of a message being processed via the now-deleted message flow have the following behavior:

They continue to stay in the transmission records within the Activity page, but the records indicate that the corresponding message flow used to process this transmission is now deleted. Furthermore, these activities are converted into read-only mode. This means that no links to the message flow work. Only the links that were set up to the stored payloads (such as the original B2B message, any TA1 acknowledgments, the transformed payload, on so on) continue to work.
Make sure the server group in Anypoint Runtime Manager called: B2BServerGroup is running. You cannot delete a message flow if the server If you are unsure, you should contact your B2B System Administrator or check the status of the server in Runtime manager: https://docs.mulesoft.com/runtime-manager/servers-settings.
Overview of steps:
Select the message flow to be deleted.
Click the undeploy button. (How long do users need to wait for this to propagate thru the system?)
Click the delete button. Remind users that they cannot delete until they click undeploy.

== Delete Identifiers

(Need to state upfront that AS2 identifiers currently cannot be deleted.)
You might want to delete an identifier when it is no longer needed. Consider that deleting an existing host or partner identifier impacts the identification and routing of B2B messages to the associated partner. Ask yourself the following when deleting an identifier: Why do you want to delete it? Do you need to replace it with another identifier? Remember that there must always be at least one identifier per message flow before you can delete it.

After successfully deleting an identifier, you can create a new identifier with the same value as the one you deleted. (Why would you want to do this?)

Overview of steps:
Once you’ve identified why you need to delete an identifier, then note what to replace it with.
If you need to replace the identifier, record the values and qualifier type needed.
Select the identifier to be deleted and click the trash can icon.
If you need a replacement, add it now by clicking the Add button.

== Delete Partners
If you are no longer trading with a partner, you can remove the partner by deleting it. Consider that deleting a partner deletes all assets associated with that partner as well as configuration records for it. For example:
Undeployment of all deployed messages
Deletion of all message flows, identifiers, endpoints, and certificates associated with that partner
Removes all listed assets
Removes the partner from the partner list

Consider that when a partner is deleted, all activities related to the partner are converted into a read-only mode, that is, no links to the message flows work. Only the links to the stored payloads (such as the original B2B message, any TA1 acknowledgments, transformed payloads, and so on) continue to work. The partner’s name stays in the transmission records but is marked as deleted.

After successfully deleting a partner, you can create a new partner with the same name as the deleted partner. (Again, why would the user want to do this?)

Make sure the server group in Anypoint Runtime Manager called: B2BServerGroup is running. You cannot delete a message flow if the server If you are unsure, you should contact your B2B System Administrator or check the status of the server in Runtime manager: https://docs.mulesoft.com/runtime-manager/servers-settings.

Overview of steps:
Select the partner to be deleted.
Click the trash can icon next to it.
If you need to create a new partner, add it now. Refer to: Configure Partner


== See Also

* xref:endpoints.adoc[Endpoints]
* xref:activity-tracking.adoc[Activity Tracking]
