= Manage Message Flows

After your message flow is running and you are using it with your partners, it doesn't require a lot of maintenance, but you can manage a message flow anytime, for example:

* If you are no longer trading with a particular partner and need to delete the message flow you created for them.
* You completed the testing for a deployed message flow in a pre-production environment, and now want to reclaim the previously allocated Mule runtime engine resources.
* You want to change a message flow by adding identifiers, selecting different endpoints, or importing a different DataWeave map.


[[edit-message-flows]]
== Edit Message Flows

After you establish a successful message flow with your partner, you can edit the flow to add identifiers, endpoints and message types, or add different DataWeave maps.

Before you make changes, carefully consider the impact on your existing message flow.

. From the Anypoint Partner Manager menu on the left, select *Message Flows* in the upper left, select a *<Message flow name>* and click it to expand it.
. To add an identifier to the message flow, click *See All* and then *New*.
. To change a receiving endpoint, click *Select* from the *Receiving endpoint* section, click *New*, select your AS2 or SFTP protocol type.
. To create a new endpoint, see xref:create-endpoint.adoc[Create and Configure Endpoints].
. To replace your existing DataWeave map, click *Import* from the Map section to choose a different DataWeave map and click *Upload mapping*.
. To view the map, you can download it by clicking the `<name>.dwl` link.
+
For more information about DataWeave map files, https://docs.mulesoft.com/mule-runtime/4.1/dataweave[DataWeave Language]
+
. To add a message type, click *Select* under the Source message, select *New*, and select a standard type such as X12 or JSON.
. To set up a target endpoint, click *Select* from the _Target at <partner name>_, and depending on the protocol, refer to one of the following:
+
* xref:endpoint-sftp-receive-target.adoc[SFTP Receive Endpoint Settings]

* xref:endpoint-https-send.adoc[HTTP and HTTPS Send Configuration]
+
. Verify that any sections of the flow that you updated show a green checkmark next to them, and click *Deploy* to deploy the configurations to Mule.
+
[NOTE]
It can take five minutes or so for your configuration changes to sync with Mule.
+
. To test your edited message flow. See xref:deploy-message-flows.adoc[Deploy and Test Message Flows].

After you confirm the successful deployment of your message flow, you can track its processed messages from the *Activity* page.

[[delete-message-flows]]
== Delete Message Flows

You might want to delete a message flow when it no longer serves its purpose, for example, if your relationship with your partner changes.

You can delete your message flow from either a sandbox or a production environment.

If you delete a message flow before it is deployed, it does not affect the Mule apps.

[NOTE]
For on
* You must xref:deploy-message-flows#UndeployMessageFlows[undeploy a message flow] before you can delete it. 
* Ensure that your on-premises Mule instances, the servers hosting them, and the server group in Anypoint Runtime Manager called `B2BserverGroup` are active and running.  +
Contact your B2B System Administrator to ensure that your on-premises Mule instances, the servers hosting them, and the server group in Anypoint Runtime Manager called `B2BserverGroup` are active and running. 

=== Steps

After the undeployment is successful, delete the message flow:

. In the Partner Manager left navigation menu, select *Message Flows*.
. Select the message flow to delete from the list and click *Delete* in the upper right of the screen.

Any previous transmissions that were created as a result of a message being processed by the message flow you deleted have the following behavior:

* The transmissions continue to stay in the transmission records within the *Activity* page, but the records indicate that the corresponding message flow used to process the transmission is now deleted.
* These activities are converted into read-only mode, so no links to the message flow work.
* Only links to the stored payloads (such as the original B2B message, any TA1 acknowledgments, the transformed payload, on so on) that were set up continue to work.


== See Also

* xref:runtime-manager::servers-settings.adoc[Runtime Manager Server Settings]
* xref:deploy-message-flows.adoc[Deploy and Undeploy Message Flows]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
