= Managing Host Certificates

Anypoint Partner Manager supports the following types of host certificates:

[%header%autowidth.spread]
|===
|Certificate Type |Description | Used by
| Public | Certificate generated by a certificate  (CA) a| 
* HTTPS Send to Partners endpoints owned by the host, when the authentication type is `Use a self-signed certificate`
* Target at Host endpoints, when the authentication type is `Use a self-signed certificate`
| Identity key a| Private key used for authentication a| The following types of endpoints, when the authentication type is `Identity key` or `Basic and Identity key`:

* SFTP Receive from Partners endpoints owned by the host
* SFTP Source at Host endpoints
* SFTP Send to Partners endpoints owned by the host
* SFTP Target at Host endpoints
|===

NOTE: For AS2 endpoints, you must configure at least one host keystore. For information, see xref:manage-as2-host-keystores.adoc[]. 

== Add a Host Certificate

To add a host certificate:

. Access the *<host>* page.
. In the *Certificates* section, click *New*.
. Select a certificate type.
. Enter the settings for the selected certificate type:
+
** <<public-certificate,Public Certificate>>
** <<identity-key,Identity key>>
+
. Click *Save*.

[[public-certificate]]
=== Public Certificate Settings

To configure settings for a public certificate:

. In the *Certificate name* field, enter the name of the public certificate.
. In the *Certificate* field, click *Choose file* and select a public certificate.

[[identity-key]]
=== Identity Key Certificate Settings

To configure settings for an identity key certificate:

. In the *Identity Key Name* field, enter the name of the identity key certificate.
. In the *<host> Identity Key PEM File* field, click *Choose file* and select an identity key certificate.
. In the *Key Phassphrase* field, enter a passphrase for protecting the identity key certificate.
. In  the *Expiration Date* field, optionally enter an expiration date for the certificate. This date is a reminder for you, but Anypoint Partner Manager doesn't enforce it.

== Update a Host Certificate

You can update a host certificate by selecting a different certificate file to associate with the certificate:

. Access the *<host>* page.
. In the *Certificates* section, click the name of the certificate that you want to update.
. Click *Edit*.
. Click *Choose File* and select a certificate file.
. Click *Update*.

== Remove a Host Certificate

If you no longer use a host certificate, you can remove it from Anypoint Partner Manager:

. Access the *<host>* page.
. In the *Certificates* section, hover over the name of the host certificate that you want to removve.
. Click the trash can icon on the right.

= See Also

* xref:certificates.adoc[]
* xref:configure-host.adoc[]