== Managing AS2 Host Keystores



== Create an AS2 Host Keystore

You can create a new keystore for the host when you configure an AS2 Receive from Partners endpoint. After you create the keystore, you can reuse it in new endpoint configurations.

To create an AS2 host keystore:

. In the navigation menu, select the host.
. In the *Endpoints* section, click *New*.
+
The *New Endpoint* window appears.
. In the *New Endpoint* window, select *Receive from partners* in the *Usage* field and *AS2* in the *Protocol* field.
. In the *<host> keystore* section, click *Select*.
. In the *Select a <host> keystore* window, click *New*.
. Complete the fields of the *New keystore for <host>* window:
.. In the *Keystore name* field, enter a unique name for the keystore.
.. In the *<host> public certificate* field, click *Choose file*, navigate to your public certificate, and then click *Open*.
.. In the *<host> private key file* field, click *Choose file*, navigate to your private key file, and then click *Open*.
.. In the *Key passphrase* field, enter a passphrase for your private key.
. Click *Upload keystore*.
+
The newly created keystore appears in the *Select a <host> keystore* window and the keystore is saved. You can either continue to xref:create-endpoint.adoc[create an endpoint] or you can close the window.

== Update an AS2 Host Keystore

When your host AS2 keystore is about to expire, follow these steps to obtain a new certificate:

. Depending on your organization’s policies, create a self-signed certificate and key pair, or obtain a new AS2 certificate from your certificate authority.
. Define a date on which you plan to switch to the new certificate.
. Share the new public certificate with your AS2 partners to give them sufficient lead time to plan the certificate switch on their side.

When it's time to switch to the new keystore follow these steps:

. In the navigation menu, select *<host>*.
. In the *Certificates* section, click the keystore to update and then click *Edit*.
. In the *<host> public certificate* field, import the new certificate.
. In the *<host> private key file* field, import the new private key file.
. In the *Key passphrase* field, enter the passphrase for the new keystore.
. Click *Update keystore*.
. After the keystore updates, do either of the following:
* If you have one AS2 receive endpoint that uses the keystore, open one message flow that references the endpoint and redeploy the flow.
* If you have more than one AS2 receive endpoint that uses the keystore, redeploy one message flow for each AS2 receive endpoint that uses the keystore.

+
Partner Manager updates the inbound and outbound AS2 applications in the runtime. The update can take up to 10 minutes to complete.

== Delete an AS2 Host Keystore

You can delete an AS2 host keystore if it has not been assigned to an endpoint. You cannot delete a certificate if it is the only certificate that is uploaded.

To delete an AS2 partner certificate:

. In the navigation menu, select *Partners*.
. Click on the partner whose certificate you want to delete.
. In the *Certificates* section, hover over the row associated with the certificate to delete.
. Click the trash can icon that appears.

== See Also
