= Managing Host Certificate Settings

Anypoint Partner Manager supports the following types of host certificates:

[%header%autowidth.spread]
|===
|Certificate Type |Description | Used by
| Public | Certificate generated by a certificate  (CA) a| * AS2 Send to Partners endpoints owned by a partner or third-party connection
* HTTPS Send to Partners endpoints owned by the host, when the authentication type is `Use a self-signed certificate`
* Target at Host endpoints, when the authentication type is `Use a self-signed certificate`
| Identity key | Private key used for authentication a| * SFTP Receive from Partners endpoints owned by the host when the authentication type is `Identity key` or `Basic and Identity key`
* SFTP Source at Host endpoints when the authentication type is `Identity key` or `Basic and Identity key`
* SFTP Send to Partners endpoints owned by the host when the authentication type is `Identity key` or `Basic and Identity key`
* SFTP Target at Host endpoints when the authentication type is `Identity key` or `Basic and Identity key`
|===

NOTE: For AS2 endpoints, you must configure at least one host keystore. For information, see xref: manage-as2-host-keystore.adoc[]. 

== Create a Host Certificate Configuration

To create a host certificate configuration:

. Access the <host> page.
. In the *Certificates* section, click *New*.
. Select a certificate type.
. Enter the settings for the selected certificate type:
+
** <<public-certificate,Public Certificate>>
** <<identity-key,Identity Key>>
+
. Click *Save*.

[[public-certificate]]
=== Public Certificate Settings

To configure settings for a Public certificate:

. In the *Certificate name* field, enter the name of the public certificate.
. In the *Certificate* field, click *Choose file* to select a public certificate.

[[identity-key]]
=== Identity Key Certificate Settings

To configure settings for an Identity Key certificate:

. In the *Identity Key Name* field, enter the name of the identity key name certificate.
. In the *<host> Identity Key PEM File* field, click *Choose file* to select an identity key private key file certificate.
. In the *Key Phassphrase* field, enter a passphrase for protecting the identity key private key file.
. In  the *Expiration Date* field, optionally enter an expiration date for the certificate. This date is a reminder for you, but Anypoint Partner Manager doesn't enforce it.

== Update a Host Certificate Configuration

You can update a host certificate configuration by selecting a different certificate file to associate with the certificate:

. Access the <host> page.
. In the *Certificates* section, click the name of the host certificate for which you want to update a different certificate file.
. Click *Edit*.
. Click *Choose File* to select a different certificate file.
. Click *Update*.

== Delete a Host Certificate Configuration

If you no longer use a host certificate, you can delete it from Anypoint Partner Manager:

. Access the <host> page.
. In the *Certificates* section, hover over the name of the host certificate configuration that you want to delete.
. Click the trash can icon on the right.

= See Also

* xref:certificates.adoc[]
* xref:configure-host.adoc[]