== Managing AS2 Partner Certificates

If you create an AS2 Receive from Partners or Send to Partners endpoint, you must assign an AS2 partner certificate to the associated partner.

== Add an AS2 Partner Certificate

To add an AS2 partner certificate:

. In the navigation menu, select *Partners*.
. Click on the partner whose certificate you want to add.
. In the *Certificates* section, click *New*.
. Select a certificate type and follow the associated steps:
+
[%header%autowidth.spread]
|===
|Certificate Type |Steps
|Private Keypair
a|
. In the *Keystore name* field, enter a unique name for the keystore. 
. In the *<host> public certificate* field, click *Choose file*, navigate to your public certificate, and click *Open*.
. In the *<host> private certificate* field, click *Choose file*, navigate to your private key file, and click *Open*.
. In the *Key passphrase* field, enter a passphrase for your private key.
| Public Certificate
a|
. In the *Certificate name* field, enter a unique name for the certificate. 
. In the *Certificate* field, click *Choose file*, navigate to your .PEM certificate file, and click *Open*.
| Identity Key
a|
. In the *Identity Key name* field, enter a unique name for the identity key. 
. In the *<host> identity key PEM file* field, click *Choose file*, navigate to your .PEM certificate file, and click *Open*.
. In the *Key passphrase* field, enter a passphrase for your identity key.
|===
. Click *Create*.
. Optionally, assign the new certificate to a partner. To do this, hover over the *AS2* cell in the row containing the certificate and click *Assign*.
+
Assigning a certificate to a partner unassigns the previously-assigned certificate.

== Update an AS2 Partner Certificate

When your partners update their AS2 certificates, they typically provide you with the new certificates and the times when they must be activated.

To update a new partner AS2 certificate:

. In the navigation menu, select *Partners*.
. Click on the partner whose certificate you want to update.
. In the *Certificates* section, click *New*.
. Select the new certificate and click *Upload certificate*.
. In the *AS2* column for the certificate entry, click *Assign*.
+
Assigning a certificate to a partner unassigns the previously-signed certificate. Anypoint Partner Manager updates the inbound and outbound AS2 applications in the runtime. The update can take up to 10 minutes to complete.

== Delete an AS2 Partner Certificate

You can delete AS2 partner certificates that are not assigned to partners.

To delete an AS2 partner certificate:

. In the navigation menu, select *Partners*.
. Click on the partner whose certificate you want to delete.
. In the *Certificates* section, hover over the row associated with the certificate to delete.
. Click the trash can icon that appears.

== See Also

* xref:certificates.adoc[Certificate Settings]
