= Managing AS2 Host Keystores

AS2 host keystores consist of a public certificate and a private key. You must configure at least one AS2 host keystore if you use AS2 endpoints.

[[host-keystore-create]]
== Create an AS2 Host Keystore

To create an AS2 host keystore:

. In the sidebar, select the host.
. In the *Keystore Name* field, enter the name of the keystore file to store your organization's private key.
. In the *<host> Public Certificate* field, click *Choose file* to select a public certificate. 
. In the <*host> Private Key File* field, click *Choose file* to select a key file.
. In the *Key Passphrase* field, enter a passphrase for protecting the private key.

== Update an AS2 Host Keystore

When the certificate for your AS2 keystore is about to expire, follow these steps to obtain a new one:

. Depending on your organization’s policies, create a self-signed certificate and key pair, or obtain a new AS2 certificate from your certificate authority.
. Define a date on which you plan to switch to the new certificate.
. Share the new public certificate with your AS2 partners to give them sufficient lead time to plan the certificate switch on their side.

When it's time to update the keystore with the new certificate, follow these steps:

. In the sidebar, select *<host>*.
. In the *Certificates* section, click the keystore to update and then click *Edit*.
. In the *<host> public certificate* field, click *Choose file*, navigate to the updated public certificate, and click *Open*.
. In the *<host> private key file* field, click *Choose file*, navigate to the private key file, and click *Open*.
. In the *Key passphrase* field, enter the passphrase for the new keystore.
. Click *Update keystore*.
. After the keystore updates, do either of the following:
* If you have one AS2 Receive from Partners or Send to Partners endpoint that uses the keystore, open one message flow that references the endpoint and redeploy the flow.
* If you have more than one AS2 Receive from Partners or Send to Partners endpoint that use the keystore, redeploy one message flow for each endpoint that uses the keystore.

+
Anypoint Partner Manager updates the inbound and outbound AS2 applications in the runtime. The update can take up to 10 minutes to complete.

== Delete an AS2 Host Keystore

You can delete an AS2 host keystore if it has not been assigned to an endpoint. You cannot delete a certificate if it is the only certificate that is uploaded.

To delete an AS2 host keystore:

. In the sidebar, select *Partners*.
. Click on the partner whose certificate you want to delete.
. In the *Certificates* section, hover over the row associated with the certificate to delete.
. Click the trash can icon that appears.

== See Also

* xref:certificates.adoc[]
* xref:endpoint-as2-receive.adoc[]
* xref:endpoint-as2 -send.adoc[]
* xref:manage-host-certificate-settings.adoc[]
