= Source at Host Message Type

The source at host message type defines the way in which your backend applications transform outbound transactions and send them to your partners.

Partner Manager automatically generates a message type identifier from the schema filename. This value can be modified.
The message identifier value used in the dynamic message routing for outbound B2B transactions.

Use the following settings to define JSON or XML settings for outbound EDI transactions:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Format a|Selected application message structure format:

* JSON
* XML |None |Yes
|Schema |Imported XSD or JSON schema file for the message type. |None |Yes
|Message type identifier a| Partner Manager automatically generates this identifier from the schema filename and uses it to dynamically route outbound B2B transactions. You can modify the message type identifier to ensure that it has a meaningful, generic name.

Your partner must pass this value when sending messages, files, or both to Partner Manager:

* If you receive the payload via an HTTP-based endpoint, the message type identifier is the relative path in the HTTP request.
* If you receive the payload via AS2 or via file-based endpoint protocols such as SFTP and FTP, the filename begins with `<message-type-id>_`.

See xref:outbound-message-routing.adoc[Outbound Message Routing] to understand how outbound routing is performed and how your backend applications should pass the message type identifier when sending application messages to Partner Manager endpoints. |None |Yes

|Reference identifiers and attributes mapping |The uploaded DataWeave script with mappings to extract the <<reference-ids-example,reference identifiers>>, business key, and custom messaging attributes from the payload received from the backend application.
{sp} +
{sp} +
The extracted values for the reference identifiers and business key are used for dynamic routing into the appropriate message flow. |None |Yes
|===

== See Also

* xref:document-types.adoc[Message Types]
* xref:partner-manager-create-message-type.adoc[Creating Message Types]
* xref:delete-message-types.adoc[Deleting Message Types]
