= Map Example for Reference Identifiers and Custom Attributes

When you create a DataWeave map to use with message flows:

* The input of the map is the payload that follows the schema uploaded in the definition for the message type.
* The output of the map contains the following fields:

* `partnerReferenceId`
+
Required identifier that uniquely identifies the receiving partner.
+
* `hostReferenceId`
+
Required if the backend app sends outbound transactions on behalf of different internal business units that require different mapping or sender identifiers on the EDI data.
+
* `businessDocumentKey`
+
Optional key reference value, such as the order number of invoice number.
+
* Custom attributes, if the associated message type has custom attributes defined.

For example, the following map transforms the XML payload from a backend application. In this example:

* `partnerReferenceId` is set to the payload's `VendorName` value,`MYTHICAL SUPPLIER, LLC`.
* `hostReferenceId` is set to the payload's `LineOfBusiness` value, `NTO Retail Canada`.
* `BusinessDocumentKey` is set to the payload's `PoNumber` value, `INVOICE-005`.
* The `Shipment ID` custom attribute is set to the payload's `purchaseNumber` value.
* The `SCAC` custom attribute is set to the payload's

%dw 2.0
output application/json
---
{
partnerReferenceId: payload.B2BMessage.Header.ReceiverID,
hostReferenceId: payload.B2BMessage.Header.SenderID,
businessDocumentKey: payload.B2BMessage.Header.BusinessKey
Attributes:
  {label:"Shipment ID"
	 values:}
  {label: "SCAC"
	values:payload.scac}

Generated output:

{
"partnerReferenceId": "NTO Retail",
"hostReferenceId": "Mythical Supplier",
"businessDocumentKey": "INVOICE-005",
"attributes":[
  {
	"label": "Shipment ID",
  "values": ALPS-SH-001"
	},
	{
	"label":"SCAC"
	"values": MVTL"
	}
]
}

== See Also
