= Receive from Partners Message Type Settings

:message-type: Receive from Partners

The Receive from Partners message type defines the way in which Anypoint Partner Manager transforms the inbound transactions sent from your partner to your organization. You can define the CSV, EDIFACT, JSON, X12, or XML format for the Receive from Partners message type.

== CSV

include::partial$csv-inbound-partial.adoc[]

== EDIFACT

Use the following settings to define EDIFACT as the format for the Receive from Partners message type:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Usage | Message usage. Allowed value is `Receive from partners`. |  | Yes
|Format | Format of the message. Allowed value is `EDIFACT`.| |Yes
|Version | EDIFACT version, such as `d10b` or `d96a`. |  |Yes
|Message type |
EDIFACT message type, such as `ORDERS`, `DESADV`, or `INVOIC`.
 |  | Yes
|Reference identifiers and attributes mapping a| Uploaded DataWeave map that extracts the reference identifiers and custom attributes from the payload received from the partner:

* The extracted reference identifier values are used for dynamic routing into the appropriate message flow.
* The extracted custom attributes enable you to have visibility into the lifecycle of your B2B workflow. For more information, see xref:use-custom-attributes.adoc[Using Custom Messaging Attributes with Message Types].
| |No
|Schema a|EDI schema for the message type. Options include:

* *Use standard EDIFACT-<version>* +
Applies the standard EDIFACT schema for the configured format and version.
* *Customize* +
Enables you to import a customized xref:connectors::x12-edi/x12-edi-schema-language-reference.adoc[EDI schema language] file, if you must make adjustments to the standard EDIFACT schema.
+
When using the customized EDI schema, you can assign a custom name to the message type definition, for example, `EDIFACT-d97a-ORDERS-<PartnerName>`.
| Use standard EDIFACT <version>| Yes
|===

== JSON or XML

Use the following settings to define JSON or XML as the format for the Receive from Partners message type:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Usage | Message usage. Allowed value is `Receive from partners`. | | Yes
|Format | Format of the message. Allowed value is `JSON` or `XML`. | |Yes
|Schema | Imported JSON or XSD schema file for the message type. | |No
|Message type identifier a| Message type identifier value used in the dynamic message routing of inbound B2B transactions:

* If a schema is associated with the message type, Partner Manager automatically generates the message type identifier from the schema filename.
{sp} +
{sp} +
You can modify this value.
* If a schema is not assciated with the message type, you must enter the message type identifier manually.

Your partner must pass the message type identifier as follows when sending inbound messages:

* If you receive the payload via an HTTP-based endpoint, your partner must pass the message type identifier as the relative path in the HTTP request.
* If you receive the payload via AS2 or a file-based endpoint protocol such as SFTP or FTP, your partner must prefix the message type identifier to the filename (`<message-type-id>_<filename>`).

| |Yes
|Reference identifiers and attributes mapping a| Uploaded DataWeave map that extracts the reference identifiers, business key, and custom messaging attributes from the payload received from the partner:

* The extracted reference identifier values are used for dynamic routing into the appropriate message flow.
* The extracted custom attributes enable you to have visibility into the lifecycle of your B2B workflow. For more information, see xref:use-custom-attributes.adoc[Using Custom Messaging Attributes with Message Types].| |Yes
|===

== X12

Use the following settings to define X12 as the format for the Receive from Partners message type:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Usage | Message usage. Allowed value is `Receive from partners`. | | Yes
|Format | Format of the message. Allowed value is `X12`. ||Yes
|Version | X12 version, such as `3010` or `5020`. | |Yes
|Message type |X12 transaction set number, such as `850` (purchase order) or `214`( for (shipment status). | | Yes
|Reference identifiers and attributes mapping a| Uploaded DataWeave map that extracts the reference identifiers, business key, and attribute from the payload received from the partner:

* The extracted reference identifier values are used for dynamic routing into the appropriate message flow.
* The extracted custom attributes enable you to have visibility into the lifecycle of your B2B workflow. For more information, see xref:use-custom-attributes.adoc[Using Custom Messaging Attributes with Message Types]. | |No
|Schema a|EDI schema for the message type. Options include:

* *Use standard X12-<version>* +
Applies the standard X12 schema for the version and message type configured.
* *Customize* +
Enables you to import a customized xref:connectors::x12-edi/x12-edi-schema-language-reference.adoc[EDI schema language] file if you must make adjustments to the standard X12 schema.
+
When using the customized EDI schema, you can assign a custom name to the message type definition, for example, `X12-7050-204-PartnerName`.
| Use standard X12-<version> |Yes
|===

For an example that shows how to customize an X12 schema, see https://www.mulesoft.com/exchange/works.integration/b2b-x12-custom-schema-example[Customize EDI X12 Schema for B2B Integrations^] in Anypoint Exchange.

== See Also

* xref:document-types.adoc[Message Types]
* xref:partner-manager-create-message-type.adoc[Creating Message Types]
* xref:delete-message-types.adoc[Deleting Message Types]
