= Modifying Message Types

You can modify a message type's settings, but what you can modify depends on the message type's usage and protocol.

To modify a message type's settings:

. In the navigation menu, select <*host-name*>.
. Locate the message type you want to modify.
. Change any of the following settings:

== Receive from Partners Message Types

You can do the following to modify the settings of Receive from Partners message types:

[%header%autowidth.spread]
|===
|Format | What You Can Modify
| EDIFACT or X12
a|
* Select a different reference map file to map the reference identifiers, business key, and custom attributes.
* Select a different schema file, if the *Schema* field is set to *Customize*.
* Add new custom message attributes.
| JSON or XML
a|
* Select a different schema file.
* Select Select a different reference map file to map the reference identifiers, business key, and custom attributes.
|===

== Source at Host Message Types

You can do the following to modify the settings of Source at Host message types:

* Select a different schema file.
* Select a different reference map file to map the reference identifiers, business key, and custom attributes.
* Add new custom message attributes.

== Target at Host Message Type

* Select a different schema file, if the *Schema* field is set to *Customize*.
