= Modifying 3rd Party Connection Settings

You can modify 3rd party connection settings including contact details, identifiers, digital certificates, and more.

To modify 3rd party connection settings:

. In Partner Manager, select *Partners* in the navigation menu.
. Click the connection you want to modify.
. Modify any of the following settings:
+
[%header%autowidth.spread]
|===
|Settings |Action a|Additional Information
|3rd party company information, including the company's address, website, and contact details a|
* Modify partner information:
+
Click *Edit* in the *About* section, click the contact type, and make the desired modifications.
+
* Delete a contact
+
Click *Edit* in the *About* section, click the contact type, and click the *Delete contact* link.
|
| Identifiers
a|
* Add a new identifier
+
Click *New* in the *Identifiers* section and enter the required fields.
+
* Delete an identifier:
+
Select the identifier and click *Delete*.
+
Because a 3rd party connection must have at least one identifier, you can't delete the last one.
+
| xref:partner-manager-identifiers.adoc[Sender and Receiver Identifiers]
| The partner's digital certificates, such as X.509 certificates
| Click *New* in the *Certificates* section.
|
| Endpoints
a| * Create a new connection-owned endpoint
+
Click *New* in the *Endpoints* section and enter the required fields.
+
* Delete a connection-owned endpoint
+
Click the endpoint's link and click *Delete*.
| xref:create-endpoint.adoc[Create and Configure Endpoints]
|===

== See Also

* xref:create-third-party.adoc[Create a New Third Party Connection]
* xref:delete-third-party.adoc[Delete a Third Party Connection]
