= Modifying Partner Settings

You can modify a partner's settings including contact details, identifiers, digital certificates, acknowledgements, control numbers, and more.

To modify a partner's settings:

. In Partner Manager, select *Partners* in the navigation menu.
. Click the partner.
. Change any of the following settings:
+
[%header%autowidth.spread]
|===
|Settings |Actions a|Additional Information
|Partner information, including a partner's address, website, and contact details a|
* Modify partner information
+
Click *Edit* in the *About* section, click the contact type, and make the desired modifications.
+
* Delete a contact
+
Click *Edit* in the *About* section, click the contact type, and click the *Delete contact* link.
|
| Identifiers
a|
* Add a new identifier
+
Click *New* in the *Identifiers* section and enter the required fields.
+
* Delete an identifier
+
Select the identifier and click *Delete*.
+
Because a partner must have at least one identifier, you can't delete the last one.
+
| xref:partner-manager-identifiers.adoc[Sender and Receiver Identifiers]
| The partner's digital certificates, such as X.509 certificates
| Click *New* in the *Certificates* section.
|
| Endpoints
a| * Create a new endpoint
+
Click *New* in the *Endpoints* section and enter the required fields.
+
* Delete an endpoint
+
Click the endpoint's link and click *Delete*.
| xref:create-endpoint.adoc[Create Endpoints]
| Acknowledgements, validations, control numbers, character sets (X12 only), and separators (X12 send format only).
a| * Modify
+
Click the appropriate link in the *Validation and acknowledgement settings* section, and make the desired modifications.
a|
* xref:edifact-receive-read-settings.adoc[EDIFACT Receive Settings]
* xref:edifact-send-settings.adoc[EDIFACT Send Settings]
* xref:x12-receive-read-settings.adoc[X12 Receive Settings]
* xref:x12-send-settings.adoc[X12 Send Settings]
|===

== See Also

* xref:create-partner.adoc[Creating Partners]
* xref:partner-manager-delete-partner.adoc[Deleting Partners]
