= Sender and Receiver Identifiers

B2B transactions use identifiers in messages to identify the senders and receivers of the messages. For X12 messages, the identifiers in the ISA and GS headers provide valuable information that enables identification of the appropriate flow to use to process the transaction.

Add identifiers and configure their values in the Partner Manager host page.

[[create-identifier]]
== Add and Configure a New Identifier

. In Partner Manager, select the name of your host organization in the left navigation menu. 
. In the *Identifiers* section, click *New*. 
. In the *New Identifier* dialog, select the identifier type from the drop-down list:
* <<as2-identifier,*AS2 Identity*>>
* <<reference-id,*Reference ID*>>
* <<x12-gs,*X12 - GS*>>
* <<x12-isa,*X12 - ISA*>>
. In *Identifier Value*, enter a value to uniquely name your identifier. 
. If you selected *X12-ISA* as the *Type* value, you must also select a *Qualifier* from the list. 
. Click *Create identifier*.

[[x12-isa]]
== X12 ISA Identifier Values

Use the following values to configure the X12 ISA identifier type:

[%header%autowidth.spread]
|===
|Setting |Description | Required

|Qualifier
a|The Qualifier types available with Anypoint Partner Manager are:

* `01 (DUNS Number)`
* `02 (SCAC - Standard Carrier Alpha Code)`
* `03 (FMC - Federal Maritime Commission)`
* `04 (IATA - International Air Transport Association)`
* `08 (UCC EDI Number)`
* `09 (X.121)`
* `10 (DoD - Department of Defense Activity Address Code)`
* `11 (DEA - Drug Enforcement Administration)`
* `12 (Phone Number)`
* `13 (UCS Code)`
* `14 (DUNS Number and Suffix Number)`
* `16 (DUNS Number with a Four Character Suffix)`
* `19 (EDI Council of Australia Communications ID)`
* `20 (HIN - Health Industry Number)`
* `30 (U.S. Federal Tax Identification Number)`
* `NR (NRMA - National Retail Merchants Association)`
* `SN (Standard Address Number)`
* `ZZ (Mutually Defined)`
|Yes 
|Identifier value
|EDI X12-ISA ID for your trading partner, which can be up to 15 characters. Your trading partner supplies you with the proper EDI X12 Interchange Sender and Receiver IDs during onboarding.
|Yes 
|===

[[x12-gs]]
== X12 GS Identifier Values

Use the following values to configure the X12 GS identifier type:

[%header%autowidth.spread]
|===
|Setting |Description | Required

|Identifier value
|EDI X12-GS ID for your trading partner, which can be up to 15 characters. Your trading partner supplies you with the proper EDI X12 Group Sender and Receiver IDs during onboarding.
|Yes
|===

[[as2-identifier]]
== AS2 Identity 

To use AS2 transport to exchange B2B transactions with your trading partner, first configure the AS2 identifier for your organization and for your trading partner.

Use the following values to configure the AS2 identifier:

[%header%autowidth.spread]
|===
|Setting |Description | Required
|Identifier value
|The AS2 identity for your trading partner. Your trading partner supplies you with the corresponding Sender and Receiver AS2 IDs during the onboarding process.
|Yes 
|===

[[reference-id]]
== Outbound Message Flow Partner Reference Identifiers

Outbound message flows that translate your backend application messages to EDI format use the Partner Reference ID when sending data to your trading partners. 

Unlike EDI transactions that have well-defined standards for how sender, receiver, and document type information is presented in the data, the source messages for outbound B2B data exchange originating from your enterprise backend systems typically follow schemas. These schemas are usually defined by your backend application teams according to your organization’s data models. 

The receiving trading partner information on the application message from the backend system might not necessarily be the same as the name of the partner in Partner Manager. This is similar to how ISA and GS identifiers on an inbound EDI message might not be the same as the profile name of the partner.

Partner Manager’s outbound message processing framework makes a dynamic lookup to determine the receiving partner based on the content in the application message received from the backend systems.

=== Example

In this example, an outbound purchase order XML message from your ERP system to your trading partner Mythical Supplier has the following content in the payload:

`<VendorName>MYTHICAL SUPPLIER, LLC</VendorName>`

An outbound payment remittance advice JSON message from your Financials system to the same trading partner contains the following content in the payload:

`"PayeeName": "MYTHICAL ENTERPRISES"`

In order for Partner Manager to route these outbound transactions to the appropriate message flows for Mythical Supplier, you must add these values as Partner Reference IDs from the partner’s profile page by <<create-identifier,creating a new identifier>> and selecting the type as *Reference ID*.

If your backend system sends outbound transactions to trading partners on behalf of more than one internal line of business, thus requiring you to set different X12 ISA and X12 GS sender identifiers on the translated outbound data (depending on which LoB is sending the transaction), you can configure partner reference identifiers on your host profile, with the value in the application message’s payload that uniquely identifies the sending LoB.

The actual usage of partner reference identifiers and how outbound message routing is determined, is explained in the outbound message documentation.


== See Also

* xref:configure-host.adoc[Configure and Manage a Host Profile]
* xref:message-flows.adoc[Message Flows]
* xref:outbound-message-routing.adoc[Outbound Message Routing]