= Sender and Receiver Identifiers
page-aliases: x12-identity-settings.adoc, delete-identifiers.adoc

AS2, EDIFACT, and X12 transactions use identifiers in messages to identify the senders and receivers of those messages. For X12 messages, the identifiers in the ISA and GS headers identify which flow to use to process the transaction.

You create identifiers at the host level.

[[create-identifier]]
== Create an Identifier

To create an identifer:

. Access the *<host>* page.
. In the *Identifiers* section, click *New*.
. In the *New Identifier* dialog, select the identifier type:
* <<as2-identifier,AS2 Identity>>
* <<edifact-unb, EDIFACT-UNB>>
* <<reference-id,Reference ID>>
* <<x12-gs,X12 - GS>>
* <<x12-isa,X12 - ISA>>
. In *Identifier Value*, enter a value that uniquely names your identifier.
. If you selected `EDIFACT-UNB` or `X12-ISA` as the identifier type, you must also select a qualifier.
. Click *Create identifier*.

[[as2-identifier]]
=== AS2 Identifier

Complete this field to configure an AS2 identifier:

[%header%autowidth.spread]
|===
|Setting |Description | Required
|Identifier value
|AS2 identity for your partner. Your partner supplies you with the corresponding sender and receiver AS2 IDs during the onboarding process.
|Yes
|===

[[edifact-unb]]
=== EDIFACT UNB Identifier

Complete these fields to configure an EDIFACT UNB identifier:

[%header%autowidth.spread]
|===
|Setting |Description | Required

|Qualifier
|
Qualifier type for your partner’s EDIFACT-UNB ID.
|Yes
| Identifier value
| EDIFACT-UNB ID for your partner, which can be up to 15 characters. Your partner supplies you with the EDIFACT Interchange Sender and Receiver IDs during onboarding.
| Yes

|===

=== Reference ID

Complete this field to configure to use a reference ID (DUNS number) identifier:

[%header%autowidth.spread]
|===
|Setting |Description |Required

|Identifier Value
|DUNS number for your partner, which is a nine-digit number that corresponds to the sender or receiver ID. Your partner supplies you with this number during onboarding.

|Yes +

|===

[[x12-gs]]
=== X12 GS Identifier

Complete this field to configure an X12 GS identifier:

[%header%autowidth.spread]
|===
|Setting |Description | Required

|Identifier value
|EDI X12-GS ID for your partner, which can be up to 15 characters. Your partner supplies you with the EDI X12 Group Sender and Receiver IDs during onboarding.
|Yes
|===

[[x12-isa]]
=== X12 ISA Identifier

Complete these fields to configure an X12 ISA identifier:

[%header%autowidth.spread]
|===
|Setting |Description |Required

|Qualifier
a|One of the following:

* `01 (DUNS Number)`
* `02 (SCAC - Standard Carrier Alpha Code)`
* `03 (FMC - Federal Maritime Commission)`
* `04 (IATA - International Air Transport Association)`
* `07 (Global Location Number (GLN))`
* `08 (UCC EDI Number)`
* `09 (X.121)`
* `10 (DoD - Department of Defense Activity Address Code)`
* `11 (DEA - Drug Enforcement Administration)`
* `12 (Phone Number)`
* `13 (UCS Code)`
* `14 (DUNS Number and Suffix Number)`
* `15 (Petroleum Accountants Society of Canada Company Code)`
* `16 (DUNS Number with a Four Character Suffix)`
* `17 (American Bankers Association (ABA) Transit Routing Number (Including Check Digit, 9 Digit))`
* `18 (Association of American Railroads (AAR) Standard Distribution Code)`
* `19 (EDI Council of Australia Communications ID)`
* `20 (HIN - Health Industry Number)`
* `21 (Integrated Postsecondary Education Data System, or (IPEDS))`
* `22 (Federal Interagency Commission on Education, or FICE)`
* `23 (National Center for Education Statistics Common Core of Data 12-Digit Number for Pre-K-Grade 12 Institutes, or NCES)`
* `24 (The College Board's Admission Testing Program 4-Digit Code of Postsecondary Institutes, or ATP)`
* `25 (ACT, Inc. 4-Digit Code of Postsecondary Institutions.)`
* `26 (Statistics of Canada List of Postsecondary Institutions)`
* `27 (Carrier Identification Number)`
* `28 (Fiscal Intermediary Identification Number)`
* `29 (Medicare Provider and Supplier Identification Number)`
* `30 (U.S. Federal Tax Identification Number)`
* `31 (Jurisdiction Identification Number Plus 4)`
* `32 (U.S. Federal Employer Identification Number (FEIN))`
* `33 (National Association of Insurance Commissioners Company Code (NAIC))`
* `34 (Medicaid Provider and Supplier Identification Number)`
* `35 (Statistics Canada Canadian College Student Information System Institution Codes)`
* `36 (Statistics Canada University Student Information System Institution Codes)`
* `37 (Society of Property Information Compilers and Analysts)`
* `38 (The College Board and ACT, Inc. 6-Digit Code List of Secondary Institutions)`
* `AM (Association Mexicana del Codigo de Producto (AMECOP) Communication ID)`
* `NR (NRMA - National Retail Merchants Association)`
* `SA (User Identification Number)`
* `SN (Standard Address Number)`
* `ZZ (Mutually Defined)`

|Yes

|Identifier value
|EDI X12-ISA ID for your partner, which can be up to 15 characters. Your partner supplies you with the EDI X12 Interchange Sender and Receiver IDs.

|Yes +

|===

== Delete Identifiers

You can delete identifiers that are no longer used in a message flow. Before you delete an identifier, consider the following:

* You can't delete the last host identifier of its type.
* Deleting an existing host or partner identifier impacts the identification and routing of B2B messages to the associated partner.
* If you must replace the identifier with another identifier, record the existing identifier's value and qualifier type.

To delete an identifier:

. In the sidebar, select *Partners*.
. Select the partner that contains the identifier to delete.
. In the *Identifiers* row, hover over the identifier to delete and click the trash can icon.

[[reference-id]]
== Outbound Message Flow Partner Reference Identifiers

Outbound message flows that transform your backend application messages to EDI format use the partner Reference ID when sending data to your partner.

Unlike EDI transactions, which have well-defined standards for how sender, receiver, and document type information is presented in the data, the source messages for outbound B2B data exchange that originate from your enterprise backend systems typically follow schemas. These schemas are based on your organization's data models and they are usually defined by your backend application teams.

The receiving partner's information about the application message from the backend application might not contain the same as the name of the partner in Partner Manager. This scenario is similar to how ISA and GS identifiers on an inbound EDI message might not be the same as the profile name of the partner.

The Partner Manager outbound message processing framework makes a dynamic lookup to determine the receiving partner based on the content of the application message received from the backend systems.

If your backend application sends outbound transactions to partners on behalf of multiple internal lines of business, set different X12 ISA and X12 GS sender identifiers on the transformed outbound data to reflect the sending line of business. In this scenario, configure partner reference identifiers on the host profile by using the value in the application message’s payload that uniquely identifies the sending line of business.

=== Example

In this example:

* An outbound purchase order XML message from your ERP system to your partner, Mythical Supplier, has the following content in the payload:
+
`<VendorName>MYTHICAL SUPPLIER, LLC</VendorName>`
+
* An outbound payment remittance advice JSON message from your financial system to the same partner has the following content in the payload:
+
`"PayeeName": "MYTHICAL ENTERPRISES"`

For Partner Manager to route these outbound transactions to the appropriate message flows for Mythical Supplier, you must add these values as partner reference IDs to the partner’s profile page. To do this, create a new identifier and select the type as *Reference ID*.

== See Also

* xref:message-flows.adoc[Message Flows]
* xref:inbound-message-routing.adoc[Inbound Message Routing]
* xref:outbound-message-routing.adoc[Outbound Message Routing]
