= Create and Configure Message Types

Message types define the schematic structure of the transactions received or sent by Partner Manager.

A message type in Partner Manager can be used in one of the following ways:

* Receive from partners
* Target at host
* Source at host
* Send to partners

Message types are always managed in the host page, regardless of whether they are used for a single partner or for multiple trading partners. Additionally, message types are reusable across message flows for different trading partners.

You can create message types from the host page  or from the Message Flow wizard. When you create message types during message flow configuration, Partner Manager automatically designates the usage for the message type.

[[create-message-type]]
== Create a Message Type

. In Partner Manager left navigation, select *<host-name>*.
. From the *Message types* section host page , click *New*.
. In the *Usage* drop-down list, select the message type:
* <<receive-and-send-to-partners,Receive from partners>>
* <<target-at-host,Target at host>>
* <<source-at-host,Source at host>>
* <<receive-and-send-to-partners,Send to partners>>
+
If you create a message type from the message flow, Partner Manager automatically determines the *Usage* value, which is automatically assigned to the host or trading partner from which the message type was created.
. Click *Save*. +
The message type appears in the *Message types* section on the host page .

[[receive-and-send-to-partners]]
== Receive From and Send To Partners

Inbound and outbound transactions between your organization and your trading partners typically follow EDI standards such as X12 or EDIFACT.

== Define X12 as an Inbound or Outbound Message Type

Use the following settings to define X12 as an inbound or outbound message type:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Format | The format of the message. |`X12`|Yes
|Version | List of valid versions: `3010`, `3020`, `3030`, `3040`, `3050`, `3060`, `3070`, `4010`, `4020`, `4030`, `4040`, `4050`, `4060`, `5010`, `5020`, `5030`, `5040`, `5050`, `6020`, `6030`, `6040`, `6050`, `7010`, `7020`, `7030`, `7040`, `7050`
 | None |Yes
|Message Type |The X12 transaction set number, such as `850` for *Purchase Order* or `214` for *Shipment Status*. |None | Yes
|Schema a|The EDI schema for the message type. Options include:

* *Use standard X12-<version>* +
This setting applies the standard X12 schema for the version and message type configured.
* *Customize* +
This setting enables you to import a customized xref:connectors::x12-edi/x12-edi-schema-language-reference.adoc[EDI schema language] file, if your requirement is to make adjustments to the standard X12 schema.
+
When using the customized EDI schema, you can assign a custom name to the message type definition, for example, `X12-7050-204-PartnerName`.
| None |Yes
|===

You can find an https://www.mulesoft.com/exchange/works.integration/b2b-x12-custom-schema-example[example] of how to customize EDI schema in Anypoint Exchange.

== Define EDIFACT as an Inbound or Outbound Message Type

Use the following settings to define EDIFACT as an inbound or outbound message type:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Format | The format of the message. |`EDIFACT`|Yes
|Version | List of valid versions: `D00A`, `D00B,` `D01A`, `D01B`, `D01C`, `D02A`, `D02B`, `D03A`, `D03B`, `D04A`, `D04B`, `D05A`, `D05B`, `D06A`, `D06B`, `D07A`, `D07B`, `D08A`, `D08B`, `D09A`, `D09B`, `D10A`, `D10B`, `D11A`, `D11B`, `D12A`, `D12B`, `D13A`, `D13B`, `D14A`, `D14B`, `D15A`, `D15B`, `D93A`, `D95B`, `D96A`, `D97A`, `D98A`, `D98B`, `D99A`, `D99B`
 | None |Yes
|Message Type |
The EDIFACT message type, such as `ORDERS`, `DESADV`, or `INVOIC`.
 |None | Yes
|Schema a|The EDI schema for the message type. Options include:

* *Use standard EDIFACT-<version>* +
This setting applies the standard EDIFACT schema for the version and message type configured.
* *Customize* +
This setting enables you to import a customized xref:connectors::x12-edi/x12-edi-schema-language-reference.adoc[EDI schema language] file, if your requirement is to make adjustments to the standard EDIFACT schema.
+
When using the customized EDI schema, you can assign a custom name to the message type definition, for example, `EDIFACT-d97a-ORDERS-<PartnerName>`.
|None| Yes
|===

[[target-at-host]]
== Target at Host

The target at host application message structure (JSON or XML) defines the way in which inbound EDI transactions are translated and sent to your backend applications.

Use the following settings to define JSON or XML settings for inbound EDI transactions:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Format a|The selected application message structure format:

* *JSON*
* *XML* |None |Yes
|Schema |The imported XSD or JSON schema file for the message type. |None |Yes
|Name |The message type name that Partner Manager automatically generates from the schema file name, which you can later modify. |None |Yes
|===

[[source-at-host]]
== Source at Host
The source at host application message structure (JSON or XML) defines the way in which your backend applications translate outbound EDI transactions and send them to your trading partners.

Use the following settings to define JSON or XML settings for outbound EDI transactions:

[%header%autowidth.spread]
|===
|Setting |Description |Default | Required
|Format a|The selected application message structure format:

* *JSON*
* *XML* |None |Yes
|Schema |The imported XSD or JSON schema file for the message type. |None |Yes
|Message type identifier a|Partner Manager automatically generates a message type identifier from the schema file name. This value can be modified.

The message identifier value used in the dynamic message routing for outbound B2B transactions.

See xref:outbound-message-routing.adoc[Outbound Message Routing] to understand how this routing is performed and how your backend applications should pass the message type identifier when sending application messages to Partner Manager endpoints. |None |Yes

|Reference identifiers and business key mapping |The uploaded DataWeave script with mapping to extract the <<reference-ids-example,reference identifiers>> and business key mappings from the payload received from the backend application for dynamic routing into the appropriate message flow. |None |Yes
|===

[[reference-ids-example]]
== Reference Identifiers and Business Key Mapping Example

The input to the DataWeave map is the payload that follows the schema uploaded in the message type definition. The output must contain the following fields:

* `partnerReferenceId` +
Required identifier that uniquely identifies the receiving partner.
* `hostReferenceId` +
Optional, except when backend systems are sending outbound transactions on behalf of different internal business units that require different mapping or sender identifiers to be set on the EDI data.
* `businessDocumentKey` +
Optional key reference value, such as `Order Number`or `Invoice Number`.

This is an example DataWeave map for an XML payload from the backend application:

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
ns ns0 http://xmlns.mulesoft.com/enterpriseobjects/finance/purchaseorder/

{
	partnerReferenceId: payload.ns0#PurchaseOrder.ns0#VendorName,
	hostReferenceId: payload.ns0#PurchaseOrder.ns0#LineOfBusiness,
	businessDocumentKey: payload.ns0#PurchaseOrder.ns0#PONumber
}

Generated output:

{
"partnerReferenceId": "MYTHICAL SUPPLIER, LLC",
"hostReferenceId": "NTO Retail Canada",
"businessdocumentKey": "INVOICE-005"
}
----

== See Also

* xref:create-outbound-message-flow.adoc[Create and Configure an Outbound Message Flow]
* xref:configure-message-flows.adoc[Create and Configure an Inbound Message Flow]
