= Creating Message Types

You can create new message types from the *<host>* page or by using the Message Flow wizard.

== Create a Message Type from the Host Page

To create a message type from the *<host>* page:

. In the sidebar, select *<host-name>*.
. From the *Message types* section, click *New*.
. In the *Usage* drop-down list, select the message usage.
. Add values to the remaining settings.
+
For setting descriptions, see the topic that corresponds to the message type usage:

* xref:message-type-receive-from-partners.adoc[Receive from Partners Message Type Settings]
* xref:message-type-send-to-partners.adoc[Send to Partners Message Type Settings]
* xref:message-type-target-at-host.adoc[Target at Host Message Type Settings]
* xref:message-type-source-at-host.adoc[Source at Host Message Type Settings]

After you create Receive from Partner and Source at Host message types, you can add up to five custom message attributes to them. For information, see xref:use-custom-attributes.adoc[Using Custom Message Attributes with Message Types].

== Create a Message Type by Using the Message Flow Wizard

To create a message type by using the Message Flow Wizard, see xref:create-inbound-message-flow.adoc[Create Inbound Message Flows] and xref:create-outbound-message-flow.adoc[Create Outbound Message Flows].

== See Also

* xref:modify-message-type-settings.adoc[Modifying Message Type Settings]
* xref:delete-message-types.adoc[Deleting Message Types]
