= Creating Message Types

You can create new message types from the *<host>* page or by using the Message Flow wizard.

== Create a Message Type from the Host Page

To create a message type from the *<host>* page:

. In the navigation menu, select *<host-name>*.
. From the *Message types* section, click *New*.
. In the *Usage* drop-down list, select the message usage.
. Add values to the remaining settings.
+
For setting descriptions, see the topic that corresponds to the message type usage:

* xref:message-type-receive-from-partners.adoc[Receive from Partners Message Type Settings]
* xref:message-type-send-to-partners.adoc[Send to Partners Message Type Settings]
* xref:message-type-target-at-host.adoc[Target at Host Message Type Settings]
* xref:message-type-source-at-host.adoc[Source at Host Message Type Settings]

+
. Optionally add up to five custom message attributes to a Receive from Partners or Source at Host message type:

.. When you complete the fields on the *New Message type* window, in the *Custom attributes* field, select a DataWeave map that defines the custom attributes.
.. Click *New Message Attribute*.
.. Enter the attribute alias and label.
+
These values must be unique for the environment.
+
.. To make the attribute searchable on the Activity window, select the *Is searchable* checkbox.
+
.. Repeat these steps for each new attribute you want to define.
. Click *Save*.
+
The message type appears in the *Message types* section on the host page.

== Create a Message Type from the Message Flow Wizard

To create a message type from the Message Flow Wizard, see xref:create-inbound-message-flow.adoc[Create Inbound Message Flows] and xref:create-outbound-message-flow.adoc[Create Outbound Message Flows].

== Create a Reference Map for a Message Type

When you create a new message type, you must associate it with a DataWeave map if you want to track specific payload values:

* The input of the map is the payload that follows the schema uploaded in the definition for the message type.
* The output of the map contains the following fields:

* `partnerReferenceId`
+
Required identifier that uniquely identifies the receiving partner.
+
* `hostReferenceId`
+
Required if the backend app sends outbound transactions on behalf of different internal business units that require different mapping or sender identifiers on the EDI data.
+
* `businessDocumentKey`
+
Optional key reference value, such as the order number or invoice number.
+
* Custom attributes, if the associated message type has custom attributes defined.

For example, the following map transforms the XML payload from a backend application. In this example:

* `partnerReferenceId` is set to the payload's `ReceiverID` value,`MYTHICAL`.
* `SenderID` is set to the payload's `LineOfBusiness` value, `NTORetail`.
* `BusinessDocumentKey` is set to the payload's `BusinessKey` value, `ORD-002-000`.
* The `PO Number` custom attribute is set to the payload's `purchaseOrder` value, `ORD-002-000`.
* The `Invoice Number` custom attribute is set to the payload's `invoiceNumber` value, `INV3423872`.

----
%dw 2.0
output application/json
---
{partnerReferenceId: payload.B2BMessage.Header.ReceiverID,
hostReferenceId: payload.B2BMessage.Header.SenderID,
businessDocumentKey: payload.B2BMessage.Header.BusinessKey,
"attributes":[
  {label: "PO Number",
  values: payload.B2BMessage.purchaseOrder},
  {label: "Invoice Number",
  values: payload.B2BMessage.invoiceNumber}
  ]
}
----

Generated output:

----
{
"partnerReferenceId": "Mythical",
"hostReferenceId": "NTORetail",
"businessDocumentKey": "ORD-002-000",
"attributes":[
  {
	"label": "Purchase Order",
  "values": "ORD-002-000"
	},
	{
	"label":"Invoice Number"
	"values": INV3423872"
	}
]
}
----




== See Also

* xref:delete-message-types.adoc[Deleting Message Types]
* xref:create-outbound-message-flow.adoc[Creating Outbound Message Flows]
* xref:configure-message-flows.adoc[Creating Inbound Message Flows]
