= Translation Maps

Anypoint Partner Manager uses Dataweave maps to transform business transactions between your partner’s message formats (EDIFACT or X12) and your organization’s enterprise application message formats (CSV, JSON, or XML).

Use Anypoint Connector for X12 or Anypoint Connector for EDIFACT with DataWeave 2.x to:

* Create translation maps in Anypoint Studio. (*Vijay, the sentence about using the connectors was in this original topic, but I'm not sure if it belongs here.*)

* Import the maps to Partner Manager when you configure inbound and outbound message flows.

To start with an example of a translation map, download and then customize the xref:https://anypoint.mulesoft.com/exchange/com.mulesoft.muleesb.modules/b2b-order-to-cash-mapping/minor/1.0/ [B2B/EDI Order to Cash - Mapping Example] from Exchange. This example inludes the following transformations for inbound flows:

* X12 4010 850 to JSON
* EDIFACT D97A to JSON
* XML to JSON

*Vijay. Maybe you should include an outbound flow in this example.*

To customize this example:

. Open the `.jar` file in Studio.
. Change the source message type.
. Change the target message type.
. Map the input to the output.
. Test the map locally.
. Import the map to a Partner Manager message flow.

== Open the .jar File in Studio

To open the `.jar` file:

. Launch Studio.
. From the *File* menu, select *Import > Packaged mule application (.jar)* and click *Next*.
. Select the downloaded `.jar` file and click *Open*.
. Click *Finish*.

== Change the Source Message Type

To change the message type:

. Click the *Global Elements* tab at the base of the Studio canvas.
. From *Global Configuration Elements*, select `X12 EDI Config` for a map to use in an inbound message flow or `xxx` for a map to use in an outbound message flow.
. Click *Edit*.
. In *Name*, change the name of the configuration to something meaningful.
. If the message flow uses the EDI, JSON, X12, or XML format:
.. In *Schema definitions*, select *Edit inline*.
.. In *Value*, enter the version and transaction set that you want to map to or from. 
+

For example, set *Value* to `/x12/00501/837.esl` to map to or from a `0051-837` transaction. (*Vijay, is this a realistic example?*)
. Click *OK*.

== Change the Target Message Type

To change the target message type:

. For all target message types except for CSV, copy the schema file of your target application message type into the `<Project-name>/src/main/resources` folder in the project. *Vijay, what do you do for a CSV file?*
. Select the *Transform Message* component.
+
The new transaction set structure displays in one pane of the Transform Message graphical view, and your application message structure (CSV, JSON, or XML) displays in the other pane of this view.
* Vijay, do you have to enter the message type somewhere here?*
. Map the input fields to the output fields.

== Test the Map Locally

To test the map locally:

. In *Package Explorer*, right-click on the template project, and select *Run > Run as Mule application*.
. Use a REST client to post a message payload to the URL `+http://localhost:8081/x12/in+`. +
The application returns the transformed CSV, JSON, or XML.
. After you verify that the map works correctly, copy the DataWeave map from `src/main/resources/x12/IN-X12-version-transaction-to-applicationmessage.dwl` and rename it to something meaningful, such as `IN-X12-4010-850-to-SAP-purchaseorder.dwl`.

== Import the Map to a Partner Manager Message Flow

When you configure message flows, you can import the `dwl` file to the *Map* section of message flow.

== See Also

* xref:configure-message-flows.adoc[Create Inbound Message Flows]
