= Replaying Inbound Transmissions

Inbound transmissions can fail due to data validation, mapping, or connectivity issues. If a transmission fails after a Partner Manager inbound endpoint secures it, you can replay the transmission. 

You can also replay transmissions that processed successfully. You might want to do this if:

* The translated payload is missing a field. 
+
In this scenario, you can upload a new map and replay the original transmission so that it goes through the updated map.
* The target system or partner that received the original translated payloads lost data due to a system issue and requested that it be resent. 

Replaying a transmission regenerates the source and reprocesses the original transaction as a new transaction. The following rules apply:

* You can replay any transmission that has a status of `Failed` or `Delivered`, except for inbound transmissions that failed AS2 security validation.
* The maximum number of transmission that you can replay in a single request is 100. 
* Partner Manager links replayed transmission instances to the original transmission record.
+
Therefore, a replay of `transmission-1` creates child transmission `transmission_2`. A replay of `transmission_2` creates `transmission_3` and is the same as replaying `transmission_1`.
+
* When an original transmission is replayed. Partner Manager sets its status to `Replaying`. Once the replay action completes, Partner Manager sets its status to `Replayed`.
* Partner Manager processes the transmission payload through the active version of the message flow. Therefore, the new transmission uses the current map and endpoint confifgurations for resolution and routing.
+
If Partner Manager doesn't find an active message flow for the transmission or message, it returns an error. 
+
* Partner Manager doesn't check for duplicate control numbers when it replays inbound transmissions.
* Partner Manager sends acknowledgments for replayed transmissions only if the acknowledgement rules changed in the message flow definition from the previous transmission or if the acknowledgment outcome is different from the previous attempt.

== Replaying Inbound Transmissions from the Transmission List View

You can replay one or more inbound transmissions from the transmissions list view:

. In the navigation menu, select *Activity*.
. In the *Messages* field Select *Transmissions*.
. Locate the transmissions to replay.
. Select the transmissions to replay.
. Click *Replay*.

== Replaying an Inbound Transmission from the Transmission Details View

You can replay an inbound transmission from the transmissions details view:

. In the transmissions list view, locate the transmission to replay.
. Click the transmission to bring up the transmission details view.
. Click *Replay*.

== Viewing a Transmission's Replay History

The replay history for a transmission shows the date for each replay and enables you to 

To view a transmission's replay history:

. In the transmissions list view, locate the transmission for which you want to see the replay history.
. Click the transmission to bring up the transmission details view.
. Click the last replayed transmission to see the following information about all replays for the located transmission:
** ID of the original transmission
** Replay date
** Replay status (a green checkmark for successful relay and a red exclamation point for a failed replay)
. Optionally, click the ID of the original transmission to see...???

== See Also

xref:activity-tracking[]
xref:activity-message-tracking[]