= Configuring Runtime Fabric Deployment Settings

You can deploy Partner Manager runtime applications to an xref:runtime-fabric::index.adoc[Anypoint Runtime Fabric] instance configured in your environment.

== Prerequisites for Deploying to Runtime Fabric

Before you deploy Partner Manager to Runtime Fabric, you must:

* Ensure that you have the required permissions for using Runtime Fabric.
* Create and configure the Runtime Fabric instance into which to deploy Partner Manager services. See xref:runtime-fabric::setting-up-runtime-fabric.adoc[Setting Up Runtime Fabric].
** If you already have an RTF instance, you can use it to deploy Partner Manager runtime applications.
* Configure Persistence Gateway in Runtime Fabric, as described in xref:runtime-fabric::persistence-gateway.adoc[Persistence Gateway].
+
Partner Manager uses a persistent Object Store via Persistence Gateway to store transaction processing information such as EDI control numbers and message routing information, which the Partner Manager runtime applications access.
* Set up an ActiveMQ (JMS) messaging broker and configure the connection settings while configuring the Partner Manager Runtime Fabric deployment settings.
+
Partner Manager uses ActiveMQ to reliably send payloads between different stages when it processes B2B transactions. The Partner Manager deployment service automatically creates the required message queues in your ActiveMQ instance when you deploy message flows.

== Configure Settings for Deploying to Runtime Fabric

To configure settings for deploying Partner Manager to Runtime Fabric, access the business unit and environment for which you want to deploy Partner Manager and then follow these steps:

. From the access management *Configure a Partner Manager environment* window, enter the following general settings:
+
[%header%autowidth.spread]
|===
| Setting | Description | Default 
| Deployment Target Type | Target type for your Partner Manager deployment. Select *Runtime Fabric*. | CloudHub 1.0
| Runtime Fabric | Name of the Runtime Fabric instance to use as your deployment target.  | 
| Runtime Version | Mule runtime engine version to run your Runtime Fabric instance.| 4.6.0
| Min Mule Version override | Minimum Mule runtime version required to deploy the runtime applications.

Configuring the Min Mule version enables you to apply a xref:mule-runtime::feature-flagging.adoc#configure-feature-flags-for-a-mule-application[feature flagging] mechanism for Partner Manager-deployed Mule runtime applications.

If you process cXML messages with <DOCTYPE> tags, you must set the `minMuleVersion` to 4.5.0 or higher. If you're migrating from an earlier version, you must perform end-to-end regression testing on your existing workflows before changing the `minMuleVersion`. a| None

[NOTE]
If you select `None`, Partner Manager defaults to using `4.3.0` as the Min Mule version.

| Anypoint MQ Region | Region where Anypoint MQ is deployed. 
{sp} +
{sp} +
When users replay transmissions when Partner Manager is deployed to Runtime Fabric, Partner Manager sends the associated transmission IDs to an Anypoint MQ queue. The document processing service app running in your Runtime Fabric instance reads the transmission IDs from Anypoint MQ to start reprocessing the transmission within your runtime applications. No transaction payload is processed via Anypoint MQ.  | US East (N. Virginia)
| Enforce deploying replicas across nodes | Whether Runtime Fabric enforces the deployment of Partner Manager application instances across different nodes. | Selected
| Use persistent object store | Whether Partner Manager application instances must use a persistent object store. This value is always selected and you can't modify it. | Selected
|===
+
. Select *Applications* and enter the following application settings:
+
[%header%autowidth.spread]
|===
| Setting |Description | Default
| Application Name Prefix |  Prefix appended to the Partner Manager application names. Maximum length is five characters. | 
| Each B2B endpoint | Reserved CPU space, CPU space limit, and memory capacity for each Partner Manager endpoint. Partner Manager deploys a generic Mule app to the runtime for each endpoint protocol and direction (receive or send) combination. For help with sizing, contact your MuleSoft Account Team. a|

* *Reserved CPU*: 0.08 vCPU
* *CPU Limit*: 0.5 vCPU
* *Memory*: 0.9 GB
| B2B API Replication Service a| Reserved CPU space, CPU space limit, and memory capacity for the Partner Manager B2B API Replication Service. a| 

* *Reserved CPU*: 0.1 vCPU
* *CPU Limit*: 0.5 vCPU
* *Memory*: 1 GB
| B2B Document Processing Service | Reserved CPU space, CPU space limit, and memory capacity for the Partner Manager B2B Document Processing Service. a| 

* *Reserved CPU*: 0.1 vCPU
* *CPU Limit*: 0.5 vCPU
* *Memory*: 1.2 GB
|===
+
. Click *Save*.
. Select *JMS Connection* and enter the JMS connection settings:
+
[%header%autowidth.spread]
|===
| Setting | Description | Default
| JMS Broker URL | URL of the JMS broker.  | 
| Username | Username used to connect to the JMS broker.| 
| Password | Password used to connect to the JMS broker. | 
|===
+
. Click *Save*.

== See Also

xref:deploy-partner-manager.adoc[]
