= Set up the Anypoint Platform for Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Set up Anypoint Partner Manager to be used by different people in your organization, namely - message flow developers, operations managers, and IT managers.
To configure the system, you should be familiar with these concepts before setting up Partner Manager:

* EDI message formats and schemas.

* Digital Certificates such as X.509 certificates in PKCS12 file format for the AS2 transport protocol.

* Configuration of protcols such as AS2, SFTP, and HTTPS.

* The concept of organizations and environments in the Anypoint platform in context to Access Management and Mule Runtime Manager.

* The Mule runtime.

* Dataweave transformations.

== Minimum Requirements

Verify that you have the following software and other requirements.
If you need any of the required entitlements, please contact your MuleSoft account representative.

* Partner Manager related entitlement requirements:

** Anypoint Platform user account with Anypoint Partner Manager entitlement.

** Appropriate roles allocated for users to access Anypoint Partner Manager.
Roles are allocated via the Access Management section in Anypoint Platform.

* License for the following optional connectors:

** AS2 connector.
** X12 connector.



* Partner Manager related technical requirements:

** Mule runtime 4.1.1 or higher. Make sure you have the needed Mule runtime capacity to handle your B2B transaction workload needs. If you are unsure about the Mule runtime capacity you need to handle your B2B transactions, please contact your MuleSoft account representative for assistance.

** A storage solution to store the B2B transmission payloads your send or receive. Storage options can include a Database, Amazon S3, Azure Blob Storage, and so on.

** Anypoint Studio 7.3 or higher.


== Environment Configuration

You'll need to set up and configure your environment before you begin using Partner Manager.
Please refer to Anypoint platform documentation to learn more about https://docs.mulesoft.com/access-management/environments[configuring your Anypoint platform environments].

=== Allocate Partner Manager Roles

There are two Administrator roles for Anypoint Partner Manager: Production and Sandbox.
Both roles have unrestricted access, but one role works in a Production environment and the other works in a Sandbox environment.

* Partner Manager Admin (Production) - Can perform all operations across Partner Manager for all Production environments.

* Partner Manager Admin (Sandbox) - Can perform all operations across Partner Manager for all Sandbox environments.

Once you have your determined role, you need to:

* Verify that you have access to Partner Manager. This means that you must have the required entitlements and have been assigned the `Partner Manager Admin` role in Access Manager for the environment.

* Setup the required Storage API. The storage API needs to be accessible from the Mule Runtime network.


=== Associate Mule Runtimes for Deployment

You need to do the following from Anypoint Runtime Manager.

. Create a server group in Anypoint Runtime Manager and name it: `*B2BServerGroup*`.
All B2B processing Mule apps are deployed to this server group. The steps to setup your server group are in https://docs.mulesoft.com/runtime-manager/server-group-create[Mule Runtime Manager documentation].

IMPORTANT: The server group you setup must use the exact name *B2BServerGroup*. This name is case sensitive.

[start=2]
. For each environment, set up your Runtime by https://docs.mulesoft.com/mule-runtime/4.2/runtime-installation-task[downloading the MuleSoft runtime] and unzipping it.

. Add the parameters mentioned in the following `wrapper.conf` file. You'll need to adjust the memory and heap size configuration numbers indicated in the following parameters for your environment.

TIP: The wrapper.conf file is located at "MULE_HOME/conf/wrapper.conf". MULE_HOME is your environment variable which you set on server, it is the home directory of Mule runtime on the machine, usually on a Linux machine something like ``/opt/{Mule installation}``.
When you reach that location you can find the `wrapper.conf` user conf directory.

[source,xml,linenums]
----

# Increase the MetaSpace
wrapper.java.additional.7=-XX:MetaspaceSize=1256m
wrapper.java.additional.8=-XX:MaxMetaspaceSize=2256m

# Increase JVM Memory
# Initial Java Heap Size (in MB), configure it as needed
wrapper.java.initmemory=2024
# Maximum Java Heap Size (in MB), configure it as needed
wrapper.java.maxmemory=3024

----
[start=4]
. Add the server in Runtime Manager based on the https://docs.mulesoft.com/runtime-manager/servers-create[Mule runtime server information]

. Include the created servers] into the server group `B2BServerGroup`. https://docs.mulesoft.com/runtime-manager/server-group-add[Server group]

. Start the Mule runtime and verify it is active within Anypoint Runtime Manager.

=== Setup the Payload Storage API

Anypoint Partner Manager enables you to connect your own storage solution (such as a database, Amazon S3, Azure Blob Storage, and so on) to store the transmission content such as incoming and outgoing B2B message payloads.
You'll need to establish an API that provides Anypoint Partner Manager with a standardized way to connect to your unique storage.
The follow the steps explain how to setup the Payload Storage API:

. Download the pre-packaged API specification (in RAML) and sample implementation template from Anypoint Exchange.
Install this API on a Mule runtime that can access the storage solution.**[MISSING INFO - link from Anypoint Exchange for the pre-packaged API and integration app from Manik / Pablo]**

. Make a note of the API address configurations - host, port, path and authentication details.
You'll need these details while associating Anypoint Partner Manager to your Payload Storage API. +

NOTE: Your payload storage API must be accessible over the internet via HTTPS. Ensure that the appropriate authentication mechanisms have been implemented to make this happen.

. Once the Payload Storage API is set up on the Mule runtime, open Anypoint Partner Manager, navigate to your organizations profile (Host) page from the left navigation.

 . Select the `Payload storage` section and configure the path to your storage.

You are ready to begin to set up message flows between you and your trading partners.

// == Troubleshooting References

// * https://help.mulesoft.com/s/article/Troubleshooting-wrapper-conf-changes-that-do-not-get-applied[Troubleshooting wrapper.conf changes]

== See Also

* xref:B2B-overview.adoc[Use Anypoint Partner Manager]
* xref:x12-identity-settings.adoc[X12 Settings]

// * xref:create-receive-message-flow.adoc[Create Receive Message Flows]
// * xref:activity-tracking.adoc[Activity Tracking]
