= Set up the Anypoint Platform for Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Set up Anypoint Partner Manager to be used by different people in your organization, namely - message flow developers, operations managers, and IT managers.
To configure the system, you should be familiar with these concepts before setting up Partner Manager:

* EDI message formats and schemas.

* Digital Certificates such as X.509 certificates in PKCS12 file format for the AS2 and HTTPS transport protocols.

* Configuration of protocols such as AS2, SFTP, and HTTPS.

* The concept of organizations and environments in the Anypoint platform in context to Access Management and Mule Runtime Manager.

* The Mule runtime.

* DataWeave transformations.

== Minimum Requirements

Verify that you have the following software and other requirements.
If you need any of the required entitlements, please contact your MuleSoft account representative.

=== Partner Manager related entitlement requirements:

* Anypoint Platform user account with Anypoint Partner Manager entitlement.

* Appropriate roles allocated for users to access Anypoint Partner Manager.
Roles are allocated via the Access Management section in Anypoint Platform.

=== License for the following connectors:

* X12 connector

* AS2 connector (optional)

=== Partner Manager related technical requirements:

* Mule runtime 4.1.1 or higher. Make sure you have the needed Mule runtime capacity to handle your B2B transaction workload needs.
If you are unsure about the Mule runtime capacity you need to handle your B2B transactions, please contact your MuleSoft account representative for assistance.

* A storage solution to store the B2B transmission payloads you send or receive. Storage options can include a Database, Amazon S3, Azure Blob Storage, and so on.

* Anypoint Studio 7.3 or higher.

== Environment Configuration

You'll need to set up and configure your environment before you begin using Partner Manager.
Please refer to Anypoint platform documentation to learn more about https://docs.mulesoft.com/access-management/environments[Configuring your Anypoint platform environments].

=== Allocate Partner Manager Roles

There is one Administrator role name Partner Manager Administrator. Depending on which environment you select, the user will assigned that role within the context of that environment.
Both roles have unrestricted access, but one role works in a Production environment and the other works in a Sandbox environment.

* Verify that you have access to Partner Manager.
This means that you must have the required entitlements and have been assigned the `Partner Manager Administrator` role in Access Manager for the environment.

For example, *Partner Manager > Partner Manager Administrator*: Enables role of Administrator for the environment.

Once you have assigned your role, you need to:

* Setup the required Storage API. The storage API needs to be accessible from the Mule Runtime network.

=== Associate Mule Runtimes for Deployment

You need to do the following from Anypoint Runtime Manager.

. Create a server group in Anypoint Runtime Manager and name it: *B2BServerGroup*.
All B2B processing Mule apps are deployed to this server group. The steps to setup your server group are in https://docs.mulesoft.com/runtime-manager/server-group-create[Create a Server Group (Hybrid)].

IMPORTANT: The server group you setup must use the exact name: *B2BServerGroup*. This name is case sensitive.

[start=2]
. For each environment, set up your Runtime by https://docs.mulesoft.com/mule-runtime/4.2/runtime-installation-task[Downloading the MuleSoft runtime] and unzipping it.

. Add the parameters mentioned in the following `wrapper.conf` file. You'll need to adjust the memory and heap size configuration numbers indicated in the following parameters for your environment.

The wrapper.conf file is located at `$MULE_HOME/conf/wrapper.conf`.
From that location you can locate the `wrapper.conf` user conf directory.

IMPORTANT: These are example values. If you are unsure about the Mule runtime capacity you need to handle your B2B transactions,
please contact your MuleSoft account representative for assistance

[source,xml,linenums]
----

# Increase the MetaSpace.
wrapper.java.additional.7=-XX:MetaspaceSize=1256m
wrapper.java.additional.8=-XX:MaxMetaspaceSize=2256m

# Increase JVM Memory
# Initial Java Heap Size (in MB)
wrapper.java.initmemory=4606
# Maximum Java Heap Size (in MB)
wrapper.java.maxmemory=4606

----
[start=4]
. Add the server in Runtime Manager based on the https://docs.mulesoft.com/runtime-manager/servers-create#create-a-server[Create a Server]

. Include the created servers into the server group you created: *B2BServerGroup*. https://docs.mulesoft.com/runtime-manager/server-group-add[Add Servers to a Group]

. Start the Mule runtime and verify it is active within Anypoint Runtime Manager.

=== Setup the Payload Storage API

Anypoint Partner Manager enables you to connect your own storage solution (such as a database, Amazon S3, Azure Blob Storage, and so on) to store the transmission content such as incoming and outgoing B2B message payloads.
You'll need to establish an API that provides Anypoint Partner Manager with a standardized way to connect to your unique storage.
The follow the steps explain how to setup the Payload Storage API:

. Download the pre-packaged API specification (in RAML) and sample implementation template from Anypoint Exchange.
Install this API on a Mule runtime that can access the storage solution.**[MISSING INFO - link from Anypoint Exchange for the pre-packaged API and integration app from Manik / Pablo]**

. Make a note of the API address configurations (make a note of the following):

** host, port, path connection

** response timeouts

** authentication details: None, API Key, Basic, Client Credentials, OAuth Token

** Certificate (.PEM format) and connection type

[xref] to HTTPS Send Configuration for complete details?

You'll need these details while associating Anypoint Partner Manager to your Payload Storage API. +

NOTE: Your payload storage API must be accessible over the internet via HTTPS.
Ensure that the appropriate authentication mechanisms have been implemented to make this happen.

. Once the Payload Storage API is set up on the Mule runtime, open Anypoint Partner Manager, navigate to your organizations profile (Host) page from the left navigation.

 . Select the `Payload storage` section and configure the path to your storage.

You are ready to begin to set up message flows between you and your trading partners.


// == Troubleshooting References

// * https://help.mulesoft.com/s/article/Troubleshooting-wrapper-conf-changes-that-do-not-get-applied[Troubleshooting wrapper.conf changes]

== See Also

* xref:B2B-overview.adoc[Use Anypoint Partner Manager]
* xref:x12-receive-read-settings.adoc[X12 Settings - Receive from Partner]

// * xref:create-receive-message-flow.adoc[Create Receive Message Flows]
// * xref:activity-tracking.adoc[Activity Tracking]
