= Payload Storage API for Partner Manager

Anypoint Partner Manager enables you to configure your own storage solution, such as database, Amazon S3, Azure Blob Storage, and so on to store transmission content, such as incoming and outgoing B2B message payloads.  

Before you create your first trading partner and message flow, you must configure your Payload Storage API within the Host organization in Partner Manager.

To store your content, you must implement an API that provides Anypoint Partner Manager with a standardized way to connect to your unique storage.

== Download and Deploy the Payload Storage API 

Follow these steps to set up the Payload Storage API:

. Download these APIs from Anypoint Exchange:
+
https://www.mulesoft.com/exchange/com.mulesoft.b2b/partner-manager-content-storage-api[Partner Manager Content Storage API]
+
https://www.mulesoft.com/exchange/com.mulesoft.b2b/partner-manager-content-storage-service-s3[Partner Manager Content Storage API - S3 Template] (sample implementation template)
+
. Implement the API to connect with your choice of storage location (S3, Database, File System, and so on).

. Deploy the API on a runtime that can access the storage solution.

. Make a note of the API URL and configuration values:
* Host, port, and path connection
* Connection Idle and Response timeouts
* Authentication types: 
 ** None
 ** API Key
 ** Basic
 ** Client Credentials
 ** OAuth Token
* Certificate (.PEM format) and connection types
+
You’ll need this information when you associate Anypoint Partner Manager with your Payload Storage API.
Your payload storage API must be accessible over the internet via HTTPS. Ensure that the appropriate authentication mechanisms are implemented to enable access over HTTPS.

== Configure the Payload Storage API

. In Anypoint Platform, open Anypoint Partner Manager. 
. In the navigation menu on the left, select your organization’s profile (host) page.
. In the *Payload storage* section of the page, click *Edit* to add the path to your payload storage.  
. Enter the following values:
* *Endpoint name*
Name for the payload storage API
* *Description*
Optional description for your payload storage
* *URL* +
Path to your payload storage 
. Optionally, if you want to view (or allow your users to view) the raw payloads of the files you receive or send, select *Allow users to download payloads*.
. Click *Save*.




