= Set up the Anypoint Platform for Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Set up Anypoint Partner Manager to be used by different people in your organization, namely - B2B integration developers, operations managers, and IT managers.

== Minimum Requirements

Verify that you have the following software and other requirements.
If you need any of the required entitlements, please contact your MuleSoft account representative.

=== Partner Manager related entitlement requirements:

* Anypoint Platform user account with Anypoint Partner Manager entitlement.

* Appropriate roles allocated for users to access Anypoint Partner Manager.
Roles are allocated via the Access Management section in Anypoint Platform.

=== License for the following connectors:

* X12 connector

* AS2 connector (optional)

=== Partner Manager related technical requirements:

* Mule runtime 4.1.5 or higher. Make sure you have the required Mule runtime capacity to handle your B2B transaction workload needs.
If you are unsure about the Mule runtime capacity required to handle your B2B transactions, contact your MuleSoft account representative for assistance.

* A storage solution to store the B2B transmission payloads you send or receive. Storage options can include a Database, Amazon S3, Azure Blob Storage, and so on.

* Anypoint Studio 7.3 or higher.

== Environment Configuration

Before you begin using Anypoint Partner Manager in Anypoint Platform, you'll need to set up and configure your environment with Partner Manager roles, associated Mule deployment instances, and a payload storage API.
Refer to the Anypoint platform documentation to learn more about https://docs.mulesoft.com/access-management/environments[Configuring your Anypoint platform environments].

=== Allocate Partner Manager Roles

There is one Administrator role called the Partner Manager Administrator. Depending on which environment you select, the user is assigned that role within the context of that environment.
Both roles have unrestricted access, but one role works in a Production environment and the other works in a Sandbox environment.

* Verify that you have access to Partner Manager.
This means that you must have the required entitlements and have been assigned the `Partner Manager Administrator` role in Access Manager for the environment.

For example, *Partner Manager > Partner Manager Administrator*: Enables this role of Administrator for the environment.

=== Associate Mule Runtimes for Deployment

You need to do the following from Anypoint Runtime Manager.

. Create a server group in Anypoint Runtime Manager and name it: *B2BServerGroup*.
All B2B processing Mule apps are deployed to this server group. The steps to setup your server group are in https://docs.mulesoft.com/runtime-manager/server-group-create[Create a Server Group (Hybrid)].

+
IMPORTANT: The server group you setup must use the exact name: *B2BServerGroup*. This name is case sensitive.
+

. For each environment, set up your Runtime by https://docs.mulesoft.com/mule-runtime/4.2/runtime-installation-task[Downloading the MuleSoft runtime] and unzipping it.

. Add the parameters mentioned in the following `wrapper.conf` file. You'll need to adjust the memory and heap size configuration numbers indicated in the following parameters for your environment.
+
The wrapper.conf file is located at `$MULE_HOME/conf/wrapper.conf`.
From that location you can locate the `wrapper.conf` user conf directory.

IMPORTANT: These are example values. If you are unsure about the Mule runtime capacity you need to handle your B2B transactions,
please contact your MuleSoft account representative for assistance.

[source,xml,linenums]
----

# Increase the MetaSpace.
wrapper.java.additional.7=-XX:MetaspaceSize=1256m
wrapper.java.additional.8=-XX:MaxMetaspaceSize=2256m

# Increase JVM Memory
# Initial Java Heap Size (in MB)
wrapper.java.initmemory=4606
# Maximum Java Heap Size (in MB)
wrapper.java.maxmemory=4606

----

. Add the server in Runtime Manager based on the https://docs.mulesoft.com/runtime-manager/servers-create#create-a-server[Create a Server]

. Include the created servers into the server group you created earlier: *B2BServerGroup*. https://docs.mulesoft.com/runtime-manager/server-group-add[Add Servers to a Group]

. Start the Mule runtime and verify it is active within Anypoint Runtime Manager.

=== Setup the Payload Storage API

Anypoint Partner Manager enables you to connect your own storage solution (such as a database, Amazon S3, Azure Blob Storage, and so on) to store the transmission content such as incoming and outgoing B2B message payloads.
To store this content, you must establish an API that provides Anypoint Partner Manager with a standardized way to connect to your unique storage.
Follow these steps to set up the Payload Storage API:

. Download these APIs from Anypoint Exchange:
+
https://anypoint.mulesoft.com/exchange/com.mulesoft.b2b/partner-manager-content-storage-api[Partner Manager Content Storage API]
+
and the sample implementation template, https://anypoint.mulesoft.com/exchange/com.mulesoft.b2b/partner-manager-content-storage-service-s3[Partner Manager Content Storage API - S3 Template]
+
. Install the API on a Mule runtime engine that can access the storage solution.

. Make a note of the API address configurations:

* Host, port, and path connection

* Response timeouts

* Authentication types: None, API Key, Basic, Client Credentials, and OAuth Token

* Certificate (`.PEM` format) and connection type

You'll need this information while associating Anypoint Partner Manager to your Payload Storage API. +

NOTE: Your payload storage API must be accessible over the internet via HTTPS.
Ensure that the appropriate authentication mechanisms have been implemented to make this happen.

. Open Anypoint Partner Manager and locate your organization's profile (host) page from the left navigation.

 . Select the `Payload storage` section and configure the path to your storage.

You are ready to begin to set up message flows between you and your trading partners.


== See Also

* xref:B2B-overview.adoc[Use Anypoint Partner Manager]
* xref:x12-receive-read-settings.adoc[X12 Settings - Receive from Partner]
