= Set up the Anypoint Platform Partner Manager 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Partner Manager can be used by different people in your organization. For example, those that design and test message flows (message flow developers), those who manage activity that is part of production (operations managers), and those who optimize back end services and performance (IT managers).
To configure the system, you should be familiar with these concepts before setting up Partner Manager:


* EDI message formats and schemas.
* Dataweave transformations.
* Digital Certificates such as X.509 certificates in PKCS12 file format for the AS2 transport protocol.
* Configuration of protcols such as AS2, SFTP, HTTPS.
* Understanding of organizations and environments in the context of Access Management and Runtime Manager. 

== Minimum Requirements

Verify that you have the following software and other requirements.

* Mule runtime engine 4.1.1 or higher. Make sure you have the needed Mule runtime Core/Vcore capacity to handle the B2B transaction load. If you are unsure about the capacity you need to handle B2B transactions, please contact your MuleSoft account representative for assistance.

* Storage for your B2B message payloads. 

* Anypoint Studio 7.1 or higher for creating DataWeave maps.

* License for the following optional Connectors:

** AS2 4.0.2 or higher.
** X12 2.0.1 or higher.

* Partner Manager Requirements:
** Anypoint Platform user account with Anypoint Partner Manager access.
** Appropriate roles allocated for users to access Anypoint Partner Manager. Roles are allocated via the Access Management section in Anypoint Platform.

**Note**

For any access or licensing issues, please contact your MuleSoft account representative for assistance.

== Environment Configuration
Set up and configure your before environment using Partner Manager.

=== Allocate Partner Manager Roles

There are two Administrator roles for Anypoint Partner Manager: Production and Sandbox. Both roles have unrestricted access, but one role works in a Production environment and one works in a Sandbox environment.

Partner Manager Admin (Production) - Can perform all operations across Partner Manager for all Production environments.

Partner Manager Admin (Sandbox) - Can perform all operations across Partner Manager for all Sandbox environments.

. Verify that you have access to Partner Manager. 
This means that you must have the required entitlements and have assigned the `Partner Manager Administrator` role in Access Management for the environment.

. Setup the required Storage API (this will be a link to Exchange with description and RAML). The storage API should be reachable from the Mule Runtime network.

=== Associate Runtimes for Deployment (Setup the Environment)

Setup a server group via Anypoint Runtime Manager to deploy the B2B Gateway. The steps to setup your server group are in [Mule Runtime Manager documentation](https://docs.mulesoft.com/runtime-manager/server-group-create).

**Note**

The server group associated to your B2B Gateway must be named exactly **B2BServerGroup** in order for it to operate correctly. The name is case sensitive.

. Create a dedicated user with the `Partner Manager - Runtime Engine` permission for the Runtime Engine. The UI Administrator does not have the required permissions to be used in the Runtime Engine.

. For each Environment, set up your Mule Runtime by downloading Mulesoft runtime and unzipping it.

. Add the following parameters in the wrapper.conf file. You'll need to adjust the numbers for your environment. Refer to the following article from support.mulesoft.com: java.lang.OutOfMemoryError: Metaspace when Deploying Applications to Mule 4 Runtime.

Note: Make sure the ports that are exposed as inbound endpoints are configured in the instance according to the security guidelines for your infrastructure.

[source,xml,linenums]
----

wrapper.java.additional.20=-Db2bAnypointUsername={{username from Step 1}}
wrapper.java.additional.21=-Db2bAnypointPassword={{password from Step 1}}

# Increase the MetaSpace 
wrapper.java.additional.7=-XX:MetaspaceSize=1256m
wrapper.java.additional.8=-XX:MaxMetaspaceSize=2256m

# Increase JVM Memory
# Initial Java Heap Size (in MB), configure it as needed
wrapper.java.initmemory=2024
# Maximum Java Heap Size (in MB), configure it as needed
wrapper.java.maxmemory=3024

----
. Add the server in Runtime Manager (See https://docs.mulesoft.com/runtime-manager/servers-create)
. Create a server group and call it: `B2BServerGroup` in Runtime Manager and include the created server (See https://docs.mulesoft.com/runtime-manager/server-group-about)
. Start Mule runtime and verify it on Runtime Manager.

=== Connect to Payload Storage
 Within Partner Manager host profile, configure the Storage API with the host, port and path from your Storage API implementation
 
Anypoint Partner Manager enables you to connect your own storage (such as a database, Amazon S3, Azure Blob Storage, and so on) to store the transmission content such as incoming and outgoing B2B messages and acknowledgments. You'll need to establish an API that provides Anypoint Partner Manager with a standardized way to connect to your unique storage.

Download the pre-packaged API and implementation template from Anypoint Exchange.[link from Anypoint Exchange for the pre-packaged API and integration app from Manik / Pablo]

Make a note of the API address configurations (host, port, path and authentication details) to use to associate the storage within Anypoint Partner Manager.

Once the API is setup, go to Partner Manager and configure the path to your storage from your Host Partner profile from the left hand section.

Once that's complete, you can begin to set up message flows between you and your configured partners.

== Partner Manager Setup Checklist

Before you set up your message flows to send and receive messages with your partners, you'll need to collect some information from them. You’ll also need to understand how your backend systems work. Use this checklist to help organize the information you need to gather for entering into AnyPoint Partner Manager later.

* Information needed for each trading partner:

** Partner name (usually the name of the company).

** Identifiers (such as the AS2 Identifier, X12 ISA, and so on).

** Message formats to send to one another (such as X12, and so on), and any associated validations with the need for acknowledgment (such as TA1, 997, 999, and so on).

** Message types to use. For example, a purchase order in X12 is an 850 mesage. You also need to know which X12 version to use in your transactions (such as 004010, 005010, and so on).

** The digital certificate (such as X.509).

** Endpoints, depending on the direction of interactions (send/receive) you want to have with your partner.

* Information you'll need as the host organization:

** Endpoints, depending on the direction of interactions with your partner.

** Identifiers (such as the AS2 Identifier, X12 ISA, and so on).

** The digital certificate (such as X.509).

** EDI message type preferences for your organization. [Example?]

** Storage for your B2B message payloads.



== See Also
* xref:create-receive-message-flow.adoc[Create Receive Message Flows]
* xref:activity-tracking.adoc[Activity Tracking]

|===
