= Set up the Anypoint Platform for Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You use Anypoint Partner Manager to set up, manage, and monitor the flow of business messages between you and your business trading partners.
Prior to deploying any message flows from Partner Manager, you need to set up and configure Anypoint Partner Manager for use by team members in your organization.
Typically those who configure, deploy, and monitor B2B Trading Partner profiles and message flows.

== Requirements for Anypoint Partner Manager

* Anypoint Platform user account with Anypoint Partner Manager entitlement.

* Required Mule vCore capacity to handle your B2B transaction workload needs.

If you require assistance, contact your account representative.

License for the following connectors that are used in your B2B message flows based on the protocols and message formats you are using:

* AS2 connector

* X12 connector

Partner Manager-related technical requirements:

* Storage for the B2B transmission payloads you send or receive, such as a database, Amazon S3, Azure Blob Storage, and so on.
For more information, refer to xref:setup-payload-storage-API.adoc[Set up the Payload Storage API for Partner Manager].

* Anypoint Studio 7.4 or later in order to create DataWeave maps for EDI data transformation.

* Mule runtime engine (Mule) 4.2.2 or later (for On-Premises only).

* The Partner Manager Administrator role for all users who need access to B2B message flows in their environment (Production or  Sandbox).

* Keep the default deployment of message flows to CloudHub (for information on CloudHub settings, refer to xref:cloudhub-deploy-options.adoc[CloudHub Deployment Options], or deploy to your own hosted on-premise Mule runtime, by clicking *Stop deploying to CloudHub* and going to  xref:deploy-onpremise.adoc[Deploy On-Premises for Partner Manager]).

== See Also

* xref:B2B-overview.adoc[Use Anypoint Partner Manager]
* xref:troubleshooting.adoc[Troubleshooting Anypoint Partner Manager]
