= Set up the Anypoint Platform for Partner Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Set up Anypoint Partner Manager to be used by different people in your organization: message flow developers, operations managers, and IT managers.
To configure the system, you should be familiar with these concepts before setting up Partner Manager:

* EDI message formats and schemas

* Dataweave transformations

* Digital Certificates such as X.509 certificates in PKCS12 file format for the AS2 transport protocol

* Configuration of protcols such as AS2, SFTP, and HTTPS

* The concept of organizations and environments in the Anypoint platform in context to Access Management and Mule Runtime Manager

== Minimum Requirements

Verify that you have the following software and other requirements:

* Mule runtime engine 4.1.1 or higher. Make sure you have the needed Mule runtime Core/vCore capacity to handle your B2B transaction workload needs

If you are unsure about the capacity you need to handle your B2B transactions, please contact your MuleSoft account representative for assistance.

* A storage solution to store the B2B transmission payloads your send or receive. Storage options can include a Database, Amazon S3, Azure Blob Storage, and so on.

* Anypoint Studio 7.1 or higher to create DataWeave maps

* License for the following optional connectors:

** AS2 4.0.2 or higher.
** X12 2.0.1 or higher.

* Partner Manager Requirements:

** Anypoint Platform user account with Anypoint Partner Manager entitlement.

** Appropriate roles allocated for users to access Anypoint Partner Manager.
Roles are allocated via the Access Management section in Anypoint Platform.

NOTE: To obtain an Anypoint Partner Manager entitlement, please contact your MuleSoft account representative.

== Environment Configuration

You'll need to set up and configure your environment before you begin using Partner Manager.
Please refer to Anypoint platform documentation to learn more about https://docs.mulesoft.com/access-management/environments[configuring your Anypoint platform environments].

=== Allocate Partner Manager Roles

There are two Administrator roles for Anypoint Partner Manager: Production and Sandbox.
Both roles have unrestricted access, but one role works in a Production environment and the other works in a Sandbox environment.

* Partner Manager Admin (Production) - Can perform all operations across Partner Manager for all Production environments.

* Partner Manager Admin (Sandbox) - Can perform all operations across Partner Manager for all Sandbox environments.

. Verify that you have access to Partner Manager.
This means that you must have the required entitlements and have assigned the `Partner Manager Admin` role in Access Management for the environment.

. Setup the required Storage API. The storage API should be accessible from the Mule Runtime network.

=== Associate Mule Runtimes for Deployment

. Create a server group in Anypoint Runtime Manager and call it: `B2BServerGroup`. All B2B processing Mule apps will be deployed to this server group. The steps to setup your server group are in https://docs.mulesoft.com/runtime-manager/server-group-create[Mule Runtime Manager documentation].

NOTE: The server group you setup must have the exact name **B2BServerGroup**. The name is case sensitive.

[start=3]
. For each environment, set up your Runtime by https://docs.mulesoft.com/mule-runtime/4.2/runtime-installation-task[downloading the MuleSoft runtime] and unzipping it.

. Add the parameters mentioned below in the wrapper.conf file. You'll need to adjust the memory and heap size configuration numbers indicated in the parameters below for your environment.

[TIP]
The wrapper.conf file is located at "MULE_HOME/conf/wrapper.conf". MULE_HOME is your environment variable which you set on server, it is the home directory of Mule runtime on the machine, usually on Linux machine something like /opt/{Mule installation}. When you reach that location you can find the wrapper.conf user conf directory.

[source,xml,linenums]
----

wrapper.java.additional.20=-Db2bAnypointUsername={{username from Step 1}}
wrapper.java.additional.21=-Db2bAnypointPassword={{password from Step 1}}

# Increase the MetaSpace
wrapper.java.additional.7=-XX:MetaspaceSize=1256m
wrapper.java.additional.8=-XX:MaxMetaspaceSize=2256m

# Increase JVM Memory
# Initial Java Heap Size (in MB), configure it as needed
wrapper.java.initmemory=2024
# Maximum Java Heap Size (in MB), configure it as needed
wrapper.java.maxmemory=3024

----
[start=5]
. Add the server in Runtime Manager based on the https://docs.mulesoft.com/runtime-manager/servers-create[reference information]
. https://docs.mulesoft.com/runtime-manager/server-group-add[Include the created servers] into the server group B2BServerGroup

. Start Mule runtime and verify it on Anypoint Runtime Manager.

=== Setup the Payload Storage API

Anypoint Partner Manager enables you to connect your own storage solution (such as a database, Amazon S3, Azure Blob Storage, and so on) to store the transmission content such as incoming and outgoing B2B message payloads. You will need to establish an API that provides Anypoint Partner Manager with a standardized way to connect to your unique storage. To setup the Storage API, follow the steps indicated below.

. Download the pre-packaged API and implementation template from Anypoint Exchange. Install this API on a mule runtime that can access the storage solution.**[TODO - link from Anypoint Exchange for the pre-packaged API and integration app from Manik / Pablo]**

. Make a note of the API address configurations (host, port, path and authentication details) associate to your storage API's implementation.

. Once the storage API is set up on the runtime, go to Anypoint Partner Manager, navigate to the host / your organizations profile page from the left-hand section, and configure the path to your storage within the section titled "Payload storage".

Once that's complete, proceed to begin setting up message flows between you and your trading partners.

== Troubleshooting References

* https://help.mulesoft.com/s/article/Troubleshooting-wrapper-conf-changes-that-do-not-get-applied[Troubleshooting wrapper.conf changes]

== See Also

* xref:B2B-overview.adoc[Use Anypoint Partner Manager]

// * xref:create-receive-message-flow.adoc[Create Receive Message Flows]
// * xref:activity-tracking.adoc[Activity Tracking]
