= Anypoint Partner Manager Setup
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



== Setup & Config - Partner Integration Onboarding

This describes the general requirements to set up and use Anypoint Partner Manager.
You should have familiarity with the following concepts:

* EDI Message formats
* Your own network of endpoints for listening to and sending messages
* Schemas
* Edit transformations using Dataweave
* Certificates
* Partner Information

You will need to be able to troubleshoot and diagnose errors produced in these areas and take or recommend corrective actions.
In addition, you should have a working knowledge or AS2, Troubleshooting and Error Correction, Filters, HIPAA (industry specific), Lookups, Promote, TRADACOMS, Transmissions, and X12.

=== Anypoint Partner Manager Workflow High-Level Overview

This is a high-level overview of the workflow for setting up, configuring, and using Anypoint Partner Manager. If you are new to Anypoint Partner Manager, you can read this for further understanding.

. Preparing to Install Anypoint Partner Manager. Overview of the installation/setup process. Includes mention of registering a server group and adding it in Runtime Manager and adding users with roles. +
. Review the system and network requirements. +
Before using Anypoint Partner Manager, you must make decisions about... You must also understand how...
. Business Trading Partner Onboarding. Set yourself up as a host partner, then configure your business trading partners. Then create a message flow between you and your partners. +
. Message Flow Setup. Configure the path a message takes between your backend systems and a partner. Then activate the message flow by deploying it. +
The setup sequence for receiving a message flow are: Receiving partner info > receiving endpoint > source message type > document map > target host.
. Monitor & Track. Once you deploy message flows, monitor and track the transmissions and messages sent between you and your partners. +

=== Pre-Setup Checklist

Before you set up your message flows to send and receive messages with your partners, you'll need to collect information from them. You'll also need to understand how your backend systems work. In preparation, use this checklist before you start.

For each trading partner you'll need the following:
* Name
* Identifiers
* The formats for the messages to send to each other (for example, X12, EDIFACT, XML, and so forth) and the validation and acknowledgment requirements (such as TA1, 997, 999, and so forth).
* What message types to send to one another. For example, a purchase order in X12 is an 850 message type. You'll also need to know which X12 version you'll be using with them.
* Certificate public key (if using AS2)
* If you are sending them messages, you'll also need the endpoints to where you will send them.

As the host, you need information about your organization's systems:
* Your organization's endpoints for receiving messages from partners. The endpoints for routing those messages to your backend systems (Targets) and the endpoints for picking up messages from those systems and sending them to partners (Sources).
* Your organization's EDI message type preferences, if they exist.
* Any identifiers and certificates you use when you send messages to your partners.

=== Setup and Configuration

Verify that you have the following:
* Anypoint Platform Manager user account with Anypoint Partner Manager access
Note to reviewers-How are role assignments for Partner Manager set up?
There will be 2 deployment models to document: (Reviewers, which will be there for Beta?)
- Cloud- a subscription that gets activated. (What about the Hybrid setup?)
- On-prem - will have installation steps.
 Reviewers -Is this true? Be sure you have registered a Server group and added it in Runtime Manager. Name it something applicable such as B2B Server. (The steps to do this are in the Runtime doc: https://docs.mulesoft.com/runtime-manager/server-group-create)

NOTE: If you are unable to access Anypoint Partner Manager, see your MuleSoft account administrator for assistance.

* Anypoint Studio with Mule 4.0 and the following connectors (reviewers please verify the connector versions):

* Transport Protocols
- AS2 v2.1.0
- FTPS v2.0.0
* Message formats
- X12 v1.2.2
* Other
- Object Store v2.1.0? (What is this?)


== Add and Configure Trading Partners

When you log into Partner Manager you see (Screenshot of the Partner Manager window to come):
. 1. Log in. You see the AnyPoint Partner Manager UI. +
NOTE: If your business was set up during the provisioning process, its name is at the top of the Name list on the Partner Page. [Reviewers - What to do if it is not?]
. 2.  Select your environment. Depending on how you are working, you see the Environment you should be using. +
. 3. To add a new partner, select *Partners* from the left-hand navigation and click the *New Partner* button. +
. 4. Add the company and contact information and click *Create Partner*. This is all you need to create a partner. +

To edit settings for an existing trading partner, use the links on the upper left to navigate to the Partners area. From the page for the New Partner you can add:
* Information to help you and your team identify this partner along with contact information in the About: field. The fields are: First Name
-Last Name
-Title
-E-mail
-Office Phone
-Mobile Phone
-Fax
-Country
-Address Line 1
-Address Line 2
-City
-State
-Postal Code

* A certificate public key for receiving messages through AS2.
* Endpoints for sending messages.
* Message types and message flows.

== Create a Message Flow for Messages to Partners

You can set up a Message Flow for Sending and Receiving from a partner.

=== Receive from a Partner

To set up Receive from partner:
. 1. Select Message Flows from the left-hand navigation. +
. 2. Click the *New Message Flow* button and select Receive from partner from the drop-down menu. +
. 3. Associate an existing partner that you created, or click the *New Partner button* to create one. +
. 4. If you are creating one, fill in the receiving endpoint. +
. 5. Select the Source message. +
. 6. Import the Dataweave script for the Map file. +
. 7. Select the Target document type. +
. 8. Click the *Done* button when the setup is complete. +
. 9. Click the *Deploy* to make the flow live. +

== Transports and Exchanges

The EDI format support for X12 via Anypoint Partner Manager.
There is support for transport protocols - AS2, SFTP, FTPS, HTTPS, SMTP, JMS

== Transaction Reporting

[Reviewers-will any of this be there for Beta?]
Audit tracking leveraging core Anypoint platform capabilities
Track high-level B2B operational metrics such as:
# of messages and # of errors (i.e. messages received, versus processed, versus failed).
Message inbound vs. outbound.

|===
