= Download and Deploy a Payload Storage API

Anypoint Partner Manager enables you to configure your own storage solution (for example, a database, Amazon S3, or Azure Blob Storage) to store transmission content.

To use your own storage solution, you must implement an API that provides Anypoint Partner Manager with a standardized way to connect to your storage.

NOTE: The payload storage API must be publicly accessible for users to be able to view payload from Partner Manager’s Activity page.

== Download and Deploy the Payload Storage API

Before you create your first partner and message flow, you must configure your payload storage API within the host organization in Partner Manager:

. Access and download the following APIs from Anypoint Exchange:
* https://www.mulesoft.com/exchange/com.mulesoft.b2b/partner-manager-content-storage-api[Partner Manager Content Storage API]
+
RAML specification for the payload storage API, which includes the URI parameters and record ID (contentRecordId) that must be returned from the API implementation's HTTP response header
+
* https://www.mulesoft.com/exchange/com.mulesoft.b2b/partner-manager-content-storage-service-s3[Partner Manager Content Storage API - S3 Template]
+
Sample template for creating the payload storage API using Amazon S3
+
. xref:general::api-led-develop.adoc[Implement the API] to connect with your choice of storage location; for example, a database, Amazon S3, or filesystem.
. xref:runtime-manager::deployment-strategies.adoc[Deploy the API] on a runtime that can access the storage solution.

. Make a note of the API URL and configuration values:
* Host, port, and path connection
* Connection Idle and Response timeouts
* Authentication types:
 ** None
 ** API Key
 ** Basic
 ** Client Credentials
 ** OAuth Token
* Certificate (`.PEM` format) and connection types
+
You’ll need this information when you associate Anypoint Partner Manager with your payload storage API.
Your payload storage API must be accessible over the internet via HTTPS. Ensure that the appropriate authentication mechanisms are implemented to enable access over HTTPS.


== Add the Payload Storage API to the Host Profile

. In Anypoint Platform, open Anypoint Partner Manager.
. From the navigation menu on the left, select your organization’s host page.
. In the *Payload storage* section of the page, click *Edit* to add the path to your payload storage.
. Enter the following values:
* *Endpoint name*: The name of the payload storage API
* *Description*: The optional description for your payload storage
* *URL*: The path to your payload storage
+
This URL does the following:
+
** Stores payloads when transactions process in the runtime
** Retrieves the payload when you click *View Payload* on the *Transaction Activity* page, unless a payload view URL is configured
+
* *Payload view URL*: (Optional) A secondary payload storage API URL that you can use to view the payload on the *Activity* page if the payload storage API is restricted to your internal network
+
. Optionally, if you want to view (or allow your users to view) the raw payloads of the files you receive or send, select *Allow users to download payloads*.
. Click *Save*.

== See Also

* xref:configure-host.adoc[Configure and Manage a Host Profile]
