= Anypoint Partner Manager Setup
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


This describes the general requirements to set up and use Anypoint Partner Manager.
You should have familiarity with the following concepts:

* EDI Message formats
* Your own network of endpoints for listening to and sending messages
* EDI Message Schemas
* Transformations using Dataweave
* Handling X.509 Certificates _(needed only if using AS2 protocol for transport)_

You will need to have the ability to troubleshoot and diagnose errors produced in these areas and take or recommend corrective actions.

=== Anypoint Partner Manager Workflow

This is a high-level overview of the workflow to configure and use Anypoint Partner Manager. If you are new to Anypoint Partner Manager you can read this for further understanding.

. Preparing to Setup Anypoint Partner Manager - Includes registering a server group and adding it in Anypoint Runtime Manager. Additionally includes details about allocating users with roles. +
. Review the System and Network Requirements - Before using Anypoint Partner Manager, you must make decisions about the URL's that you will use to send and/or receive B2B messages as you interact with your partners. +
. On-Boarding Technical Details of your Partner  - Set up your own organization's configurations and then proceed to configure partners you interact with. A partner can be a purchaser, a supplier, or reseller. Subsequently, create a message flow between you and your partners to enable B2B transactions. +
. Configure Message Flows - Configure the path a B2B message takes between your backend systems and a partner. Then activate the message flow by deploying it. +
. Monitor Activity - Once you deploy message flows, monitor and track the transmission of messages sent between you and your partners. +


=== Minimum Requirements

Verify that you have the following:

- Anypoint Platform user account with Anypoint Partner Manager access
{NOT FOR BETA} - Appropriate roles allocated for users to access Anypoint Partner Manager. Roles are allocated via 'Access Management' in Anypoint Platform.

NOTE: If you are unable to access Anypoint Partner Manager, please contact your MuleSoft representative for assistance.

* Minimum Software Requirements
- Mule runtime 4.1.1 or higher.
- Anypoint Studio 7.1 or higher
- The latest versions of the following connectors, as applicable to your use case:
** Transport Protocols
*** AS2 - minimum verison 4.0.2
*** SFTP - minimum verison 1.2.4
** Message formats
*** X12 - minimum verison 2.0.1
- Other
** Object Store v2

* If your Mule runtimes are not on CloudHub, setup a server group with the name "B2BServerGroup" (name is case sensitive). The steps to setup your server group are in the Runtime doc: https://docs.mulesoft.com/runtime-manager/server-group-create.


=== Setup Checklist

Before you set up your message flows to send and receive messages with your partners, you'll need to collect information from them. You'll also need to understand how your backend systems work. In preparation, use this checklist before you start.

For each trading partner you'll need the following:

* Name of the Partner.
* Identifiers (such as AS2 Identifier, X12 ISA, EDIFACT UNB, and so forth).
* Formats for the messages to send to each other (such as X12, EDIFACT, XML, and so forth), the associated validations and the need for acknowledgment (such as TA1, 997, 999, and so forth).
* Identify the message types to use. For example, a purchase order in X12 is a 850 mesage. Following the example, you will also need to know which X12 version you'll be using in your transactions (such as 004010, 005010, and so forth).
* X.509 Certificate _(needed only if using AS2 protocol for transport)_.
* You will also need endpoints depending on the direction of interactions with your partner.

As the host, you need the following information about your organization:

* Your organization's endpoints to receive messages from partners. The endpoints for routing those messages to your backend systems. Similarly, you will need the endpoints to pick up messages from your backend systems, to send them to partners.
* Your organization's EDI message type preferences.
* Any identifiers and certificates you need to use.
* A store for your B2B message payloads. Anypoint Partner Manager enables you to connect your own storage (such as a database, Amazon S3, Azure Blob Storage, and so forth). To connect to your storage, you will need to establish an API that cna be registered with Anypoint Partner Manager to connect to the storage.

== Getting Started with Partner Onboarding

=== Add and Configure Trading Partners

When you log into Anypoint Partner Manager you see (Screenshot of the Partner Manager window to come):

. Log in. You see the AnyPoint Partner Manager UI. +

NOTE: If your business was set up during the provisioning process, its name is at the top of the Name list on the Partner Page.

. Select your environment. Depending on how you are working, you see the Environment you should be using. +

NOTE: Please do not use the 'Design' environment.

. To add a new partner, select *Partners* from the left-hand navigation and click the *New Partner* button. +
. Add the 'Partner Name' and at least one identifier and click *Create Partner*. This is all you need to create a new partner. +

To edit settings for an existing trading partner, use the links on the upper left to navigate to the 'Partners' tab. From the page for the specific Partner, you can add information to help you and your team identify this partner along with contact information in the About: field. The information that can be made available here includes:

* Partner's Name,
* Description of the Partner
* A Logo for the Partner via a png or svg file

_**Note to Maria** - Please add an image of the Partners details here_

* A Corporate Address that includes - Street Name and Number, City, State, Country, and Postal Code

_**Note to Maria** - Please add an image of the address section here_

* Contacts that includes:
** Contact's Name
** Type of Contact - Business Contact, Technical Contact, or Other Contact
** Email Id of the Contact
** Phone number of the Contact

NOTE: Up to 3 contacts can be added.

_**Note to Maria** - Please add an image of the contacts section here_

* A certificate public key for receiving messages through AS2.
* Endpoints for sending messages.
* Message types and message flows.

=== Create a Message Flow for Messages to Partners

You can set up a Message Flow for Sending and Receiving from a partner.

==== Receive from a Partner

To set up Receive from partner:

. Select Message Flows from the left-hand navigation. +
. Click the *New Message Flow* button and select Receive from partner from the drop-down menu. +
. Associate an existing partner that you created, or click the *New Partner button* to create one. +
. If you are creating one, fill in the receiving endpoint. +
. Select the Source message. +
. Import the Dataweave script for the Map file. +
. Select the Target document type. +
. Click the *Done* button when the setup is complete. +
. Click the *Deploy* to make the flow live. +

== Transports and Exchanges

The EDI format support for X12 via Anypoint Partner Manager.
There is support for transport protocols - AS2, SFTP, HTTPS

== Transaction Reporting

[Reviewers-will any of this be there for Beta?]
Audit tracking leveraging core Anypoint platform capabilities
Track high-level B2B operational metrics such as:
# of messages and # of errors (i.e. messages received, versus processed, versus failed).
Message inbound vs. outbound.

|===
