= Anypoint Partner Manager Setup
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


This page describes the general requirements to set up and use Anypoint Partner Manager. You should have familiarity with the following concepts:

* EDI message formats
* EDI message schemas
* Transformations using Dataweave
* Handling X.509 Certificates _(needed only if using AS2 transport protocol)_
* Your own network of endpoints for listening to and sending messages

You will need to have the ability to troubleshoot and diagnose errors produced in these areas and take or recommend corrective actions.

=== Anypoint Partner Manager Workflow

**SECTION NEEDS TO BE MOVED ELSEWHERE**

Below, find a high-level overview of the workflow to configure and use Anypoint Partner Manager.

. Preparing to Setup Anypoint Partner Manager - Includes registering a server group and adding it in Anypoint Runtime Manager. Additionally includes details about allocating users with roles. +
. Review the System and Network Requirements - Before using Anypoint Partner Manager, you must make decisions about the URL's that you will use to send and/or receive B2B messages as you interact with your partners. +
. On-Boarding Technical Details of your Partner  - Set up your own organization's configurations and then proceed to configure partners you interact with. A partner can be a purchaser, a supplier, or reseller. Subsequently, create a message flow between you and your partners to enable B2B transactions. +
. Configure Message Flows - Configure the path a B2B message takes between your backend systems and a partner. Then activate the message flow by deploying it. +
. Monitor Activity - Once you deploy message flows, monitor and track the transmission of messages sent between you and your partners. +


=== Minimum Requirements

Verify that you have the following:

- Anypoint Platform user account with Anypoint Partner Manager access {_**NOT FOR BETA**_}
- Appropriate roles allocated for users to access Anypoint Partner Manager. Roles are allocated via the 'Access Management' section in Anypoint Platform.

_**Note to Maria** - Please add an image of the landing page of Anypoint Platform page that shows Partner Manager_

NOTE: If you are unable to access Anypoint Partner Manager, please contact your MuleSoft representative for assistance.

* Minimum Software Requirements
- Mule runtime 4.1.1 or higher.
- Anypoint Studio 7.1 or higher.
- The latest versions of the following connectors, as applicable to your use case:
** Transport Protocols.
*** AS2 - minimum connector version 4.0.2.
*** SFTP - minimum connector version 1.2.4.
** Message formats.
*** X12 - minimum connector version 2.0.1.

* You need to designate runtimes to deploy the B2B Gateway i.e. the Mule application that processes your B2B transactions. 

NOTE: Please ensure you have the needed runtime capacity to handle your B2B transaction load. If you are not sure about the capacity you need to handle your B2B transactions, please contact your MuleSoft representative.

* A storage to persist your B2B message payloads.

=== Setup Checklist

Before you set up your message flows to send and receive messages with your partners, you'll need to collect information from them. You'll also need to understand how your backend systems work. In preparation, use this checklist before you start.

For each trading partner you'll need the following:

* Name of the Partner.
* Identifiers (such as AS2 Identifier, X12 ISA, EDIFACT UNB, and so forth).
* Formats for the messages to send to each other (such as X12, EDIFACT, XML, and so forth), the associated validations and the need for acknowledgment (such as TA1, 997, 999, and so forth).
* Identify the message types to use. For example, a purchase order in X12 is a 850 mesage. Following the example, you will also need to know which X12 version you'll be using in your transactions (such as 004010, 005010, and so forth).
* X.509 Certificate _(needed only if using AS2 protocol for transport)_.
* You will also need endpoints depending on the direction of interactions with your partner.

As the host, you need the following information about your organization:

* Your organization's endpoints to receive messages from partners. The endpoints for routing those messages to your backend systems. Similarly, you will need the endpoints to pick up messages from your backend systems, to send them to partners.
* Your organization's EDI message type preferences.
* Any identifiers and certificates you need to use.
* Your storage information to persist the B2B payloads.

== Getting Started with Anypoint Partner Manager

Anypoint Partner Manager makes it easy to send and receive B2B messages with your trading partners. There are three main steps required to get started using the application:

- Configure your Profile
- Configure Trading Partners
- Associate Runtimes for Deployment
- Allocate Partner Manager Roles

_**Maria** - Please link the bullet points above to the section headers that follow below_

=== Configure your Profile

The first thing that you'll want to do is to configure your own profile. Your profile defines important information used to identify you with your partners. Select the tab with your organizations name from the left-hand side menu to get started configuring your profile.

The Profile selection contains everything that is relevant to your identity in a B2B exchange. It also contains global settings that can be used across several B2B message flows. There are a number of settings available for various configurations, however, the majority are optional. To get started you will need to specify the following:

- **Identifiers** - Specify one or more identifiers that identify your organization during B2B exchanges. Identifiers are information that you will give your trading partner when exchanging profile information. Your partners will use this value to load the settings for your profile, so they can process your requests. Examples of identifiers for your organizations include:
** AS2 Identifier - the value that you set here will be sent in the headers of AS2 transmissions that you initiate
** X12 ISA - the value that you set here will be sent in the Interchange header of X12 messages that you initiate
** X12 GS - the value that you set here will be sent in the Group header of X12 messages that you initiate


- **Certificates** - Certificates are needed when using the AS2 protocol. The certificate your provide here signs outgoing messages to your partners and decrypts incoming transmissions. The AS2 port uses a private key certificate in PKCS#12 format (that is, a .pfx or .p12 file). To provide your certificate, follow the steps mentioned below:
** Click the *New* button
** In the modal window, click on the *choose file* button
** Upload the private certificate belonging to your organization

NOTE: Your public key certificate is not used by the application. It is used by your partner to encrypt messages to you.

- **Payload Storage** - Anypoint Partner Manager enables you to connect your own storage (such as a database, Amazon S3, Azure Blob Storage, and so forth) to store the incoming B2B message payload. To connect to your storage, you will need to establish an API that provides Anypoint Partner Manager with a standardized way to connect to your unique storage. 

Steps to setup the API are mentioned below:

* Download the pre-packaged API and integration implementation from Anypoint Exchange.
* Deploy the Mule app on your runtime.
* Note down the API address configurations (host, port, path, and so forth) that you will use later to associate the storage within Anypoint Partner Manager.

_**Note to Maria** - Please obtain the link from Anypoint Exchange for the pre-packaged API and integration app from Manik / Pablo_

Once the API is setup, navigate back to your organization's profile and navigate to the **Payload Storage** section

* Click the Edit button
* Provide the following details based on the API configuration you setup earlier - Host, Port, Path. Defaults for the Connection timeout and Response timeout can be modified, per your needs
* Configure the authentication needed to access the API. The options include - Non, Basic Authentication, OAuth Token, Client Credentials, and API Key


=== Add and Configure Trading Partners

. When you log into Anypoint Platform and navigate to Anypoint Partner Manager you see related UI.(Screenshot of the Partner Manager window to come): +

NOTE: If your business was set up during the provisioning process, its name is at the top of the Name list on the Partner Page._**Maria - not sure what this line means**_

. Select your execution *environment* from the top left. You will use Partner Manager in the chosen Environment. +

NOTE: Please do not use the 'Design' environment.

. To add a new partner, select *Partners* from the left-hand navigation and click the *New Partner* button. +
. Add the 'Partner Name' and at least one identifier and click *Create Partner*. This is all you need to create a new partner. +

To edit settings for an existing trading partner, use the links on the upper left to navigate to the *Partners* tab. From the page for the specific Partner, you can add detailed information related to the partner. The information that can be made available here includes:

* Partner's Name.
* Description of the Partner.
* A Logo for the Partner via a png or svg file.

_**Note to Maria** - Please add an image of the Partners details here_

* A Corporate Address that includes - Street Name and Number, City, State, Country, and Postal Code.

_**Note to Maria** - Please add an image of the address section here_

* Contacts that include:
** Contact's Name
** Type of Contact - Business Contact, Technical Contact, or Other Contact
** Email Id of the Contact
** Phone number of the Contact

NOTE: Up to three contacts can be added.

_**Note to Maria** - Please add an image of the contacts section here_

* Add more *Identifiers* or edit previously added Identifiers.
* Add a *Certificate* associated to your use of the AS2 protocol.


=== Associating Runtimes

If your Mule runtimes are not on CloudHub, setup a server group via Anypoint Runtime Manager. The steps to setup your server group are in [Runtime Manager documentation](https://docs.mulesoft.com/runtime-manager/server-group-create).

NOTE: The server group associated to your B2B Gateway need to be named "B2BServerGroup" (the name is case sensitive).


=== Allocate Partner Manager Roles {_**NOT FOR BETA**_}

_**Maria** - please use the details in the document linked for the B2B roles ==> https://docs.google.com/document/d/1KgCPD2U51VnlkiWvBqzRyIJ8X8r5b41o1RTidtaqfYE/edit?usp=sharing _}



- [Create and Deploy a Message Flow](https://github.com/mulesoft/docs-partner-manager/blob/docs-4446-beta-docs-review/modules/ROOT/pages/setup.adoc#create-a-message-flow)
- View Activities

=== Create and Deploy a Message Flow

You can set up a Message Flow for Sending and Receiving from a partner.

==== Receive from a Partner

To set up Receive from partner:

. Select Message Flows from the left-hand navigation. +
. Click the *New Message Flow* button and select Receive from partner from the drop-down menu. +
. Associate an existing partner that you created, or click the *New Partner button* to create one. +
. If you are creating one, fill in the receiving endpoint. +
. Select the Source message. +
. Import the Dataweave script for the Map file. +
. Select the Target document type. +
. Click the *Done* button when the setup is complete. +
. Click the *Deploy* to make the flow live. +

== Transports and Exchanges

The EDI format support for X12 via Anypoint Partner Manager.
There is support for transport protocols - AS2, SFTP, HTTPS

== Transaction Reporting

[Reviewers-will any of this be there for Beta?]
Audit tracking leveraging core Anypoint platform capabilities
Track high-level B2B operational metrics such as:
# of messages and # of errors (i.e. messages received, versus processed, versus failed).
Message inbound vs. outbound.

|===
