= Transmissions View
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::partial$include-v1-eol.adoc[]


== Content Area

Each row has 6 columns:

From:: Who the transmission came from
To:: Who it was sent to
Date:: Date and time at which the event occurred
Direction:: Either *Inbound* or *Outbound*
Transmission Type:: What it was sent over
Label:: Any label associated with the transmission

== Detail Pane

* Contains information about the transmission
* The Message payload is viewable through a link provided
* All IDs can be copied through the copy button to the right of it

== Filters

Direction:: Inbound or Outbound
Partner:: Pick the partner associated with the transmission
File Name:: Enter in part or all of a file name
Transport:: Pick the transport the transmission was sent over

Date::
* Today
* Past 48 Hours
* This Week
* This Month

From:: Select a date from calendar; only errors that occurred after that date will appear.
To:: Select a date from calendar; only errors that occurred before that date will appear.

=== To show all transmissions

Click *Clear filters*.

== Top Bar

* A *Transaction* button will appear when a transmission is selected
** This will take you to the *Transaction* view and highlight this specific transmission