= Partner Manager 2.0 Troubleshooting

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

//Titles of troubleshooting topics must indicate a description about the issue, for example, "Monthly payroll not generating". All or a part of the actual displayed message must be included in the title.

//Include an introduction to explain what the error is about, for example, when you <do this>, you receive <this output> and <this> happens.
// Try to include as much information as possible about how the error is generated, and where it is generated. Provide tha actual error string, if possible. If the error is generated in a particular component of the product, clearly mention that as well.


= Unsuccessful Message Flow Deployment Error
You’ve set up your message flow and clicked Deploy. You may receive an error notification indicating that your deployment is unsuccessful.

== Cause

//<In this section, include information about what causes this issue, if possible. Remember to make the title plural if there are more than one causes listed.>
Any of the following can produce this type of error:

* You do not have the appropriate server group configured or have the wrong name for the server group. Check Verify Server Group Setup.
* Your runtime servers are either not set up, or are not active. Check Verify Runtime Server Setup.
* Your payload storage is not set up. Check Verify Payload Storage Setup.

== Solutions

If you encounter these situations then please review the following to resolve your issue.

=== Verify Server Group Setup

Verify that your `B2BServerGroup` is active.

. From the Anypoint platform, select Anypoint Runtime Manager and select your environment.
. Click Servers from the left navigation.
. Verify that you have a server group named `B2BServerGroup` and that is shows should have the status: Running.

If you do not have this server group set up, refer to https://docs.mulesoft.com/partner-manager/2.0/setup#associate-mule-runtimes-for-deployment[Associate Mule Runtimes for Deployment].

If you see any status other Running, refer to https://docs.mulesoft.com/runtime-manager/servers-actions[Shut down, Delete, or Restart Servers (Hybrid)].

=== Verify Runtime Server Setup

If your B2BServerGroup is in a Running state, then verify your runtime server.

. From the Anypoint platform, select Anypoint Runtime Manager and select your environment.
. Click *Servers* from the left navigation.
. Click `B2BServerGroup`.
. Within the server group, check for Mule runtime with status Running.

If you see any status other Running, refer to https://docs.mulesoft.com/runtime-manager/servers-actions[Shut down, Delete, or Restart Servers (Hybrid)].
If you do not see a server within the server group, it means that you do not have a Mule runtime server setup to process your B2B integrations and you should set up a runtime server by referring to https://docs.mulesoft.com/partner-manager/2.0/setup#associate-mule-runtimes-for-deployment[Associate Mule Runtimes for Deployment]

=== Verify Payload Storage Setup

 Verify that your `Payload Storage` is active.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select your <Hostname> profile.
. Scroll down to the `Payload storage` section and click *Edit*.
. Review your payload storage configuration, and if it is not configured, refer to https://docs.mulesoft.com/partner-manager/2.0/setup#setup-the-payload-storage-api[Set up the Payload Storage API].
. If your payload storage is already configured, you can leverage the configuration via a simple test request (use a browser extension such as Postman on Google Chrome) to the configured payload storage endpoint.

If all these scenarios have been verified successfully, and you still cannot deploy message flows, please raise a case on MuleSoft’s customer portal.


//<Include information about how to fix the issue only; no other explanation that belongs in the intro or Cause section.> 


= Cannot process B2B transactions successfully

You are performing tests on the flow or when your partner sends you B2B messages and you determine that the transactions are not getting processed.

== Causes


== Solutions

=== Verify Flow configurations

Verify your message flow configuration to ensure it matches the configuration per your partner.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select your <Hostname> profile.
. Select *Message Flows*.
. Search for your message flow by the partner name or the message type such as 850.
. Once you locate the message flow, click on the message flow card to open it up.
. From the Message flow configurator, verify the following information per your agreement with your trading partner:

** The correct identifiers are associated with the trading partner.

** The appropriate receive endpoint is configured in the flow.

** The appropriate document type (such as X12, version - 4010, message type - 850) is configured.

** Verify that you have the appropriate acknowledgment configuration.

** Verify that you have an appropriate DataWeave map in the transformation section.

** Verify that you have configured an appropriate target such as both the message type of the target and the associated endpoint configuration.

If all of these look good, then ensure that the last deployment for this flow was successful by viewing the latest deployment history on the right side of the flow.
If you observe a Failed status, try to deploy the message flow to ensure all your configurations have persisted on the Mule runtime apps.

NOTE - it can take a maximum interval of 5 minutes for your most recent changes to be effective on the runtime B2B Mule apps.

Verify B2B integration apps
Verify that your B2B integration apps are active.

From the Anypoint platform, select Anypoint Runtime Manager and *Applications*.
Verify that the B2B apps on the Mule Runtime are active by looking for a status of `started`. The list of apps includes:

APIReplicationService
DocumentProcessingService
One or more inbound apps. The names of these apps are prefaced with inbound-
One or more outbound apps. The names of these apps are prefaced with outbound-
There may be one or more acknowledgment apps. The names of these apps are prefaced with ack-

If any of the B2B integration apps do not have a started status, from the Anypoint platform, select Anypoint Runtime Manager and *Applications*.
For each app that does not have started status, select its row in the table and select *Restart* from the drop-down menu in the upper right of the status area in the information panel.
If restarting the app does not help you recover the application, select its row in the table and select *Delete* from the drop-down menu in the upper right of the status area in the information panel and confirm the deletion.
Navigate back to the message flow related to the app you just deleted and deploy the message flow.
Consider the following when performing a delete:

If you delete the `DocumentProcessingService` or the `APIReplicationService`, deploying any flow results in the redeployment of those apps.
If you delete any of the inbound and/or outbound and/or ack apps, you have to redeploy the specific flow corresponding to the deleted apps.

If all these scenarios have been verified successfully, and you still cannot deploy message flows, please raise a case on MuleSoft’s customer portal.




== Cause

== Solution

== Cause

== Solution

== Cause

== Solution

== Cause

== Solution

== Cause

== Solution

== Cause

== Solution

== See Also
// Add links to any related errors, if required. You might need to add links about the concept of the component where the error occurs, or perhaps the absence of the requirement which caused the error.
* xref:file-name.adoc[link-text]
//add any pertinent links
