= Resolve Current Issues with Partner Manager 2.0

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Here are several resources you can use when troubleshooting problems Anypoint Partner Manager 2.0.
Some are known issues with workarounds, but you can also glean information from your payloads and by examining log files. For more information on log files, See
https://docs.mulesoft.com/mule-runtime/4.2/logging-and-debugging[Logging and Debugging].

= Unsuccessful Message Flow Deployment Error
You’ve set up your message flow and clicked Deploy. You may receive an error notification indicating that your deployment is unsuccessful.

== Cause

//<In this section, include information about what causes this issue, if possible. Remember to make the title plural if there are more than one causes listed.>
Any of the following can produce this type of error:

* You do not have the appropriate server group configured or have the wrong name for the server group. Check Verify Server Group Setup.
* Your runtime servers are either not set up, or are not active. Check Verify Runtime Server Setup.
* Your payload storage is not set up. Check Verify Payload Storage Setup.

== Solutions

If you encounter these situations then please review the following to resolve your issue.

=== Verify Server Group Setup

Verify that your `B2BServerGroup` is active.

. From the Anypoint platform, select Anypoint Runtime Manager and select your environment.
. Click Servers from the left navigation.
. Verify that you have a server group named `B2BServerGroup` and that is shows should have the status: Running.

If you do not have this server group set up, refer to https://docs.mulesoft.com/partner-manager/2.0/setup#associate-mule-runtimes-for-deployment[Associate Mule Runtimes for Deployment].

If you see any status other Running, refer to https://docs.mulesoft.com/runtime-manager/servers-actions[Shut down, Delete, or Restart Servers (Hybrid)].

=== Verify Runtime Server Setup

If your B2BServerGroup is in a Running state, then verify your runtime server.

. From the Anypoint platform, select Anypoint Runtime Manager and select your environment.
. Click *Servers* from the left navigation.
. Click `B2BServerGroup`.
. Within the server group, check for Mule runtime with status Running.

If you see any status other Running, refer to https://docs.mulesoft.com/runtime-manager/servers-actions[Shut down, Delete, or Restart Servers (Hybrid)].
If you do not see a server within the server group, it means that you do not have a Mule runtime server setup to process your B2B integrations and you should set up a runtime server by referring to https://docs.mulesoft.com/partner-manager/2.0/setup#associate-mule-runtimes-for-deployment[Associate Mule Runtimes for Deployment]

=== Verify Payload Storage Setup

Verify that your `Payload Storage` is active.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select your <Hostname> profile.
. Scroll down to the `Payload storage` section and click *Edit*.
. Review your payload storage configuration, and if it is not configured, refer to https://docs.mulesoft.com/partner-manager/2.0/setup#setup-the-payload-storage-api[Set up the Payload Storage API].
. If your payload storage is already configured, you can leverage the configuration via a simple test request (use a browser extension such as Postman on Google Chrome) to the configured payload storage endpoint.

If all these scenarios have been verified successfully, and you still cannot deploy message flows, please raise a case on MuleSoft’s customer portal.


//<Include information about how to fix the issue only; no other explanation that belongs in the intro or Cause section.> 


= Cannot process B2B transactions successfully

You are performing tests on the flow or when your partner sends you B2B messages and you determine that the transactions are not getting processed.

== Causes


== Solutions

=== Verify Flow configurations

Verify your message flow configuration to ensure it matches the configuration per your partner.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select your <Hostname> profile.
. Select *Message Flows*.
. Search for your message flow by the partner name or the message type such as 850.
. Once you locate the message flow, click on the message flow card to open it up.
. From the Message flow configurator, verify the following information per your agreement with your trading partner:

** The correct identifiers are associated with the trading partner.

** The appropriate receive endpoint is configured in the flow.

** The appropriate document type (such as X12, version - 4010, message type - 850) is configured.

** Verify that you have the appropriate acknowledgment configuration.

** Verify that you have an appropriate DataWeave map in the transformation section.

** Verify that you have configured an appropriate target such as both the message type of the target and the associated endpoint configuration.

+

. If all of these look good, then ensure that the last deployment for this flow was successful by viewing the latest deployment history on the right side of the flow.

. If you observe a Failed status, try to deploy the message flow to ensure all your configurations have persisted on the Mule runtime apps.

NOTE: It can take a maximum interval of 5 minutes for your most recent changes to be effective on the runtime B2B Mule apps.

=== Verify B2B integration apps

Verify that your B2B integration apps are active.

. From the Anypoint platform, select Anypoint Runtime Manager and *Applications*.

. Verify that the B2B apps on the Mule Runtime are active by looking for a status of `started`. The list of apps includes:

** APIReplicationService

** DocumentProcessingService

** One or more inbound apps. The names of these apps are prefaced with inbound-

** One or more outbound apps. The names of these apps are prefaced with outbound-

** There may be one or more acknowledgment apps. The names of these apps are prefaced with ack-

+

. If any of the B2B integration apps do not have a started status, from the Anypoint platform, select Anypoint Runtime Manager and *Applications*.

. For each app that does not have started status, select its row in the table and select *Restart* from the drop-down menu in the upper right of the status area in the information panel.

. If restarting the app does not help you recover the application, select its row in the table and select *Delete* from the drop-down menu in the upper right of the status area in the information panel and confirm the deletion.

. Navigate back to the message flow related to the app you just deleted and deploy the message flow.

Consider the following when performing a delete:

** If you delete the `DocumentProcessingService` or the `APIReplicationService`, deploying any flow results in the redeployment of those apps.

** If you delete any of the inbound and/or outbound and/or ack apps, you have to redeploy the specific flow corresponding to the deleted apps.

If all these scenarios have been verified successfully, and you still cannot deploy message flows, please raise a case on MuleSoft’s customer portal.


= In the Anypoint Partner Manager Activity section, I receive a transaction indicating `Unrecognized partner`

Occasionally, in the Activity section of Anypoint Partner Manager, you may see tracking information such as this:

(Screenshot not in this draft)

== Causes

This situation occurs with one of the following:

* Partner Manager cannot identify the sender of the transmission. This is because the partner is not configured in Partner Manager, or because the identifier associated with the partner is not configured.

* Partner Manager cannot identify the host for the transmission. This is because the identifier associated with the host is not configured.

* Partner Manager cannot identify both the partner and the host of this transmission.

== Solutions

=== Verify Partner Identifiers

Verify that your partner has the appropriate identifiers configured as needed to support the transmission.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select *Partners* <name of your specific partner related to this transmission>.

. From the Partners profile, scroll to the Identifiers section and verify that the identifier you are looking for is present in the identifiers listed in the table.

. If the desired partner identifier is not present, click *New* and select an identifier type from the Type drop-down to uniquely identify your partner.

. Provide a value for your identifier (and qualifier for X12-ISA) and click *Create identifier* to save your changes. See xref:x12-identity-settings.adoc[Identifiers] for more info on X12-ISA settings.

=== Verify Organization (Host) Identifiers

Verify that your organization (the host) has the appropriate identifiers configured as needed to support the transmission.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select *Partners* <name of your organizations / sub-organizations related to this transmission>.

. Within the Host’s profile page, scroll to the Identifiers section and verify that the identifier you are looking for is present in the identifiers listed in the table.

. If the desired host identifier is not present, click *New* and select an identifier type from the Type drop-down to uniquely identify your partner.

. Provide a value for your identifier (and qualifier for X12-ISA) and click *Create identifier* to save your changes. See xref:x12-identity-settings.adoc[Identifiers] for more info on X12-ISA settings.

= In the Anypoint Partner Manager Activity section, I receive a transaction indicating `Unrecognized standard`

Occasionally, in the Activity section of Anypoint Partner Manager, you may see tracking information such as this:

(Screenshot not in this draft)

== Cause

This situation occurs when Partner Manager receives a transmission in unsupported data format. For example, receiving a CSV, XML and so forth on receiving endpoints.

== Solution

If you encounter such a scenario, then verify with your partner that they are sending valid X12 format files.


= In the Anypoint Partner Manager Activity section, I receive a transaction indicating `Deployed Message flow configuration not found for Message: <name>`

Occasionally, in the Activity section of Anypoint Partner Manager, you may see tracking information such as this:

(Screenshot not in this draft)

== Causes

This situation occurs in one of these scenarios:

** A transmission is received that contains a message type that is not configured for any partner or flow.

** A transmission is received that contains a message type that is not supported by Anypoint Partner Manager.

== Solution

If you encounter such a scenario, then verify that the message type received via the transmission.

. For the activity that you are viewing, inspect the error message to glean the message type received. It should contain a message identifier string like this: “v004010-810-1548-000000001”. Parts of this message are:

** v004010 - X12 format version received in transmission

** 810 - Message type received

** 1548 - Group Segment Identifier (GS06)

** 000000001 - Message Segment Identifier (ST02)

+

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select *Message Flows*.

. If you know the specific flow you are searching for, click the card related to that flow to expand the associated configurations.

. If you do not know which flow you are looking for, search by partner name or message type (such as 850) to identify possible related message flows.

. Once you find the related message flow, click the message flow card to open up the flow.

. In the Message flow configurator, verify that the appropriate message type (such as X12, version - 4010, message type - 850) is configured and that this matches the type of file that was listed in the Activity which indicated that an unrecognized standard was being used.

. If there is a discrepancy between the type of message configured in the message flow compared to the message received in the activity, then either contact your partner and inform them to send the appropriate file, or correct your message flow to ensure the message type configured matches the expected file you will receive from your partner.

Partner Manager only supports receiving X12 files. If your partner sends you any other type of file such as (JSON, XML, CSV, and so on), contact your partner and ask them to send the appropriate file type to you.

= In the Anypoint Partner Manager Activity section, I see activities with an error message indicating `Failure to store message payload`

Occasionally, in the Activity section of Anypoint Partner Manager, you may see tracking information such as this:

(Screenshot not in this draft)

== Cause

This situation occurs when one of the following occurs:

** The payload storage API on the host’s profile is not appropriately configured.

** The payload storage API is not functioning.

** The storage solution associated to the payload storage API is not functioning.

== Solution

If you encounter such a scenario, then verify the Payload Storage API.

. Verify the appropriate configuration for the payload storage API by a simple test request (use a browser extension such as Postman on Google Chrome).

. To view if the payload storage API is active/functioning, visit Anypoint Runtime Manager to verify if the related payload storage app is active and try restarting the app.

. If the payload storage app is functioning, verify the storage source such as the S3 bucket, or Azure Blob store, or database, and so on that you may be using as the storage solution and ensure that this solution is up and functioning.

If all these scenarios have been verified successfully, and you still cannot deploy message flows, please raise a case on MuleSoft’s customer portal.

= I do not receive TA1 acknowledgments for my transmissions.

Anypoint Partner Manager sends TA1 ack’s back for any received transmission, if configured to do so.

== Cause

In case you are not receiving TA1 configurations, please review the following configuration.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select *Partners* and Receive from <Partner_Name>.

. Scroll to Validation and Acknowledgment settings and click *X12*.

. Within the Acknowledgements section ensure that the option for ‘Send TA1 for each transmission from <partner name>’ is selected.

. Configure the Acknowledgement endpoint as in xref:endpoints.adoc[Endpoints]

. Click *Save* when done.

This enables TA1 acknowledgments for all transmissions received by the specific partner.

= I recently updated and deployed my message flow, however, the configurations haven’t taken effect on the runtime B2B apps. Did I do this incorrectly?

Your runtime B2B Mule apps receive the latest configuration from the Anypoint Partner Manager control plane at a 5 minute interval.
Depending on when you made the configuration changes to your message flows in Partner Manager and deployed them, it can take a maximum interval of 5 minutes for your most recent changes to be effective on the runtime B2B Mule apps.


// == See Also
// Add links to any related errors, if required. You might need to add links about the concept of the component where the error occurs, or perhaps the absence of the requirement which caused the error.
// * xref:file-name.adoc[link-text]
//add any pertinent links
