= In the Anypoint Partner Manager Activity section, I see activities with an error message indicating `Failure to store message payload`

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Occasionally, in the Activity section of Anypoint Partner Manager, you may see tracking information such as this:

[source,xml,linenums]
----
Unrecognized standard from unrecognized partner
Received <date>
File <name>
----

== Causes

This situation occurs when one of the following occurs:

** The payload storage API on the host’s profile is not appropriately configured.

** The payload storage API is not functioning.

** The storage solution associated to the payload storage API is not functioning.

== Solution

If you encounter such a scenario, then verify the Payload Storage API.

. Verify the appropriate configuration for the payload storage API by a simple test request (use a browser extension such as Postman on Google Chrome).

. To view if the payload storage API is active/functioning, visit Anypoint Runtime Manager to verify if the related payload storage app is active and try restarting the app.

. If the payload storage app is functioning, verify the storage source such as the S3 bucket, or Azure Blob store, or database, and so on that you may be using as the storage solution and ensure that this solution is up and functioning.

If all these scenarios have been verified successfully, and you still cannot deploy message flows, please raise a case on MuleSoft’s customer portal.


// == See Also
// Add links to any related errors, if required. You might need to add links about the concept of the component where the error occurs, or perhaps the absence of the requirement which caused the error.
// * xref:file-name.adoc[link-text]
//add any pertinent links
