= Deployed Message flow configuration not found for Message: <name>

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You might occasionally see tracking information such as this in the Activity section of Anypoint Partner Manager:

[source,xml,linenums]
----
X12 from <partner>
Received <date>
File <name>
control #
TA1 sent
----

== Causes

This information appears in the Activity section when one of the following occurs:

** A transmission is received that contains a message type that is not configured for any partner or flow.

** A transmission is received that contains a message type that is not supported by Anypoint Partner Manager.

== Solution

Verify that the message type was received via the transmission:

. For the activity that you are viewing, inspect the message to determine the message type received.
The message should contain a message identifier string like this: `v004010-810-1548-000000001`. Parts of this message are:

** v004010: X12 format version received in a transmission

** 810: Message type received

** 1548: Group Segment Identifier (GS06)

** 000000001: Message Segment Identifier (ST02)

. From within your Anypoint Partner Manager, Sandbox or Production environment select *Message Flows*.

. If you know the specific flow you are searching for, click on the card related to that flow to expand the associated configurations.

. If you do not know which flow you are looking for, search by partner name or message type (such as 850) to identify possible related message flows, and click on the message flow card to open up the flow.

. In the message flow configurator, verify that the appropriate message type (such as X12, version - 4010, message type - 850) is configured and that this matches the type of file that was listed in the Activity that indicated that an unrecognized standard was being used.

. If there is a discrepancy between the type of message configured in the message flow compared to the message received in the activity, then either contact your partner and ask them to send the appropriate file, or correct your message flow to ensure that the message type configured matches the type you expect to receive from your partner.

Partner Manager supports receiving only X12 files. If your partner sends you any other type of file such as (JSON, XML, CSV, and so on), contact your partner and ask them to send the appropriate file type to you.
