= Missing TA1 acknowledgments for my transmissions

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


Anypoint Partner Manager sends TA1 acknowledgments back for any received transmission, if configured to do so. Your trading partner may contact you to tell you that they are not receiving TA1 acknowledgements.

== Cause
Any of the following can lead to this type of error:

. Your trading partners X12 settings are incorrectly configured do not send TA1’s back to the partner.

. The endpoint to which you are sending that TA1’s back may be incorrectly configured.

In case you are not receiving TA1 configurations, please review the following configuration.

. From within your Anypoint Partner Manager environment (either Sandbox or Production) select *Partners* and Receive from <Partner_Name>.

. Scroll to Validation and Acknowledgment settings and click *X12*.

. Within the Acknowledgements section ensure that the option for ‘Send TA1 for each transmission from <partner name>’ is selected.

. Configure the Acknowledgement endpoint as in xref:endpoints.adoc[Endpoints]

. Click *Save* when done.

This enables TA1 acknowledgments for all transmissions received by the specific partner.
