= In the Anypoint Partner Manager Activity section, I receive a transaction indicating `Unrecognized standard from unrecognized partner`

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Occasionally, in the Activity section of Anypoint Partner Manager, you may see tracking information such as this:

[source,xml,linenums]
----
Unrecognized standard from unrecognized partner
Received <date>
File <name>
----

== Cause

This situation occurs when Partner Manager receives a transmission in unsupported data format. For example, receiving a CSV, XML and so forth on receiving endpoints.

== Solution

If you encounter such a scenario, then verify with your partner that they are sending valid X12 format files.



// == See Also
// Add links to any related errors, if required. You might need to add links about the concept of the component where the error occurs, or perhaps the absence of the requirement which caused the error.
// * xref:file-name.adoc[link-text]
//add any pertinent links
