= `Unrecognized standard from unrecognized partner`

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You might occasionally see tracking information such as this in the Activity section of Anypoint Partner Manager:

[source,xml,linenums]
----
Unrecognized standard from unrecognized partner
Received <date>
File <name>
----

== Cause

This information appears in the Activity section when one of the following occurs:

* Partner Manager receives a transmission that is in an unsupported data format. For example, receiving a PDF, image, and so forth on receiving endpoints.

* Your trading partner sends you a valid X12 file but you have not configured a message flow that can accept it.

* You do not recognize the trading partner because they are not set up by you in Anypoint Partner Manager.

== Solution

If you encounter any of these situations, then verify with your partner that they are sending valid X12 format files that align with the message flows you have created and associated to the trading partner.
