= `Unrecognized partner` transaction reported

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You might occasionally see tracking information such as this in the Activity section of Anypoint Partner Manager:

[source,xml,linenums]
----
<identifier> from Unrecognized partner
<date> control #
Partner not found for <identifier> with <value>
----

== Causes

This information appears in the Activity section when one of the following occurs:

* Partner Manager cannot identify the sender of the transmission either because the partner is not configured in Partner Manager, or because the identifier associated with the partner is not configured.

* Partner Manager cannot identify the receiver for the transmission because the identifier associated with the receiver is not configured.

* Partner Manager cannot identify both the sender and the receiver of this transmission.

== Solutions

Verify partner and host identifiers.

=== Verify Partner's Identifiers

Verify that your partner has the appropriate identifiers configured as needed to support the transmission.

. From within your Anypoint Partner Manager, Sandbox or Production environment select *Partners* <name of your specific partner related to this transmission>.

. From the Partners profile, scroll to the Identifiers section and verify that the identifier you are looking for is present in the table.

. If the desired partner identifier is not present, click *New* and select an identifier type from the Type list to uniquely identify your partner.

. Provide a value for your identifier (and a qualifier for X12-ISA) and click *Create identifier* to save your changes. See xref:x12-identity-settings.adoc[] for more information about X12-ISA settings.

=== Verify Organization (Host) Identifiers

Verify that your organization (the host) has the appropriate identifiers configured as needed to support the transmission.

. From within your Anypoint Partner Manager, Sandbox or Production environment select *Partners* <name of your organizations / sub-organizations related to this transmission>.

. Within the Host’s profile page, scroll to the Identifiers section and verify that the identifier you are looking for is present in the table.

. If the desired host identifier is not present, click *New* and select an identifier type from the Type list to uniquely identify your partner.

. Provide a value for your identifier (and a qualifier for X12-ISA) and click *Create identifier* to save your changes. See xref:x12-identity-settings.adoc[] for more information about X12-ISA settings.
