= Undeploying Message Flows

Undeploying a message flow prevents future messages from being processed and enables you to recover resources that are consumed by a message flow that you no longer need.

You can undeploy your message flow from either a sandbox or a production environment. The undeployment process takes about five minutes, during which actions such as `Deploy` and `Delete` are unavailable.

[IMPORTANT]
During the undeployment process, do not log out of Anypoint Partner Manager or close your browser window.

To undeploy a message flow:

. In the sidebar, select *Message Flows*.
. Select the message flow to undeploy from the list and click *Undeploy*.

Partner Manager checks to see if any of the applications deployed to Mule are orphaned as a result of the undeployment. Partner Manager then cleans up orphaned applications to release any resources that the applications consumed.

== See Also

* xref:deploy-message-flows.adoc[Deploying and Testing Message Flows]
* xref:create-inbound-message-flow.adoc[Creating Inbound Message Flows]
* xref:create-outbound-message-flow.adoc[Creating Outbound Message Flows]
