= Update the AS2 Host Keystore

When your host AS2 keystore is about to expire, follow these steps to update the keystore with a new certificate and private key pair:

. Depending on your organization’s policies, create a self-signed certificate and key pair, or obtain a new AS2 certificate from your certificate authority.
. Define a date on which you plan to switch to the new certificate.
. Share the new public certificate with your AS2 partners to give them sufficient lead time to plan the certificate switch on their side.

When it's time to switch to the new keystore:

. From the *<host>* page, click the keystore you want to update and then click *Edit*.
. In the *<host> public certificate* field, import the new certificate.
. In the *<host> private key file* field, import the new private key file.
. In the *Key passphrase* field, enter the keystore passphrase.
. Click *Update keystore*.
. After the keystore updates, do either of the following:
* If you have one AS2 receive endpoint that uses the keystore, open one message flow that references the endpoint and redeploy the flow.
* If you have more than one AS2 receive endpoint that use the keystore, redeploy one message flow for each AS2 receive endpoint that uses the keystore.

+
Partner Manager updates the inbound and outbound AS2 applications in the runtime. The update can take up to 10 minutes to complete.

== See Also

*
