= Upgrading Message Flow Runtime Templates

Anypoint Partner Manager uses prebuilt templates to convert your B2B message flow configurations into runtime applications. As these templates are updated, you can upgrade your message flows to use them to take advantage of new capabilities that enable better integration with your trading partner's ecosystem.

Runtime templates related to Partner Manager are upgraded when:

* A new feature or functionality is added
* A component on which your environment is dependent, such as a connector version, is upgraded
* A security vulnerability is fixed
* Functional and performance defects are resolved in the template
* Flow optimizations are implemented

When new runtime templates are available, the *Upgrade deployments* button in the top right corner of the *Message Flow* page is enabled.

Before upgrading your production environment, upgrade your nonproduction environments to test the changes on some of your message flows.

To take advantage of new features, click the *Upgrade deployments* button.

The process of updating all your message flows can take several minutes, depending on the number of message flow configurations and runtime applications in your environment.

When your message flows are deployed to CloudHub, your existing message flows are uninterrupted during the upgrade process.

When your message flows are deployed to your hosted runtimes, your runtime applications are stopped when the upgrade process begins, and then restarted when the upgrade is complete, which results in down time.

== See Also

* xref:deploy-message-flows.adoc[Deploying and Testing Message Flows]
