= Template Version Upgrades

Partner Manager leverages prebuilt templates that convert your B2B message flow configurations into runtime applications. These templates are periodically updated to add new features and enhancements. You can upgrade your message flows to use the updated templates to take advantage of the new capabilities that enable you to better integrate with your trading partner ecosystem.

Runtime templates related to Anypoint Partner Manager v2 are upgraded in the following situations: 
A new feature / functionality is added
A dependent component (such as a connector version) is upgraded.
A security vulnerability is resolved.
Functional / performance defects are resolved in the template.
Flow optimizations

When new template versions are released, you will see the Upgrade deployments button enabled in the top right corner of the Message flows page. 

To take advantage of the new features released, you can click the Upgrade deployments button, which begins the process of updating all your message flows to use the latest template version. 

This process can take several minutes depending on the number of message flow configurations and runtime applications your environment has. 
When your message flows are deployed to CloudHub, your existing message flows are uninterrupted during the upgrade process.
When your message flows are deployed to your hosted runtimes, your runtime applications are stopped when the upgrade process begins, and will be started when the upgrade is complete, resulting in a down time.

We recommend upgrading your non-production environments and testing some of your message flows prior to upgrading your production environment.


