= Upgrading Message Flow Runtime Templates

Anypoint Partner Manager uses prebuilt templates to convert your B2B message flow configurations into generic applications. As these templates are updated, you can upgrade your message flows to use them to take advantage of new capabilities that enable better integration with your partner's ecosystem.

Runtime templates related to Partner Manager are upgraded when:

* A new feature or functionality is added
* A component on which your environment is dependent, such as a connector version, is upgraded
* A security vulnerability is fixed
* Functional and performance defects are resolved in the template
* Flow optimizations are implemented

When new runtime templates are available, the *Manage deployments* button changes color and shows a tooltip to indicate a new version is available. To take advantage of the new features, click *Manage deployments* and select one of these options:

* Upgrade deployments
+
Updates the Mule applications in your runtime with the latest template versions that contain new features or bug fixes.

[NOTE]
====
Before upgrading your production environment, upgrade your nonproduction environments to test the changes on some of your message flows.

The time it takes to update your message flows depends on the number of message flow configurations and runtime applications in your environment.

When you deploy message flows, your existing message flows continue uninterrupted during the upgrade process.
====

* Apply environment settings
+
Updates the Mule applications in your runtime with the latest available template versions.

To apply your selection, confirm you understand the effects of these actions and click *Confirm*.

== See Also

* xref:deploy-message-flows.adoc[Deploying and Testing Message Flows]
