= Configure Receive Settings for Inbound X12 Messages

Partner Manager enables you to configure the X12 acknowledgments, validation rules, character encoding, and control numbers to apply when receiving inbound X12 messages from the selected partner.

To configure X12 receive settings:

. In the navigation menu, select *Partners*.
. Select the partner to associate with the settings.
. In the *Validation and acknowledgment settings* section's *Receive from <partner-name>* column, click *X12*.
. Select a link to configure:
* <<ack-settings,Acknowledgment settings>>
* <<validation-settings,Validation settings>>
* <<control-numbers,Control numbers>>
* <<character-set,Character set and separators>>
. Click *Save*.

[NOTE]
It can take up to approximately five minutes for your configuration changes to sync with Mule.

[[ack-settings]]
== Acknowledgment Settings

Use the following settings to configure the acknowledgments to send in response to inbound X12 messages:

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Send TA1 for each transmission from <recipient>.
a|Provides a Technical Acknowledgment (TA1) to the Interchange sender that reports the status of the processing of an interchange header and trailer by the address receiver:

* If the ISA and IEA of a received X12 message are valid, the host sends a positive TA1 ACK, regardless of the status of the other content.
* If the ISA and IEA of a received X12 message are not valid, the host sends a TA1 ACK with an error code.

The TA1 ACK is sent inside an ISA or IEA envelope. The ISA and IEA are no different than any other interchange.
|Disabled

|Send 997 functional acknowledgment when messages fail to route to a message flow
a|Sends a functional acknowledgment (the receipt and syntactical acceptability of a message) when there is a failure to route the message to one of the message flows.


|Disabled
|===

=== X12 997 Functional Acknowledgment

The X12 997 functional acknowledgment reports the status of a received interchange. It reports all of the errors encountered while processing the received document.
As with all X12 transaction sets, the 997 functional acknowledgment is sent inside a GS or GE envelope.

The 997 functional acknowledgment does the following:

* Acknowledges the receipt of an interchange or functional group
* Accepts or rejects one or more functional groups or transactions
* Verifies and reports compliance with the standard

If an interchange contains multiple groups, a 997 acknowledgment is returned for each group.

If a group contains multiple transaction sets, then the acknowledgment for that group contains one loop for each transaction set. This applies only if AK2 loops are generated for accepted transaction sets.

[[validation-settings]]
== Validation Settings

Use these settings to ensure that all X12 messages received from a partner meet validation rules. Parter Manager logs all validation errors and reports them in the CONTRL acknowledgments.
*Vijay, is it correct to say "the host rejects", or should we say "Partner Manager rejects"?

[%header%autowidth.spread]
|===
|Setting a|Description |Default

|Fail when value length outside allowed range
a| * If selected, the host rejects transactions with values that are too long or too short.
*Vijay, is the "too short" text correct? It is in the current doc.*
* If unselected, the values are used.
| Enabled

|Fail when invalid character in value
a| * If selected, the host rejects transactions with invalid characters.
* If unselected, the characters are either passed through or substituted.

|Enabled

|Fail if value is repeated too many times
a|* If selected, the host rejects transactions with values that are repeated too many or too few times.
*Vijay, is the "too few times" correct? It is in the current text.*
* If unselected, the values are accepted.
|Enabled

|Fail if unknown segments are used
a|* If selected, the host rejects transactions that contain unknown segments.
* If unselected, If unselected, the host ignores unused segments.
|Disabled

|Fail when segments are out of order
a|* If selected, the host rejects transactions that have out-of-order segments.
* If unselected, the segments are reordered.
| Enabled

|Fail when too many repeats of segment
| If selected, the host rejects transactions with segments repeated too many times.
|Enabled

|Fail when unused segments are included
a|* If selected, the host rejects transactions containing segments marked as unused in the schema.
* If unselected, the host ignores unused segments.
+
*Vijay, what is the difference between this option and the "Fail if unknown segments are used* setting? Both are in the interface. Is this a bug?*
| Disabled

|Enforce conditional relationship validations a| * If selected, any missing conditional data elements causes the generation of the X12 transaction to fail.
* *Vijay, what happens if this is not enabled? Is the X12 transaction generated with out-of-order segments*?
| Disabled
|===

[[control-numbers]]
=== Control Numbers

Use these settings to apply validations related to the use of control numbers within inbound X12 messages:

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Requires unique interchange control number (ISA13)
a| If selected, the host records the interchange numbers previously processed and rejects duplicate interchange numbers from the same partner (as determined by the interchange sender and receiver identification).
|Enabled

|Requires unique group control number (GS06)
a| If selected, the host enforces globally unique Group Control Numbers (GS06) for received functional groups.

This configuration requires group numbers to be unique across all interchanges received from the same partner and application, as determined by the interchange sender and receiver identification, combined with the functional group sender and receiver application codes.
| Disabled

|Require unique transaction set control number (ST02)
a| If selected, the host enforces globally unique Transaction Set Control Numbers (ST02) for received transaction sets.

This configuration requires transaction set numbers to be unique across all functional groups received from the same partner and application, as determined by the interchange sender and receiver identification, combined with the functional group sender and receiver application codes.
|Disabled
|===

[[character-set]]
=== Character Set and Encoding

Use these settings to apply character set and encoding options for received X12 message:

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Character set
a|Defines the characters allowed in string data. When set, invalid characters are replaced by the substitution character. If no substitution character is enabled for receive messages in the parser options, the host rejects the messages.
Either way, the invalid characters are logged and are reported in the 997 functional acknowledgments for the receive messages. | `EXTENDED`

|Character encoding
a|Indicates the character encoding for messages. This character encoding is used for both send and receive messages.
*Vijay, the sentence above is in the current doc but I don't think it is true, since you can set the encoding in the send settings separately from the receive settings.* | `ISO8859_1`
|===

== See Also

* xref:create-inbound-message-flow.adoc[Create and Configure an Inbound Message Flow]
* xref:create-partner.adoc[Create a New Partner]
* xref:modify-partner-settings.adoc[Modify a Partner's Settings]
