= Configuring Send Settings for Outbound X12 Messages

Partner Manager enables you to configure the X12 envelope parameters, delimiters, validation rules, character encoding, and control numbers to apply when sending an outbound X12 transmission to a partner.

To configure a partner's X12 send settings:

. In the navigation menu, select *Partners*.
. Select the partner for whom you want to configure the settings.
. In the *Validation and acknowledgment settings* section's *Send to <partner-name>* column, click *X12*.
. In the menu on the left, select the setting to configure:
* <<general-settings,General settings>>
* <<authorization-settings,Authorization settings>>
* <<ta1-ack-settings,TA1 Acknowledgment settings>>
* <<global-control-numbers,Global control numbers>>
* <<character-set,Character set and separators>>
. Click *Save*.

The values you configure in the partner's settings page are used by default for all X12 messages going to that partner.

You can override the settings you configure at the partner level, with the exception of TA1 and control numbers, or at the message flow level by selecting the *Custom* option while creating an outbound message flow.

[NOTE]
It can take up to five minutes for your configuration changes to sync with Mule.

[[general-settings]]
== General Settings

Use the following settings to configure the transaction usage, specify the responsible standards agency, and enforce length limits and conditional relationship validations:

[%header%autowidth.spread]
|===
|Setting |Description |Default Value

|Usage indicator (ISA15)
a|Indicates if the X12 transaction sent is for testing, production, or information only.

Possible values include:

* I - Information
* T - Test
* P - Production
a|* `P - Production` +
For production environments
* `T - Test` +
For sandbox environments

|Responsible agency code (GS07)
a|Define the standards agency responsible for the standard in the GS segment.

Possible values include:

* T - Transportation Data Coordinating Committee (TDCC)
* X - Accredited Standards Committee X12
|`X`

|Enforce length limits
a|If selected, any data elements with a length outside of the definition in the X12 schema cause the generation of the X12 transaction to fail.
|Enabled

|Enforce conditional relationship validations
|If selected, any missing conditional data elements will cause the generation of the X12 transaction to fail.
|Enabled
|===

[[authorization-settings]]
== Authorization Settings

Use the following settings to configure the authorization and security qualifier for the transactions:

[%header%autowidth.spread]
|===
|Setting |Description |Default
|Authorization qualifier (ISA01)
|
|None
|Security qualifier (ISA03)
|
|None
|===


[[ta1-ack-settings]]
== TA1 Acknowledgment Settings

Use the following settings to configure whether a technical acknowledgment is required, and the receive endpoint for the acknowledgment:

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Expect TA1 for each transmission sent to <partner>
a|If selected, sets the value in ISA14 to 1 on the generated X12 payload, indicating that a Technical acknowledgment (TA1) is required.
|Disabled
|Endpoint
a|When the option to expect a TA1 is selected, click *Select* to specify the *Receive from <partner>* endpoint. The acknowledgment will be received as an inbound transmission.
|None
|===

[[global-control-numbers]]
== Global Control Numbers

Partner Manager applies a global control number at the partner level on the X12 interchanges and functional groups generated from outbound message flows. These control numbers are sequenced across all message types (including functional acknowledgments) that are sent to a partner.

The control number starts with a default value of `1`, and is sequentially increased as your organization begins sending outbound transmissions.

To set the control number sequence value to a different number to maintain sequencing and avoid duplication:

. Click *Change* and enter the desired control number.
. Click *Save*.

[NOTE]
It can take up to five minutes to apply the change at runtime.

[[character-set]]
== Character Set and Separators

Use the following settings to set the character encoding and delimiters for the generated X12 payload:

[%header%autowidth.spread]
|===
|Setting |Description | Default Value

|Character set
a|Characters allowed in string data.

|Character encoding
a|Character encoding for messages.

|Segment terminator
a|Segment terminator character.
| `~`

|Data element separator
a|Data element separator character.
| `*`

|Component element separator (ISA16)
a|Component element separator character.
| `>`

|Line ending between segments
a|Line ending to add between segments. This enables you to add line endings between segments to improve the readability of the output message text.

Possible values include:
|===

== See Also

* xref:create-outbound-message-flow.adoc[Creating and Configuring Outbound Message Flows]
* xref:create-partner.adoc[Creating Partners]
* xref:modify-partner-settings.adoc[Modify Partner Settings]
