= X12 Send (Outbound) Settings

Partner Manager enables you to configure the X12 envelope parameters, delimiters, validation rules, character encoding, and control numbers to apply when sending an outbound X12 transmission to a trading partner.

Values configured in the Partner level settings are used by default for all X12 messages going to that trading partner. You can override the default settings (with the exception of TA1 and control numbers) at a message flow level by selecting the Custom option while creating an outbound message flow. 
Note: It may take up to five minutes for your configuration changes to sync with Mule runtime.

== Configure the Send Settings

. In the left navigation menu, select the partner for whom to configure the send settings. 
. In the *Validation and acknowledgment settings* section, under *Send to <partner-name>*, click *X12*.
. In the menu on the left, select the setting to configure:
* <<general-settings,*General*>>
* <<authorization-settings,*Authorization*>>
* <<ta1-ack-settings,*TA1 Acknowledgment*>>
* Global control numbers
* Character set & separators
. Click *Save*. 

[[general-settings]]
== General Settings

[%header,cols="3s,7a"]
|===
|Setting |Description

|Usage indicator (ISA15)
a|Indicates if the X12 transaction sent is for testing, production or information only. Possible values include:

I - Information
T - Test
P - Production
Default: 
P - Production (for Production environment)
T - Test (for Sandbox environments)

|Responsible agency code (GS07)
a|Define the standards agency responsible for the standard in the GS segment.
Possible values:
T - Transportation Data Coordinating Committee (TDCC)
X - Accredited Standards Committee X12
Default: X

|Enforce length limits
a|If selected, any data elements with length falling outside of the definition in the X12 schema will cause the generation of the X12 transaction to fail.
Default: Selected

|Enforce conditional relationship validations
|If selected, any missing conditional data elements will cause the generation of the X12 transaction to fail.
Default: Selected
|===

[[authorization-settings]]
== Authorization Settings

[[ta1-ack-settings]]
== TA1 Acknowledgment Settings

[%header,cols="3s,7a"]
|===
|Setting |Description

|Expect TA1 for each transmission sent to <partner>
a|If selected, sets the value in ISA14 to 1 on the generated X12 payload indicating that a Technical acknowledgement (TA1) is required.
Default: Not Selected
|Endpoint
a|When the option to expect a TA1 is selected, you should also select a Receive from partner endpoint through which the acknowledgement will be received as an inbound transmission.
|===


