= Configuring Send Settings for Outbound X12 Messages

Partner Manager enables you to configure the X12 envelope parameters, delimiters, validation rules, character encoding, and control numbers to apply when sending an outbound X12 transmission to a partner.

To configure a partner's X12 send settings:

. In the navigation menu, select *Partners*.
. Select the partner for whom you want to configure the settings.
. In the *Validation and acknowledgement settings* section's *Send to <partner-name>* column, click *X12*.
. In the menu, select the setting to configure:
* <<general-settings,General settings>>
* <<authorization-settings,Authorization settings>>
* <<ta1-ack-settings,TA1 Acknowledgment settings>>
* <<global-control-numbers,Global control numbers>>
* <<character-set,Character set & separators>>
. Click *Save*.

The values you configure in the partner's settings page are used by default for all X12 messages going to that partner.

You can override the settings you configure at the partner level except for TA1 and control numbers. You can override the message-flow-level settings by selecting the *Custom* option while creating an outbound message flow.

[NOTE]
Your changes can take up to five minutes to take effect on the runtime.

[[general-settings]]
== General Settings

Use the following settings to configure the transaction usage, specify the responsible standards agency, and enforce length limits and conditional relationship validations:

[%header%autowidth.spread]
|===
|Setting |Description |Default Value

|Usage indicator (ISA15)
a|Indicates if the X12 transaction sent is for testing, production, or information only.

Possible values include:

* I - Information
* T - Test
* P - Production
a|* `P - Production` +
For production environments
* `T - Test` +
For sandbox environments

|Responsible agency code (GS07)
a|Define the standards agency responsible for the standard in the GS segment.

Possible values include:

* T - Transportation Data Coordinating Committee (TDCC)
* X - Accredited Standards Committee X12
|`X`

|Enforce length limits
a|If selected, any data elements with a length outside of the definition in the X12 schema cause the generation of the X12 transaction to fail.
|Enabled

|Enforce conditional relationship validations
|If selected, any missing conditional data elements cause the generation of the X12 transaction to fail.
|Enabled

|Enforce code set validations
|If selected, Partner Manager enforces X12 code set validations, as defined in the X12 schemas.
|Disabled
|===

[[authorization-settings]]
== Authorization Settings

Use the following settings to configure the authorization and security qualifier for the transactions:

[%header%autowidth.spread]
|===
|Setting |Description |Default
|Authorization qualifier (ISA01)
|
|None
|Security qualifier (ISA03)
|
|None
|===


[[ta1-ack-settings]]
== TA1 Acknowledgment Settings

Use the following settings to configure whether a technical acknowledgement is required, and the receive endpoint for the acknowledgement:

[%header%autowidth.spread]
|===
|Setting |Description |Default

|Expect TA1 for each transmission sent to <partner>
a|If selected, sets the value in ISA14 to 1 on the generated X12 payload, indicating that a Technical acknowledgement (TA1) is required.
|Disabled
|Endpoint
a|When the option to expect a TA1 is selected, click *Select* to specify the *Receive from <partner>* endpoint. Partner Manager will receive the TA1 as an inbound transmission.
|None
|===

[[global-control-numbers]]
== Global Control Numbers

Partner Manager applies a global control number at the partner level on the X12 interchanges and functional groups generated from outbound message flows. These control numbers are sequenced across all message types (including functional acknowledgements) that are sent to a partner.

The control number starts with a default value of `1`, and is sequentially increased as your organization begins sending outbound transmissions.

To set the control number sequence value to a different number to maintain sequencing and avoid duplication:

. Click *Change* and enter the desired control number.
. Click *Save*.

[NOTE]
Your changes can take up to five minutes to take effect on the runtime.

[[character-set]]
== Character Set & Separators

Use the following settings to set the character encoding and delimiters for the generated X12 payload:

[%header%autowidth.spread]
|===
|Setting |Description | Default Value

|Character set
a|Set of characters allowed in string data.
|EXTENDED

|Character encoding
a|Character encoding for messages.
|UTF8

|Segment terminator
a|Segment terminator character.
| `~`

|Data element separator
a|Data element separator character (can be a hex code).
| `*`

|Component element separator (ISA16)
a|Component element separator character (can be a hex code).
| `>`

|Line ending between segments
a|Character to use for line endings between segments to improve the readability of the output message text. Possible values include:

* NONE
+
Generates the EDIFACT payload as a single line with segments separated by this character
+
* CR
+
Carriage return
+
* CRLF
+
Carriage return and line feed
+
* LF
+
Line Feed
|CRLF

|Use segment line ending in last line
|If `Yes`, Partner Manager applies the segment line ending character to the last segment in the payload.
|No

|===

== See Also

* xref:create-outbound-message-flow.adoc[Creating Outbound Message Flows]
* xref:create-partner.adoc[Creating Partners]
* xref:modify-partner-settings.adoc[Modify Partner Settings]
