= Configure X12 Send (Outbound) Settings

Partner Manager enables you to configure the X12 envelope parameters, delimiters, validation rules, character encoding, and control numbers to apply when sending an outbound X12 transmission to a trading partner.

== Configure the Send Settings

. In the left navigation menu, select the partner for whom to configure the send settings. 
. In the *Validation and acknowledgment settings* section, under *Send to <partner-name>*, click *X12*.
. In the menu on the left, select the setting to configure:
* <<general-settings,*General*>>
* <<authorization-settings,*Authorization*>>
* <<ta1-ack-settings,*TA1 Acknowledgment*>>
* <<global-control-numbers,Global control numbers>>
* <<character-set,*Character set & separators*>>
. Click *Save*. 

The values you configure in the partner's settings page are used by default for all X12 messages going to that trading partner. You can override the settings you configure at the partner level, with the exception of TA1 and control numbers, at the message flow level by selecting the *Custom* option while creating an outbound message flow. 

[NOTE]
It can take up to five minutes for your configuration changes to sync with Mule.

[[general-settings]]
== General Settings

[%header%autowidth.spread]
|===
|Setting |Description |Default Value

|Usage indicator (ISA15)
a|Indicates if the X12 transaction sent is for testing, production or information only. Possible values include:

* I - Information
* T - Test
* P - Production
a|* P - Production +
For production environments
* T - Test +
For sandbox environments

|Responsible agency code (GS07)
a|Define the standards agency responsible for the standard in the GS segment.

Possible values include:

* T - Transportation Data Coordinating Committee (TDCC)
* X - Accredited Standards Committee X12
|`X`

|Enforce length limits
a|If selected, any data elements with a length outside of the definition in the X12 schema cause the generation of the X12 transaction to fail.
|Selected

|Enforce conditional relationship validations
|If selected, any missing conditional data elements will cause the generation of the X12 transaction to fail.
|Selected
|===

[[authorization-settings]]
== Authorization Settings

[[ta1-ack-settings]]
== TA1 Acknowledgment Settings

[%header%autowidth.spread]
|===
|Setting |Description 

|Expect TA1 for each transmission sent to <partner>
a|If selected, sets the value in ISA14 to 1 on the generated X12 payload indicating that a Technical acknowledgement (TA1) is required.
By default, this option is not selected.
|Endpoint
a|When the option to expect a TA1 is selected, you should also select a Receive from partner endpoint through which the acknowledgement will be received as an inbound transmission.
|===

[[global-control-numbers]]
== Global Control Numbers

Partner Manager applies a global control number at a partner level on the X12 interchanges and functional groups generated from outbound message flows. These control numbers are sequenced across all message types (including functional acknowledgements) sent to a trading partner.

The control number starts with a default value or 1 and is sequentially increased as your organization begins sending outbound transmissions. If you need to set the control number sequence value to a different number to maintain sequencing and avoid duplication, click Change and enter the desired control number. It may take up to 5 minutes for the change to be applied at runtime.

[[character-set]]
== Character Set and Separators

These settings enable you to set the character encoding and delimiters to use on the generated X12 payload:

[%header%autowidth.spread]
|===
|Setting |Description | Default Value

|Character set
a|Characters allowed in string data. 

Possible values include:

* BASIC
* EXTENDED
* UNRESTRICTED | `EXTENDED`

|Character encoding
a|Character encoding for messages.

Possible values include:

* PLATFORM
* ASCII
* ISO8859_1
* IBM1047
* UTF8 | `UTF8`

|Segment terminator
a|Segment terminator character. 
| `~`

|Data element separator
a|Data element separator character.
| `*`

|Component element separator (ISA16)
a|Component element separator character.
| `>`

|Line ending between segments
a|Line ending to add between segments. This allows you to add line endings between segments to improve the readability of the output message text.

Possible values include:

* NONE - X12 payload generated will be a single line, with segments separated by the segment terminator character
* CR - Carriage Return
* CRLF - Carriage Return & Line Feed
* LF - Line Feed
|
|===

== See Also

* xref:create-outbound-message-flow.adoc[Create and Configure an Outbound Message Flow]
