== HTTP(S) Send Configuration

Use these settings when sending with the secure HTTP(S) protocols.
This includes endpoints for sending transmissions to your partner and endpoints that are targets at your organization.

[%header,cols="3s,7a"]
|===
|Name |Description
|Protocol
|Select *HTTP* or *HTTPS* +
Required: Yes +
Default: HTTPS

|Endpoint Name
|Name used to easily identity the function of this endpoint. +
Required: Yes +
Default: N/A

|Description
|Describe a purpose and any other important details for this endpoint. +
Required: No +
Default: Selected

|URL
|Enter a well-formed URL (including the path) where the request is to be sent such as:
https://www.mulesoft.com/sendRequest?name=something +
Required: Yes +
Default: N/A

|Connection Idle Timeout (milliseconds)
|Must be an integer greater than or equal to 1000. +
Required: Yes +
Default: 3000

|Response Timeout (milliseconds)
|Must be an integer greater than or equal to 1000. +
Required: No +
Default: none
|===

See xref:Certificates.adoc[Certificates] for more info on configuring certificates in Partner Manager.

=== Authentication Settings

Depending on how you set up your authentication policy, refer to the appropriate authentication type and descriptions here.

[%header,cols="3s,7a"]
|===
|Authentication Type |Description
|None
|No authentication. +
Required: No +

|API Key
|`HTTP Header Name` - The Header parameter associated to the API Key. +
`API Key` - The value for the access key you set. +
Required: No +

|Basic
|Simple authentication policy protects the API by requiring username and password when calling apps make a request. +
`Username` - Enter the username you set up with this authentication policy. +
`Password` - Enter the username you set up with this authentication policy. +

|Client Credentials
|`Client ID` - The Client Id the OAS gave you when registering your application. +
`Client Secret` - The Client Secret the OAS gave you when registering your application.
`Client Header` - Add the key-value pairs, if they don't exist. +
`Client Secret Header` - Add the secret key-value pairs, if they don't exist. +

|OAuth Token
|`Token URL` - Enter a valid authorization URL +
`Client ID` -The Client Id the OAS gave you when registering your application. +
`Client Secret` - The Client Secret the OAS gave you when registering your application.
|===
