== HTTP Send Configuration

Use these settings when sending with the HTTP protocol.

[%header,cols="3s,7a"]
|===
|Name |Description
|Protocol
|Select *HTTP*  +
Required: Yes +
Default: HTTP

|Endpoint Name
|Name used to easily identity the function of this endpoint. +
Required: Yes +
Default: N/A

|Description
|Describe a purpose and any other important details for this endpoint. +
Required: No +
Default: Selected

|URL
|Enter a well-formed URL (including the path) where the request is to be sent such as:
`https://www.mulesoft.com/sendRequest?name=something` +
Required: Yes +
Default: N/A

|Connection Idle Timeout (milliseconds)
|Must be an integer greater than or equal to 1000. +
Required: Yes +
Default: 3000

|Response Timeout (milliseconds)
|Must be an integer greater than or equal to 1000. +
Required: No +
Default: None
|===

=== Authentication Settings

[%header,cols="3s,7a"]
|===
|Authentication Type |Description
|None
|No authentication required. +
Required: No +

|API Key
|Validation access key.
`HTTP Header Name` - The Header parameter associated to the API Key. +
`API Key` - The value for the access key you set. +
Required: No +

|Basic
|Simple authentication policy API protection. Requires a username and password when calling apps to make a request. +
`Username` - Enter the username you set up with this authentication policy. +
`Password` - Enter the username you set up with this authentication policy. +

|Client Credentials
|For validating the client and service provider. +
`Client ID` - The Client Id the OAS gave you when registering your application. +
`Client Secret` - The Client Secret the OAS gave you when registering your application. +
`Client Header` - Add the key-value pairs, if they don't exist. +
`Client Secret Header`- Add the secret key-value pairs, if they don't exist. +

|0Auth Token
|Specific authorization for validation access. +
`Token URL` - Enter a valid authorization URL to the Token +
`Client ID` - The Client Id the OAS gave you when registering your application. +
`Client Secret` - The Client Secret the OAS gave you when registering your application.
|===
