= Tracking Scenarios
:keywords: Anypoint b2b Anypoint Partner Manager concepts

include::partial$include-v1-eol.adoc[]


This section identifies scenarios in which Anypoint Partner Manager (APM) is useful to track B2B exchanges. A basic knowledge of APM is assumed; see  xref:anypoint-partner-manager.adoc[Anypoint Partner Manager] for more information.

== Replaying an Incomplete Transaction

On the xref:transaction-monitoring.adoc[B2B Transactions Page], the Transactions View includes a table in which each row corresponds to a transaction.  The first column shows transaction completion status, as follows:

Green checkmark:: Indicates a complete transaction.
Red exclamation point (*!*):: Indicates a transaction has one or more errors that prevented completion.

After you identify and fix the cause of the error that prevented the transaction from completing, you can use APM to re-run the transaction.

Possible errors include:

* Server down
* Dependency (for example, a map or code element) has changed
* Required data is absent

NOTE: Only replay transactions after resolving the issue or issues that caused the error.

For more information, see "Transactions View" in xref:transaction-monitoring.adoc[Transaction Monitoring].

== To Replay a Transaction

. Click the row corresponding to the transaction you want to replay.
+
NOTE: For a transaction to be replayable, the second (Replay Status) column must be blank or contain a gray partial circle, but must not contain a blue partial circle.
+
A blue *Replay* button appears in the Top Bar.
+
. Click the blue *Replay* button
+
The button becomes unclickable, and a message that the transaction is being replayed appears in its place.
+
Once the transaction has been replayed, the blue replay circle appears in the Replay Status Column of the transaction that you replayed.
+
. To see if the replayed transaction succeeded or failed, click the replayed transaction.
+
. In the Transaction Detail Pane, a link to *view replays* appears.
+
This automatically filters the grid by *Transaction ID*, so that only transactions that are replays of the original transaction appear.
+
If the replayed transaction fails again, repeat this process until the replay completes.
+
You can always view a list of all of transactions that have been replayed from a given original transaction by clicking the link in the Transaction Detail Pane of any transaction for which the blue replay circle appears in the Replay Status Column.
+
Once the replay succeeds, a green check appears next to the replayed transaction.
If you need to continue replaying the transaction, you can do so with the same replay button as before, but you will be alerted with a warning before you can continue. This is to prevent unnecessary replays from happening.

== Common Errors

If you see an atypical number of errors of a similar nature, you can review all of them simultaneously.

The *Dashboard* at the top of the xref:transaction-monitoring.adoc[Transaction Monitoring] provides a summary of what has happened in a given timeframe (the default is the current day) including how many errors have been detected during that timeframe.

== To View Error Information in the Dashboard

. Hover over different slices of the Errors Pie Chart to see what types of errors have occurred.
. To see information for a given error type, click one of the slices.
+
The Error View appears, showing only the error type over which you were hovering.
+
This enables you to look for a pattern among these errors that will facilitate a solution to the errors. This is useful when transactions are failing. but you can't ascertain the solution by just looking at the transactions themselves.
+
The navigation buttons at top right enable you to view the transactions with which these errors are associated.

== Transport Problem Identification

If you notice that you are getting a large number of errors from a single type of transport, you can sort your transmissions using a filter in combination with the Transmissions View on the xref:transaction-monitoring.adoc[Transaction Monitoring]. The filter allows you to view a given transport type and see the differences between those that failed and those that succeeded.

You can find additional relevant information in the Transmissions Detail Pane to the right. In the Detail Pane, you can see what happened with individual transactions with which transmissions were involved through a navigation button in the upper corner.

This allows you to follow transactions through their entire cycle, and if necessary replay them through the replay button.

Because consistent navigation is helpful in looking for patterns and correcting errors, many filters persist from view to view. This allows you to look for commonalities across data types.

== When a Partner Needs Records

Often, a partner requires specific information relating to a transaction, transmission, or document. The following explains ways to access and use that information.

== Finding Transmissions

. On *View Dropdown List* of the xref:transaction-monitoring.adoc[B2B Transactions Page], choose *Transmissions*.
+
The Transmissions View appears.
+
. In the *Transmission ID* filter, enter the partner ID.
+
The Transmissions Detail Pane populates with information that is likely relevant the partner's request.
+
. To copy a long string for partner use, click the *copy* button to the right of the string.
+
Additional relevant information can be found using the various filter and sort possibilities this view presents.
+
NOTE: You can always use the *Clear Filters* button to get back to the full view.
+
If you need to find out more information about a transmission or just where it exists in the larger scope you can click on the *Transaction* button in the upper right corner to view the transmission in context.

== Finding Documents

. On *View Dropdown List* of the xref:transaction-monitoring.adoc[B2B Transactions Page], choose *Documents*.
+
The Documents View appears.
. In the *Document ID* filter, enter the Document ID that the partner provided you.
+
The Document Detail Pane populates with information that is likely relevant to the partner's request.
+
To copy a long string for partner use, click the *copy* button to the right of the string.
+
Additional relevant information can be found using the various filter and sort possibilities this view presents.
+
NOTE: You can always use the *Clear Filters* button to get back to the full view.
+
If you need to find out more information about a document, or to see where it fits into the bigger picture, you can click on the *Transaction* button in the upper right corner to view the document in context.
